### ISSUE TITLE
Add "Insecure" Option to validate-queries plugin

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1099]
Our [graphql-cli-validate-magento-pwa-queries](https://github.com/magento-research/pwa-studio/tree/develop/packages/graphql-cli-validate-magento-pwa-queries) plugin should accept an "insecure" flag that sets the `NODE_TLS_REJECT_UNAUTHORIZED` environment variable to `0` when set.

This allows the plugin to run even when certificates are untrusted.

**Comment by awilcoxa** [comment]
implemented in previous PR
