### ISSUE TITLE
Open Source a validate-queries graphql-cli Plugin

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1100]
Our [graphql-cli-validate-magento-pwa-queries](https://github.com/magento-research/pwa-studio/tree/develop/packages/graphql-cli-validate-magento-pwa-queries) `graphql-cli` plugin is very specific to Magento & PWA, but the general need to validate queries against a GraphQL schema would be useful to the larger front end community.

We could publish a `validate-queries` plugin that is basically our `graphql-cli-validate-magento-pwa-queries` plugin, but with all the Magento / PWA-specific stuff stripped out.

**Comment by awilcoxa** [comment]
Closing for now.
