### ISSUE TITLE
[feature]: Investigate Peer Dependency Warnings

### ISSUE THREAD

**Issue by tjwiebell** [magento/pwa-studio#1106]
**Is your feature request related to a problem? Please describe.**
New developers cloning and installing the project are met with numerous peer dependency warnings, that might make someone new to npm/yarn think something is wrong with the project.

**Describe the solution you'd like**
Investigate the matrix of dependency versions between peers, and see if there's anything we could modify about `package.json` to hoist as many packages as possible from parents.

**Describe alternatives you've considered**
`yarn --silent` doesn't seem to suppress these warnings, only way to do this is to pipe the output to nowhere `yarn > /dev/null 2>&1`, but that would making debugging actual failed installed very difficult.

**Additional context**
More senior developers have seen these warnings before, and understand what they mean, and they do not raise alarms. We should be conscious that weren't not sacrificing a more stable project to make first install for junior developers less concerning. If moving `dependencies` to `peerDependencies` causes any breakage, this doesn't seem worth it.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [x] `upward-js`
- [ ] `upward-spec`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story
