### ISSUE TITLE
[feature]: Implement basic CMS block on Venia homepage

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#1107]
**Is your feature request related to a problem? Please describe.**
As part of the PWA Studio, we need to demonstrate a basic CMS example on Venia that can be utilized by partners and developers creating basic PWA with new GraphQL from the Magento 2.3.1 release. Work has been done already for 2.3.0 and several examples have been shared from the Community including Comwrap (contribution), Experius and ShipperHQ (Stan) recently. This could be utilized on Category over time. This effort is to consolidate and implement the best of these efforts prior to UI Components.

**Describe the solution you'd like**
Basic programmable CMS content for the Venia homepage but managed within the Magento 2 admin. First version does not require advanced interactions (e.g. carousel, gallery) but should "snap" between mobile, tablet and desktop breakpoints. Does not require PageBuilder at first but available in time. Reuse as a UI Component is desirable.

**Describe alternatives you've considered**
Several considerations for CMS have been implemented for homepage and footer. This will be the first of an iterative CMS example that will integrate additional capabilities and security improvements over time.

**Additional context**
Previous issues #277 (PR) and stock/mages #460 may be helpful with original user story #460. Please work with @soumya-ashok on final UX design guidance for this basic promo (product teaser) during implementation.

**Please let us know what packages this feature is in regards to:**
- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [X] `peregrine`
- [X] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by soumya-ashok** [comment]
In this mockup - https://magento.invisionapp.com/share/K5P65T3HVRQ 
I've modified the sale banner under new arrivals with an image from Adobe stock, and a layout that could be generated in PageBuilder.

Consulted with Eugene and he feels that the footer on the home page is also a good candidate for a CMS block.

**Comment by rakeshgsharma** [comment]
@soumya-ashok Is there any react based implemention done for the components like sales banner, new arrivals, etc. I can't seem to find any in the venia-concept/components. In the documentation also, there are  just reference images and no implementation in react. Will I have to write the HTML for them on my own?

**Comment by soumya-ashok** [comment]
@rakeshgsharma The only image carousel that has been implemented is the one currently on the product detail page.

As far as I know, we do not have any implementations of any of the static / marketing banners in the proposed design at the moment.  Are you interested in contributing this work?

**Comment by sirugh** [comment]
@ericerway can we close this now that we have the PageBuilder impl on the sample sites develop.pwa-venia.com and venia.magento.com?

**Comment by sirugh** [comment]
Discussed with Eric - closing this as we do have the PB example. MagentoCE users can still use the cms blocks, just without PB.
