### ISSUE TITLE
[bug]: Unable to create subfolders inside queries folder

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#1108]
**Describe the bug**
Right now it's not possible to create a subfolder inside the `venia-concept/src/queries` the reason you might wanna do this is to better structure your queries. 

For example you might wanna create a subfolder like `venia-concept/src/queries/category` that contains all queries related to the category.

**To Reproduce**
1. Create `venia-concept/src/queries/category` and keep it empty for now.
2. Run `yarn run build`.
3. run `yarn run watch:venia`
4. See error `Error: EISDIR: illegal operation on a directory, read`

**Expected behavior**
No error and the watch command just continues to run as usual

**Possible solutions**
Some globbing should be added to `PWADevServer.js` on line 177 so instead of just returning the direct `.graphql` files it should search recursive. This could be done with just plain JS but there seems to be a good package for this see https://github.com/isaacs/node-glob

**Please complete the following device information:**
 - Device [Macbook pro]:
 - OS Mojave 10.14.4 Beta (18E215a)
 - Magento Version: default from `.env.dist`
 - PWA Studio Version: [develop][v2.1.0]
 - NPM version `6.5.0`:
 - Node Version `v11.9.0`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by Jordaneisenburger** [comment]
Not sure if this is a bug because there might be a reason to no structure your query files that I'm not aware of. But if this is in fact a bug i'd like to take ownership

**Comment by awilcoxa** [comment]
@zetlen

**Comment by supernova-at** [comment]
I don't see any technical reason why we shouldn't do this and `node-glob` seems a sensible solution to me :thumbsup:.

I'm cool if @Jordaneisenburger makes this improvement for sure.

**Comment by Jordaneisenburger** [comment]
Problem seems to have been resolved. Check second last query file
![image](https://user-images.githubusercontent.com/19858728/62073886-e8364580-b241-11e9-9a09-96c20d51f2e0.png)

**Comment by zetlen** [comment]
Excellent! Now that #1498 is merged and the `configureWebpack` function takes a special flag for `graphqlQueries`, I'd like to ask @Jordaneisenburger if it still works. It should now be driven by the presence of a file path in the UPWARD file, rather than a particular directory like `queries`.

**Comment by Jordaneisenburger** [comment]
@zetlen it still works after the merge, well done!
