### ISSUE TITLE
Research: Adobe hosting security requirements for applications like PWA

### ISSUE THREAD

**Issue by sharkySharks** [magento/pwa-studio#1112]
It is yet to be fully determines all of the Adobe security requirements needed for hosted applications and whether their security standards are necessary for the PWA project, since we deliver packages and not a deployed site for customer use.

Some relevant Adobe documentation can he found [here](https://wiki.corp.magento.com/pages/viewpage.action?spaceKey=GCO&title=Hosting+Security+Model)

What needs to determined:

- Do demo applications, like venia, that are publicly accessible considered `production`? What does that mean for the security needed when hosting, per Adobe?
- What static security scanning software should PWA use to test code in automated CI pipeline(s)?
- What Composition Analysis software should PWA use to test code in automated CI pipeline(s)?
- Should Blessed Base Containers (BBC) be used for every application? Where can application images be stored and also be accessible by AWS? Examples? - [bbc docs](https://git.corp.adobe.com/ASR/bbc-factory)

**Comment by supernova-at** [comment]
@cherdman , your input is needed on this ticket.

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-47

**Comment by sirugh** [comment]
Ticket is cancelled.
