### ISSUE TITLE
[feature]: Simplify Venia webpack config

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1115]
**Is your feature request related to a problem? Please describe.**
The Venia Webpack configuration file `packages/venia-concept/webpack.config.js` is very large and contains a lot of configuration rules that don't seem specific to the Venia project. It's one of the places where third parties have the hardest time maintaining a fork of Venia for their own work.

**Describe the solution you'd like**
Buildpack should "own" more of the Webpack configuration rules so that Venia can be simpler and more focused on presentation. The Venia webpack config should use presets from Buildpack and derive configuration from a more centralized .env file.

**Describe alternatives you've considered**
- Breaking up the webpack config into smaller chunks using aggregation patterns
- Hiding webpack config itself using a buildpack CLI

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by awilcoxa** [comment]
addressed in #1498
