### ISSUE TITLE
EPIC: Create New Shopper Components in Peregrine

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#1133]
Goal: Creation of new shopper components for Venia and moving them into Peregrine. End state is that each existing Venia component as a functional component that exists in Peregrine which we will then go back and retrofit into Venia.  

This sub-epic represents the effort to create the remaining functional Peregrine components for Venia:

Wish Lists
Ratings and Reviews
Coupons

**Comment by awilcoxa** [comment]
Consolidating new shopper components to the Storefront and Theming milestone for further consideration. Closing this Epic and we will track effort against new milestone and possibly break work back out after review.
