### ISSUE TITLE
[feature]: Wish Lists Component

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#1134]
Add support for Wish Lists into existing Venia Storefront

### JIRA issue for design
https://jira.corp.magento.com/browse/UXD-152

**Comment by supernova-at** [comment]
We were just having a discussion about sharing your favorites list (unauthenticated).

I wanted to point out that while it may not be useful to an individual shopper, it would be great for registry-type shopping occasions like birthdays or holidays.

Sharing is inherently concerned with more than just the "individual shopper" anyway.

**Comment by awilcoxa** [comment]
Consolidating new shopper components to the Storefront and Theming milestone for further consideration

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-76

**Comment by soumya-ashok** [comment]
Full LUMA parity for wish list will need My Account. Are we expecting to deliver the full feature or do we want to consider a "light" route with guest wish list and no My Account management @awilcoxa  - Can discuss this more once you are back from MLEU.

**Comment by sirugh** [comment]
Closing - handled by other wishlist epic tickets.
