### ISSUE TITLE
[feature]: Coupons Component

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#1136]
Add support for coupons into Venia storefront

### JIRA issue for design
https://jira.corp.magento.com/browse/UXD-171

**Comment by awilcoxa** [comment]
Consolidating new shopper components to the Storefront and Theming milestone for further consideration

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-23

**Comment by schensley** [comment]
Updated the UX Deliverables ticket for this item.  
Ready for review.

https://jira.corp.magento.com/secure/RapidBoard.jspa?rapidView=2089&projectKey=UXD&view=detail&selectedIssue=UXD-171

**Comment by schensley** [comment]
The UX Deliverables ticket has been updated with a design for Coupon Code for the current Venia cart page for your consideration.  https://jira.corp.magento.com/browse/UXD-171

**Comment by sirugh** [comment]
Done.
