### ISSUE TITLE
Assign Guest Cart to Customer

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1144]
# Summary

When a guest customer logs in, items in the guest cart should be transferred to the customer cart.

# Acceptance Criteria

1. Go to the Venia storefront
1. Be sure you are logged out (a guest user)
1. Add an item to your cart
1. Log in
1. See that the item added in Step 3 appears in your cart

# Possible Solutions

## GraphQL

GraphQL support for this feature is "coming soon". Since this is the preferred solution, we may want to wait for this support.

## REST API

Alternatively, the REST API exposes a [carts/{cartId}](https://devdocs.magento.com/redoc/2.3/customer-rest-api.html#operation/quoteCartManagementV1AssignCustomerPut) endpoint that

> Assigns a specified customer to a specified shopping cart.

Unfortunately this endpoint requires an admin token (which requires admin credentials). Since we don't want to publicly expose admin credentials in the source code or make them viewable in the network tab, the real work of going this route would be to create a solution that allows us to call admin endpoints without exposing admin credentials.

**Comment by awilcoxa** [comment]
Need to check with GQL to see if dependency is delivered

**Comment by awilcoxa** [comment]
https://jira.corp.magento.com/browse/PWA-243

**Comment by sirugh** [comment]
This was resolved with the addition of #2377
