### ISSUE TITLE
Venia PDP if user selects size option - What events are running in background? 

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1179]
1-  Say, If I select Fashion Size - M, does Fashion color options updates and removes/disables all color option which doesn't have size M?
2- Why image reloads?
3- Why there is no default selection by default? (Any business reason?)

**Comment by awilcoxa** [comment]
@dpatil-magento can you add repro here and detailed description of the issue?

**Comment by dpatil-magento** [comment]
Closing this, created separate tickets with more details - #1527 and #1528
