### ISSUE TITLE
Add support to allow local MFTF runs on AWS docker container.

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1180]
TBD - @dpatil-magento to update.

**Comment by awilcoxa** [comment]
@dpatil-magento @tjwiebell can you add more detail here for this feature request?

**Comment by dpatil-magento** [comment]
Closing this ticket as its low priority item compared to other tickets in list. Also, it's not stopping us from running MFTF tests or to debug any MFTF test failure issues.
