### ISSUE TITLE
Feature - Run MFTF tests in parallel in AWS

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1186]
Issue - Currently MFTF tests on CI (AWS) runs on single instance. To complete a one round of regression it takes 10-20 mins. Its not huge deal for now as we have only 15 MFTF tests. But in future if our  MFTF suite for PWA grows then we need to find ways to reduce the time to run all tests on CI env.

Possible Solution  - Run MFTF tests in parallel on multiple docker containers, which will reduce overall runtime.

**Comment by awilcoxa** [comment]
@dpatil-magento can you add more detail?

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-46

**Comment by dpatil-magento** [comment]
Tracked in Jira.
