### ISSUE TITLE
[bug]: If registered user tries to create account with email already in use then system does not show proper error message.

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1210]
Pre-condition - 
1. Customer should be created 

Steps - 
1. Go to venia storefront and try to create account with customer created in pre-condition.

Expected - User should be shown with proper error message like "Email not available. Please try different email". Please check with Business on message content. Or check what error API returns in this case.
Actual - User is shown with message "An error occurred. Please try again" which is confusing.

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/42394916-9ad9-49ba-92a4-0f8840d3236a)

**Comment by awilcoxa** [comment]
Bigger question here is if more detailed error messages are being returned from API, why are we not displaying it rather than hard coding our own error messages (seems like the latter would be duplicative). Moving forward to grooming so we can prioritize.

**Comment by soumya-ashok** [comment]
In terms of interaction, I think a good way to handle this type of error would be to show a form-level error in the form of a toast that says "An account already exists for this email ID" or "There is an existing account associated with this email ID".
In addition, it would be good to highlight the field that is associated with the error message, which in this case would be the email field.
@supernova-at Thoughts?

**Comment by supernova-at** [comment]
> show a form-level error in the form of a toast

I think a toast could look cool as long as we keep consistency throughout the app. In other words, every time a form submission fails, the error appears via a toast.

> it would be good to highlight the field that is associated with the error message

Highlighting the field that is associated with the message is much harder unfortunately, since we just have a big block of text to work with:

```
Error: POST /rest/V1/customers responded 400 Bad Request: 

Message:

  A customer with the same email address already exists in an associated website.


    at eval (M2ApiRequest.js?62e0:248)
```

We'd have to manually hardcode the link between this error message and our `email` field, since the server doesn't know about any client fields.

I should note that we ran into a similar issue on the Sign In form when users submit bad username / password though, and we would benefit from a ticket that [reworks the error handling code](https://github.com/magento-research/pwa-studio/blob/develop/packages/peregrine/src/RestApi/Magento2/M2ApiResponseError.js) so that it makes the error message (in this case "A customer with the same email address already exists in an associated website.") available to the UI to display in a toast.

**Comment by soumya-ashok** [comment]
@supernova-at Yes, my thought is that we would apply the same treatment for all form-level errors.
If is not trivial to let them know which field is the problem, do we have the option of being specific with error messages?

**Comment by soumya-ashok** [comment]
Two approaches for this situation, field level and form level. I know only form level is possible for now, but wanted to share the other one for feedback.

![My Account - Account Exists 1](https://user-images.githubusercontent.com/25960021/57889905-ad547200-77fb-11e9-98b9-56bfd994145a.png)

![My Account - Account Exists 2](https://user-images.githubusercontent.com/25960021/57889906-ad547200-77fb-11e9-9df6-9fd46e4770ab.png)

**Comment by awilcoxa** [comment]
Toast solution is the preferred implementation for this defect. We should move forward assuming the second design above as the solution.

**Comment by tjwiebell** [comment]
Blocked until `createAccount` is re-factored to a functional component that can use `useToasts`. Will check with @jimbo if we want to bring that component into this scope, and merge in front of the larger #1191 left drawer re-factor.

**Comment by dani97** [comment]
@zetlen  @supernova-at  @awilcoxa 
pwa-studio/packages/venia-ui/lib/components/CreateAccount/asyncValidators.js has validateEmail action  that calls /rest/V1/customers/isEmailAvailable but we have not used it anywhere.

From latest Graphql we have isEmailAvailable query too.
![Screenshot 2019-10-13 at 9 51 45 PM](https://user-images.githubusercontent.com/13298685/66718638-b6c22480-ee03-11e9-916d-f2e62e044534.png)


We can use this as  as a validation for email input or call query before create customer mutation.
Please share your thoughts on this

**Comment by sirugh** [comment]
So I was just poking around looking for low-hanging rest calls to convert and I did this before realizing there was an issue :(

Apologies if you were already working on it @dani97! I'll push what I have and we can figure out what to do from there.

**Comment by dani97** [comment]
No problem @sirugh. I didn't start working on this issue.
