### ISSUE TITLE
[bug]: Search suggestion box - Previous pending GraphQl query should be canclled if new GraphQl query is initiated

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1225]
Steps - 
1. Go to Venia storefront and Enter search string Top    (GraphQl query should be initiated)
2. Now before search suggestion shows results ...append S to string "Top" to make it "Tops"

Expected - Query for string Top should be cancelled and results for new query Tops should be returned.
Actual - Both queries run together and updates results.

**Comment by awilcoxa** [comment]
@jimbo @sirugh for further research

**Comment by sirugh** [comment]
To add to this issue - its technically impossible to cancel the http call that is made from the apollo client. That said, if we switch to the [apollo useQuery hook](https://www.apollographql.com/docs/react/essentials/queries/#the-usequery-hook) it may "Just Work" as we are probably doing some special state storage within our hook that they aren't doing.

**Comment by bgindikagamage** [comment]
add new apollo hook for mutation .. (use psot method not get method)

**Comment by awilcoxa** [comment]
Blocked by effort needed to switch to Apollo hooks, we'll revisit at the time that we've made that switch in #1657

**Comment by sirugh** [comment]
We have since switched to apollo hooks but auto-cancellation doesn't seem baked in. We have options:

a) debounce input
b) [AbortController](https://evilmartians.com/chronicles/aborting-queries-and-mutations-in-react-apollo#howto) (This is experimental and would require polyfills.)
