### ISSUE TITLE
[bug]: Dev server and upward-js do not support HTTP2

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1271]
**Describe the bug**
Our local server environments don't use HTTP2. This is a serious performance problem.

We use [webpack-dev-server](https://github.com/webpack/webpack-dev-server/) as our local development server, and upward-js as our local production staging server. Both of those use [Express](https://expressjs.com) as their HTTP handling framework, and Express still does not support HTTP2, after promising it for years.

In [this issue](https://github.com/expressjs/express/issues/2364), Express maintainers say that Express is HTTP version-agnostic, but the maintainers of webpack-dev-server in [this issue](https://github.com/webpack/webpack-dev-server/issues/1713) disagree; since Express claims compatibility only with the `node-spdy` module, and [that module is basically unmaintained](https://github.com/spdy-http2/node-spdy/issues/339). It's a circle of pointing fingers and it suggests that we do not know when HTTP2 support will arrive as part of the natural update cycle.

**To Reproduce**
1. Check out the develop branch.
2. Run `yarn install && yarn build && yarn watch:venia`
3. Copy the dev server URL to your clipboard.
4. Open a browser tab. While it is still blank, open the developer tools and go to the Network tab.
5. Paste and load the dev server URL. 
6. Look at the Protocol column in the network request table.

**Expected behavior**
-`h2` should be the Protocol
- Requests should load in a massively parallel way, instead of the HTTP 1 limit of six at a time
- Server push should be **possible**, though not implemented yet

**Screenshots**

Dev server loading with HTTP1
![image](https://user-images.githubusercontent.com/1643758/58359480-3f3a2b80-7e49-11e9-9795-e53ecdb1f957.png)

Dev server loading with HTTP2 (I hacked it just to make the screenshot)
![image](https://user-images.githubusercontent.com/1643758/58359073-50823880-7e47-11e9-8dcd-1e9bde03a74b.png)

**Additional context**
HTTP2 is very important for us to get right. Not only for the speed and concurrency it offers and the server push capability that enables outstanding prefetch, but also for less political, more marketing-related reasons:

- It's a default expectation for a modern offering
- It's part of the PWA best practices guide
- Lighthouse rewards it
- Competitors have it

The good news is that HTTP2 is working in all of our _production_ environments.
- https://venia.magento.com through UPWARD-PHP and Magento Cloud's underlying HTTP2 support
- https://veniapwa.com through a Now.sh reverse proxy
- https://venia-canary.now.sh through a serverless architecture where the IaaS handles HTTP2

So this is a high severity issue, but not a high priority one. We need to be "native HTTP2", and right now, the only reason that our production systems are issuing HTTP2 responses is that the deployment environments are wrapping our server in their own optimization.

**Possible solutions**
First of all, we should be using native NodeJS http2, which has existed since Node 8. We shouldn't be using the `spdy` module, as express continues to do. Some ideas:

- Switch to [koa](https://koajs.com), which would require a bunch of refactoring of middlewares but not a huge architectural change
- Switch to [micro](https://github.com/zeit/micro), which would require a bigger architectural change to the dev and prod servers, but be the most aggressively fast and leading-edge
- Stop using a web server library abstraction at all and use Node's increasingly-friendly HTTP2 library directly

All of these would require, at the very least, that:
- we move off `webpack-dev-server` and re-architect our hot reloading environment
- we reimplement upward-js to use HTTP2 (and extend UPWARD with http2-only concepts to make it the best practices enforcing system it needs to be.
- we do the due diligence to ensure that we're taking advantage of HTTP2 in all our recommended deployment targets

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [x] `upward-js`
- [x] `upward-spec`

**Comment by awilcoxa** [comment]
Closing based on grooming review.
