### ISSUE TITLE
Architecture questions about UPWARD / feature requests

### ISSUE THREAD

**Issue by paales** [magento/pwa-studio#1290]
I'm trying to use UPWARD and am trying to extend it by adding additional backends, custom resolve logic etc. But.. I'm running into issues, hope you guys can answer my questions:

- The proxy doesn’t allow us to add header information to the request? Isn’t that something that should be possible in upward? We need to add Authentication bearer tokens for our endpoint.

- How can we debug the requests that are made? It seems to be throwing an error when a GraphQL query throws an error, but it doesn’t show what the query was or what the variables were.

- How can I write a method to parse a string and use the result of that somewhere? We need to split the URL into its separate segments and do a backend GraphQL query based on that.

- Can we have a fallback system in upward? I see the currently configured system will _always_ use `.html` to check if it should fetch an app-shell and other file extensions are used for static files.. But in our case we dont want to have a file extension for pages..

- It isn’t clear what the system variables are? Are those `status`, `headers`, `body`?

- It seems Upward doesn’t create a unified graph? At least not in the GraphQL sense (like Gatsby does for example). It does expose a single proxy URL (which is nice)

- I’m not sure how to actually create a plugin for Upward. I’d like to implement apollo-federation to stitch multiple GraphQL endpoints together. Also I’d like to add a GraphQL intermediate layer for a REST endpoint we have, it seems that I currently need to create a separate service for that which does all of this. (not sure if that is bad or a good thing).

In general I really like the idea, but it seems that the declarative nature is pretty limiting in its current form. Also I have my questions about programming in a `yml` file while such a file should be a configuration file, which it doesn't seem to be in its current form.. I do get the point of portability, but that puts the burden of implementing _all_ possible features on the UPWARD team. A proper plugin system would be a much better idea?

**Comment by Banhawy** [comment]
I am here also trying to figure out how to set **Authentication header** in the upward graphql proxy. Our development servers require server authentication and I've had to use product endpoint just to be able to develop anything.

**Comment by supernova-at** [comment]
Unassigning folks, as automation moved the ticket to "in development" when that is not accurate.

Pinging @zetlen @jcalcaben instead.

**Comment by niklaswolf** [comment]
+1
We also need a way for UPWARD to connect to a magento backend behind a basic auth.
