### ISSUE TITLE
Peregrine: MiniCart Component

### ISSUE THREAD

**Issue by jimbo** [magento/pwa-studio#1293]
Refactor the minicart within the right drawer, to prepare for migration to Peregrine.

- [x] Refactor class components to functional ones
- [ ] Add unit tests for new components
- [ ] @jimbo to add more checklist items here

**Comment by sirugh** [comment]
@jimbo did this already get done in #1266? I'm confused as to whether we need this issue anymore.

**Comment by awilcoxa** [comment]
ticket is meant to address rework for logical components of minicart checkout.

**Comment by jimbo** [comment]
@sirugh @awilcoxa 
- All of the work to prepare for migration to Peregrine that could happen did happen in #1266.
- The work that couldn't happen (app state, REST calls) can't happen for the cart in isolation.
- Any remaining work should be tracked under "migrate app state to Peregrine" a la #1483
