### ISSUE TITLE
[feature]: Branded first render #1275  follow up ticket

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1301]
For every visual design that is meant to be linkable and could be viewed as the first page of a session, we need a fallback for first render with minimal variation across pages of this type to satisfy the use case of slower connections.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by soumya-ashok** [comment]
@jimbo to provide options based on discussion for what is possible to implement.

**Comment by sirugh** [comment]
Moving to JIRA.
