### ISSUE TITLE
Icon component to use CSS instead of attributes

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1315]
Currently the [Icon](https://github.com/magento-research/pwa-studio/blob/develop/packages/venia-concept/src/components/Icon/icon.js) component takes an `attrs` prop that it applies directly to `react-feather` icons.

Unfortunately that requires us to keep presentational details in our JavaScript components, which is an anti-pattern.

It would be better to move these presentational details to CSS if possible.

**Comment by awilcoxa** [comment]
@supernova-at is this related to #739?

**Comment by sirugh** [comment]
The reason for this abstraction is to provide a single "wrapping" component with a minimal API without enforcing opinionated styling within the `Icon` component itself. That said, the `Icon` component also takes `classes` and applies a root style to the surrounding span. Is it possible that we can just pass styling in this way? Methinks maybe this ticket isn't necessary and we just use css classes. 


```js
// in css
.icon {
  fill: 'rgb(var(--venia-teal))'
}

// in js
return <Icon classes={classes.icon} />
```

**Comment by sirugh** [comment]
@awilcoxa I don't necessarily think these are the same issue but we should certainly take styling into account when we make changes to the icon component implementation.

**Comment by awilcoxa** [comment]
Closing as will not do
