### ISSUE TITLE
Convert City and State Fields to Autocomplete fields

### ISSUE THREAD

**Issue by soumya-ashok** [magento/pwa-studio#1333]
Currently, the City and State fields are open text fields. In accordance with best practices, it would be preferable for these to be autocomplete fields similar to search when the user begins entering in them.

As an enhancement, if it is possible to collect ZIP first and auto populate City and State, it would reduce friction in form completion during checkout.

![Screen Shot 2019-06-12 at 2.05.05 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/167b919a-f968-4c59-be37-40c3213517dd)

**Comment by LukasKiederle** [comment]
I will take this task.

**Comment by awilcoxa** [comment]
Closing for now, we'll want to revisit this again once we have a better solution for I18n.
