### ISSUE TITLE
Remove "back arrow" icon from first level of main menu

### ISSUE THREAD

**Issue by soumya-ashok** [magento/pwa-studio#1334]
The current state is this - 

![Screen Shot 2019-06-12 at 2.08.52 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/1c6d5772-28c3-4386-b461-a3311fb1703e)

The back arrow performs the same thing as the close icon. It would be preferable to make the action clear by removing the back arrow and keeping just the close icon at the topmost level of the nav. menu.

![Screen Shot 2019-06-12 at 2.12.23 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/9a1958f2-7f85-4c19-925c-040d920291cf)

**Comment by supernova-at** [comment]
Community member Narendra Vyas has picked up this ticket.

**Comment by sirugh** [comment]
Blocked on #972
