### ISSUE TITLE
Convert quantity selector from drop-select to open text field

### ISSUE THREAD

**Issue by soumya-ashok** [magento/pwa-studio#1370]
Currently, the quantity selector on the PD page for Venia functions like a drop-select that uses the native device UI

![Screen Shot 2019-06-18 at 12.38.35 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/100ea486-586d-49f0-b9c4-630c0930b518)

The recommendation is to change this input type to be an open text input that pulls up a numeric keyboard when engaged.

Use-cases to be covered
1. Shopper requests a quantity that is unavailable based on catalog data
Shopper enters the number in the quantity and makes the add to cart request, request fails and an error toast is displayed _(Mockup to be provided)_

2. Shopper requests a quantity that is more than a hard-coded max limit on the field 
Use default field-level browser validation + error message?

**Comment by awilcoxa** [comment]
related to #1324 need to review overall treatment and evaluate if we should do both changes togeter (stepper+open text) or simply one treatment

**Comment by narendravyas24** [comment]
Hi @awilcoxa :

Please let me know exactly what is to be implemented in this, in PR that I have raised #1324 stepper was implemented but as per discussion in #1281 I was suggested to use a open text instead.

Please suggest. Thanks.

**Comment by soumya-ashok** [comment]
Feedback has been provided on the stepper PR. Since the work has already been done to implement the stepper, lets go with that approach once the feedback has been addressed @narendravyas24

**Comment by narendravyas24** [comment]
@soumya-ashok : Thanks a lot, hope to receive the feedbacks soon from other members as well so that I shall start.

**Comment by awilcoxa** [comment]
closing this ticket as progress on stepper functionality has moved forward
