### ISSUE TITLE
[bug]: Lost session on graphql at PWADev local server

### ISSUE THREAD

**Issue by codynguyen1** [magento/pwa-studio#1371]
**Describe the bug**
I created a new API and use it to save a value to the session (both customer and checkout session) from parameters, then try to get it on the same request (which does not contain parameter), it's working fine on localhost Magento 2.3.1 version, but got error (session value disappear) on PWA dev server graphql (with url like: https://magento-venia-jyovz.local.pwadev:8971/graphql).

**To Reproduce**
(this is just sources I added to check session value, the problem is that all session value is lost on the pwa dev server, eg. I added custom catalog discount to logged in customer, but it won't show on Venia concept)
1. On Dataprovider I added:
$storeManager = $this->storeManager();
        if ($args) {
            if (isset($args['currency'])) {
                $this->getSession()->setData('custom', $args['currency']);
            }
        }
        return array(
            'store_id' => (int)$storeManager->getStore()->getId(),
            'currency' => $storeManager->getStore()->getCurrentCurrencyCode(),
            'config_json' => $this->getSession()->getData('custom')
        );
2. On params of graphql I added 
{
  "currency": "Sample"
}
3. Query:
query storeConfigData($storeId: Int, $currency: String) {
  simiStoreConfig(storeId: $storeId, currency: $currency) {
      store_id
      currency
    	config_json
  }
}
4. Send request, check result, remove params and send request again.

**Expected behavior**
Keep session values.

**Screenshots**
![1](https://user-images.githubusercontent.com/16347586/59746684-9c3acd00-92a1-11e9-8594-1c94b8b44725.png)
![2](https://user-images.githubusercontent.com/16347586/59746682-9c3acd00-92a1-11e9-966a-a4caba5d16cd.png)
![3](https://user-images.githubusercontent.com/16347586/59746686-9cd36380-92a1-11e9-8666-9d572fa4dd7c.png)
![4](https://user-images.githubusercontent.com/16347586/59746687-9cd36380-92a1-11e9-8d22-c4e146ecaec0.png)

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Macbook pro 2015
 - OS [e.g. iOS8.1, Windows 10]: MacOS Mojave
 - Browser [e.g. Chrome, Safari]: Chrome
 - Browser Version [e.g. 22]: 74.0.3729.169 
 - Magento Version: 2.3.1
 - PWA Studio Version: 2.1.0
 - NPM version `npm -v`: 6.4.1
 - Node Version `node -v`: v10.15.3

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [v] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [v] `upward-js`
- [v] `upward-spec`

**Comment by awilcoxa** [comment]
@zetlen @cpartica

**Comment by zetlen** [comment]
Hey @codynguyen1, thanks for filing this in such detail. The GraphQL API does not automatically hook into the PHPSESSIONID cookie. Instead, you have to pass an OAuth bearer token through the `Authorization` header. Is your GraphiQL app doing this? If not, you can add headers to the GraphQL playground available in the PWADevServer.

**Comment by codynguyen1** [comment]
Hi @zetlen ,
I see that pwa-studio is not modifying Header of request of apollo, do we have to do it manually and how to do that?
As I described above, the Graphql API is working fine if we do not use upward proxy server, so maybe there could be a solution that can be applied via Upward?

**Comment by zetlen** [comment]
@codynguyen1 Venia `upward.yml` isn't configured to do anything to headers like `Authorization`. For GraphQL requests, it's supposed to just be a simple proxy. If it's not doing that, then you've found a bug!

Can you please show me a request/response pair for calling GraphQL directly, and then a request/response pair for calling GraphQL through UPWARD? If we can narrow down how the requests are different, we can triage.

**Comment by awilcoxa** [comment]
@codynguyen1 do you have any updates here based on @zetlen last comment? Please let us know if you're still seeing the same issue.

**Comment by codynguyen1** [comment]
I had to send store id, customer id, user session id and currency code along with GraphQL/Rest requests to receive the right user-based content, now it is working fine, just hoped there could be a solution that I did not have to do it manually.
