### ISSUE TITLE
Knowledge Transfer: How to run MFTF on pwa-studio repo

### ISSUE THREAD

**Issue by cherdman** [magento/pwa-studio#1373]
@tjwiebell @dpatil-magento are the only two members of the team who know how to run the MFTF test suite against PWA Studio. It behooves us to share this knowledge with other members as a team.

**Comment by awilcoxa** [comment]
Expected output: Generate clear documentation for using the tools to run the full test suite in the existing CI environment.

**Comment by dpatil-magento** [comment]
How to run MFTF - https://github.com/magento-research/pwa-tests

**Comment by cherdman** [comment]
Dev's link above is sufficient to close out this issue.
