### ISSUE TITLE
[doc]: Missing documentation for publishing to production environment

### ISSUE THREAD

**Issue by threescs** [magento/pwa-studio#1375]
Hello pwa-studio developers , I want a simple release production documentation. For example, execute the package.json script.

**Comment by jcalcaben** [comment]
Hi @threescs, have you read our topic for deploying to Cloud?
https://magento-research.github.io/pwa-studio/tutorials/cloud-deploy/

**Comment by jcalcaben** [comment]
Moving to Blocked/Hold to bring up for discussion on the exact details we need to document about deploying to production.

**Comment by supernova-at** [comment]
The answer would be to have a Docker image that accomplishes this.

**Comment by supernova-at** [comment]
Assigned to Craig to escalate getting a Docker resource for this

**Comment by cherdman** [comment]
New link to Cloud Deploy tutorial: https://magento.github.io/pwa-studio/tutorials/cloud-deploy/

**Comment by cherdman** [comment]
Created a new issue (https://github.com/magento/pwa-studio/issues/1553) to track this work and assigning to the backlog.
