### ISSUE TITLE
[bug]: Fix useEffect dependency warnings in toasts

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#1377]
**Describe the bug**
After adding the eslint plugin for hooks we identified that there is a potential to introduce bugs around some apis such as `addToast`.

Currently, a component may import and use `addToast` within a `useEffect` hook like so:

```js
const MyComponent = props => {
  const [, { addToast } ] = useToasts();
  useEffect(() => {
    addToast({
      // some locally scoped toast props
    })
  }, []); // warning! `addToast` should be added as a dependency!
  return (<div></div>);
}
```

The above code would throw an eslint warning because `addToast` should be provided as a dependency to `useEffect`. However, if you add the `addToast` function as a dependency the effect will actually re-render endlessly adding toast after toast after toast. I believe this happens because `addToast` is re-created, but I'm not positive -- you'll need to look into this.

**To Reproduce**
1. Add `addToast` and `toasts` as dependencies to the `useEffect` [here](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/App/app.js#L72).
2. Throw an error in `miniCart.js#render`.
3. Try to close the error toast. It should keep reappearing.
4. Also add `addToast` to the dependency array in the toasts storybook file. It should endlessly loop.

**Expected behavior**
No lint errors, and the app should behave "correctly" as in when you close the toast it should invoke the `onDismiss` and it definitely should not infinitely render.

**Possible solutions**
https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies
https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often
https://github.com/facebook/create-react-app/issues/6880

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by tjwiebell** [comment]
This may also be helpful when coming up with a solution:

https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops

**Comment by awilcoxa** [comment]
needs additional investigation for solution, but issue/bug warrants further discovery

**Comment by awilcoxa** [comment]
Will revisit this after completion of Modular Component Library milestone

**Comment by sirugh** [comment]
For future-me, or whomever picks this up -- the reason we are pushing back on this is that we are making some changes to the Peregrine API and directory structure. Those may be applicable to the Toast work and since this issue will likely require a refactor we may as well wait.
