### ISSUE TITLE
CICD - Release automation improvements. 

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1383]
1. Make version label on individual PR's mandatory. Scan for highest major/minor/patch for each package and then publish. Current approach is manually updating version for each package in config file.
2. Try for tools like yarn/npm or lerna for updating dependencies and devdependecies.  Current approach is shell script for find and replace.
3. `gren release`  creating its own release notes instead of using local CHANGELOG.  Need to play around this.

**Comment by awilcoxa** [comment]
@dpatil-magento to validate issues and breakout to separate issues.

**Comment by dpatil-magento** [comment]
I will update this ticket as I start working on individual issues of this ticket.

**Comment by dpatil-magento** [comment]
Removed `2. Fix #1379 - publishConfig related issue. Current approach is to publish anything under packages directory` as its being taken care by #1540

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-43

**Comment by dpatil-magento** [comment]
Tracked in Jira.
