### ISSUE TITLE
[feature]: Update Swatch Treatments

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1390]
Immediately upon color selection on the product detail page, this is the current state -

![Screen Shot 2019-06-12 at 2.01.13 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/3b09e4c7-e928-4744-bdd0-961678172613)

The desired state is -

![Screen Shot 2019-06-25 at 9 37 21 AM](https://user-images.githubusercontent.com/25960021/60107706-f833a480-972c-11e9-8a7b-74ba3a0c63b2.png)

Acceptance Criteria:
  * Remove the `Tooltip` component and its usages (on the PDP and in the MiniCart)
  * Replace with the treatment from the image above
  * New component should be fully unit tested

**Comment by supernova-at** [comment]
This issue has been assigned to @realchriswells.

**Comment by sirugh** [comment]
@realchriswells how is this going? We are about to work on fixing the a11y for the filter modal and this will be part of it. If you are able to work on it, let us know, otherwise we will take over.

**Comment by realchriswells** [comment]
Hi @sirugh - Looks like I am running out of time to get this finished. Might be best if it's taken over from me.

**Comment by sirugh** [comment]
Thanks for letting us know @realchriswells!

**Comment by dani97** [comment]
@sirugh can you assign to me. I have made the changes. Need to write tests.

**Comment by dani97** [comment]
Drafted PR #1512
