### ISSUE TITLE
How to add custom route, or handle cms page?

### ISSUE THREAD

**Issue by PiotrSzlagura** [magento/pwa-studio#1394]
**Describe the request**
Hello!
I'm trying to run some custom routes and cms pages using PWA Studio, but I have no idea where to start. I found that you use `urlResolver` from graphql, but so far it can't handle cms pages or my custom url rewrites. Where should I start? I failed to find anything regarding this topic in docs.

**Possible solutions**
It would be great if documentation included instructions on how to handle such situations. If there is topic about this which I missed, please show me where can I find it.

**Please let us know whether this is a new topic or a topic change request:**
 - [x] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by awilcoxa** [comment]
#1499 contains refactors which will be documented before merge and should add clarity here
