### ISSUE TITLE
[discussion]: How should we handle logging around `useReducer` and other hooks?

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#1397]
**Is your feature request related to a problem? Please describe.**
With the advent of `useReducer` usage we will inevitably lose some of the logging currently handled by our [logging middleware](https://github.com/magento-research/pwa-studio/blob/develop/packages/venia-concept/src/middleware/log.js). We should replace it with something similar.

**Describe the solution you'd like**
Some logging solution that isn't too complex and doesn't affect the runtime.
Should be disabled when `process.node.ENV === 'production'`.

**Describe alternatives you've considered**
#1374 adds some basic logging but @jimbo and I have discussed alternatives such as a composed logging functionality:

```js
/**
 * A higher order function that creates a named log group and returns a wrapped
 * function whose logs will be contained within the log group.
 *
 * @param {string} name the group's name
 * @returns {Function} a wrapped function
 */
export const withLogger = (name = 'LOG') => fn => (...args) => {
    console.groupCollapsed(name);
    const result = fn(...args);
    console.groupEnd();

    return result;
};

/**
 * A higher order function that wraps a reducer function and logs action type,
 * payload, and result state to the browser console.
 * @param {*} reducer a reducing function to wrap with logging
 * @returns {Function} a wrapped reducer function
 */
export const withReducerLogger = reducer => (state, action) => {
    const result = reducer(state, action);

    console.group(`action: "${action.type}"`);
    console.group('payload');
    console.log(action.payload);
    console.groupEnd();
    console.group('next state');
    console.log(result);
    console.groupEnd();
    console.groupEnd();

    return result;
};

// Logs each update/dispatch with above logges.
withLogger('myLogger')(withReducerLogger(useReducer(reducer, initialState)));
```

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by awilcoxa** [comment]
Closing for now, will re-open or address if issue becomes a priority.
