### ISSUE TITLE
[SPIKE] Venia App Caching and Cache Busting

### ISSUE THREAD

**Issue by tjwiebell** [magento/pwa-studio#1400]
Placeholder for a few general problems with our ServiceWorker file, and how we're handling updates to the application.

### Problem
Currently, when an update is pushed out to Venia, you will almost certainly run into some unexpected behavior with caching, and the only way to recover is to do a nuclear cache clear (Chrome DevTools > Application > Clear Storage > Clear site data + Hard Refresh). This is not a great user experience for anyone, and there's no way we could release this as production ready until we've come up with a way to bust the cache.

### Potential Solution
1. Investigate our workbox configuration in `sw.js`, and validate that we're using the correct caching strategies to support a production app. Most of this code came from the community, and the project has matured a lot since its creation, so there may be some necessary changes to support cache busting. An area I would explore is the strategy for `*.html` files, and how it might conflict with the stale while revalidate strategy of javascript files. I suspect this is causing the app shell to be refreshed from the server, but it's expecting to serve js content from the cache, which doesn't exist. Due to this setup, refreshing the page will result in the correct render, because the revalidate in the background actually populates the cache. Info about strategies here: https://developers.google.com/web/tools/workbox/modules/workbox-strategies

2. If this were a standard web app, an ideal solution is to gracefully handle app updates on request (ie. network first requests invalidate the cache, using some sort of file hashing). This somewhat violates the vision of PWA, and we should try to always serve assets from the cache, and validate in the background. Since we don't want these failed first renders, a solution could be a background task that revalidates, but instead of automatically busting with the `StaleWhileRevalidate` strategy, we display a toast to the user saying there are updates available for the app, and to bust the cache based on a user event of accepting the update. There appears to be a feature in workbox, which is worth exploring: https://developers.google.com/web/tools/workbox/modules/workbox-broadcast-cache-update

@zetlen - please fill in any additional detail here, or if you have a desired solution for Venia that should be explored that isn't covered above.

**Comment by ericerway** [comment]
Worth reviewing Workbox v5 (alpha) when this starts to see how this might be affected. https://twitter.com/workboxjs/status/1149021887709753344

**Comment by awilcoxa** [comment]
Will be addressed in discovery/research effort for #1623
