### ISSUE TITLE
Graphql request with "Store" in header doesn't return the correct data from specific store.

### ISSUE THREAD

**Issue by Akiyama246** [magento/pwa-studio#1409]
**Describe the bug**
Graphql "Store" header value is set, but data from all store is returned.

**To Reproduce**
1. Go to graphql playground or tools that could query graphql
2. Query for CmsBlocks for example
3. Set "Store" header value to a specific store. (assume having 2 stores, A and B. "Store: B" header is set in graphql request)
4. CMS block data from all stores is returned.

**Expected behavior**
CMS block data from store B is returned.

**Additional context**
Venia and upward doesn't have an implementation on store code in store url.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
 - Browser [e.g. Chrome, Safari]: Any
 - Magento Version: 2.3.1
 - PWA Studio Version: 3.0
 - NPM version `npm -v`: 6.4.1
 - Node Version `node -v`: 10.15.3

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by skynixukraine** [comment]
@Akiyama246  please reopen, it still does not pass store code to headers
