### ISSUE TITLE
[docs]: Add "How to add env variables to .env" to docs

### ISSUE THREAD

**Issue by anthonyhacart** [magento/pwa-studio#1413]
**Describe the bug**
If I want to select another website using MAGENTO_WEBSITE_CODE variable in the .env file, Venia still grab the defautl website products

**To Reproduce**
1. Go to .env of venia-concept
2. Change MAGENTO_WEBSITE_CODE and put another website from your current Magento
3. Recompile and run Venia
4. See the results, all products and categories come from the base website store

**Expected behavior**
We should have product of the chosen MAGENTO_WEBSITE_CODE

**Please complete the following device information:**
 - Device:  PC
 - OS : Ubuntu
 - Browser: Chrome
 - Magento Version: 2.3.2
 - PWA Studio Version: 3.0.0
 - NPM version `npm -v`: 6.4.1
 - Node Version `node -v`: 10.14.1

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by MarynaVozniuk** [comment]
@magento give me develop instance

**Comment by awilcoxa** [comment]
Further discovery: 
* all new variables must defined in the build pack variable definitions file; document this carefully so it's easy 
* confirm how to access different website (store) catalogs through GQL

**Comment by supernova-at** [comment]
This may be a documentation issue.

**Comment by bordeo** [comment]
@awilcoxa how can we define new variables?

**Comment by awilcoxa** [comment]
Removed bug label and categorizing this as a new feature request for multi-store support. Moving to backlog as new feature prioritization for grooming.

**Comment by zetlen** [comment]
@bordeo It is a documentation issue as @supernova-at pointed out. We should make it clearer in documentation that you're supposed to add the new env var definition to `packages/pwa-buildpack/envVarDefinitions.json`.

**Comment by jcalcaben** [comment]
Closing this issue since we just published topics covering environment variables:

* [Configuration Management](https://magento.github.io/pwa-studio/pwa-buildpack/configuration-management/)
* [Create environment file](https://magento.github.io/pwa-studio/pwa-buildpack/reference/buildpack-cli/create-env-file/)
* [Load environment file](https://magento.github.io/pwa-studio/pwa-buildpack/reference/buildpack-cli/load-env/)
