### ISSUE TITLE
CICD - Attach AWS Policies to IAM role via pull request

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1438]
TBD -  Need to check with @sharkySharks before we start working on this. 

Example - attach as part of pull request AWS CLI - https://docs.aws.amazon.com/cli/latest/reference/iam/attach-role-policy.html

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-42

**Comment by dpatil-magento** [comment]
Refer Jira ticket.

**Comment by sharkySharks** [comment]
we should discuss at some point putting your infrastructure in code outside of the bash scripts, like with terraform.
