### ISSUE TITLE
[feature]: Url-Resolver doesn't support Multistore-Setup

### ISSUE THREAD

**Issue by niklaswolf** [magento/pwa-studio#1451]
Right now the urlResolver doesn't support multistore-setups.
https://github.com/magento-research/pwa-studio/blob/bf5a040944f94cadcdb5b1bb58d71bbf645eaa75/packages/peregrine/lib/Router/resolveUnknownRoute.js#L94

In the GraphQl documentation (https://devdocs.magento.com/guides/v2.3/graphql/send-request.html) it says, that you have to provide the store-code as an additional header. But since the header is hardcoded in the urlResolver, there is no way to change the headers for the urlResolver query.
We use the `Page` component from Peregrine, which uses `resolveUnknownRoute` indirectly through `MagentoRouteHandler`.
There has to be a way to at least be able to add a store header to this query.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by Akiyama246** [comment]
Is anyone actively working on this?

**Comment by niklaswolf** [comment]
See https://github.com/mothership-gmbh/pwa-studio/blob/1451-urlresolver-multistore/packages/peregrine/lib/Router/resolveUnknownRoute.js 
I'd be happy for some testcase contributions that cover these changes.

**Comment by zetlen** [comment]
This is a good observation and a real problem, but I don't think it will be fixed in `urlResolver`. We want to replace `urlResolver` with a clearer concept of `Route` in the schema. I'll link to that proposal document once it's ready. Then, it would be `Route` where we add multi-store capability and other conventions like that.

**Comment by niklaswolf** [comment]
@zetlen Okay, I did not know about your plans to replace the urlResolver. I'm looking forward to see the proposal!

**Comment by zetlen** [comment]
@niklaswolf I've opened the architecture proposal here! https://github.com/magento/architecture/pull/226

**Comment by zetlen** [comment]
I think we should rephrase this issue to cover multistore support throughout the PWA system. How would you feel about that?

**Comment by niklaswolf** [comment]
@zetlen sure, go for it. I did not want to open such a big issue just out of a bug report, but as it turned out, it's of course a totally different point

**Comment by cherdman** [comment]
Closing in favor of later issue regarding multi-store support.
