### ISSUE TITLE
Discovery: GQL research for filters

### ISSUE THREAD

**Issue by awilcoxa** [magento/pwa-studio#1452]
We need to determine if there are any blockers for GQL filters that will prevent us from working on #1432

**Comment by supernova-at** [comment]
Just had a meeting with the GraphQL team, here's where we stand:

[GraphQL #500](https://github.com/magento/graphql-ce/issues/500) (MC-18450) may or may not be included in 2.3.3. We will know by August 9.

If the feature is included in 2.3.3 we can update Venia to use it and keep the existing UI / UX.

If the feature is not included in 2.3.3 we are left with a non-functional UI in Venia.
We have some options there too. We could:
* Change the filters to not include configurable product details. We could filter on things like `price`.  The full list is available [here](https://github.com/magento/graphql-ce/blob/dffe94dcd89a02ef3c3a7e5bec28f25346a9a67a/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L279-L315). I don't think any of them are that useful for filtering purposes.
* Put the UI behind a feature flag and turn it off until we become unblocked.

If the GraphQL feature does not make it into 2.3.3 my recommendation is that we put the filtering UI behind a feature flag and turn it off until it is implemented.

**Comment by supernova-at** [comment]
We could create a ticket to use the REST API for this and open it up for community contribution since it is a highly desired feature by some key stakeholders.

**Comment by awilcoxa** [comment]
I'm going to place this in blocked/hold for now until we hear the final outcome from GQL team on Aug 9th. Additional action items will be determined pending that update.

**Comment by cherdman** [comment]
Quick update: Talked to the GraphQL team and they have permission to work on this post-8/2 code freeze. However, there is still a lot of risk to getting this into 2.3.3. As stated, they'll know more by around August 9th.

**Comment by supernova-at** [comment]
This did not make it into `2.3.3`.

**Comment by supernova-at** [comment]
Closing this discovery issue as resolved: #1432 is blocked by [graphql-ce #500](https://github.com/magento/graphql-ce/issues/500).
