### ISSUE TITLE
[bug]: Desktop Only  -  Add product to cart > click checkout , without closing checkout right drawer > Sign in to account > Shows error.

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1460]
**Describe the bug**
Add a product to cart and click on checkout button. Now without closing right drawer, click anywhere on the page then sign in to account from main menu. After login > User gets an error, PFA screen.

**To Reproduce**
1. Go to Venia and add a product to cart.
2. Click on checkout button.
3. Click on "Ship To" link. (Shipping address input form displayed)
4.  Click anywhere in the page to close right drawer. (Just Dont Close right drawer by clicking X icon).
5. Sign in to account via main menu.

**Expected behavior**
User should be logged in without any errors.

**Actual behavior**
User is logged in but gets an error. Which disappears after sometime.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/ccdc46ec-38d0-4bb4-8424-57ca184a387d)

**Comment by dani97** [comment]
@dpatil-magento couldn't reproduce the issue. Can you check this still an issue.

**Comment by dpatil-magento** [comment]
@dani97 Updated steps, can you try with updated steps once?    

I'm able to reproduce with updated steps on https://develop.pwa-venia.com/

**Comment by dani97** [comment]
Yes I can reproduce it now, care became empty too
