### ISSUE TITLE
[bug]: WARNING: heuristic fragment matching going on!

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#1474]
**Describe the bug**
When you visit a simple product detail page you will see this error in the chrome console
`WARNING: heuristic fragment matching going on!`

Not 100% verified but when you visit a category page with multiple simple products the error gets thrown multiple times preventing the page from loading 

**Please complete the following device information:**
 - Device [Mac]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [Chrome]:
 - Browser Version [76]:
 - Magento Version: 2.3.2
 - PWA Studio Version: 3.0.0
 - NPM version `6.4.1`:
 - Node Version `10.15.1`:

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by sirugh** [comment]
I'm not seeing this error. Can you share any more info? What constitutes a _simple_ product detail page?

**Comment by Jordaneisenburger** [comment]
@sirugh When i clone pwa-studio (no edits) and use the provided backend url and visit this page (see screenshot) i get the warnings. I tried the solution provided in this [medium](https://medium.com/commutatus/whats-going-on-with-the-heuristic-fragment-matcher-in-graphql-apollo-client-e721075e92be) post and it seemed to work but not all of the times if i recall correctly. Don't have enough knowledge about apollo/graphql yet to decide if this is a good solution.
<img width="1675" alt="Screenshot 2019-07-29 at 20 08 53" src="https://user-images.githubusercontent.com/19858728/62071743-79ef8400-b23d-11e9-9a6b-ec9aace2468a.png">

**Comment by awilcoxa** [comment]
We should/will tackle this as a larger effort for improving Apollo usage and overall performance. Backlogged for now.

**Comment by awilcoxa** [comment]
@supernova-at

**Comment by Jordaneisenburger** [comment]
Adding #1662 for more context about the solution.
