### ISSUE TITLE
[bug]: Iphone 5/SE - Unable to select product attribute size/color in edit cart window if user first does scroll and then try to select color or size.

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1486]
**Describe the bug**
Iphone 5/SE - Unable to select product attribute size/color in edit cart window if user first does scroll and then try to select color or size.  Issue does not happen on pixel3 might be because of bigger screen size.

**To Reproduce**
1. Add product to cart and go to Edit cart window.
2. Scroll page either up or down.
3. Try to select a size or color attribute.

**Expected behavior**
User should be able to select attributes.

**Actual behavior**
Attributes not getting selected.

**Note**
Issue does not happen in desktop.

**Comment by awilcoxa** [comment]
Dev can you add a screen shot/gif of this?

**Comment by awilcoxa** [comment]
Also for follow up discussion, device support requirements.

**Comment by dpatil-magento** [comment]
This scenario is hard to capture as it happens only on device and not on desktop or Chrome dev tools mobile view.  But If you are unable to reproduce by following the steps please let me know.

**Comment by awilcoxa** [comment]
Closing as won't fix, while we haven't formalized a device support policy I'm making the call that Iphone5/SE falls outside of the future scope.
