### ISSUE TITLE
[bug]: Broken add to cart flow when product is out of stock

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#1490]
**Describe the bug**
When in the store configuration "Display Out of Stock Products" equals "no" and one or more simple products on a configurable product are 'out of stock' even when qty is more than 0. The add to cart breaks with the following error. 
![image](https://user-images.githubusercontent.com/19858728/62141550-0ad16880-b2ed-11e9-829b-a27e20fcbebd.png)

This happens because inside `src/pwa-studio/packages/venia-concept/src/util/appendOptionsToPayload.js` the `findMatchingVariant`function is being called. Inside that function there is no check if the actual product exists and therefor it tries to do get `[code]` on `null`

**To Reproduce**

**important**: cataloginventory/options/show_out_of_stock needs to be set to "No"

1. Go to a configurable product that has at least 1 product variant that has stock status "out of stock" in the config
2. Click on an option that you know is in stock
3. Click add to cart
4. open browser console and see the error

**Expected behavior**
We expect a product to be added without errors

**Possible solutions**
Filter out only the variants that have a product object inside `appendOptionsToPayload`

**Please complete the following device information:**
 - Device Mac
 - OS MacOS 10.14.6 Beta
 - Browser Chrome
 - Browser Version 76:
 - Magento Version: 2.3.2
 - PWA Studio Version: 3.0.0
 - NPM version `6.4.1`:
 - Node Version `10.15.1`:

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by Jordaneisenburger** [comment]
This seems to resolve the issue (at least in our setup). But not sure if this is a decent solution.

See highlight area in screenshot.
![image](https://user-images.githubusercontent.com/19858728/62143244-f2af1880-b2ef-11e9-8b22-3d2e7b3497b2.png)

**Comment by Jordaneisenburger** [comment]
seems to be related to https://github.com/magento-research/pwa-studio/issues/1459

**Comment by zetlen** [comment]
@Jordaneisenburger In your screenshot, it looks to me like `findMatchingVariant` ought to do the filtering. As it is, you're iterating through the variants at least twice, and maybe that's not necessary...

**Comment by Jordaneisenburger** [comment]
@zetlen yep you are totally right. I checked the following (see screenshot highlight) and that seems to work as well.
![image](https://user-images.githubusercontent.com/19858728/62513507-9a5ea600-b81c-11e9-9673-03619587b5e0.png)

**Comment by awilcoxa** [comment]
@Jordaneisenburger is this still an active issue? Can you ping us/update if so.

**Comment by awilcoxa** [comment]
marked as P3S3 low priority after grooming

**Comment by davemacaulay** [comment]
This issue is tracked under https://jira.corp.magento.com/browse/PWA-125

**Comment by sirugh** [comment]
Closing as cancelled
