### ISSUE TITLE
[bug]: Built in Docker container doesn't start a working server

### ISSUE THREAD

**Issue by dimitar-ivanov-tryzens** [magento/pwa-studio#1504]
**Describe the bug**
When a docker container is started from the provided script it doesn't start a healthy working website. After a successful build, the webserver instead of loading Venia returns Invalid Host header

**To Reproduce**
1. Go to `pwa-studio` root
2. Execute `bash docker/run-docker`
3. Wait for the image to build and for the dev server to start
4. Visit https://pwa-docker.localhost in browser. Instead of PWA, Invalid Host Header is shown

**Expected behavior**
I would expect Venia homepage to load.

**Additional context**
When the dev server is loaded it displays the following message:
```
PWADevServer ready at http://0.0.0.0:8080/
GraphQL Playground ready at http://0.0.0.0:8080/graphiql 
```
I would expect here the domain specified as a DEV_SERVER_HOST to show, but I might be wrong on this.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
 - OS [e.g. iOS8.1, Windows 10]: Ubuntu 18
 - Browser [e.g. Chrome, Safari]: Firefox
 - Browser Version [e.g. 22]: 68
 - Magento Version: MAGENTO_BACKEND_URL=https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/
 - PWA Studio Version: 3.0
 - NPM version `npm -v`: supplied from container
 - Node Version `node -v`: supplied from container

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by dani97** [comment]
I too experience this issue. Because of this, I could not check service worker :(

**Comment by awilcoxa** [comment]
for follow up with @cherdman regarding docker resourcing
