### ISSUE TITLE
 Research- Perfomance test framework for pwa-studio

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1510]
Some interesting  tools:
1. Lighthouse/Lighthousebot - https://github.com/GoogleChromeLabs/lighthousebot
2. Webpagetest - https://www.webpagetest.org/
                              https://github.com/marcelduran/webpagetest-api
3. Speedtest.io > Leaderboard > https://www.sitespeed.io/documentation/sitespeed.io/performance-dashboard/#up-and-running-in-almost-5-minutes

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-39

**Comment by dpatil-magento** [comment]
Its completed, running webpagetest on CI.
