### ISSUE TITLE
Update Repository References in Internal Tools

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1524]
The repository has moved. Existing browser traffic to the old location (https://github.com/magento-research/pwa-studio) will redirect to the new location (https://github.com/magento/pwa-studio), but we should update references where possible in case that ever changes.

Places to change:
  - [ ] PWA Project Home in Confluence

**Comment by supernova-at** [comment]
@awilcoxa, @soumya-ashok are there other places like this we should change?

**Comment by soumya-ashok** [comment]
@supernova-at I have a bunch of issues in the current backlog linked to UX items for tracking. Would those need to be updated?

**Comment by supernova-at** [comment]
> I have a bunch of issues in the current backlog linked to UX items for tracking. Would those need to be updated?

Where are they linking, can you give me an example URL?  I'm thinking they probably don't.

**Comment by supernova-at** [comment]
Updated PWA Home page in Confluence
