### ISSUE TITLE
Move PWA Studio companion repositories

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1526]
Now that the `pwa-studio` repository has moved, we may want to move all or some of the following companion repositories:

- [ ] https://github.com/magento-research/upward-php
- [ ] https://github.com/magento-research/magento2-upward-connector
- [ ] https://github.com/magento-research/pwa-tests

**Comment by supernova-at** [comment]
@dpatil-magento , @zetlen, @tjwiebell :

1. Are there any other repositories that should be added to this list?
2. Are there any repositories that can be removed from this list?

**Comment by dpatil-magento** [comment]
Looks good, nothing else I can think of.

**Comment by zetlen** [comment]
@supernova-at I think we have to move these as well:

https://github.com/magento-research/directive-parser (for parsing RootComponents)
https://github.com/magento-research/magento-eslint (for Magento-wide eslint config we should all use)

**Comment by jcalcaben** [comment]
should the code samples repository be moved too, or can it stay in magento-research?

**Comment by zetlen** [comment]
I think it can, since nothing is consuming it as a dependency.

**Comment by supernova-at** [comment]
These repositories are staying in `magento-research` for now.
