### ISSUE TITLE
[bug]: On PDP page if user selects size option then same images reload, unwanted api/graphql calls?

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1528]
**Describe the bug**
Go to Venia PDP page for configurable product and select size. Same Product images reloads which is not required.

**To Reproduce**
1. Go to Venia PDP page for configurable product example - /valeria-two-layer-tank.html
2. Select a size.

**Expected behavior**
Size should get selected and no other actions should happen.

**Actual behavior**
Same set of Images reloads which is not required.

**Comment by sirugh** [comment]
I think this happens because we recreate the map of `mediaGalleryEntries` in `productFullDetail.js`. I believe this fully remounts the carousel/thumbnails.

**Comment by zetlen** [comment]
Perfect for a React-based learning bug. We're doing some extra renders and we need to stop.
You'll need:
- The Chrome step debugger
- React developer tools

**Comment by shakyShane** [comment]
I've looked into this - the issue is actually because the initial page render may return a media collection containing 3 items - but then following an option selection there is always 1 extra image - this causes the re-render and fetch of a separate image.

**Comment by sirugh** [comment]
I actually think this was fixed when I worked on the carousel or product page talons.

**Comment by sirugh** [comment]
Yea just double checked on `develop`, this is not an issue any more.
