### ISSUE TITLE
[CICD] - Retire now.sh for pwa-studio

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1546]
As we have AWS instances running. We can retire now.sh deployments. 

AWS - 
`master` - https://prodtest.pwa-venia.com/
`develop` - https://develop.pwa-venia.com/
Individual PR's - https://PR-NUMBER.pwa-venia-staging.com/ example - https://pr-1536.pwa-venia-staging.com/

**Comment by sirugh** [comment]
@dpatil-magento do we post a comment/have an easily accessible link in each PR now that AWS auto deploys? If not, we should :D

**Comment by supernova-at** [comment]
> @dpatil-magento do we post a comment/have an easily accessible link in each PR now that AWS auto deploys? If not, we should :D

It looks like [danger](https://github.com/magento/pwa-studio-cicd/blob/master/pwa-studio-configs/dangerfile.js#L468-L469) should be doing that for us.

**Comment by dpatil-magento** [comment]
@supernova-at   Mr @sirugh implemented it :)
