### ISSUE TITLE
[BUG]: png's with transparent background are changed to black background

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#1547]
**Describe the bug**
When product images are png's and have a transparent background the background will be changed to black by `@magento/expres-sharp` inside `packages/pwa-buildpack/node_modules/@magento/express-sharp/lib/transform.js` at line `17` format is hardcoded set to jpeg.

When i remove `format` from the object i get the desired effect: images with transparent backgrounds. You also want to add .png support to `packages/pwa-buildpack/lib/Utilities/addImgOptMiddleware.js` I know .png's are not the best image format for the web but a lot of merchants use them and we should support it.

**Expected behavior**
Show images the same way they are uploaded

**Screenshots**
![Screenshot 2019-08-11 at 15 01 11](https://user-images.githubusercontent.com/19858728/62834163-e9f00800-bc48-11e9-8563-1f5bc910bcd3.png)

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by DanielRuf** [comment]
Seems the package still links to the old repo: https://www.npmjs.com/package/@magento/express-sharp

Where is the package hosted?

**Comment by Jordaneisenburger** [comment]
Looks to me like this is the package magento uses but also in this one the .jpeg seems hardcoded.
https://github.com/pmb0/express-sharp/blob/develop/lib/transform.js

**Comment by DanielRuf** [comment]
I don't think so. There is no recent change which relates to the last two releases on npmjs.

They forked it and host it under the magento org account.

But still links to the original repo owned by the creator, not any person from the Magento teams.

**Comment by Jordaneisenburger** [comment]
In terms of the bug i don't think it matters where the repo resides?

**Comment by DanielRuf** [comment]
> In terms of the bug i don't think it matters where the repo resides?

At least if we want to fix it (contributors) ;-)
Would be great if we could contribute to it.

**Comment by Jordaneisenburger** [comment]
> > In terms of the bug i don't think it matters where the repo resides?
> 
> At least if we want to fix it (contributors) ;-)
> Would be great if we could contribute to it.

Agreed.

**Comment by sirugh** [comment]
https://github.com/magento-research/express-sharp

**Comment by Jordaneisenburger** [comment]
@zetlen created a PR for this issue see https://github.com/magento-research/express-sharp/pull/1
