### ISSUE TITLE
[doc]: Tutorials and documentation on production deployment

### ISSUE THREAD

**Issue by cherdman** [magento/pwa-studio#1553]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to learn about how to deploy my PWA to a production environment through documentation and/or tutorials.

**Describe the solution you'd like**
ex. Docker

**Describe alternatives you've considered**
Magento Cloud: https://magento.github.io/pwa-studio/tutorials/cloud-deploy/

*This ticket is in response to https://github.com/magento/pwa-studio/issues/1375 and #1402 *

**Comment by jcalcaben** [comment]
This issue is currently blocked by: #1244

**Comment by sirugh** [comment]
Closing this. See https://magento.github.io/pwa-studio/tutorials/cloud-deploy/ for tutorials about prod deployment!
