### ISSUE TITLE
Investigate Replacing some CICD with GitHub Actions

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1568]
[GitHub Actions](https://github.com/magento/pwa-studio/actions) can perform a lot of the things we're currently doing in https://github.com/magento/pwa-studio-cicd such as running tests and linter on push, adding labels to pull requests based on which files changes (all of our `pkg:` labels), and more.

Our actions can be defined right here in our own repository, some other repo, or from a docker image. 

GitHub also maintains a [marketplace](https://github.com/marketplace?type=actions) to find / share common actions.

**Comment by supernova-at** [comment]
Here is also a curated list of useful actions: https://github.com/sdras/awesome-actions.

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-37

**Comment by sirugh** [comment]
We've got a pretty decent CICD set up right now. Closing this as stale. We can open up specific feature/tooling requests in new issues :)
