### ISSUE TITLE
Update Contributing Guidelines

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1573]
**Describe the request**

Now that we have moved to the `magento` organization and we have a new process enforced by EngComm tools, we should agree on a process for ticket assignment and update our `CONTRIBUTING.md` file accordingly.

**Possible solutions**

The primary objective is to define a process that the community (and we) follow for assigning issues to community members.

**Comment by sirugh** [comment]
Closing this as stale.
