### ISSUE TITLE
[feature]: CICD - Add 6 chars of commit hash to venia storefront URL deployed on AWS.

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1576]
**Is your feature request related to a problem? Please describe.**
So currently storefront URL just has PR number which would cause confusion on which commit is being deployed.  Ideal scenario would be when pr-build job fails then still AWS instances would be running previous version of App and it might be confusing for team who dont not have access to AWS.

**Describe the solution you'd like**
Add 6 characters of commit hash which is shown on github.

**Describe alternatives you've considered**
NA

**Comment by supernova-at** [comment]
Is related to #1227 .

**Comment by dpatil-magento** [comment]
Closing the issue as #1227 will solve the problem.
