### ISSUE TITLE
Add all Public API components to Storybook

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1578]
Currently Venia UI's Storybook only has a handful of components available:

1. Image
1. Header
1. MiniCart
1. SearchBar
1. ToastContainer
1. Braintree Dropin

Since all of the components in Venia UI are considered part of our Public API, we should expect partners to be using them and therefore we should add them to our Storybook.

**Comment by sirugh** [comment]
I think we should turn this into a milestone and then create issues for each of the components missing storybook. Then it's easily trackable and it has a nice pretty progress bar for people who care about nice pretty progress bars :D

**Comment by supernova-at** [comment]
Internal core epic PWA-1031 covers Storybook improvements.
