### ISSUE TITLE
Publish Venia UI Storybook

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1579]
Currently, the only way to view the Venia UI Storybook is to clone & install the repository and run `yarn run storybook:venia`.

It would be great if we published the Storybook much like we do with the Venia app itself.

We should publish both the latest `release` version of the Storybook (including the release number would be a nice touch), along with the latest version on `develop`.

**Comment by jcalcaben** [comment]
If we can't get a dedicated server to host this, we can export the latest release version as a static site and add those files as a subdirectory to the pwa-devdocs site.

https://storybook.js.org/docs/basics/exporting-storybook/

**Comment by supernova-at** [comment]
This will be covered by internal core epic PWA-1031.
