### ISSUE TITLE
[feature]: Create typescript definitions for peregrine and venia-ui

### ISSUE THREAD

**Issue by paales** [magento/pwa-studio#1585]
**Is your feature request related to a problem? Please describe.**
We're currently trying to use Peregrene / venia-ui components in our own polyglot frontend stack which is written in typescript. We'd like to have type safety when using the React elements.

**Describe the solution you'd like**
It would be nice if there are typescript definition files available for all components that can be used in an external system.

**Describe alternatives you've considered**
Well, I think there is great value in developing PWA studio in TypeScript completely, but that is more of an internal choice than it's an external feature request.

**Additional context**
The editor doesn't understand how the component works:
![Schermafbeelding 2019-08-21 om 10 26 04](https://user-images.githubusercontent.com/1244416/63415481-1997d080-c3fe-11e9-8b74-0962d426c029.png)

**Please let us know what packages this feature is in regards to:**
- [x] `venia-ui`
- [x] `peregrine`

**Comment by larsroettig** [comment]
@paales best is maybe close it and move information in the new ticket what's you thing about this approve
