### ISSUE TITLE
[bug]: Uncaught Invariant Violation: You must pass a component to the function returned by connect. Instead received undefined

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#1590]
**Describe the bug**

Occasionally, with a dev server running like `yarn run watch:falkowski` a code change forcing a hot-reload will trigger this error:

> Uncaught Invariant Violation: You must pass a component to the function returned by connect. Instead received undefined

Which traces into the `client.js` file (I think, will update if I see it again).

Hard refreshes don't fix it, but quitting and restarting the watcher works (every time). Everything is fine for a while, then it'll randomly happen later. Not sure why.

**To Reproduce**

Not sure exactly. Have a watcher running, and write code. It only happens during a hot-reload (not launching a server).

**Expected behavior**
Hot-reloading stays hot and reloading.

**Screenshots**

**Additional context**
Reference to Slack thread: https://magentocommeng.slack.com/archives/C71HNKYS2/p1566412835381800?thread_ts=1566411734.381300&cid=C71HNKYS2

For me, it occurred working on the `create-account` route.

In Slack, others mentioned it seems to occur on Root Components.

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Magento Version: 2.3.2
 - PWA Studio Version: August 12 (am) 2019
 - NPM version `npm -v`: 6.9.0
 - Node Version `node -v`: 10.16.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by brendanfalkowski** [comment]
Possibly related to circular dependency or wrong default import between components: https://haodong.io/redux-testing-invariant-violation-error

**Comment by sirugh** [comment]
To add to this, I was also getting this error when changing `ProductFullDetail` which is imported by `Product`, a RootComponent.

**Comment by brendanfalkowski** [comment]
Just reproduced it, here's the error:

![Screen Shot 2019-08-22 at 11 25 17 AM](https://user-images.githubusercontent.com/214924/63539730-98a90980-c4cf-11e9-9bbc-f3f13bde4769.png)

And exactly what I did beforehand:

1. Restarted my watcher.
1. Page loaded fine.
1. Edited `packages/ce/src/components/CreateAccountPage/createAccountPage.js`
1. Code change: added our `<Heading>` component as an import, and used it to add an H2.
1. Saved.
1. Hot-reloader hanged.

**Comment by zetlen** [comment]
This is maybe a harder problem to solve, but it's probably solvable with some carefully chosen breakpoints. You'll need:

- The Chrome debugger
- The React developer tool extension

**Comment by brendanfalkowski** [comment]
Retested after updating to PWA Studio 4.0.0 + dependencies in our project. The errors are slightly more informative now (probably the React version bump), but the issue still occurs.

![Screen Shot 2019-10-22 at 11 51 44 AM](https://user-images.githubusercontent.com/214924/67319955-76793b00-f4c2-11e9-9814-415bc24d1cb4.png)

The workaround (just restart the watch process) is fast enough that I probably can't justify tracing it short-term until patience hits zero.

**Comment by zetlen** [comment]
Thanks for the update. This _might_ be an incompatibility between Redux `connect()` and lazy-loaded React classes. This shouldn't normally happy, because `connect()` should be called synchronously at class definition. But if you need to late-bind `connect()`, I found this article with a method:

https://medium.com/front-end-weekly/the-power-of-redux-and-react-lazy-bdeb21028f43

**Comment by tjwiebell** [comment]
@brendanfalkowski - Sounds like this is low priority for you, but was curious if you could help with some additional repro detail. This error looks familiar, but I haven't seen it pop up in the last couple weeks, so I'm curious if it was resolved by a component re-factor in the latest `develop` line.

**Comment by brendanfalkowski** [comment]
@tjwiebell — If I'm roughing out UI for 6 hours, hot-reload errors probably cause me to restart the watch process 25-75x. Most days I probably lose 10-20 minutes to restarting the build.

The workaround is easy and always works (restart the build) so it's high-annoyance but low-priority for me to spend time on — only because it looks like tooling's domain and looks like a rabbit hole.

Over PWA 2.x, 3.x, and 4.x the errors logged to devtools have changed, but the behavior causing it has always been similar. I just can't justify the time to chase each variant when I know restarting the build gets me back to work, and it'll probably change in PWA 5.x or maybe get fixed forever.

My current MO is getting modules into QA, and this problem seems (so far) to only affect the watch command (i.e. me) and not the stage command (i.e. users). So I'm choosing to be patient with it.

I can reproduce the two most common errors at the drop of a hat by simple combinations of adding an import, using an unused import, or removing an import while the watcher is running.

I've just learned to stop the watcher, add my imports, use them, then restart the watcher when I'm roughing out UIs. That's the good DevEx currently.

Attached two videos showing the most common issue (memory leak):
https://share.getcloudapp.com/12uEjmP4

And a new one I haven't seen before:
https://share.getcloudapp.com/WnuAW9kQ

**Comment by sirugh** [comment]
@brendanfalkowski is that second video one of you editing a RootComponent?

I tried making almost identical changes to the `Product` RootComponent and I could not get it to throw in the same manner :(

**Comment by sirugh** [comment]
Looks like the `staticContext` warning is "resolved" in #1966 except it still breaks (shows a shell of button and no text).

**Comment by brendanfalkowski** [comment]
Both videos are editing a root component (brendan.js) but similar errors occur when adding/using imports for any component in my experience.

The "hot-reload leads to empty shell w/ header/footer but no content and no console/devtools errors" issue happens sometimes too. I haven't paid enough attention to spot the sequence that causes it though.

**Comment by sirugh** [comment]
@brendanfalkowski check out the PR. 🙏 Hoping it fixes the issue for ya!
