### ISSUE TITLE
[tooling]: scrap storybook until we can do it better!

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#1591]
We have storybook in venia-ui...concept? one of those. Anyways, we should remove it so we can get rid of some added complexity until we get to a point where we have a stable API for our components and where we can dedicate some time to doing it right.

As is, we have maybe four components in storybook and we don't mandate writing new ones, nor do we really have time or feel it important enough to write more while we are doing other work on components.

**Comment by frqnck** [comment]
The whole idea of components and Storybook is to promote decoupling. Having these in place from the start go made a lot of sense. Let the community create/update the missing stories, create the edges cases, etc. Further down the line, having this in place would certainly help refactoring these unstable components' API. The idea was good, scrapping it is an error.

StorefrontUI is leveraging Storybook full-on [see their components playground](https://storybook.storefrontui.io) that will likely spearhead their development and community interest. 

I am only starting out with PWA Studio, but I am now considering reviewing Storefront UI (and potentially run it alongside UPWARD) as an alternative to the venia-ui/peregrine stuff.

**Comment by sirugh** [comment]
@frqnck I get that. While we would all love to see people adding stories to storybook it just isn't happening and our team doesn't have bandwidth to maintain or add to them as we would like. That said, maybe instead of removing them we need to open some `help wanted` issues to add storybook for specific components.

Thank you, sincerely, for your feedback! It alone will probably stop us from a complete removal of the storybook code :)

**Comment by frqnck** [comment]
Great to hear. Requesting ˋHelp wantedˋsounds a very good idea. I would likely contribute to this effort. Sadly at present Storybook does not run out of the box and seems broken so getting this back up and running would be the first call. I will try to take a look into it and see if I can help with a fix.

**Comment by sirugh** [comment]
Closing as stale. Who was this guy... :P
