### ISSUE TITLE
[doc]: Webpack less configuration

### ISSUE THREAD

**Issue by senioritydev** [magento/pwa-studio#1612]
Please provide web-pack configuration file for less and css loader which should have scope of venia-ui repository

**Comment by zetlen** [comment]
Who wants to add loader options to `configureWebpack`? This will be a fun exercise in contribution to Buildpack. You'll need

- Some experience with NodeJS
- Connect a debugger (like Chrome or VSCode) to the running Node process
- The Webpack configuration API open in another tab.

**Comment by Jordaneisenburger** [comment]
I believe this is already possible by pushing new loaders into `clientConfig.module.rules` in `webpack.config.js` we do the same for `.scss` files for a project that's build via the creat-pwa command.

**Comment by awilcoxa** [comment]
@zetlen  can you weigh in on Jordan's comment?

**Comment by zetlen** [comment]
Jordan is right; my instinct is to try and make a "friendlier" API for it, but Webpack's existing configuration API works well. We can close, and our documentation can link out.
