### ISSUE TITLE
[bug]: Resolve GitHub Security Alerts

### ISSUE THREAD

**Issue by cherdman** [magento/pwa-studio#1613]
**Describe the bug**
GitHub's automated security fixes has identified issues with two dependencies: `mixin-deep` and `set-value`.

https://github.com/magento/pwa-studio/network/alerts

**Possible solutions**
- Upgrade `mixin-deep` to version **1.3.2** or later.
- Upgrade `set-value` to version **2.0.1** or later

**Comment by supernova-at** [comment]
Closed because these dependencies were in devdocs and buildpack and the severity was not as indicated. Created a separate (non-critical) issue to upgrade dependencies here: #1621

**Comment by juliosong** [comment]
@cherdman Hi I've received the same alerts and tried the dependabot auto-fix. However, it says it can't fix the set-value issue as "as one or more other dependencies require a version that is incompatible with this update." I wondered if you knew any other way to fix this. Thanks!
