### ISSUE TITLE
Implement Product Slider component for Venia

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#162]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer I want to create a product slider component for Venia so that I can display rich content by criteria from the Magento CMS.

- Examples include New Arrivals carousel

Assumptions: successful setup and completion of Venia examples, sample data (mock data in JSON; not GraphQL dependent); well formatted and proper content (data); mobile first and UX principles established in design documentation.

## Expected result:

AC
Summary of GraphQL coverage; identification of needs to share GraphQL
Create sample React component with CMS ID as a prop; retrieve and render
Testing and documentation (Storybook)

**Comment by artKozinets** [comment]
![slider-parts.png](https://images.zenhubusercontent.com/5b310669505d510c73d5f5e4/cba5c090-f096-4010-8ae3-6dc13f8d548f)

**Comment by ericerway** [comment]
@artKozinets do you think we can do this on Monday? Even if it's work in progress?

**Comment by awilcoxa** [comment]
Closing as obsolete.

**Comment by sreerajsaseendran** [comment]
Hi
Is it implemented/released? Could you please help to find the commit?

Thanks
