### ISSUE TITLE
[Research Story]: Audit the efficiency of rendering and painting on the screen

### ISSUE THREAD

**Issue by cherdman** [magento/pwa-studio#1625]
**What?**
Analyze Venia pages and components to see if they re-render unnecessarily or too frequently, or in general if they run repetitive code unintentially.

**Why?**
React UIs are easy to quickly make, but in exchange, certain patterns can make React do more work than necessary to repaint the UI. This causes bad performance, slow response times due to "layout thrashing", and high energy consumption on battery-powered devices.
Auditing our rendering and painting on the screen will allow us to identify possible real and perceptual performance gains, enabling us to improve actual user experience.

**How?**
- Use performance profilers in Chrome dev tools and other browsers, including Safari in the iOS Simulator
- Record profile information while using all storefront UI behaviors: navigation, selection, filtering, cart, checkout
- Identify areas where many re-renders from high up in the render tree are occurring in a short time
- Investigate any common patterns which cause excessive re-render

**Acceptance Criteria**
- Write-up of audit results and proposed changes
- Actions and next steps created in the form of GitHub issues

**Comment by supernova-at** [comment]
# Results

## Metrics Affected

* [First Contentful Paint](https://developers.google.com/web/tools/lighthouse/audits/first-contentful-paint?utm_source=lighthouse&utm_medium=unknown)
* [First Meaningful Paint](https://developers.google.com/web/tools/lighthouse/audits/first-meaningful-paint?utm_source=lighthouse&utm_medium=unknown)
* [Time to Interactive](https://developers.google.com/web/tools/lighthouse/audits/time-to-interactive?utm_medium=unknown&utm_source=lighthouse)
* [Speed Index](https://developers.google.com/web/tools/lighthouse/audits/speed-index?utm_source=lighthouse&utm_medium=unknown)
* [First CPU Idle](https://developers.google.com/web/tools/lighthouse/audits/first-cpu-idle?utm_source=lighthouse&utm_medium=unknown)
* [Max Potential First Input Delay](https://developers.google.com/web/updates/2018/05/first-input-delay?utm_source=lighthouse&utm_medium=unknown)

### Dev Tools / CI Process (how to measure)

* [Google Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/?url=veniapwa.com)
* [Profile React Components](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab). [This walkthrough is good too](https://calibreapp.com/blog/react-performance-profiling-optimization/).

## Best Practices

- [x] [Use React in Production mode](https://reactjs.org/docs/optimizing-performance.html#use-the-production-build)
- [ ] Load images progressively with something like https://github.com/verlok/lazyload
- [ ] [Minimize the number of critical resources](https://scotch.io/courses/10-web-performance-audit-tips-for-your-next-billion-users-in-2018/fmp-first-meaningful-paint#toc-watch-the-critical-rendering-path)
- [ ] Test with an "Average phone". Industry standard right now is the Moto G4.

## Problems Identified / Proposed Changes

* [Enable Text Compression](https://developers.google.com/web/tools/lighthouse/audits/text-compression?utm_source=lighthouse&utm_medium=unknown)

![Screen Shot 2019-09-18 at 9 16 40 AM](https://user-images.githubusercontent.com/13182778/65156650-112eb780-d9f5-11e9-9cb4-b79c07dfcdd0.png)

* [Serve images in next-gen formats](https://developers.google.com/web/tools/lighthouse/audits/webp?utm_source=lighthouse&utm_medium=unknown)

![Screen Shot 2019-09-18 at 9 17 55 AM](https://user-images.githubusercontent.com/13182778/65156741-38858480-d9f5-11e9-8324-888d927d77a2.png)

## Profile Baseline

![Screen Shot 2019-09-18 at 8 54 03 AM](https://user-images.githubusercontent.com/13182778/65154899-ec851080-d9f1-11e9-9d2a-6054af7ae8ed.png)

We're doing a good job memoizing our expensive functions:

![Screen Shot 2019-09-18 at 8 55 29 AM](https://user-images.githubusercontent.com/13182778/65155022-1e967280-d9f2-11e9-83db-2da0c8cf6c97.png)

Immediately after our first render there is a cascading update:

![Screen Shot 2019-09-18 at 8 57 34 AM](https://user-images.githubusercontent.com/13182778/65155188-69b08580-d9f2-11e9-9eb4-362a4ac0be40.png)

We should investigate `MagentoRouteHandler.componentDidMount` and `HeadTag.componentDidMount`, the latter of which scheduled a cascading update.

## Additional Resources

* [JS Startup Optimization](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/javascript-startup-optimization/)

**Comment by supernova-at** [comment]
- [x] Write-up of audit results and proposed changes
- [x] Actions and next steps created in the form of GitHub issues

**Comment by supernova-at** [comment]
Well it turns out I did mostly the wrong kind of investigation on this one.

Re-opening to dive back into React-specific performance (via the React Profiler).

**Comment by supernova-at** [comment]
# Audit Results

## Use performance profilers in Chrome dev tools and other browsers, including Safari in the iOS Simulator

## Record profile information while using all storefront UI behaviors: navigation, selection, filtering, cart, checkout

## Identify areas where many re-renders from high up in the render tree are occurring in a short time

## Investigate any common patterns which cause excessive re-render

**Comment by supernova-at** [comment]
Issues created and added to performance milestone https://github.com/magento/pwa-studio/milestone/20
