### ISSUE TITLE
[feature]: Include cached lockfiles with venia-concept to make install faster

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1631]
Once #1500 is merged, the `venia-concept` folder will serve as a scaffolding template for new projects. This functionality is similar to [create-react-app](https://create-react-app.dev/).

When creating a new project, the scaffolding generator copies files into the new project directory and then installs dependencies. These new projects don't have lockfiles (either `package-lock.json` or `yarn.lock`, depending on their chosen NPM client), and so it takes them much longer to install and they are not guaranteed to use a known snapshot of dependencies.

These new projects copied from `venia-concept` won't have lockfiles because `venia-concept` is maintained as part of this monorepo, where the lockfile is at repo root.

Not having a pre-prepared lockfile for a new project makes it slow to create the project, and possibly unstable.

**Describe the solution you'd like**
 Install `venia-concept` dependencies in the `venia-concept` directory itself, with each supported NPM client (`npm` and `yarn`) in turn. Each will create a lockfile. Copy this lockfile to a sibling file, like `yarn.lock.cached`. *Optionally, gzip this file.*

Add handlers to the visitor implementation in `venia-concept/_buildpack/create.js` to unzip, customize, and copy those lockfiles depending on the NPM client the user chose.

**Benefits**
* Speed of scaffolding a project
* Resilience against bugs 

**Additional context**
 There is precedent for this; [create-react-app maintains a lockfile](https://github.com/facebook/create-react-app/tree/master/packages/create-react-app) in source control for newly generated projects.

**We will need to automatically maintain and version the lockfile. This means that part of an end-to-end test run includes automatically regenerating, gzipping, and committing the lockfile.**

**Please let us know what packages this feature is in regards to:**
 - <x] `venia-concept`
 - [ ] `venia-ui`
 - [ ] `pwa-buildpack`
 - [ ] `peregrine`
 - [ ] `pwa-devdocs`
 - [ ] `upward-js`
 - [ > `upward-spec`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story
