### ISSUE TITLE
Replace remaining redux selectors with derived state values

### ISSUE THREAD

**Issue by jimbo** [magento/pwa-studio#1632]
**Is your feature request related to a problem? Please describe.**

Putting selector functions for getting derived state from a redux store is not an uncommon pattern, but it's not one we ever endorsed or used widely. Now that we're providing redux state from context, with a single connector per slice, we shouldn't need them.

**Describe the solution you'd like**

- For derived state that's used widely, append it directly to the context value.
- For derived state that's only used in a few places, let the component calculate it.

**Describe alternatives you've considered**

This is the alternative to the current pattern.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by sirugh** [comment]
Added to Modular Component Library milestone as a follow-on/nice-to-have.

**Comment by sirugh** [comment]
>append it directly to the context value.
@jimbo when you say this do you mean do this work in the context creator like [here](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/context/user.js#L21) or in the reducer's initialState?

**Comment by jimbo** [comment]
> > For derived state that's used widely, append it directly to the context value.
> 
> @jimbo when you say this do you mean do this work in the context creator like [here](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/context/user.js#L21) or in the reducer's initialState?

The former.

```es6
// selectors/cart.js
export const isCartEmpty = cartState =>
    !cartState.details.items || cartState.details.items.length === 0

// context/cart.js
const cartApi = useMemo(/* ... */)

const derivedCartState = useMemo(
  () => ({
    ...cartState,
    isEmpty: isCartEmpty(cartState)
  }),
  [cartState]
)

const contextValue = useMemo(
  () => [derivedCartState, cartApi],
  [cartApi, derivedCartState]
)
```
