### ISSUE TITLE
[feature]: Utilize graphql returned color for swatches

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#1633]
**Is your feature request related to a problem? Please describe.**
Currently we randomize the colors in the product component because GQL does not return the hex code or any way for the UI to determine what color to display. There is an open issue for this in GQL: https://github.com/magento/graphql-ce/issues/196.

**Describe the solution you'd like**
When the GQL issue is resolved/merged/released I would like to update our product query and swatch code to use the hex value returned.

**Describe alternatives you've considered**
If there was a mapping of colors returnable by the gql endpoint and hex colors we could maintain it on the UI and render a map. I don't think this is scaleable or a good idea, but it is an alternative :P

Another more realistic alternative would be to get the data from the rest endpoint instead of graphql. I'm not sure how to obtain that information or whether it even exists, but it should be a fallback incase we need to be "production ready" and don't have this data available in gql yet.

**Additional context**
https://github.com/magento/graphql-ce/issues/196
https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/ProductOptions/swatch.js#L58-L59

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by deiserh** [comment]
assigned

**Comment by awilcoxa** [comment]
can go into next release but need to evaluate to ensure backwards compatibility, keeping in backlog

**Comment by awilcoxa** [comment]
2.3.5 released today, needs review
