### ISSUE TITLE
[feature]: Gallery items creates new items even if items didn't change

### ISSUE THREAD

**Issue by amsterdamharu** [magento/pwa-studio#1641]
Gallery items components re [creates new items](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Gallery/items.js#L38-L45) even if items did not change. This causes the items in list to execute render function.

Instead only map items [when items changed](https://github.com/amsterdamharu/pwa-studio/blob/d63b803/packages/venia-ui/lib/components/Gallery/items.js#L60-L63).

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

A suggestion on how to change code is [here](https://github.com/magento/pwa-studio/pull/1642)

**Comment by codynguyen1** [comment]
This problem seems to be fixed with the pwa-studio 5.0, @amsterdamharu have you tried again?

**Comment by sirugh** [comment]
Closing as stale.
