### ISSUE TITLE
Upgrade Apollo View Layer

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1657]
PWA Studio depends on [apollo-client](https://github.com/apollographql/apollo-client) and (currently) its React view layer integration [react-apollo](https://github.com/apollographql/react-apollo).

As of `v3.0.0` of `react-apollo`, however, Apollo recommends using hooks for all new Apollo code going forward. In addition to following best practices, PWA Studio can realize a 50% Apollo bundle size savings by only installing [@apollo/react-hooks](https://www.npmjs.com/package/@apollo/react-hooks).

Acceptance Criteria:
  1. `react-apollo` is uninstalled and not included in the webpack bundle
  1. `@apollo/react-hooks` is used instead 
  1.  Remove Peregrine's `useQuery` hook and replace all usages with Apollo's `useQuery` hook
  1.  Remove usages of the `Query` component and replace with Apollo's `useQuery` hook

**Comment by zetlen** [comment]
A 50% bundle size savings? I can't believe these deals! 💵 💸 💰 

We will need to replace all instances of the `Query` component. Is that a separate story?
