### ISSUE TITLE
[bug]: Product Full Detail allows adding to cart without all required options selected

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#1658]
**Describe the bug**
A product should only be allowed to be added to cart if all the required options are selected. For example we require a color _AND_ a size to be selected, however currently if you select one of them then the `add to cart` button is enabled and you can click it. This will throw an error because the API requires both options.

**To Reproduce**
1. Go to a product page
2. Click a color or size, but not both.
3. Click `Add to cart`
4. See error in console.

**Expected behavior**
The button should not be enabled until _both_ options are selected.

**Screenshots**
[![Image from Gyazo](https://i.gyazo.com/1d92498f8da673cca0a9205c554eb436.png)](https://gyazo.com/1d92498f8da673cca0a9205c554eb436)

**Possible solutions**
In `getIsMissingOptions` the `optionSelections.size` check is invalid. If only one option is picked it will show size 2 and one of the keys will have a value of `undefined`. While this check is valid (if the map is smaller than the possible options we are missing options) we should also check to make sure no _required_ values are `undefined`.

**Comment by MKostiantyn** [comment]
#mm19pl

**Comment by sirugh** [comment]
Resolved in talon conversion work.
