### ISSUE TITLE
Apollo Client Advanced Configuration

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1659]
A full list of configuration options for `apollo-client` can be found at https://www.apollographql.com/docs/react/essentials/get-started/#configuration-options.

Please ensure the following options are set appropriately:

1. `fetchOptions` / `headers`

We always want to send the `Accept-Encoding` header with `gzip` listed.
Note: Is this a default? Requests appear to already include this header.

2. `cacheRedirects` 

Especially useful in the case of drilling down into the details of a particular product, we can provide a map of functions here that helps Apollo find existing data in its cache.

Update: `cacheRedirects` work is big enough that it has its own ticket: https://github.com/magento/pwa-studio/issues/1661.

3. `credentials` 

This may well be its own separate ticket as well, but we'll likely have to leverage `credentials` to handle the authenticated user flow entirely in GraphQL.

**Acceptance Criteria:**
1. A "base" GraphQL configurator that can be extended by projects like Venia
1. A good set of defaults such as the ones described above

**Comment by zetlen** [comment]
The apollo client is essential to our Peregrine hooks. What do you think of putting this configurator in Peregrine itself, @jimbo and @supernova-at ?

**Comment by supernova-at** [comment]
If we like the extensibility model we've adopted for webpack configs, I think that could make sense here too.

"Here's what PWA Studio expects (baseline / default), you can overwrite some things if you want to".

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-68

**Comment by supernova-at** [comment]
Closing as too old / no longer applicable.
