### ISSUE TITLE
Change the bigger venia-ui direct "dependencies" to "peerDependencies"

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1660]
We want developers to be able to control the versions of the larger and more important dependencies of our libraries. The tool for doing this is `peerDependencies` in `package.json`. 

A good example of what we want is the package.json in Peregrine: it depends on libraries like `@apollo/react-hooks`, but instead of making them transitive "hard" dependencies, it allows the downstream dependent project--`venia-concept` in this case--to supply the `@apollo/react-hooks` dependency in its own `dependencies` array, and therefore more carefully control what versions of these shared libraries it is using.

Currently, `venia-ui` has [fourteen hard dependencies](https://github.com/magento/pwa-studio/blob/b93a38a49197ddc2cbb1bbd1cb4ed0665c92fe06/packages/venia-ui/package.json#L35-L50):

```json
  "dependencies": {
    "@apollo/react-hooks": "~3.1.2",
    "informed": "~2.1.13",
    "jarallax": "~1.11.1",
    "load-google-maps-api": "~2.0.1",
    "lodash.escape": "~4.0.1",
    "lodash.over": "~4.7.0",
    "memoize-one": "~5.0.0",
    "prop-types": "~15.7.2",
    "react-feather": "~2.0.3",
    "react-head": "~3.1.1",
    "react-slick": "~0.25.2",
    "redux-actions": "~2.6.4",
    "redux-thunk": "~2.3.0",
    "uuid": "~3.3.2"
 }
```

Some of these are very small, like `uuid`, and maybe we can get away with keeping them abstracted behind `venia-ui`. But some of them, like `jarallax` and `@apollo/react-hooks`, are large and significant, and `venia-concept` should own them, so that third-party developers can own them.

Original @supernova-at issue description:
> Similar to #1565 but just in the scope of Apollo dependencies, please clean up and get rid of dependencies listed in packages that don't need them.
> 
> Specifically, `apollo-client`, `apollo-cache-inmemory`, `apollo-cache-persist`, and `apollo-link-http` are listed as dependencies of both `venia-concept` and `venia-ui`.
> 
> Likely only one of these packages needs these dependencies.

**Comment by zetlen** [comment]
Our own implementation of `useQuery` is causing some regressions in later versions of apollo-client. This would be rectified by fixing #1657 .

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-67

**Comment by zetlen** [comment]
Renaming this issue to clarify something about peregrine and venia-ui.
