### ISSUE TITLE
Improve Cache Hits for PDPs

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1661]
Apollo's [InMemoryCache](https://www.apollographql.com/docs/react/v2.5/advanced/caching/#inmemorycache) is a normalized data store that serves as our Apollo cache.

It has a [configuration option](https://www.apollographql.com/docs/react/v2.5/advanced/caching/#configuration) called `cacheRedirects` which gives us an opportunity to serve PDP data from the cache instead of having to re-fetch product data.

Here is a [guide](https://www.apollographql.com/docs/react/v2.5/advanced/caching/#cache-redirects-with-cacheredirects) from Apollo on how to accomplish this.

The tradeoff is that the initial "category list" query that displays products must include all the details the PDP needs. This ticket should leverage `fragments` as a way to ensure those fields stay in sync, otherwise Apollo won't find it in the cache.

The tradeoff is between requesting too much data on the category pages (PDP data needs for every product) vs the server communication overhead required for a single PDP (additional request, response parse, latency, loading, etc.).

📝 This work is closely related to https://github.com/magento/pwa-studio/issues/1666.

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-66
