### ISSUE TITLE
Fix Simple Product Heuristic Fragment Matcher

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1662]
By default, `apollo-cache-inmemory` uses a heuristic fragment matcher. Since PWA Studio is using fragments on unions and interfaces, we will need to use an `IntrospectionFragmentMatcher`.

Apollo provides a guide on how to accomplish this here:
https://www.apollographql.com/docs/react/advanced/fragments/#fragments-on-unions-and-interfaces

**Acceptance Crtieria**
1. The console warning that appears in development when viewing a simple product PDP no longer appears

**Comment by Jordaneisenburger** [comment]
@supernova-at I've just implemented this solution in our project, I can make a PR if you're interested ?

**Comment by sirugh** [comment]
@Jordaneisenburger definitely, or we can talk about it in the public channel first, or in here! Whatever works for you.

**Comment by Jordaneisenburger** [comment]
> @Jordaneisenburger definitely, or we can talk about it in the public channel first, or in here! Whatever works for you.

@sirugh I'll make a PR so that we have something tangible to talk about

**Comment by Jordaneisenburger** [comment]
@sirugh PR open at #1707

**Comment by supernova-at** [comment]
I took this one over and have updated #1707.
