### ISSUE TITLE
Enable Apollo useQuery partialRefetch

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1663]
After moving to Apollo's new hooks in #1657, ensure that the `partialRefetch` option on the `useQuery` hook is set to `true`.

The Apollo docs say:

> If true, perform a query refetch if the query result is marked as being partial, and the returned data is reset to an empty Object by the Apollo Client QueryManager (due to a cache miss). The default value is false for backwards-compatibility's sake, but should be changed to true for most use-cases.

See https://www.apollographql.com/docs/react/api/react-hooks/#options.

Side note: It would be great if consumers didn't have to set this value on *every* usage of `useQuery` 😉

**Comment by supernova-at** [comment]
This issue is on `hold` until #1657 is complete.

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-65

**Comment by supernova-at** [comment]
Closing this issue in favor of the JIRA one.
