### ISSUE TITLE
Use Apollo's OptimisticUI

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1665]
Optimistic UI is a pattern to simulate the results of a mutation and update the UI even before receiving a response from the server. This affects the perceived performance of the app to make it _feel_ faster.

In appropriate places throughout Venia, implement Optimistic UI via Apollo.

Some places that it could be implemented include:
  1. Add to cart
  2. Update item in cart
  3. Remove item from cart
  4. Favorite item in cart

Here is [Apollo's documentation on Optimistic UI](https://www.apollographql.com/docs/react/features/optimistic-ui/#basic-optimistic-ui).

Improved use cases like "add to cart", not the LCP

**Comment by supernova-at** [comment]
This issue is on `hold` until we upgrade to use Apollo's hooks in #1657 , and implement cart mutations in #1668 .

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-64
