### ISSUE TITLE
Normalize the Apollo Cache

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1666]
Apollo Client splits out each object in a GraphQL result with a `__typename` and an `id` (or `_id`) property into its own entry in the Apollo cache.

Returning a value from a mutation with an `id` property will automatically update any queries that fetch the object with the same `id`.

Please see the [Apollo Guide for Normalization](https://www.apollographql.com/docs/react/advanced/caching/#normalization) for more information.

**Acceptance Criteria**
1. We should always include `id` in our queries and mutation results. A good way to ensure these stay in sync is to use `fragment`s.
1. If a GraphQL type does not include the `id` field, we will have to implement `dataIdFromObject` manually to ensure cache hits

📝 This work is closely related to https://github.com/magento/pwa-studio/issues/1661.

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-63

**Comment by sirugh** [comment]
This should be handled with the migration to Apollo v3 type policies. Going forward, normalization issues will result in console warnings during development and can be handled at that time.
