### ISSUE TITLE
Replace REST Cart Operations with GraphQL Mutations

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1668]
Magento 2 GraphQL defines mutations on the cart that PWA Studio is not yet taking advantage of.

In fact, they even have a [checkout tutorial](https://devdocs.magento.com/guides/v2.3/graphql/tutorials/checkout/checkout-customer.html).

The bulk of our REST usage is in the context of managing the cart, so see if we can't replace that with GraphQL calls instead.

It would be great if we didn't have to re-fetch / query for the cart again after these mutations 🥇 .

The full list of available mutations is in the schema, but here's a quick screenshot from GraphiQL:
![Screen Shot 2019-09-11 at 8 25 06 AM](https://user-images.githubusercontent.com/13182778/64701109-bf72b400-d46d-11e9-96b5-e3bfdf69e328.png)

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-62

**Comment by sirugh** [comment]
Done!
