### ISSUE TITLE
Batch Initial Data Needs

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1669]
To decrease the number of roundtrips to the server, create a GraphQL query that fetches all the initial data that a PWA storefront would need.

This could include:
  * The navigation tree
  * The list of categories
  * The cart and its details
  * Store configuration / information

See the [getCategory query](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/queries/getCategory.graphql) for an example of how to query multiple types with one query.
Remember too that every field and nested object can potentially get its own set of arguments.

If we can get this data up front initially, it will be sitting there in the cache as users navigate around the store and the app can respond to interactions & navigations quickly without having to consult the server for data.

There is, of course, a tradeoff here: Don't request so much data that the initial app load takes too long.

**Comment by supernova-at** [comment]
This may not be advisable.

It's easy enough to look at the initial batch of requests Venia makes and combine them into a single query. But how do we keep that query up-to-date when any component can be dropped into the initial page load flow?

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-57
