### ISSUE TITLE
Upgrade to @apollo/react-testing

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1671]
There are a few places (like [this](https://github.com/magento/pwa-studio/blob/fa0a4c9b45757c272f6b745c546e8b61b1da40db/packages/venia-ui/lib/components/Footer/__tests__/footer.spec.js#L3)) where we're using `react-apollo/test-utils`.

We should upgrade to the new `@apollo/react-testing` library:
https://www.apollographql.com/docs/react/api/react-testing/#installation

**Comment by dani97** [comment]
@supernova-at Is this still valid, I don't see any usage of `react-apollo/test-utils`

**Comment by sirugh** [comment]
We just spoke about this today in dev time. Looking to start using more of the apollo utils when writing/updating tests. Not sure this needs to be a feature, as it'll just need to be something we enforce when writing pull requests.
