### ISSUE TITLE
[bug]: Magento 2.3.2 - PWA - phtml Graphql fetching Issue via Static Block

### ISSUE THREAD

**Issue by subhajyotiint** [magento/pwa-studio#1681]
**Describe the bug**
When trying to call a phtml file in a static block, it's returning the null or empty value of the phtml file, but return the static HTML contents.

**To Reproduce**
1. admin create a static  block,
2. Then call a phtml file, and save it
3. Fetch the static block using graphql
4. See the issue

**Expected behavior**
Returning the phtml content.

**Screenshots**
![image](https://user-images.githubusercontent.com/54358160/64859041-ca347100-d646-11e9-9420-76d3725430f2.png)
![image](https://user-images.githubusercontent.com/54358160/64859126-0c5db280-d647-11e9-808e-f296c31fddb5.png)
![image](https://user-images.githubusercontent.com/54358160/64859206-3ca55100-d647-11e9-837b-95dd26e2d29a.png)

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `magento graphql provider`

**Comment by awilcoxa** [comment]
needs review @zetlen @sirugh

**Comment by fooman** [comment]
This issue looks like more related to the GraphQl project than PWA - I'd suggest filing the same issue there https://github.com/magento/graphql-ce

**Comment by zetlen** [comment]
Thanks, @fooman! He's right, @subhajyotiint. This, like the other issue you've opened, is a better fit for the graphql-ce maintainers.
