### ISSUE TITLE
[bug]: Widget in static block fetching error using graphql

### ISSUE THREAD

**Issue by subhajyotiint** [magento/pwa-studio#1682]
**Describe the bug**
Called a Product listing widget in a static block it's working properly in Magento frontend, but when trying to fetch the static content by using graphql then the error occurs.

**To Reproduce**
1. Go to admin,
2. Create a static block
3. Call product listing by using widget
4. Fetch the static block using graphql
5. See the error

**Expected behavior**
Product listing element.

**Screenshots**
![image](https://user-images.githubusercontent.com/54358160/64859731-ac680b80-d648-11e9-9fef-a5f09443b149.png)
![image](https://user-images.githubusercontent.com/54358160/64859754-bc7feb00-d648-11e9-970f-279156dcaa93.png)

**Please let us know what packages this bug is in regards to:**
- [ ] `Magento GraphQl`
- [ ] `GraphQl Provider`
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by nmalecki** [comment]
#mm19

**Comment by awilcoxa** [comment]
Needs review from @zetlen @sirugh

**Comment by zetlen** [comment]
@subhajyotiint This looks like a real issue, but you would have better luck if you opened it in the https://github.com/magento/graphql-ce repository instead. This issue is about the behavior of the GraphQL API alone, and not any PWA Studio code, so the GraphQL team will be better at handling it.
