### ISSUE TITLE
[feature]: Enable native image lazy-loading in browsers

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1689]
**Is your feature request related to a problem? Please describe.**
Like all other assets in a PWA, images should not load until they're needed. In a traditional webpage (and an older browser), images load when the page loads--even if they're way down the screen! The "lazy loading" technique developed to correct this.

In a lazy load, the code assumes an image is only needed when it appears in the viewport, or when it's about to. JavaScript libraries use scroll height measurement and the IntersectionObserver API to observe this and begin loading images when necessary. We could add one of these libraries to our codebase and to Venia.

Or, we could use the [native lazy loading features](https://www.machmetrics.com/speed-blog/browser-native-lazy-loading-coming-in-2019/) that browsers are starting to support. Since browsers are doing the work to support this natively, we should let them do it and not add a polyfill or additional library.

**Describe the solution you'd like**
Add the `loading="lazy"` attribute to our images, as described in [this article](https://addyosmani.com/blog/lazy-loading/) and in other places. **That's it.**

**Describe alternatives you've considered**
Many lazy loading libraries exist, and using them as polyfills would support the browsers that don't do it natively yet.

However, they would add complexity and payload size; they would have an overall negative impact on customer experience.

Some of these libraries support a custom experience for lazy loading. We can replicate this using a combination of native lazy loading and the transparent placeholder images we already use.

**Additional context**
Between this and #1584, this would fix #668.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-56
