### ISSUE TITLE
Migrate PWA CICD to PWA AWS account.

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1704]
PWA CICD on AWS currently setup on Shared/Regression AWS account. Now we have got new PWA specific AWS account, which can be fully managed by PWA team.

Need to migrate entire PWA CICD to new AWS account. 

- [x]   Host Zones in AWS r53
- [x]   Add PWA domains to r53
- [x]   Create S3 buckets for storage with expiration rules.
- [x]   Create parameter store variables
- [x]   Create pull request to update certificate path and S3 bucket names if any.
- [x]   add `pwa-test`codebuild project
- [x]   add `pwa-build` and `pwa-deploy` codebuild project
- [x]   add `pwa-cleanup` codebuild project
- [x]   add 'pwa-nightlybuild' codebuild project
- [x]   add `pwa-demo` pipeline - `develop` branch
- [x]   add `pwa-staging` pipeline -  `release' branch`
- [x]   add `pagebuilder-demo` pipeline- existing `pagebuilder` support
- [x]   add MFTF builds
- [x]   add rules to expire logs
- [x]   add `pwa-stable` codebuild project - 'master' branch 
- [x]   add `pwa-release` codebuild project  
- [ ]   Raise request to NameServer updates for existing domains.  (Its better to do this task after we release 4.0.0)

**Comment by dpatil-magento** [comment]
There will be some down time when we switch to new account as we are using same domains in new and old AWS account.  So, storefront will not be accessible until domain registry gets updated.

**Comment by sharkySharks** [comment]
@dpatil-magento you have 2 domains that you can use in your environments. I believe you are only using one of these domains currently for production: `pwa-venia.com`, but you also have `pwa-venia-staging.com`, so I would probably set up your staging environment to use the staging url and when that is proven to work, and we have your code in terraform, then it will be trivial to update prod and turn off your old prod environment.

![Screen Shot 2019-09-30 at 9 29 36 AM](https://user-images.githubusercontent.com/7784948/65888503-41674600-e365-11e9-96d0-e862e8783d21.png)

**Comment by dpatil-magento** [comment]
Closing this one as most of the tasks have been completed. We will have new ticket for tracking actual migration date and Name server update request.
