### ISSUE TITLE
Document Performance Measurement Tools

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1710]
# Overview

Research story #1625 identified several metrics to measure and how to measure them.

# The Ask

Document (tutorials / guides preferably) how to measure using each of the following tools:

* [Google Page Speed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fvenia.magento.com%2F)
* [WebPageTest](https://webpagetest.org/)
* [React Component Profiler](https://reactjs.org/docs/optimizing-performance.html#profiling-components-with-the-chrome-performance-tab)

# Acceptance Criteria

* A publicly linkable document that we can use to standardize the way we collect important application metrics

**Comment by supernova-at** [comment]
There is no associated PR for this issue.
Instead, please review this Wiki page: https://github.com/magento/pwa-studio/wiki/How-We-Measure-Performance.

**Comment by dpatil-magento** [comment]
These might be testing flows but good to document?
1. Currently we measure performance of home page only.  But we should start tracking Category and Product page too.  How about search results page?
2. Mostly in phase 2, we should try tracking checkout flow as well?  Its Being a overlay not sure, I would say good to track time taken once use clicks on Confirm button till Confirm screen.

On WPT Adobe has private instance - https://wiki.corp.adobe.com/display/WCMSOps/Webpagetest   nice to try it out.

**Comment by supernova-at** [comment]
I have updated the document 👍
