### ISSUE TITLE
WebPageTest GitHub Action

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1711]
# Overview

Each PR into PWA Studio gets a unique, custom deployment powered by our CI process.
WebPageTest is an important tool for measuring our deployed artifact.

# The Ask

Install the [WebPageTest GitHub Action](https://github.com/marketplace/actions/webpagetestaction) to run against every PR and report WebPageTest results.

**Comment by sirugh** [comment]
Can we use actions that require secrets in our public repo? I don't think so :(

**Comment by supernova-at** [comment]
Hmm, good question. I was hoping the secret would live in GitHub configuration and not in our repo. We may have to close this if we can't do it securely.

**Comment by sirugh** [comment]
Do we still want this? I think it's a cool idea, unless we have some other perf metric tests that run on PRs.

Also the marketplace link doesn't seem to work, but there is this: https://github.com/JCofman/webPagetestAction. Maybe it's the same?

If you still want this, let's move it internal, as it'll be unlikely that an external contributor would have permission to add this stuff.
