### ISSUE TITLE
Redirect HTTP traffic on venia.magento.com

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1713]
# Overview

Our Lighthouse Audit shows that Venia is only 6/7 "PWA Optimized" because the site https://venia.magento.com does not redirect HTTP traffic to HTTPS:

![Screen Shot 2019-09-19 at 9 22 30 AM](https://user-images.githubusercontent.com/13182778/65252807-35ef6180-dabf-11e9-944b-34f197a8dbb5.png)

# The Ask

Redirect HTTP traffic to HTTPS on venia.magento.com.
See https://developers.google.com/web/tools/lighthouse/audits/http-redirects-to-https?utm_source=lighthouse&utm_medium=devtools.

Note: this may not be a PWA Studio change.

**Comment by sirugh** [comment]
@cherdman @ericerway who owns this host?

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-26
