### ISSUE TITLE
Enable GZIP on Server

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1714]
# Overview

JSON + GZIP is one of GraphQL's [recommended best practices](https://graphql.org/learn/best-practices/#json-with-gzip):

> because it is mostly text, it (JSON) compresses exceptionally well with GZIP

Gzipping responses from the backend will reduce the number of bytes transferred over the wire back to the client.

Note that PWA Studio is already sending the `Accept-Encoding: gzip` header with its GraphQL requests, so we can see immediate results when GZIP is enabled.

It is also one of our biggest opportunities to speed up our initial page load:

![Screen Shot 2019-09-19 at 9 28 07 AM](https://user-images.githubusercontent.com/13182778/65253190-d8a7e000-dabf-11e9-8af8-b95333191101.png)

**Comment by sirugh** [comment]
Should we open this issue with the graphql team?

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-25
