### ISSUE TITLE
[feature]: Make a `withRouter` hook and use it

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#1715]
**Is your feature request related to a problem? Please describe.**
We use the `withRouter` HOC in several places.

```js
const ComponentThatUsesRouterProps = props => {
  const { history } = props;
  // do something with provided history
};
export default withRouter(ComponentThatUsesRouterProps);
```

**Describe the solution you'd like**
If there is a hook equivalent we should use it _or_ we should roll our own.

```js
const ComponentThatUsesRouterProps = props => {
  const { history } = useRouter();
  // do something with history
};
export default ComponentThatUsesRouterProps;
```

**Describe alternatives you've considered**
The alternative is that we leave it as is but I'd rather not ;)

**Comment by dani97** [comment]
@sirugh  https://reacttraining.com/react-router/core/api/Hooks can we use this. They just replace withRouter with four hooks but we can will be using one or other in our code

**Comment by dani97** [comment]
https://reacttraining.com/blog/react-router-v5-1/

**Comment by sirugh** [comment]
Please do give this a shot!

**Comment by dani97** [comment]
Thanks @sirugh

**Comment by brendanfalkowski** [comment]
@dani97 @sirugh — I saw this yesterday, same idea: https://usehooks.com/useRouter/

**Comment by dani97** [comment]
@brendanfalkowski  Thanks for your suggestion, but we are using mostly location and history in most places, so I guess `useLocation`  gives more readability than `useRouter`.
