### ISSUE TITLE
HeadTag Cascading Update

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1719]
Immediately after our first render there is a cascading update:

![Screen Shot 2019-09-18 at 8 57 34 AM](https://user-images.githubusercontent.com/13182778/65155188-69b08580-d9f2-11e9-9eb4-362a4ac0be40.png)

Investigate `HeadTag.componentDidMount` and `MagentoRouteHandler.componentDidMount`, the former of which scheduled a cascading update.

If there are code changes that can be made to avoid the cascading update, please make them.

**Comment by sirugh** [comment]
We don't own HeadTag: https://github.com/tizmagik/react-head/blob/master/src/HeadTag.js
