### ISSUE TITLE
[doc]: State management

### ISSUE THREAD

**Issue by jcalcaben** [magento/pwa-studio#1720]
**Describe the request**

We need topic that explains how to do state management with PWA Studio libraries.

**Possible solutions**

A topic that should answer the following questions:

- What is state management?
- What are common state management strategies/libraries?
- How does PWA Studio manage state in Venia?
- What do I need to do to manage state using PWA Studio libraries?

**Comment by sirugh** [comment]
@jimbo we should probably help out with this when possible.
