### ISSUE TITLE
[doc]: Update project wiki

### ISSUE THREAD

**Issue by jcalcaben** [magento/pwa-studio#1721]
**Describe the request**

The project wiki is out of date.

**Possible solutions**

Update the project wiki with more up to date information about the project, how to contribute, dependency management, etc.

**Comment by sirugh** [comment]
Include updates to installing, adding dependencies through `yarn` and using the `resolutions` field in package.json

**Comment by jcalcaben** [comment]
There is no PR associated with this issue, but the following wiki pages have been updated and should be reviewed:

* https://github.com/magento/pwa-studio/wiki/Definition-Of-Quality
* https://github.com/magento/pwa-studio/wiki/Dependency-Management
* https://github.com/magento/pwa-studio/wiki/Project-coding-standards-and-conventions
* https://github.com/magento/pwa-studio/wiki/PWA-Studio-Development-Guiding-Principles
* https://github.com/magento/pwa-studio/wiki/Venia-Code-Requirements

**Comment by supernova-at** [comment]
> https://github.com/magento/pwa-studio/wiki/Dependency-Management

This one needs some work. It starts off talking about `npm` and `lerna` which we don't use anymore, and I think the example

```sh
yarn install --save-dev <moduleToAdd>
```

should be 

```sh
yarn workspace @magento/<package> add <moduleToAdd>
```

**Comment by supernova-at** [comment]
Newest changes look good 👍

**Comment by jcalcaben** [comment]
Closing issue as there is nothing specific left to do.
