### ISSUE TITLE
Make pagination bar non-sticky

### ISSUE THREAD

**Issue by soumya-ashok** [magento/pwa-studio#1723]
The current implementation of pagination has it fixed at the bottom of the window.
Research indicates that it would be better for this element not to be fixed.
Pagination controls can be placed at the bottom of the page under all the product listings.

**Comment by sirugh** [comment]
@soumya-ashok can you expand or provide a mock for this? I'm a little confused by what you're asking for here.

**Comment by sirugh** [comment]
Also, is this something we can do with a toggle/configuration so people can do it either way?

**Comment by soumya-ashok** [comment]
@sirugh People can definitely customize and utilize the pattern that works best for their context, but the standard design that we have would have the pagination inline under page content.

In the gif below, you can see how the pagination bar is sticky until we reach the end of the page, where it attaches itself to the page. We just need to remove the sticky state and have it live at the bottom of the page.

![Screen Recording 2019-09-20 at 9 30 59 AM](https://user-images.githubusercontent.com/25960021/65338511-fb092e80-db8f-11e9-92f5-852afcc6c496.gif)

**Comment by sirugh** [comment]
[![Image from Gyazo](https://i.gyazo.com/d51cab6f805bb65d6c00f59fd8517680.gif)](https://gyazo.com/d51cab6f805bb65d6c00f59fd8517680)

^ gif of current functionality which we *do not want*. We want it to always be at the bottom under the images, like where it is when you scroll down far enough.

**Comment by brendanfalkowski** [comment]
FWIW, we removed sticky pagination already (also sticky header). It looks cool, but we try to always err on letting the user have their full screen for content rather than a fixed UI.

**Comment by soumya-ashok** [comment]
@brendanfalkowski Yes, agreed. Thanks for adding to the discussion! :)

**Comment by zetlen** [comment]
This ticket is currently unassigned and @soumya-ashok has helpfully suggested it for Munich Contribution Day 2019. If you want to take this ticket at Munich Contribution day, bear these things in mind:

- This ticket is an enhancement, not a bug. The current sticky footer is not broken, it's just not the UX choice that we want Venia to make.
- Note that the Venia CSS modules do not have any backwards compatibility tricks or vendor prefixes in them. Venia intentionally has no support for obsolete browsers, to keep its codebase small. Any CSS processing that must occur for current-day compatibility will occur in the build step.
- Pay attention to the [CSS Grid](https://css-tricks.com/snippets/css/complete-guide-grid/) patterns in the Venia CSS modules when changing style. Try to stick with those patterns.
- As Soumya and Stephen have discussed above, this could easily be an option for developers to select. However, that should not be a configuration value in component props. We'd rather have an alternate version of the component than add complexity to the component itself. That way, you can keep the bundle small by only importing the components you are using. So if you want to try keeping the sticky footer as an available alternative, make sure to implement it as a separate component!

**Comment by LukasKiederle** [comment]
I am working on it
