### ISSUE TITLE
[bug]: States on continue shopping button in empty cart

### ISSUE THREAD

**Issue by soumya-ashok** [magento/pwa-studio#1724]
**Describe the bug**
On the desktop site, when the pointer hovers over the button, the text disappears.

**To Reproduce**
1. Go to the shopping cart on desktop veniapwa.com
2. Move the mouse pointer over the "continue shopping" button

**Expected behavior**
Button in static state is dark gray background, white text
Button in mouse-over state is teal background, white text
There should be no distinctly visible border on the button in either state

**Screenshots**
<img width="360" alt="Screen Shot 2019-09-19 at 4 42 05 PM" src="https://user-images.githubusercontent.com/25960021/65283648-2989f980-dafd-11e9-9a17-1a243149159a.png">

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device: Desktop Mac
 - OS: Mac Mojave 10.14.5
 - Browser: Chrome
 - Browser Version: 76.0.3809.132

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by zetlen** [comment]
This ticket is currently unassigned and @soumya-ashok has helpfully suggested it for Munich Contribution Day 2019. If you want to take this ticket at Munich Contribution day, it should be relatively simple to fix. It would be a good way to get started on the PWA Studio development stack!

**Comment by LukasKiederle** [comment]
I am currently working on it

**Comment by LukasKiederle** [comment]
I setup magento 2.3.2 with the current pwa-studio instance and the bug was not reproducable. It works as expected.

**Comment by joniklas** [comment]
Can confirm: Works as expected on Chrome Version 76.0.3809.132 (Official Build) (64-bit) Mac Mojave

**Comment by sirugh** [comment]
Cool, this has probably been fixed on `develop` then. FWIW we should be using the `develop` branch release for noting bugs: https://develop.pwa-venia.com/
