### ISSUE TITLE
Remove Venia logo from loading state

### ISSUE THREAD

**Issue by soumya-ashok** [magento/pwa-studio#1725]
It is not best practice to have brand elements associated with any potentially negative scenarios such as loading states that may or may not lead to a successful and quick page load.

The recommendation is to remove the logo from all loading states and to either use a generic icon or just plain text.

Scope: 
* Replace existing Venia branded logo with provided asset (SVG or CSS icon) 

PO would prefer something simple in this scope, something along the lines of: https://loading.io/spinner/rolling/-bar-circle-curve-round-rotate. Try to following existing branding for color selection, `--venia-orange` would be fine or `--venia-grey-dark`. 
Nice to have: 
* Research adding extension point to existing logo configuration

**Comment by sirugh** [comment]
Oh wow. Didn't know that!

Any suggestions for what these should look like now? Are you talking about the spinner?

**Comment by soumya-ashok** [comment]
@sirugh I recently learned this myself! Yes, I mean the spinner. We can keep just the text for now until we land on a more elegant solution. Would that work?

**Comment by supernova-at** [comment]
It'll work but "perceived performance" wants some sort of indication that _something_ is happening. A think a simple animation is better than static text in that regard.

**Comment by sirugh** [comment]
How about spinning text :D

**Comment by soumya-ashok** [comment]
@supernova-at Could we use the 3 blinking dots?
@sirugh :P

**Comment by zetlen** [comment]
@soumya-ashok Too bad about the spinner being a worst practice--it's very attractive.

This might be an opportunity to introduce the [emerging best practice of page skeletons](https://blog.iamsuleiman.com/stop-using-loading-spinner-theres-something-better/). There's a ready-made [React component](https://www.npmjs.com/package/react-loading-skeleton) to implement it quickly. This could be an exploratory ticket for implementing a generic one...

**Comment by zetlen** [comment]
Add the skeleton! Thanks @LucasCalazans

**Comment by brendanfalkowski** [comment]
Requesting @soumya-ashok approval: 
![source](https://user-images.githubusercontent.com/214924/67899135-e4ef7600-fb1e-11e9-9eae-4f148cacea7c.gif)

**Comment by soumya-ashok** [comment]
@zetlen @brendanfalkowski The page skeleton is what we have been wanting to do for loading state so if that's possible now, then let's try that for sure.

**Comment by dani97** [comment]
@LucasCalazans  https://github.com/danilowoz/react-content-loader. 
https://github.com/buildo/react-placeholder
I found these two libraries,  you may have already chosen a better library, just check these two.

**Comment by larsroettig** [comment]
@awilcoxa is this still todo?  then will take this

**Comment by kandy** [comment]
There is good example of skeleton UI for  catalog page to product page transition https://demo.scandipwa.com/

**Comment by awilcoxa** [comment]
@soumya-ashok can we find a new SVG to replace the logo, we'll keep the scope of this ticket small and specific to logo replacement and can create follow on ticket for page skeleton implementation.

**Comment by koushikch7** [comment]
@soumya-ashok  this alike would be better which is relative as well,
https://loading.io/spinner/shopping/-e-commerce-purchase-buy-shop-cart-pay-order

**Comment by tjwiebell** [comment]
@LucasCalazans - This scope has been reduced to just logo replacement, so I removed your assignment from several months back. If you're still interested in fulfilling the reduced scope, let us know, and you can jump on it once we get the new loading asset.

@soumya-ashok - If this requires some time investment and research, please just let us know, and we can plan accordingly.

**Comment by soumya-ashok** [comment]
@tjwiebell I'm fine with taking the simplest possible route now and using a standard spinner like in the link @awilcoxa above if we're just replacing the logo and not working on the first paint / loading experience in a more comprehensive way.
