### ISSUE TITLE
[doc]: JSDocs for Peregrine List components

### ISSUE THREAD

**Issue by jcalcaben** [magento/pwa-studio#1728]
**Describe the request**

Create or update comment blocks in for the Peregrine [List components][] so that they adhere to [JSDocs][] standards.

[jsdocs]: https://devdocs.io/jsdoc/
[list components]: https://github.com/magento/pwa-studio/tree/develop/packages/peregrine/lib/List

**Possible solutions**

Add JSDoc comment blocks to the Peregrine List components:

* List
* Items
* Item

See [useListState][] for a good example of JSDoc comments.

[useListState]: https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/List/useListState.js

**Comment by zetlen** [comment]
This ticket is currently unassigned and @jcalcaben has helpfully suggested it for Munich Contribution Day 2019. If you want to take this ticket at Munich Contribution day, bear these things in mind:

- [JSDoc works much like JavaDoc](https://devdocs.io/jsdoc/) and other docblock comment systems. JSDoc doesn't use all the same directives as PHP documentation, so use the reference manual to find what works.
- Higher-order functions should have higher-order signatures. Try to avoid using the `Function` type; instead define the signature of the lambda in place, where JSDoc permits it.
