### ISSUE TITLE
[doc]: JSDocs for ProductImageCarousel components

### ISSUE THREAD

**Issue by jcalcaben** [magento/pwa-studio#1729]
**Describe the request**

Create or update comment blocks in for the Venia-UI [ProductImageCarousel][] component so that it adhere to [JSDocs][] standards.

[jsdocs]: https://devdocs.io/jsdoc/
[productimagecarousel]: https://github.com/magento/pwa-studio/tree/develop/packages/venia-ui/lib/components/ProductImageCarousel

**Possible solutions**

Add JSDoc comment blocks to the Carousel component in ProductImageCarousel.

See [ToastContainer][] for a good example of JSDoc comments.

[ToastContainer]: https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/ToastContainer/toastContainer.js

**Comment by zetlen** [comment]
This ticket is currently unassigned and @jcalcaben has helpfully suggested it for Munich Contribution Day 2019. If you want to take this ticket at Munich Contribution day, [see the comment here for tips on JSDoc contribution.](https://github.com/magento/pwa-studio/issues/1728#issuecomment-533756378).
