### ISSUE TITLE
[doc]: JSDocs for basic Venia UI components

### ISSUE THREAD

**Issue by jcalcaben** [magento/pwa-studio#1730]
**Describe the request**

Create or update comment blocks for some of the basic Venia-UI component so that they adhere to [JSDocs][] standards.

[jsdocs]: https://devdocs.io/jsdoc/

**Possible solutions**

Add JSDoc comment blocks to the following basic components:

* [Modal][]
* [Mask][]
* [Trigger][]
* [Logo][]
* [Button][]
* [Button Group][]

[modal]: https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Modal/modal.js
[mask]: https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Mask/mask.js
[trigger]: https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Trigger/trigger.js
[button]: https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Button/button.js
[button group]: https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/ButtonGroup/buttonGroup.js
[logo]: https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Logo/logo.js

See [ToastContainer][] for a good example of JSDoc comments.

[ToastContainer]: https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/ToastContainer/toastContainer.js

**Comment by zetlen** [comment]
This ticket is currently unassigned and @jcalcaben has helpfully suggested it for Munich Contribution Day 2019. If you want to take this ticket at Munich Contribution day, [see the comment here for tips on JSDoc contribution.](https://github.com/magento/pwa-studio/issues/1728#issuecomment-533756378).

**Comment by LukasKiederle** [comment]
I am working on it

**Comment by RanadeepPolavarapu** [comment]
I'll take this.
