### ISSUE TITLE
[bug]: Post-install script should stop suggesting custom origin setup once it's complete

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1731]
**Describe the bug**
When checking out and installing dependencies, a post-install script runs which logs:

```
$ node scripts/monorepo-introduction.js
Preparing packages...
Set up a custom origin for your copy of venia-concept:
	yarn buildpack create-custom-origin packages/venia-concept
```

It continues to log that custom origin notice even after you have run the command. It should detect that you've already run the command and stop logging.

**To Reproduce**
1. From repository root, run `yarn run watch:venia`.
2. If necessary, go through the steps and set up a custom origin. Then run `yarn run watch:venia` again, to observe the dev server starting and binding to the custom domain.
3. Quit the dev server.
4. Run `yarn install`.

**Expected behavior**
After install, the system should recognize that your repo is already set up. It should do no logging beyond "Preparing packages".

**Screenshots**

**Additional context**
This is a recent addition to `scripts/monorepo-introduction.js` that exposes a small bug in Buildpack's `configureHost` function. It's a good first issue for community developers who want to work on tooling.

**Possible solutions**
- Modify `configureHost.js` so it always builds its hash from the absolute directory path.
- Modify `monorepo-introduction.js` so it always passes an absolute directory path to `configureHost().`
The first is probably better.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by LukasKiederle** [comment]
I am currently working on it
