### ISSUE TITLE
[bug]: react-feather is still including unused icons in the bundle

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1732]
**Describe the bug**
The `react-feather` library is supposed to support "tree-shaking", where Webpack can eliminate unused code from its bundle. However, it's not working for `react-feather`:

![image](https://user-images.githubusercontent.com/1643758/65369218-5d0d7680-dc18-11e9-9b99-7c1f04f1e752.png)

In #1415 we updated to react-feather 2.0, but it's still not tree shaking.

**To Reproduce**
1. Run `yarn run stats:venia`.
2. Wait for the analyzer window to open.
3. Observe the large `react-feather` block.
4. Open the filter drawer on the left. Search for "feather". Observe that it's a LOT of code!

**Expected behavior**
Only the icons we use are present in the bundle.

**Additional context**
We do want to eventually use something else than `react-feather`, per #739, but in the meantime, we have a responsibility not to pollute the bundle!

**Possible solutions**
There may be some webpack configuration involved, or maybe we need to change our dependency on `react-feather`.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by sirugh** [comment]
This used to work. I'm wondering if [this change](https://github.com/magento/pwa-studio/blob/develop/packages/venia-concept/webpack.config.js#L24) to the webpack config introduced this problem.

**Comment by sirugh** [comment]
Oh, no, that's not the problem... [THIS IS!!!](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/package.json#L40)

**Comment by dani97** [comment]
@sirugh  @zetlen I found two version of react-feather from lock file
In venia-ui https://github.com/magento/pwa-studio/blob/bcfe8f6aea8c354f6ec481f513b4ceaafe5282d2/packages/venia-ui/package.json#L40
and venia-concept https://github.com/magento/pwa-studio/blob/bcfe8f6aea8c354f6ec481f513b4ceaafe5282d2/packages/venia-concept/package.json#L100
I guess this is causing the issue all along, can we make it uniform to 2.0.3

**Comment by dani97** [comment]
Sorry @sirugh  you found it already  :+1:
