### ISSUE TITLE
[bug]: Search and Create Account should load asynchronously on request instead of in main bundle

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1733]
**Describe the bug**
The Search and CreateAccount RootComponents should load asynchronously, like all other RootComponents such as Product and Category. Instead, [the router statically imports them](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/App/renderRoutes.js) to manually specify them in the bundle.

These should change to dynamic imports, to reduce the size of the initial `client.js` bundle and improve load time.

**To Reproduce**
1. Run `yarn run stats:venia`.
2. When the Webpack Bundle Analyzer opens up, examine the `client.js` bundle.
3. Notice that the RootComponents for Search and CreateAccount are compiled into the `client.js` entry file.

**Expected behavior**
A separate async chunk file for each RootComponent.

**Additional context**

The Search and CreateAccount RootComponents are different from the catalog RootComponents, because the app does not route them with the `urlResolver` query via `resolveUnknownRoute()`. Instead, they are hardcoded routes in `renderRoutes.js`. That makes sense.

However, they don't need to be statically imported into `renderRoutes.js`. We can use dynamic `import()` calls to make separate chunks from those files, just as the router automatically does with Product, Category, and CMSPage RootComponents.

**Possible solutions**
Modify `renderRoutes.js` to import the hardcoded RootComponents using `import()` and `React.lazy()`. Use `Suspense` and a fallback spinner to asynchronously load them.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by sirugh** [comment]
Is this possibly related to #1742?

**Comment by supernova-at** [comment]
#1742 is concerned with the loading of the `SearchBar` component; I think this issue is talking about the Search page itself

**Comment by dani97** [comment]
@zetlen  https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/AuthModal/authModal.js, because of this **createAccount**  component is present in main bundle. The client bundle doesn't have search component now as of #1742

**Comment by supernova-at** [comment]
Closed by #1765 .

**Comment by sirugh** [comment]
@supernova-at did you mean to close this? #1955 references this as the issue for it.

**Comment by sirugh** [comment]
@supernova-at did you mean to close this? #1955 references this as the issue for it.

**Comment by supernova-at** [comment]
> @supernova-at did you mean to close this? #1955 references this as the issue for it.

I did, yeah - these are two separate things. I updated the reference in #1955.
