### ISSUE TITLE
Build-time GraphQL

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1739]
# Overview

Run-time calls to the GraphQL API to fetch data introduce latency and delay to the application.
Investigate whether we can fetch any data that the initial load of the application needs at build time and preload the application with it.

## Risks / Caveats

1. We don't know the frequency of builds. It may be entirely possible that the site is only ever "built" once.
1. We don't know the frequency of data updates. How will the application "update" this data if it is changed in the M2 Admin (for example) after build time?

It may be entirely possible that the result of this investigation is "we should not do this".

## References

[The GraphQL project documentation](https://devdocs.magento.com/guides/v2.3/graphql/caching.html) has good information on what data changes and how frequently (and when it should be updated).

**Comment by sirugh** [comment]
We already do this in the webpack configurator. Unclear whether that should continue to happen now that we support multi-store and also we need to be able to react to config changes without forcing a client to rebuild their runtime bundle. 

The storeConfig query provides a lot of information but it is store specific. Perhaps a better thing to do would be to understand the specific data we want to pre-fetch, do it for all possible stores, and make that call happen in the service worker. I'm closing this for now, to clean up our github issue log, but if you think it is worth an investigation we should open an internal JIRA ticket :)
