### ISSUE TITLE
GET or POST GraphQL queries

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1740]
# Overview

[The Magento GraphQL documentation](https://devdocs.magento.com/guides/v2.3/graphql/caching.html) states

> Only queries submitted with an HTTP GET operation can be cached. POST queries cannot be cached.

# The Ask

Determine the pros & cons of sending GET `query` requests to GraphQL instead of POST.

1. This "full page" caching may not be applicable to PWAs
1. This may have negative side effects

**Comment by sirugh** [comment]
#2602
