### ISSUE TITLE
Category Page Performance

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1744]
# Overview

The category page performance profile looks like this for its initial load:

![](https://user-images.githubusercontent.com/13182778/65355027-97dec280-dbb6-11e9-9cd5-4a27b7a0167d.png)

![](https://user-images.githubusercontent.com/13182778/65355037-9dd4a380-dbb6-11e9-830c-94444c819e91.png)

# The Ask

Investigate the Category page for performance improvements.
The primary candidates for improvement are: `FilterBlock` (67% of the total time), and the `List`s within `List`s.

**Comment by awilcoxa** [comment]
additional discovery required, should revisit after Peregrine effort

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story
