### ISSUE TITLE
PDP Item Selection Performance

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1746]
# Overview

On the PDP (for example), selecting an option (color, size) for the first time leads to an expensive operation inside the `Items` component:

![Screen Shot 2019-09-23 at 10 27 15 AM](https://user-images.githubusercontent.com/13182778/65439455-cba32d80-ddec-11e9-8e7a-6e09ecc5d7a1.png)

Note that updating its child `Item` components only takes about half the total time.

# The Ask

Investigate what the `Items` component is doing before updating its child `Item` components. See if we can optimize that operation.

**Comment by awilcoxa** [comment]
needs additional discovery to determine cause, may be resolved by Talons work for product options (big maybe?)

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-54

**Comment by sirugh** [comment]
Closing as done.
