### ISSUE TITLE
Unnecessary Renders when Opening the Cart drawer

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1747]
# Overview

Here is the performance profile when opening the cart drawer for the first time:

![](https://user-images.githubusercontent.com/13182778/65342168-c9946100-db97-11e9-9df3-d36b0dc7529b.png)

Here are the timing details:

![](https://user-images.githubusercontent.com/13182778/65342689-d6fe1b00-db98-11e9-8e57-8174ec04ae5d.png)

Note that this is all before we get the details of the cart and render the `MiniCart` itself.

# The Ask

Why does opening the cart drawer update...

1. `VeniaHeadProvider`, `HeadProvider`, and `Footer`?
1. `Suspense` > `Route` > `SearchBar` (may be resolved in #1742)
1. `CartTrigger`
1. `HeadProvider` > `Container`

Note that these updates are included under a `Provider` update, which I believe stems from a call to `getCartDetails` when we open the cart drawer. These may be eliminated when we move away from `ApolloProvider` in #1657 .

**Comment by awilcoxa** [comment]
Moving to backlog for consideration at later date

**Comment by sirugh** [comment]
The old Mini Cart was deprecated in 2020 :)
