### ISSUE TITLE
Opening Checkout Form updates MiniCart Body

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1748]
# Overview

Opening the checkout drawer has the following performance profile:

![](https://user-images.githubusercontent.com/13182778/65354266-b6dc5500-dbb4-11e9-8588-36ac614a8cfb.png)

# The Ask

Investigate why the `MiniCart/Body` component is being updated here. If we can get rid of that update, this transition becomes a lot smoother.

**Comment by sirugh** [comment]
Can you identify what changes triggered the updates? In this case I think `minicart` and `checkout` share a state in `step`, so changes to it may cause the updates.

**Comment by awilcoxa** [comment]
investigate if this issue still occurs after implementation of list Talon by @sirugh

**Comment by awilcoxa** [comment]
might be related to #1807

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
