### ISSUE TITLE
Duplicate Updates on Checkout Form Submissions

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1749]
# Overview 

It appears we are getting duplicate updates on checkout form submissions such as address form, payments form and shipping method form.

Here is the address form for example:

![](https://user-images.githubusercontent.com/13182778/65354440-23efea80-dbb5-11e9-8d2c-a286fcb58d24.png)

Note: the number of duplicate updates may be related to how many fields are in the form.

**Comment by sirugh** [comment]
Are you saying that each form is updated twice or are you talking about the smaller spikes within the chart?

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
