### ISSUE TITLE
[doc]: Talons documentation

### ISSUE THREAD

**Issue by jcalcaben** [magento/pwa-studio#1756]
**Describe the request**

The concept of "Talons" needs documentation.

**Possible solutions**

A topic that answers the following questions:

* What are Peregrine Talons?
* Why are they needed?
* How do they work?
* How can developers use them?

Use this draft as a starting point: https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/README.md

**Please let us know whether this is a new topic or a topic change request:**
 - [x] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Additional information**

From Slack by @sirugh :

>Mixins are the last leg of our multi-phase refactor of Peregrine hooks and venia-ui components.
>...
>The idea is to separate the logic of the component from the view layer. Basically the mixin will take in some set of props and have some API that currently matches whatever the component was using to display. For example you will notice that classes are not passed or computed by the mixin but things like callbacks, effects are handled within.
>And the idea is not necessarily to share code between multiple components inside OUR codebase, so you won't, for example, see multiple components calling the useAuthModal hook. It is a 1:1 relationship.
>...a developer can work with the view layer and composition of their app without having to worry about the functionality.
>...
>Using the useSignIn hook you could roll your own SignIn component, style it however you want, as long as you provide the props required by the hook.

From Slack by @jimbo 
>the custom hooks we want to encapsulate the logic from Venia components would not be your typical custom hooks. they're not utilities, they're not abstract, and they're not designed to be reusable. all they are designed to do is separate the code that returns React elements (Venia components) from the logic needed to make those components work (Peregrine custom hooks)
>...
>our Peregrine component hooks (talons, now) are not designed to be reusable outside of a PWA Studio app. in fact, they're not designed to be reusable within a PWA Studio app. they are solely designed to allow you to change presentation (DOM & CSS) without having to reimplement the logic
>...
>multiple options for people, on a per-component basis:
>- if a Venia component works for you without customization, great—use it directly
>- if you like how the Venia component works but not how it looks, modify it or write your own component that uses the corresponding talon from Peregrine
>- if you don't like how the Venia component works, write your own component from scratch

**Comment by sirugh** [comment]
Should these even be called `mixins`?

https://reactjs.org/blog/2016/07/13/mixins-considered-harmful.html
https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

**Comment by supernova-at** [comment]
> Should these even be called mixins?

It is a very overloaded term in front end development.

**Comment by supernova-at** [comment]
@jcalcaben talons

![image](https://user-images.githubusercontent.com/13182778/65520370-12585c80-dead-11e9-82ff-d631e1f87875.png)
