### ISSUE TITLE
[feature]: Implement image caching at Service Worker Level.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1766]
**Is your feature request related to a problem? Please describe.**
Related to #1673 

**Describe the solution you'd like**
Always cache the best resolution version of an image.

1. If a higher resolution version is requested, fetch the higher resolution image, bust the cache, insert this image and return the image to the client. If fetcher failed, return the available image to the client. If the fetch is taking longer than a THRESHOLD value, return the available image and replace that with the fetch's result when resolved.
2. If a lower resolution image is requested, return the available image and do not make any network call.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-53

**Comment by revanth0212** [comment]
This is already being done by the SW.

**Comment by revanth0212** [comment]
My bad. There seems to be some change that needs to be done. Clearly even if a high-resolution version is avaialable the SW is still requesting a low-resolution image.

![image](https://user-images.githubusercontent.com/35203638/67711924-f9056d00-f990-11e9-8cb5-41732777542a.png)

**Comment by revanth0212** [comment]
Fixed it.

Left is Develop and Right is with PR #1938 changes.

Look at the fetch times for the last 2 images. It is less on the right side because the cached version is being returned by the SW.

![image](https://user-images.githubusercontent.com/35203638/67788129-b8b0f800-fa3f-11e9-9c53-2db5f599df3c.png)
