### ISSUE TITLE
[feature]: Implement product image pre fetching.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1769]
**Is your feature request related to a problem? Please describe.**
Related to #1673 

**Describe the solution you'd like**
As of today, we do not prefetch images on the products page. For instance if the user is looking at image number X, we can make the service worker request images X-1 and X+1 for a smoother and faster experience. This can be achieved by the react component as well. We can make the call about where to implement this logic.

This might be a far fetch but we can prefetch the corresponding image of a different color. For instance if the user is viewing the green version of image X, prefetch the other versions of X as well. The reason I call this a far fetch is that we will be prefetching `number_of_colors * 3` every time (X-1, X, X+1). Again there will be incremental benefits to this but the initial investment is high due to too many prefetches.

Ideally, this only needs to be implemented on devices connected to WiFi.

**Describe alternatives you've considered**
Implementing this logic in https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/ProductImageCarousel/carousel.js

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by awilcoxa** [comment]
Need to decide whether we should do this at service worker level or within the image carousel component of Peregrine @jimbo @sirugh

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-51
