### ISSUE TITLE
[feature]: Implement background sync at the Service Worker Level.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1771]
**Is your feature request related to a problem? Please describe.**
Related to #1673 

**Describe the solution you'd like**
We can implement background sync as part of the service worker. This feature of the service worker will periodically update the cache of certain requests like the catalog, product availability, comments, ratings (when the user is on a certain product page), order status, etc. This will increase the performance of the app because the data is readily available and UI update faster.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by awilcoxa** [comment]
Scope of issue should address enablement of background sync functionality but not all of the possible implementations/use cases

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-50

**Comment by revanth0212** [comment]
Background sync is not available in all the browsers as of today. Removing from the Performance Milestone for now. Will revisit in the future.
