### ISSUE TITLE
[feature]: Implement API to listen to postMessages from Service Worker.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1772]
**Is your feature request related to a problem? Please describe.**
Related to #1673 

**Describe the solution you'd like**
Implement an API to listen to messages sent by the service worker using postMessage API. This can particularly useful to tell the client when new data is available. For instance, as mentioned in #1766 and #1767, we can return cached data if the service is unreachable or taking too long. In such cases, the UI will be using stale data. Using this API we can let the UI know about updated data and let it refresh silently to show the most recent data.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-49
