### ISSUE TITLE
[feature]: Implement utilities to help with Service Worker decision making based on environments.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1774]
**Is your feature request related to a problem? Please describe.**
Related to #1673 

**Describe the solution you'd like**
Behavioral logic needs to be implemented into the Service Worker. For instance, only prefetch route based bundles when on WiFi and desktop or background sync only if on Wifi or High-Speed internet. These helper functions need to be implemented as utility functions because they can be useful in Venia and Peregrine.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-48

**Comment by revanth0212** [comment]
Removing from the Performance Milestone for now. Will revisit in the future.

**Comment by sirugh** [comment]
Closing as cancelled.
