### ISSUE TITLE
[feature]: Implement optimistic updates API.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1776]
**Is your feature request related to a problem? Please describe.**
Maybe related to #1673 

**Describe the solution you'd like**
This is something that needs a bit of caution while using. We can use optimistic updates to improve the performance of the app by returning a fake yes from the Service Worker about the update. If for some reason the update fails, a message will be posted back to the client about the failure and necessary actions will be triggered to deal with the failure. This obviously is not applicable for certain actions like placing an order or login but can be very useful when it comes to posting a comment or giving a rating.

It would be straight forward if we implement optimistic updates as part of Venia and Peregrine. But if we need to implement features like #1766 and #1767 we can couple them with this and gain more benefits in the process. We can utilize the postMessage reaction API which will be implemented as part of #1772 for this.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by supernova-at** [comment]
We can do this via Apollo too - see #1665 .

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story
