### ISSUE TITLE
[feature]: Cache only 1 version of HTML and return that for all routes.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1781]
**Is your feature request related to a problem? Please describe.**
Related to #1673 

**Describe the solution you'd like**
As of today, all routes get the same HTML file even if the request originated as `/`, `/search.html` or `/venia-tops.html` or `/valeria-two-layer-tank.html` but with a different name. The problem arises when the user directly goes to a certain products page during the offline mode, whose HTML is not cached. Even though it is the same HTML since the route is different the browser will redirect to Network Unreachable error. This is because we give different names to routes that bear the same content and the service worker caches that HTML with the key as the route. We should change the HTML handler in service worker to save only 1 version of HTML and return it even if the request originated from a different route.

By not requesting HTML every time and utilizing a cached version till something changes we can save 855 Bytes of data over the network and also reduce our cache memory footprint.

![out_temp](https://user-images.githubusercontent.com/35203638/65625404-663c7180-df91-11e9-86ab-e52c00d16e97.gif)

![image](https://user-images.githubusercontent.com/35203638/65623698-f973a800-df8d-11e9-9146-14f3af988d80.png)

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by revanth0212** [comment]
If the HTML changes in the future we can show a message like this

![image](https://user-images.githubusercontent.com/35203638/65892895-a70b0080-e36c-11e9-8c37-01c24be4dc8f.png)

so the user can click and update the app.

This solution, I feel, might be annoying since customers who are shopping would not like to reload a page.

The second solution would be to use versioning API and request the current version of index.html and if:

- that is same as what is in the cache return the cached HTML file 
- that is not same as what is in the cache, request new HTML file and update the cache

This was we won't be requesting 850 Bytes of data every time and also speed up the app load since it is served from cache, and if something changes we will only be wasting minimal amount of time.

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-69
