### ISSUE TITLE
[feature]: API to get details about the latest build.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1782]
**Is your feature request related to a problem? Please describe.**
Related to #1673 and #1781 

**Describe the solution you'd like**
This API will be useful to know whether to request HTML file and replace that in the cache or keep using the cached version.

This API call can return information like when was the last time a new build was generated and the UI can compare that against the stored value and if they don't match, request a new file and update the cache.

This was we won't be downloading 850 Bytes of data all every time and also save on cache. Also, this will increase the performance since most of the time the HTML will be served from the cache which is faster than a network call.

```es6
// At higher level

if (await fetch('/latest_build_details') !== current_build_details) {
    return fetch('/')
} else {
    return caches.match('/client.[hash].js')
}
```

**Describe alternatives you've considered**
We can start using versioning for builds which can be requested over the network instead of the time of build. Versioning can be utilized somewhere else as well if needed. But to stay simple the easiest way is to simply the build date and time.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by revanth0212** [comment]
This API will be used to achieve the performance benefits mentioned in #1781

**Comment by supernova-at** [comment]
Might #1227 benefit from this too?

**Comment by revanth0212** [comment]
Not needed anymore since we have decided to not worry about fetching HTML multiple times. [We will be using SW to fetch the HTML in the background](https://github.com/magento/pwa-studio/pull/1874).

**Comment by sirugh** [comment]
I actually think this'd still be useful in terms of serving information about the package such as versions of dependencies or uptime or even still the date the build was last run.
