### ISSUE TITLE
[misc]: Tests for sw.js

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1789]
**Is your feature request related to a problem? Please describe.**
Related to #1673 

**Describe the solution you'd like**
Write tests for sw.js. Now that a lot of things will be changing relative to current sw.js, having tests will help.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by zetlen** [comment]
https://hackernoon.com/service-worker-testing-made-easy-9a2d8e9aa50 might be a good start.

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-71
