### ISSUE TITLE
[bug]: Webpack build times get slower in bigger projects

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#1796]
**Describe the bug**
While developing we save files a lot. Every save triggers webpack and makes it compile again. There seems to be a speed issue with every subsequent re-compile taking longer and longer.

**Some numbers:**

Initial  `yarn run watch:storefront` / `yarn run watch:all`: 

<img width="829" alt="Screenshot 2019-09-27 at 08 08 48" src="https://user-images.githubusercontent.com/19858728/65746067-1202d000-e0fe-11e9-8916-0f4b087f7fec.png">

subsequent re-compile 1:

<img width="823" alt="Screenshot 2019-09-27 at 08 10 28" src="https://user-images.githubusercontent.com/19858728/65746142-4c6c6d00-e0fe-11e9-84ac-85ca2dddb234.png">

subsequent re-compile 2:

<img width="823" alt="Screenshot 2019-09-27 at 08 11 37" src="https://user-images.githubusercontent.com/19858728/65746268-abca7d00-e0fe-11e9-9bef-2275e081c41b.png">

subsequent re-compile 3:

<img width="823" alt="Screenshot 2019-09-27 at 08 12 40" src="https://user-images.githubusercontent.com/19858728/65746244-97868000-e0fe-11e9-8dfa-a59f11993b5c.png">

**To Reproduce**
1. Run one of the watch commands and you should see compilation time take longer and longer every subsequent re-compile 

**Expected behavior**
I expect re-compile times to be fast, Not sure what fast is yet but we should aim for +- 1.5-2 sec

**Additional context**
This output is because I wrapped webpack inside [this](https://github.com/stephencookdev/speed-measure-webpack-plugin#readme) tool to better analyze what's happening.

**Things might be worth looking into:**
- With the SMP tool described above it caught my eye that every re-render this output gets shown and the list gets longer it doesn't clean itself. So this could be something but it might also be something created by the use of this plugin. 
<img width="823" alt="Screenshot 2019-09-27 at 08 25 07" src="https://user-images.githubusercontent.com/19858728/65746908-555e3e00-e100-11e9-811c-5bee6d101b63.png">

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Macbook pro
 - OS [e.g. iOS8.1, Windows 10]: Mojave 10.14.6
 - Magento Version: 2.3.2
 - PWA Studio Version: Latest develop minus +- 5 commits
 - Node Version `10.15.1`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by revanth0212** [comment]
We merged #1691 recently that has some changes done to the webpack config. You might wanna check that once. I see that in the screenshots you have the `MediaBackendURLFetcherPlugin` which was removed a while ago.

**Comment by zetlen** [comment]
@Jordaneisenburger That `UpwardIncludePlugin` hook error is pretty interesting. The `UpwardIncludePlugin` is pretty new; it's unit tested, but it isn't proven in production scenarios. It may be that we need to add some cleanup in it; maybe every time it invokes `CopyWebpackPlugin` it needs to remove the previous assets?

**Comment by Jordaneisenburger** [comment]
> We merged #1691 recently that has some changes done to the webpack config. You might wanna check that once. I see that in the screenshots you have the `MediaBackendURLFetcherPlugin` which was removed a while ago.

Thanks will check it out

**Comment by awilcoxa** [comment]
Marked as P3S3 low priority during grooming

**Comment by davemacaulay** [comment]
Due to lack of activity we've opted to close this issue.

If you encounter this issue you should stop the watch command and restart your build.
