### ISSUE TITLE
[bug]: When express-sharp is down, the media files don't get served.

### ISSUE THREAD

**Issue by rancollier** [magento/pwa-studio#1808]
When express-sharp is down, the media files don't get served.
```
Emitting no ServiceWorker in development mode. To enable development mode for ServiceWorkers, pass `enableServiceWorkerDebugging: true` to the ServiceWorkerPlugin configuration.
Cannot add image optimization middleware due to dependencies that are not installed or are not compatible with this environment:
- @magento/express-sharp: Reason: Found vendored libvips v8.8.1 but require v8.7.4. Please remove the 'node_modules/sharp/vendor' directory and run 'npm install'.
- @magento/express-sharp: Reason: expressSharp is not a function
```
@zetlen found a possible solution.
https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/upward.yml#L15
needs to be updated to: `pattern: '^/(graphql|rest|media)(/|$)'`

**Comment by zetlen** [comment]
Hey, this is an oversight in `upward.yml` and I've got it fixed in #1830, which also updates express-sharp to the version that respects `NODE_TLS_REJECT_UNAUTHORIZED=0`.
