### ISSUE TITLE
Create talons for app shell components

### ISSUE THREAD

**Issue by jimbo** [magento/pwa-studio#1821]
**Is your feature request related to a problem? Please describe.**

This work is part of the effort to extract component logic from Venia into Peregrine (#1604).

**Describe the solution you'd like**

Create talons for components within the following subdirectories of `venia-ui/lib/components`:

- [x] `App` (#1828)
- [x] `FilterModal`
- [x] `Footer` (#1860)
- [x] `Header` (#1793)
- [x] `SearchBar` (#1786)

**Additional context**

The following subdirectories fall into this category, but aren't ready for talons:

- `Head`
- `ToastContainer`

The following subdirectories fall into this category, but don't need talons:

- `Main`

**Please let us know what packages this feature is in regards to:**

- `venia-ui`
- `peregrine`

**Comment by sirugh** [comment]
Donezo
