### ISSUE TITLE
Create talons for right drawer components

### ISSUE THREAD

**Issue by jimbo** [magento/pwa-studio#1823]
**Is your feature request related to a problem? Please describe.**

This work is part of the effort to extract component logic from Venia into Peregrine (#1604).

**Describe the solution you'd like**

Create talons for components within the following subdirectories of `venia-ui/lib/components`:

- [x] `Checkout` (#1775)
- [x] `MiniCart` (#1807)

**Please let us know what packages this feature is in regards to:**

- `venia-ui`
- `peregrine`

**Comment by sirugh** [comment]
#1807 
#1775
