### ISSUE TITLE
Create talons for main page components

### ISSUE THREAD

**Issue by jimbo** [magento/pwa-studio#1824]
**Is your feature request related to a problem? Please describe.**

This work is part of the effort to extract component logic from Venia into Peregrine (#1604).

**Describe the solution you'd like**

Create talons for components within the following subdirectories of `venia-ui/lib/components`:

- [x] `CategoryList` (#1755)
- [x] `CreateAccountPage` (#1778)
- [x] `Gallery` (#1791)
- [x] `ProductFullDetail` (#1814)
- [x] `ProductImageCarousel` (#1817)
- [x] `ProductOptions` (#1819)
- [x] ~`ProductQuantity`~ (unnecessary)

**Additional context**

The following subdirectories fall into this category, but don't need talons:

- `ErrorView`

**Please let us know what packages this feature is in regards to:**

- `venia-ui`
- `peregrine`

**Comment by awilcoxa** [comment]
Closing as completed
