### ISSUE TITLE
Create talons for generic components

### ISSUE THREAD

**Issue by jimbo** [magento/pwa-studio#1825]
**Is your feature request related to a problem? Please describe.**

This work is part of the effort to extract component logic from Venia into Peregrine (#1604).

**Describe the solution you'd like**

Create talons for components within the following subdirectories of `venia-ui/lib/components`:

- [x] `Image` (#1803)
- [x] `Pagination` (#1812)

**Additional context**

The following subdirectories fall into this category, but aren't ready for talons:

- `CmsBlock`

The following subdirectories fall into this category, but don't need talons:

- `Button`
- `ButtonGroup`
- `Checkbox`
- `Field`
- `Icon`
- `LoadingIndicator`
- `Logo`
- `Mask`
- `Modal`
- `RadioGroup`
- `RichText`
- `Select`
- `TextArea`
- `TextInput`
- `Trigger`

**Please let us know what packages this feature is in regards to:**

- `venia-ui`
- `peregrine`

**Comment by sirugh** [comment]
Donezo.
