### ISSUE TITLE
[feature]: Custom templates for create-pwa scaffolding

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1831]
With `buildpack create-project` and `npm init @magento/pwa`, you can scaffold a new project based on `venia-concept`. Right now, it can only `venia-concept` as a template.

However, most of the work for custom templates is already done!

- The `createProject` function searches for template source on both the filesystem and NPM
- The template package itself contains instructions on how it should be copied and modified, using the `_buildpack/create.js` file

However, these systems are not robust enough today.

- They can't use globally installed NPM packages
- They can't use arbitrary filesystem directories because they need a package.json
- They don't make it easy to "extend" a parent template

**Describe the solution you'd like**
- A solid resolution strategy for template arguments that respects package names, filesystem, and maybe other locators like GitHub
- Updating `npm init @magento/pwa` to accept a custom argument

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story
