### ISSUE TITLE
Making GraphQL Calls

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1843]
In `venia-ui` and `venia-concept` we use `apollo-client` and `@apollo/react-hooks` hooks to make GraphQL calls and update the Venia reference storefront.

In `buildpack` and `peregrine` though, we are currently simply `fetch`ing data via POST requests to the `/graphql` endpoint on `MAGENTO_BACKEND_URL`.

I'm curious if we can't use an `apollo-client` in `buildpack` and `peregrine`. Doing so can DRY up our code, allow us to use Apollo's- and bake in our own- best practices, and provides consistency across our projects.

**Comment by sirugh** [comment]
Just remember `buildpack` is server side (and sometimes only at initialization time of the studio) and `peregrine` is runtime.

**Comment by sirugh** [comment]
Not sure this is necessary anymore - we have cleaned up most instances of GQL to use the apollo client in browser including those in Peregrine.
