### ISSUE TITLE
[feature]: Automate service worker route creation logic.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1858]
**Is your feature request related to a problem? Please describe.**
It will be an addition to what #1857 does.

**Describe the solution you'd like**
We need to write a function that will automatically read the upward yaml's route handler and creates the service worker route handler because they need to be in sync.

**Describe alternatives you've considered**
For now, they will be done manually by the developer. It is being handled in #1857.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story
