### ISSUE TITLE
[bug]: favicon not loading in stage mode.

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1861]
**Describe the bug**
Venia favicon is not loading in the stage mode. Works fine in watch mode.

**To reproduce**
1. Run `yarn build && yarn stage:venia`.
2. Go to the URL mentioned in the terminal.
3. No favicon should be loaded even though the service responsed with 200.

**Expected behavior**
favicon should show up in the tab just like in `watch` mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/35203638/66347455-04c5bc80-e91a-11e9-8811-05998c111867.png)

![image](https://user-images.githubusercontent.com/35203638/66347534-2de64d00-e91a-11e9-9851-898c6ca1c90f.png)

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: MacBookPro
 - OS [e.g. iOS8.1, Windows 10]: Mac OS Sierra
 - Browser [e.g. Chrome, Safari]: Chrome

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [x] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by supernova-at** [comment]
I noticed this on our deployments of the latest [develop](https://develop.pwa-venia-staging.com) and [release / master](https://magento.pwa-venia-staging.com/) too.
