### ISSUE TITLE
Issue with CMS page in PWA

### ISSUE THREAD

**Issue by ankitpatel2931** [magento/pwa-studio#1864]
Hi Team,

I need help in PWA magento 2.3.
I have configured PWA venia theme successfully.
Category and product pages and all other things working fine with PWA.

When I am trying to run default CMS page of magento 2 it gives me error like below.
1) magento2url/privacy-policy-cookie-restriction-mode => Working Fine (Normal without PWA)
2) magento2pwaurl/privacy-policy-cookie-restriction-mode => gives me error like page not found
3) magento2pwaurl/privacy-policy-cookie-restriction-mode.html => gives me homepage content always doesn't matter with URL

Is there anything needs to setup to access normal CMS pages in PWA? Could anyone please guide me how can I access CMS page from pwa store?

Thanks in advance.

**Comment by ThibaultAndreis** [comment]
It's a work in progress, you can check feature/page-builder to see if it's what you need.

**Comment by ankitpatel2931** [comment]
Not getting you exactly. I want to open cms page in PWA same like magento 2. Currently I am getting error as I describe above. Could you please elaborate how can I achieve this?

**Comment by ThibaultAndreis** [comment]
This feature is currently being developed under the name of "page builder" but not released yet, you can check how it works in the feature/page-builder branch or test it.

**Comment by ankitpatel2931** [comment]
Ok. Thanks for the reply.

**Comment by davemacaulay** [comment]
@ThibaultAndreis @ankitpatel2931 `feature/page-builder` does not include a CMS Page router, which is required to fix the issue described here.

**Comment by idziakjakub** [comment]
Hi @ankitpatel2931,

I have a workaround to render HTML from CMS Page content, please just replace content in file:

`packages/venia-ui/lib/RootComponents/CMS/cms.js`

to:

```
import React from 'react';
import { useQuery } from '@apollo/react-hooks';
import cmsPageQuery from '../../queries/getCmsPage.graphql';
import { fullPageLoadingIndicator } from '../../components/LoadingIndicator';
import { number } from 'prop-types';

const CMSPage = props => {
    const { id } = props;
    const { loading, error, data } = useQuery(cmsPageQuery, {
        variables: {
            id: Number(id),
            onServer: false
        }
    });

    if (error) {
        if (process.env.NODE_ENV !== 'production') {
            console.error(error);
        }
        return <div>Page Fetch Error</div>;
    }

    if (loading) {
        return fullPageLoadingIndicator;
    }

    if (data) {
        return (
            <div>
                <div dangerouslySetInnerHTML={{__html: data.cmsPage.content}} />
            </div>
        );
    }
    return null;
};

CMSPage.propTypes = {
    id: number
};

export default CMSPage;

```

**Comment by ankitpatel2931** [comment]
Hi @idziakjakub,

I am getting error like below after adding code. When I run sudo yarn run build from pwa-studio direectory.

ERROR in ../venia-ui/lib/RootComponents/CMS/cms.js
Module not found: Error: Can't resolve '@apollo/react-hooks' in '/var/www/html/dalvey-m2/pwa-studio/packages/venia-ui/lib/RootComponents/CMS'
 @ ../venia-ui/lib/RootComponents/CMS/cms.js 10:0-47 18:18-26
 @ ../venia-ui/lib/RootComponents/CMS/index.js
 @ (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1
 @ multi (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js

Could you please guide me about above issue?
I have referred https://github.com/apollographql/react-apollo/issues/398
But no luck with it.

Thanks.

**Comment by idziakjakub** [comment]
Hello @ankitpatel2931,

are you sure you are using the latest version of PWA Studio?
Most components in PWA Studio are using '@apollo/react-hooks' library.
Please double check your installation.

**Comment by idziakjakub** [comment]
@ankitpatel2931 you don't need my fix anymore, because branch `feature/page-builder` is now merged to `develop`. You have to pull new changes from the branch and it will work.

**Comment by zetlen** [comment]
Open Source Magento needs to display CMS pages easily too. It won't be ideal, because we can't safely process the HTML and we'll have to inject it, but this would be a great issue for making a Peregrine talon to do that!

**Comment by ankitpatel2931** [comment]
Hi @zetlen , @idziakjakub , @ThibaultAndreis , @davemacaulay ,

Thanks for the replay.
Magento 2 CMS page working fine in PWA setup after taking pull from develop branch.
