### ISSUE TITLE
[bug]: 4.0.0 update, FetchError: request to graphql failed, reason: unable to verify the first certificate

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#1885]
**Describe the bug**
After updating to PWA Studio 4.0.0, `yarn run build` fails when verifying the certificate for the GraphQL endpoint.

**To reproduce**
1. Updated existing project to PWA Studio 4.0.0
2. `yarn install`
3. `yarn run build`

```
yarn run v1.17.3
$ yarn ce run build
$ yarn workspace @watscomagento/ce run build
$ yarn run build:prod
$ yarn run clean && yarn run load-env && webpack --no-progress --env.mode production
$ rimraf dist
$ node ../pwa-buildpack/bin/buildpack load-env --core-dev-mode .
{ FetchError: request to https://ce.test/graphql failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/packages/pwa-buildpack/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://ce.test/graphql failed, reason: unable to verify the first certificate',
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
FetchError: request to https://ce.test/graphql failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/packages/pwa-buildpack/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/brendan/.nvm/versions/node/v10.16.1/bin/node
Arguments: /usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js run build
Directory: /Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/packages/ce
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Build should finish.

**Additional context**

I had this issue back in March, but I don't know what fixed it:
https://github.com/magento/pwa-studio/pull/1045#issuecomment-475423200

Output of `curl https:/ce.test/graphql` as requested here:
https://github.com/magento/pwa-studio/issues/1052

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
```

**Possible solutions**

DID NOT WORK — Tried deleting the `devcert` folder as documented here.
https://manuals.gravitydept.com/frameworks/magento-pwa-studio/troubleshooting

DID NOT WORK — Tried generating the certificate as documented here:
https://magento.github.io/pwa-studio/venia-pwa-concept/setup/
`yarn buildpack create-custom-origin packages/ce`
This process succeeded, but the build does not work afterward.

DID NOT WORK — Tried deleting and regenerating the `.env` file.
`MAGENTO_BACKEND_URL="https://ce.test/" yarn buildpack create-env-file packages/ce`
This process succeeded, but the build does not work afterward.

WORKED — Changed my `.env` to use an HTTP backend URL (not HTTPS).
https://github.com/magento/pwa-studio/issues/1311
This issue suggests that fix is not needed anymore, but seems like it is.

**Please complete the following device information:**
 - Magento Version: 2.3.2
 - PWA Studio Version: 4.0.0
 - NPM version `npm -v`: 6.9.0
 - Node Version `node -v`: 10.16.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Can you paste output of `DEBUG=pwa-buildpack:* yarn build`?

**Comment by brendanfalkowski** [comment]
Same error as the original error exit, just adds the `.env` var dump (obfuspiced the keys)

```bash
yarn run v1.17.3
$ yarn ce run build
$ yarn workspace @watscomagento/ce run build
$ yarn run build:prod
$ yarn run clean && yarn run load-env && webpack --no-progress --env.mode production
$ rimraf dist
$ node ../pwa-buildpack/bin/buildpack load-env --core-dev-mode .
  pwa-buildpack:Utilities:loadEnvironment.js Using environment variables from .env: [object Object] +0ms
  pwa-buildpack:Utilities:loadEnvironment.js Current known env
  MAGENTO_BACKEND_URL: 'https://ce.test/'
  CUSTOM_ORIGIN_ENABLED: true
  CUSTOM_ORIGIN_ADD_UNIQUE_HASH: true
  CUSTOM_ORIGIN_SUBDOMAIN: ''
  CUSTOM_ORIGIN_EXACT_DOMAIN: ''
  DEV_SERVER_HOST: ''
  DEV_SERVER_PORT: 0
  DEV_SERVER_SERVICE_WORKER_ENABLED: false
  DEV_SERVER_WATCH_OPTIONS_USE_POLLING: 0
  STAGING_SERVER_HOST: ''
  STAGING_SERVER_PORT: 0
  IMAGE_SERVICE_PUBLIC_PATH: '/img/'
  IMAGE_SERVICE_CACHE_EXPIRES: '1 hour'
  IMAGE_SERVICE_CACHE_DEBUG: false
  IMAGE_SERVICE_CACHE_REDIS_CLIENT: ''
  UPWARD_JS_UPWARD_PATH: 'upward.yml'
  UPWARD_JS_BIND_LOCAL: true
  UPWARD_JS_LOG_URL: true
  CHECKOUT_BRAINTREE_TOKEN: 'ifyouwanttobemyloveryougottogetwithmyfriends'
 +8ms
{ FetchError: request to https://ce.test/graphql failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/packages/pwa-buildpack/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message:
   'request to https://ce.test/graphql failed, reason: unable to verify the first certificate',
  type: 'system',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
FetchError: request to https://ce.test/graphql failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/packages/pwa-buildpack/node_modules/node-fetch/lib/index.js:1444:11)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/brendan/.nvm/versions/node/v10.16.1/bin/node
Arguments: /usr/local/Cellar/yarn/1.17.3/libexec/lib/cli.js run build
Directory: /Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/packages/ce
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by brendanfalkowski** [comment]
From Slack — add `NODE_TLS_REJECT_UNAUTHORIZED=0` in your `.env`

This works (same as using HTTP) but I'm not sure if this is a Node thing or undocumented Magento thing. It's not part of the generated `.env` file.

**Comment by zetlen** [comment]
This belongs to a general family of usability problems that come with using a local Magento instance. The main things we have to do are:

- Make it easy to give the Magento instance a valid self-signed TLS certificate
- Make the Magento instance respond over HTTPS and redirect from HTTP to HTTPS
- Expose the SSL certificate and key to the environment running PWA Studio
- Configure both the Node.js development environment and the developer's browser to trust the self-signed certificate

It would be best to automate that process; if that's hard to do, then we should at least make it only a few steps.

**Comment by tjwiebell** [comment]
@zetlen 
I'm going to assume @brendanfalkowski and I have both jumped on the Valet train, and the first two bullets are simple (`valet secure`). Exposing these self-signed certs will require some investigation, but seems feasible given we've been able to leverage the same functionality with `devcert`.

While this sounds like a perfect long term vision, I did want to propose a simple change right now, so we can avoid suggesting `NODE_TLS_REJECT_UNAUTHORIZED=0` anywhere in the app (would be devastating if someone went live with having SSL disabled in the entire app). Can we do something similar in `packages/pwa-buildpack/lib/Utilities/graphQL.js` as below? Seems it would be scoped to the GraphQL build step, and wouldn't continue to pollute the environment afterward.

https://github.com/magento/pwa-studio/blob/develop/packages/pwa-buildpack/lib/WebpackTools/plugins/UpwardDevServerPlugin.js#L9

**Comment by zetlen** [comment]
FYI @tjwiebell @brendanfalkowski I'm working on a more robust fix for this issue; at runtime, all our contact with the Magento backend should go through one UPWARD-created proxy, and that proxy should be configurable at runtime to include a custom certificate authority. The image opt middleware should work more like a compression middleware: instead of placing its own calls, it should just transform the response on the way through.

**Comment by tjwiebell** [comment]
Fixed by #1969

**Comment by zetlen** [comment]
Reopening to have a trackable issue for #2005 to run CI against.

**Comment by zetlen** [comment]
Reopening to have a trackable issue for #2005 to run CI against.

**Comment by this-is-shivangi** [comment]
**Describe the bug** : IWhen setting up magento pwa on the server getting connection timeout error.
**To reproduce**
Steps to reproduce the behavior:

1. yarn create @magento/pwa
2. changes in the env for backend url
3. yarn build

See error
`FetchError: request to https://demo13.iitpl.com/graphql failed, reason: connect ETIMEDOUT 14.141.23.100:443
    at ClientRequest.<anonymous> (/var/www/html/demo13.iitpl.com/pwa-studio/node_modules/@magento/pwa-buildpack/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
FetchError: request to https://demo13.iitpl.com/graphql failed, reason: connect ETIMEDOUT 14.141.23.100:443
    at ClientRequest.<anonymous> (/var/www/html/demo13.iitpl.com/pwa-studio/node_modules/@magento/pwa-buildpack/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
