### ISSUE TITLE
[SPIKE]: Extensibility via React Portals

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#1892]
# Extensibility via Portals Spike

This spike will investigate _additive_ (not _destructive_ ie. deletion/replacement) extensibility through use of [React Portals](https://reactjs.org/docs/portals.html). Using Portals for extensibility allows us to work around the potential issues of Webpack aliasing for replacement. Aliasing is good for global replacement of module imports and maybe even useful for targeting imports within a single module, but it does not provide a means to do specific, granular replacement within a single component. React Portals provide a means by which to declaratively expose specific extension points (via node id) in addition.

Below is a small code example to illustrate. `Header` is a Venia UI component and we want to allow extension before and after the Logo/Title.

```js
// A VeniaUI Header component
export const Header = props => {
  const { title } = useHeader(props);
  return (
    <div>
      <div id="extension-point-1" />
      <Logo />
      <span>{title}</span>
      <div id="extension-point-2" />
    </div>
  )
}
```

```js
/**
 * An extension that displays a user icon followed by the username. If the user
 * clicks the icon redirect to the account page if they are logged in, otherwise
 * show the login form.
 */
export const UsernameExtension = props => {
  const [{ username, isLoggedIn }, { showLogin, showMyAccount }] = useUserContext();

  const handleIconClick = useCallback(() => {
    if (isLoggedIn) {
      showMyAccount();
    }
    else {
      showLogin();
    }
  }, [isLoggedIn, showLogin, showMyAccount]);

  const extensionDom = (
    <div>
      <Icon src={UserIcon} onClick={handleIconClick} />
      {username}
    </div>
  );

  return ReactDOM.createPortal(
    extensionDom,
    document.getElementById('extension-point-1')
  );
}
```

## Questions

* **Where can extension points exist?**
 _Technically anywhere, at least within `AppContext` so that extensions have
 access to global state/actions. That said, **local context** such as forms presents
 another issue to be solved_.
* **Where should extension points exist?**
 _Generally "whitespace" in the application. But I can see CSS being problematic. 
 How do we deal with css selectors that apply to children like "grid", nth-child, etc?_
* **How do we name/identify extension points?**
  - `extension-point-#`
  - `<component>-extension-point-#`
  - `<component>-extension-point-before-<identifier>`, `<component>-extension-point-after-<identifier>`
* **How do we expose id/location of extension points for extension authors?**
 _We publish the API for our components. The EP within each is considered public
 API so we would need to figure out how to expose those. Additionally we wouldn't
 be able to change ordering if we just used a counter. Using `before/after` is
 probably most resilient to change._
* **How do we handle asynchronously rendered extension points?**
  **TODO**
* **What happens if two extensions target a single point?**
 _Using createPortal, they are rendered in the order they appear in client code._
 [![Image from Gyazo](https://i.gyazo.com/4e00ca35b965d4e63d23ca1e64fca032.png)](https://gyazo.com/4e00ca35b965d4e63d23ca1e64fca032)
* **What if the target doesn't exist or is permanently removed from the tree?**
 _We can conditionally render portals and log an error._
* **How do we pass props to extensions?**
 _In my opinion, we don't. Extensions should be self-contained and self-styled.
  If extensions need access to shared values they should get them from context._

## Pros

_TODO_

## Cons

_TODO_

## Examples

https://codesandbox.io/s/elated-sea-qmssv

## Spikes:

1) https://github.com/magento/pwa-studio/pull/1894
2) https://github.com/magento/pwa-studio/pull/1899

**Comment by cherdman** [comment]
@revanth0212  and @zetlen , I'm closing this issue and the related spike PRs.
