### ISSUE TITLE
[feature]: Gift cards in Venia 

### ISSUE THREAD

**Issue by awilcoxa** [magento/pwa-studio#1901]
As a shopper, I want to be able to use a gift card during my checkout process in order to apply my gift card balance to my existing order. The gift card balance should be deducted from my total order and I should be able to see this in my checkout summary.

### JIRA issue for design
https://jira.corp.magento.com/browse/UXD-173

Acceptance criteria: 
Venia Storefront supports gift card entry 
Uses GraphQL 
User can enter gift card number
Gift cards are validated 
Display of gift card balance 
Use can apply total or partial gift card balance to order 
Does not require authentication 

Out of scope: 
Applying gift card balance to account 

Additional Consideration: 
Peregrine/Talons requirements

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x ] `venia-ui`
- [ ] `pwa-buildpack`
- [ x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-78

**Comment by soumya-ashok** [comment]
Gift cards also have a My Account side to them, but for this milestone, we will be delivering the cart version as demo-ed by @schensley at the last design review. @awilcoxa

**Comment by schensley** [comment]
PNG and MP4 design deliverables attached to: https://jira.corp.magento.com/browse/UXD-173
Please review.

**Comment by sirugh** [comment]
Done! #2124
