### ISSUE TITLE
[doc]: Debugging with PWA Studio

### ISSUE THREAD

**Issue by jcalcaben** [magento/pwa-studio#1906]
**Describe the request**

Debugging in PWA Studio

**Possible solutions**

A new topic that covers the following:

* What is debugging?
* Why debug?
* How to enable debugging in PWA Studio

**More information**

Using build:dev to make uncompressed bundles, to debug things you can't reproduce in dev mode

Using the DEBUG environment variable to control the logging by the debug library used in our NodeJS tools

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Please let us know whether this is a new topic or a topic change request:**
 - [x] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by awilcoxa** [comment]
closing as resolved: https://magento.github.io/pwa-studio/pwa-buildpack/troubleshooting/
