### ISSUE TITLE
[doc]: Developer tools

### ISSUE THREAD

**Issue by jcalcaben** [magento/pwa-studio#1907]
**Describe the request**

Documentation on useful developer tools

**Possible solutions**

A new topic that provides a list of useful developer tools such as the React , Apollo, and GraphQL dev tools

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Please let us know whether this is a new topic or a topic change request:**
 - [x] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by awilcoxa** [comment]
closing as resolved
