### ISSUE TITLE
[doc]: Using GraphQL playground

### ISSUE THREAD

**Issue by jcalcaben** [magento/pwa-studio#1908]
**Describe the request**

A topic that describes the GraphQL playground feature in PWA Studio

**Possible solutions**

A topic that covers the following:

* What is the GraphQL playground
* How to use the GraphQL playground

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Please let us know whether this is a new topic or a topic change request:**
 - [x] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by awilcoxa** [comment]
closing as resolved: https://magento.github.io/pwa-studio/technologies/basic-concepts/graphql/
