### ISSUE TITLE
[bug]: remove redux.compose() where not needed

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#1915]
**Describe the bug**
`redux.compose()` is sometimes used with a single argument, which isn't necessary:
https://redux.js.org/api/compose

**Expected behavior**
The function passed as an argument can be called directly because no composition is needed.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by zetlen** [comment]
This is a quick fix and a great first issue! It's just code cleanup.
