### ISSUE TITLE
[bug]: Upon removing the last layered navigation filter, the url search segment is not cleared

### ISSUE THREAD

**Issue by shakyShane** [magento/pwa-studio#1921]
**Describe the bug**
Upon removing the last layered navigation filter, the url `search` segment is left with empty `?&`

**To reproduce**
1. Go to any product list
2. Select 1 or more filters & hit click 'apply filters'
3. remove all filters
4. see `?&` in the url bar

**Expected behavior**
the url is cleaned of search params

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by dani97** [comment]
https://github.com/magento/pwa-studio/pull/1884 should have fixed this issue. Couldn't reproduce too,

**Comment by sirugh** [comment]
Sweet! Closing.
