### ISSUE TITLE
[feature] Compatibility with multiple websites and stores

### ISSUE THREAD

**Issue by idziakjakub** [magento/pwa-studio#1925]
**Is your feature request related to a problem? Please describe.**
I have current working Magento with one website and one store view. I want to create a second website and store view and use PWA Studio on a storefront.
When I installed PWA Studio and connected it with a new website URL I'm getting data from the first `default` website (CMS pages, products, categories). I checked PWA Studio code and I see there are no settings or env variables to set which store/website I want to use:

- according to this documentation: `https://devdocs.magento.com/guides/v2.3/graphql/send-request.html` GraphQL has the ability to send a header with store code, but I don't see an implementation of it in code.
- in `peregrine` module every API endpoint calls are not using store code in URL, eg.
`file: packages/peregrine/lib/store/actions/cart/asyncActions.js`
```
            const guestCartEndpoint = '/rest/V1/guest-carts/${cartId}/items/${
                item.item_id
            }';
            const signedInCartEndpoint = '/rest/V1/carts/mine/items/${
                item.item_id
            }'; 
```

**Describe the solution you'd like**
I think in the simplest solution store/website code should be stored in env file and the developer should have the ability to select which store/website data will be fetched from API / GraphQL.
Every GraphQL query should have defined `"Store"` header and API call should have store code in URL endpoint.

**Describe alternatives you've considered**
The more advanced solution should have a map of all used websites/store views in env settings and store switcher, which will store data about the current store view in browser storage.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [x] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Closing this as we have implemented a good portion of multi-store compatibility including a store switcher and gql header additions.
