### ISSUE TITLE
[bug]: Filters: unable to select fashion color filters

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1930]
**Describe the bug**
User is unable to select Fashion colors filters. 

**To reproduce**
1. Go to any category and click on Filters button on `develop` https://magento.pwa-venia.com/
2. On Filters drawer expand Fashion Color section.
3. Click on any Fashion color. 

**Expected behavior**
Color should get selected as Filter.

**Expected behavior**
Colors are no more getting selected.

Note - Works fine in `4.0.0` release https://magento.pwa-venia.com/.  Broken in `develop` https://develop.pwa-venia.com/

**Screenshots**
**`develop`**

<img width="343" alt="image" src="https://user-images.githubusercontent.com/40405790/67324252-26f23980-f4d9-11e9-8787-edfea2c82c7b.png">

**`master` (4.0.0)**

<img width="352" alt="image" src="https://user-images.githubusercontent.com/40405790/67324233-1d68d180-f4d9-11e9-8ed5-a794e4c6f352.png">

**Comment by sirugh** [comment]
These are being rewritten right now in #1884. Check with @jimbo and see if he has fixed this in the refactor. If he has, we can close this.
