### ISSUE TITLE
[feature]: Provide .gitignore file when setting up new pwa using npm init @magento/pwa

### ISSUE THREAD

**Issue by duckchip** [magento/pwa-studio#1931]
Hi guys, 

I just set up a new pwa project using `npm init @magento/pwa` and noticed that the .gitignore file is missing.

It would be nice if this comes by default :) 

Thx in advance!

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by LucasCalazans** [comment]
Working on this issue
