### ISSUE TITLE
[feature]: Support for nodejs >= 12.x in magento/venia-concept

### ISSUE THREAD

**Issue by abolivar** [magento/pwa-studio#1934]
The status: Active for version NodeJS 10.x LTS ends in April/2020

**Please let us know what packages this feature is in regards to:**
- [X] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by LucasCalazans** [comment]
A good thing to say is that the documentation says that NodeJS >=10.14.1 is compatible.
https://magento.github.io/pwa-studio/venia-pwa-concept/setup/#prerequisites

**Comment by abolivar** [comment]
> A good thing to say is that the documentation says that NodeJS >=10.14.1 is compatible.
> https://magento.github.io/pwa-studio/venia-pwa-concept/setup/#prerequisites

Yes, but you will not install it if you have 11 or 12, the package.json for venia-concept sets: 

`"engines": {
    "node": "10.x",
    "yarn": ">=1.12.0"
  }`

At first glance I don't see anything depreciated with node 12, and it should only be replaced by:
`"engines": {
    "node": ">=10.x",
    "yarn": ">=1.12.0"
  }`

Which is the dependency version in the other packages

**Comment by thierry2015** [comment]
Any development on this?

**Comment by 0ctothorp** [comment]
Yeah, also this is causing the same problem in `create-pwa` since it uses `venia-concept` as a template for new projects. Everytime I start a project I need to change `engines.node` to `>=10.x` in package.json.
