### ISSUE TITLE
[feature]: Get the catalog page size using GraphQL query

### ISSUE THREAD

**Issue by LucasCalazans** [magento/pwa-studio#1940]
**Is your feature request related to a problem?**
We need to get the catalog page size value from the `storeConfig` query, since that it is already implemented on the Magento GraphQL.

**Additional context**
Magento GraphQL implementation: https://github.com/magento/graphql-ce/pull/650

Files where it needs to be replaced:
* https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/RootComponents/Category/category.js#L125
* https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/RootComponents/Category/categoryContent.js#L14
* Probably not this one, but it will be a good reference on where we need to update: https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/store/reducers/catalog.js#L22 

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by larsroettig** [comment]
Work on this :-)

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Work has been completed as part of https://github.com/magento/pwa-studio/pull/2686
