### ISSUE TITLE
[bug]: Build and watch fail with bad error message when environment validation fails

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1942]
**Describe the bug**
Since #1832 and the new `configureWebpack` structure, trying to run the dev server or build with an invalid environment will log a strange error message.

```sh
15:41 jzetlen@jzetlen-macOS $ DEV_SERVER_PORT=bad yr watch:venia
yarn run v1.19.1
$ yarn venia run watch
$ yarn workspace @magento/venia-concept run watch
$ webpack-dev-server --progress --color --env.mode development
  ⓧ  Invalid environment variables:
     DEV_SERVER_PORT: Invalid number input: "bad"
TypeError: projectConfig.sections is not a function
    at module.exports (packages/pwa-buildpack/lib/Utilities/getClientConfig.js:206:38)
✨  Done in 3.85s.
```

It's not properly handling an error state returned by `loadEnvironment()`.

**To reproduce**
1. Check out the develop branch and install.
2. Run `DEV_SERVER_PORT=bad yarn run watch:venia`, which sets an invalid environment variable before running watch.

**Expected behavior**
The process should exit nonzero and should not log an unfamiliar-looking error message.

**Additional context**
This is because the new `configureWebpack` pattern assumes that `loadEnvironment()` will return a `projectConfig` object. But every return value from `loadEnvironment()` must be checked for an `error` property before proceeding, which may not be clear enough in that API. This is to distinguish normal validation errors from unexpected exceptions, which actually throw.

**Possible solutions**
Detect the error state in `configureWebpack` with a conditional, and exit nonzero. The `loadEnvironment()` function will take care of logging the right error message.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by dpatil-magento** [comment]
re-verified after recent commits, looks good.
