### ISSUE TITLE
[bug]: Not able to get the filters state outside filter modal, coz now it is private

### ISSUE THREAD

**Issue by abelyanvahe** [magento/pwa-studio#1947]
**Describe the bug**
So I see that you moved the state to local state. But if you remember, the getCategory query happens in the category component, which is outside the FilterModal component. So How you are going to get the filters there in order to send it with the getCategory query?
In the previous version, I could easily get it from Redux via context, but now I don't see any ways.
Thanks in advance.

**Possible solutions**
Not sure what needs to be done in this situation. Maybe you will advice?

**Comment by abelyanvahe** [comment]
Hi @jimbo . Thanks for your reply. I would prefer the first option. useFilterState should belong to the category component. In that case we can use it easily in the category query.

**Comment by abelyanvahe** [comment]
If you could do that and deploy, that would be great)

**Comment by jimbo** [comment]
@abelyanvahe It'll have to go through our pipeline; it's not something we're just going to build right now and deploy. 😅 

For now, I'd suggest pulling filter params from the URL or pinning to an earlier commit. Alternatively, if you already have a changeset in mind, please consider opening a pull request. Thank you!

**Comment by awilcoxa** [comment]
Marked as P3S3 low priority during grooming

**Comment by larsroettig** [comment]
I think can be closed @awilcoxa should be fine now

**Comment by davemacaulay** [comment]
This is tracked internally within https://jira.corp.magento.com/browse/PWA-168

**Comment by sirugh** [comment]
Closing as cancelled.
