### ISSUE TITLE
[feature]: Update to graphql-cli@4.0.0-alpha and use codegen

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#1950]
**Is your feature request related to a problem? Please describe.**
The 3.x version of the `graphql-cli` tool has some bugs including https://github.com/Urigo/graphql-cli/pull/447, which aren't being fixed because they're working on version 4.0.0. Let's adopt the 4.0 alpha, which includes some much better features including **codegen, which would give us TypeScript definitions and autocomplete for GraphQL types.**.

**Describe the solution you'd like**
- Upgrade of the graphql-cli dependency to 4.0.0-alpha
- Port our graphql-cli plugin to the new API
- (Alternatively, deprecate our plugin if the new architecture no longer requires a plugin to do what we need)
- Add `codegen` scripts which autogenerate TypeScript definition files for the current schema
- Add those scripts to the standard dev lifecycle
- Confirm that they autocomplete in text editors

**Describe alternatives you've considered**
We can check on the `apollo-cli` tool again, but last I checked, it was not really useful outside the apollo-server ecosystem.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story
