### ISSUE TITLE
[doc]: Telling me plz how to build pwa from scratch

### ISSUE THREAD

**Issue by DevAwais** [magento/pwa-studio#1967]
**Describe the request**
A clear and concise description of the documentation request or where the documentation can be improved.

**Possible solutions**
How would you word this addition or change?

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by awilcoxa** [comment]
Hi @DevAwais If you have specific questions on implementing/building a PWA please direct them to community slack channel and we would be happy to assist (I've sent you an invite via email).
