### ISSUE TITLE
[bug]: Directive parser for root components fails

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#1990]
**Describe the bug**

A root component's default export must be sourced from `/components`. If it lives in the same folder as the root component's `index.js` then the Magento directive parser will fail the build with this error when certain imports (for me, API fetching with useQuery) are called.

```
ERROR in (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1
    Module build failed (from (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js):
    TypeError: Cannot read property 'type' of undefined
        at Parser.match (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/Parser.js:67:22)
        at Parser.parseDirective (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/Parser.js:43:19)
        at Parser.parse (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/Parser.js:29:14)
        at module.exports (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/Parser.js:168:58)
        at comments.reduce (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/index.js:12:38)
        at Array.reduce (<anonymous>)
        at parseDirectives (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/node_modules/@magento/directive-parser/src/index.js:11:40)
        at Promise.all.rootComponentFiles.map (/Users/brendan/work/clients/ce/carrierenterprise.com_m2/repo-pwa/packages/pwa-buildpack/lib/WebpackTools/plugins/RootComponentsPlugin.js:108:56)
        at process._tickCallback (internal/process/next_tick.js:68:7)
     @ multi (webpack)-dev-server/client?https://watscomagento-ce-nibh1.local.pwadev:8634 (webpack)/hot/dev-server.js (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js client[2]
```

**To reproduce**

Create a new root component like this:

File: /RootComponents/CustomerInfo/index.js

```
/**
 * @RootComponent
 * description = 'Customer Info'
 * pageTypes = CUSTOMER_INFO
 */
export { default } from './customerInfo';

```

File: /RootComponents/CustomerInfo/customerInfo.js

```
import React, { useEffect } from 'react';
import { useQuery } from '@magento/peregrine';
import customerInfoQuery from '../../queries/getCustomerInfo.graphql';

const CustomerInfo = () => {
    // Writing this line causes failure
    const [{ data, error }, { runQuery, setLoading }] = useQuery(
        customerInfoQuery
    );
    return <p>Hello world</p>;
};
```

If you do this with the watcher running, it'll be fine. If you write the useEffect code to actually fetch data that'll work too.

But once you stop and restart the watcher, the build will fail.

You have to remove every import related to querying (useEffect, useQuery, customerInfoQuery) and the useQuery call before the build will work again. Weirdly if you add them one-at-a-time, and restart the build between each change it will not fail to build until `useQuery` is called.

**Expected behavior**
A root component's default export can be a component stored in the root component folder.

The default export must be sourced from `/components` to work.

**Additional context**
I'm not sure if a Talon had been used in the root component's component that it would have failed. I didn't test that case — only querying directly fails.

Our repo is synced up to develop circa October 9, 2019 @ 4:30pm, so we still have:
`import { useQuery} from '@magento/peregrine';`

On October 10, this was replaced with Apollo Hooks version of useQuery. I did not test if the directive parsing fails similarly in a current "develop" instance of PWA Studio.

**Possible solutions**
Discussed with @sirugh @supernova-at @jimbo on CommEng Slack. It "should" work, but Magento is moving toward root components being "thin" (i.e. directive parsing comments + import a component).

Option A: change where the component lives, which doesn't break the directive parser when useQuery hooks are used.
* From: `RootComponents/{Name}/{name}.js`
* To: `components/{Name}/{name}.js`

Option B: keep the folder in RootComponents, but remove the comment block identifying the type. This also works, but you need to understand what's happening here so it's not great.

Option C: change where the component lives, but don't bloat the `/components` folder tons for view-level components that aren't *really* reusable from a UI perspective. The real root components that Magento needs to do directive parsing on where left in place.
* From: `RootComponents/{Name}/{name}.js`
* To: `modules/{Name}/{name}.js`

For posterity, we went with Option C for now because this is a clearer organizational structure than a naming convention tacked onto each component.

**Please complete the following device information:**
 - PWA Studio Version: 4.0.0 circa October 9, 2019 @ 4:30pm
 - NPM version `npm -v`: 6.9.0
 - Node Version `node -v`: 10.16.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Following grooming, team flagged as a P3 (average) priority. Bug currently remains in backlog and will be addressed following any existing P0-P2 bugs. We can re-prioritize based on additional information from community (@brendanfalkowski).

**Comment by Jordaneisenburger** [comment]
@brendanfalkowski I encountered a similar issue check https://github.com/magento/pwa-studio/issues/2239

**Comment by davemacaulay** [comment]
This is tracked under https://jira.corp.magento.com/browse/PWA-166
