### ISSUE TITLE
[feature]: Implement list/grid switcher for PLP

### ISSUE THREAD

**Issue by MaksymShcherbyna** [magento/pwa-studio#1991]
**Description**
Currently theme doesn't have any alternatives for change PLP view. So my offer is implement toggle button, for example, near title to change view. As example, please see screens below.

Before click on button:
![gridView](https://user-images.githubusercontent.com/57752997/69349079-d6106500-0c7f-11ea-8e38-4b59fad2aa9d.png)

After click on button:
![listView](https://user-images.githubusercontent.com/57752997/69349089-d9a3ec00-0c7f-11ea-9e03-040e9551bc73.jpg)

- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Sorry but this isn't a feature that we're looking to implement in PWA Studio. You are, of course, welcome to fork and apply the changes you made to your own repository. In the future we hope to make it easier to customize/extend the code for your own needs but currently we are just trying to harden around the current UI before making any major refactors or unplanned UX decisions.
