### ISSUE TITLE
Apply Filters button is enabled after removing all selected category in category filter

### ISSUE THREAD

**Issue by gauravagarwal1001** [magento/pwa-studio#1996]
**Describe the bug**
Apply Filters button is enabled after removing all selected category in category filter.

**To reproduce**
    1. Go to any category page.
    2. Click on filter button.
    3. Select some category and click on apply button.
    4. Again open category filter and remove all category selection .
    No filter is selected but apply button is enabled

**Expected behavior**
Apply Filter button must be disable if category is not selected

**Screenshots**
![ezgif-1-fb3812b64da4](https://user-images.githubusercontent.com/37572719/69385630-01c63600-0ce6-11ea-9fa3-539ab6f0d5ba.gif)

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Now tracked in JIRA: https://jira.corp.magento.com/browse/PWA-220

**Comment by sirugh** [comment]
> This is actually functioning as intended. Instead, a better check would be to make only enable the "Apply Filters" button if the filters have been touched AND differ from the state they opened with.
I'm going to close this for now, if you want to try to solve it in the future, open a new issue but let's discuss the solution before you give it a shot so we can save everyone some time :)
