### ISSUE TITLE
Email validation missing in forgot password form 

### ISSUE THREAD

**Issue by gauravagarwal1001** [magento/pwa-studio#1998]
**Describe the bug**
 Email validation in forgot password form.

**To reproduce**
Go to pwa-studio home page
Click on navigation
Go for Sign in and then click on forgot password link
Forgot password form email field has only required validation

**Expected behavior**
Forgot password form email field must have email as well as required field validation

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Now tracked in JIRA: https://jira.corp.magento.com/browse/PWA-191
