### ISSUE TITLE
Development Url Issue on Server

### ISSUE THREAD

**Issue by shikhasshukla** [magento/pwa-studio#2006]
I have uploaded my Pwa studio on server "test.demo.com" which is already secured and i set the .env  file with following details 
DEV_SERVER_HOST=test.demo.com
DEV_SERVER_PORT=5000
so every time my project is running at "http://test.demo.com:5000/". But Pwa features are not working as my url is not secure. How to set https for my url when project is build.

**Comment by NamCt1191995** [comment]
On version 4.
`CUSTOM_ORIGIN_ENABLED = 1`

Lower version it should be `MAGENTO_BUILDPACK_PROVIDE_SECURE_HOST`

**Comment by awilcoxa** [comment]
Closing as resolved, thanks @NamCT246 

@shikhasshukla if you're still having issues feel free to post in the community slack channel.
