### ISSUE TITLE
Host venia theme on server but generated secure url not run on other devices.

### ISSUE THREAD

**Issue by vpberiya** [magento/pwa-studio#2016]
Generate ssl certificate for **CUSTOM_ORIGIN_EXACT_DOMAIN**=www.pwa.com using command **yarn buildpack create-custom-origin packages/venia-concept**.

after excuting the **yarn run build && yarn run stage:venia** generate the secure url like https://www.pwa.com but this secure the url only run securely for my own pc but on another devices not run becuase of invalild certificate.

**Comment by sirugh** [comment]
Correct, the `create-custom-origin` script generates a certificate for local development only. You'll need an actual certificate when hosting your server for production.

**Comment by vpberiya** [comment]
How to connect actually certificate with our venia theme folder on server
