### ISSUE TITLE
[doc]: Production PWA Studio Performance Optimization

### ISSUE THREAD

**Issue by jihadbek** [magento/pwa-studio#2020]
Hi,
i try to find a good documentation for performance related configs and optimization needed when using PWA studio, the points which i am ( and maybe others ) not sure about similar to some settings of magento which i dont know if it does affect PWA performance or not like :
- Full Page Cache and other types of caching.
- Running Magento in Developer or production modes
- Server Side Optimization and settings to improve a production PWA Studio Performance related to node.js and PM2 .
Thanks!

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by davemacaulay** [comment]
Hey @jihadbek here are some answers to your questions expanding on Anthoula's above.

- Full Page Caching is part of Magento core and won't have an impact on performance for PWA Studio.
- If you're running a production store it'd be advisable to run the back-end in production mode, running in developer mode may cause slow downs in areas which could impact PWA Studio.
- We currently only have supported documentation for our Magento Cloud deployment. We do not currently have an SSR solution so cannot recommend configuration regarding Node.js / PM2.

We are currently in the process of preparing a number of performance pieces of work, which will be released with necessary documentation. So please be on the look out for these in future releases.

For now I'm going to close this ticket, if you have more questions please let us know.
