### ISSUE TITLE
[bug]: Error 500 for load image category and product

### ISSUE THREAD

**Issue by haunguyen1989** [magento/pwa-studio#2045]
Describe the bug
Images of categories & products are not shown on the frontend -- instead the request returns a 500. Following that image-url yields a 500 with the body-text:
Status Code: **500 Internal Server Error**
https://magento-venia-concept-3328z.local.pwadev:8048/media/catalog/category/timeless.jpg?auto=webp&format=pjpg&width=80&height=100&fit=cover

**- I have test url:**
https://magento-venia-concept-3328z.local.pwadev:8048/media/catalog/category/timeless.jpg
**=> It's work**
**- But if I have parameter:**
https://magento-venia-concept-3328z.local.pwadev:8048/media/catalog/category/timeless.jpg?auto=webp&format=pjpg&width=80&height=100&fit=cover
**=> It's don't work**

**To Reproduce**
I have a local Magento 2.3.3 instance running, loaded with the Venia sample-data, running locally at "https://backend-pwa.dev.com/" (mapped to the /pub in the docksal vhost configuration). The storefront is configured to use this endpoint as MAGENTO_BACKEND_URL. Categories and products are displayed, just not the image.

**Steps to reproduce the behavior:**

Go to the home page that should display category images
Click on any category to view products that should display product images
![Screenshot from 2019-12-26 10-09-04](https://user-images.githubusercontent.com/44774202/71455480-d42e4a00-27c7-11ea-9109-a925a6f8f12f.png)
![Screenshot from 2019-12-26 10-10-53](https://user-images.githubusercontent.com/44774202/71455541-0d66ba00-27c8-11ea-85a1-bb53c9989db8.png)
![Screenshot from 2019-12-26 10-11-33](https://user-images.githubusercontent.com/44774202/71455567-266f6b00-27c8-11ea-879b-9ac615289069.png)

**Expected behavior**
Images being displayed.

**Comment by dpatil-magento** [comment]
@haunguyen1989  Is this related to  https://github.com/magento/pwa-studio/pull/2005 ?

**Comment by awilcoxa** [comment]
Flagged for prioritization during backlog grooming

**Comment by awilcoxa** [comment]
closed by #2005

**Comment by awilcoxa** [comment]
Re-opening until PR is merged

**Comment by tjwiebell** [comment]
Actually closed by #2005 now.
