### ISSUE TITLE
[bug]: Upward JS is having trouble serving binary files

### ISSUE THREAD

**Issue by SirCoolness** [magento/pwa-studio#2049]
**Describe the bug**
Upward-js seems to have issue serving binary files (images, archives, etc) through the FileResolver. 

**To reproduce**
1. Run in staging `yarn run stage:venia`
2. Open `http://<served host>/favicon.ico`
3. It should come out empty or with an error

**Expected behavior**
GET favicon in browser.

**Additional context**
This seems to be related to [#408](https://github.com/magento/pwa-studio/issues/408)

**Possible solutions**
The issue seems to be caused by 'binary' being interpreted as 'latin1' by node js. https://stackoverflow.com/a/46441727

**Please complete the following device information:**
 - Device: Desktop
 - OS: Ubuntu 18.04 (linux 5.3.0-lowlatency)
 - Browser: Chrome, Firefox
 - PWA Studio Version: develop branch
 - NPM version: 6.9.0
 - Node Version: v10.16.0

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [x] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by treestonemedia** [comment]
👍

**Comment by awilcoxa** [comment]
Added to backlog for prioritization in next grooming
