### ISSUE TITLE
[bug]: webpack issue when yarn run build

### ISSUE THREAD

**Issue by subhastak** [magento/pwa-studio#2100]
ERROR in (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1
Module not found: Error: Can't resolve './..
enia-uilibRootComponentsCMSindex.js' in 'C:\xampp\htdocs\magento\pwa-studio\packages\venia-concept'
@ (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-1 5:71-177
@ multi (webpack)-inject-plugin/dist/webpack-inject-plugin.loader?id=webpack-inject-module-1 ./src/index.js

**To reproduce**
1. Take a windows machine.
2. Follow the instruction to set up venia storefront using the link https://magento.github.io/pwa-studio/venia-pwa-concept/setup/
3. See error when running the command "yarn run build"

**Expected behavior**
Should build without giving errors.

**Screenshots for the Build**
![yarn build 1](https://user-images.githubusercontent.com/59599892/72334860-07d40400-36e4-11ea-92cd-2297e71c1df3.png)
![yarn build 2](https://user-images.githubusercontent.com/59599892/72334863-086c9a80-36e4-11ea-946f-52b8e4d30c3e.png)
![yarn build 3](https://user-images.githubusercontent.com/59599892/72334864-086c9a80-36e4-11ea-8fd8-1feafb103721.png)

**Comment by sirugh** [comment]
This is being tracked with https://github.com/magento/pwa-studio/issues/898, closing as duplicate. Please follow that issue for updates!

**Comment by abdul-hameed-dev** [comment]
@sirugh i am getting same issue, please can you help me out from this issue

**Comment by DeepShah2511** [comment]
@sirugh I ma also facing this issue it's webpack issue in Magento PWA, can you help me out with this issue
![yarn-run-build-webpack-issue](https://github.com/magento/pwa-studio/assets/43378314/4f97f3d2-3244-42f0-b6b3-aaaa079ad4d2)
