### ISSUE TITLE
[feature]:  Allow to use `connectToDevTools` for  `VeniaAdapter`

### ISSUE THREAD

**Issue by larsroettig** [magento/pwa-studio#2105]
**Is your feature request related to a problem? Please describe.**
To use the Apollo Browser extension is required to use set  
`connectToDevTools: true` on adapter create.

*Browser extension:* 
https://www.apollographql.com/docs/react/development-testing/developer-tooling/

**Describe the solution you'd like**

Allow setting `connectToDevTools: true` on developer mode for https://github.com/magento/pwa-studio/blob/ca08ad83b474bb3e49a114c37aa3f5fba14265a2/packages/venia-ui/lib/drivers/adapter.js#L67

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by zetlen** [comment]
I spoke with @larsroettig in Slack about this and he's working on a PR for it.

**Comment by sirugh** [comment]
Unless I'm mistaken this property is only exposed as a way to enable dev tools in production or to manually disable the dev tools in development. Check out Apollo's [documentation](https://www.apollographql.com/docs/react/development-testing/developer-tooling/#configuration).

> Apollo Client adds this hook to the window automatically unless process.env.NODE_ENV === 'production'

After installing the chrome extension I'm able to view Apollo dev tools, the cache, and used queries/mutations on the `develop` branch.

> While your app is in dev mode, the devtools will appear as an "Apollo" tab in your chrome inspector.
