### ISSUE TITLE
[bug]: venia-static files don't load out-of-the box with scaffolding command

### ISSUE THREAD

**Issue by rossmc** [magento/pwa-studio#2109]
**Describe the bug**
Files such as `manifest.json` and `favicon.ico` do not load after you create a project with the _create-pwa_ scaffolding command.

The issue is slightly different if you start running the project with `yarn run watch` or `yarn start`.  

**To reproduce**
1. Creat a clean PWA Studio project with 
```
yarn create @magento/pwa
yarn run buildpack create-custom-origin .
yarn watch
```
2. Open the project in a browser.  Note that neither the  `manifest.json` or `favicon.ico` files load.
3. Try to open the manifest.json file in the browser, i.e. _example.local.pwadev:8092/manifest.json_
4. Note the _Error in PWADevServer v5.0.0-rc.1_.  **This is the first issue with this.**
5. The error above can be solved by copying the [venia-static/] from github to your project's root directory.  I think this step should not be required.
6. Try running the project with a the local staging server.
```bash
yarn run build
yarn start
```
7. Open the project in a browser.  Note that even with the _venia-static/_  folder added that neither the  `manifest.json` or `favicon.ico` files load.
8. Try to open the manifest.json file in the browser again.
9. Note a different error message the _Error in upward-js v4.0.0-rc.1_.  **This is the second issue with this.**

**Expected behavior**
I would expect that the _venia-static/_ files should load without any issues after creating a project with the _create-pwa_ scaffolding command

**Screenshots**
![Screenshot 2020-01-17 at 12 01 57](https://user-images.githubusercontent.com/2452991/72664036-9785f500-39f9-11ea-9c05-ecc052a5a65f.png)
![Screenshot 2020-01-17 at 12 02 57](https://user-images.githubusercontent.com/2452991/72664037-9785f500-39f9-11ea-8472-272edd90b689.png)
![Screenshot 2020-01-17 at 12 03 48](https://user-images.githubusercontent.com/2452991/72664038-9785f500-39f9-11ea-8a5b-34adc0c2450b.png)
![Screenshot 2020-01-17 at 12 04 02](https://user-images.githubusercontent.com/2452991/72664039-981e8b80-39f9-11ea-830f-82087eff3c4e.png)
![Screenshot 2020-01-17 at 17 49 18](https://user-images.githubusercontent.com/2452991/72664040-981e8b80-39f9-11ea-9ae8-3605c428685f.png)

**Additional context**
These are the _@magento_ package versions being used in my projects package.json.
```json
"@magento/babel-preset-peregrine": "1.0.1-rc.1",
"@magento/eslint-config": "~1.5.0",
"@magento/peregrine": "5.0.0-rc.1",
"@magento/pwa-buildpack": "5.0.0-rc.1",
"@magento/upward-js": "4.0.0-rc.1",
"@magento/venia-ui": "2.0.0-rc.1",
```

**Possible solutions**
I can get these files to load if I do the following, but I don't think this is the best approach.  Posting it here for now incase someone finds it useful.
1. Copy the [venia-static/] from github to your project's root directory.
2. Make the following change to package.json for the staging server to work correctly.
```
diff --git a/package.json b/package.json
index 3968fa2..4715d5e 100644
--- a/package.json
+++ b/package.json
@@ -7,7 +7,7 @@
   "license": "UNLICENSED",
   "scripts": {
     "buildpack": "buildpack",
-    "build": "yarn run build:prod",
+    "build": "yarn run build:prod && cp -R venia-static dist/",
```

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: MacbookPro
 - OS [e.g. iOS8.1, Windows 10]: OSX Mojave 10.14.5
 - Browser [e.g. Chrome, Safari]: Chrome 
 - Browser Version [e.g. 22]: 79 
 - Magento Version: https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/
 - PWA Studio Version: 5.0.0-rc.1
 - NPM version `npm -v`: 6.9.0
- Yarn version `yarn -v`: 1.13.0
 - Node Version `node -v`: v10.16.3

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

[venia-static/]: https://github.com/magento/pwa-studio/tree/develop/packages/venia-ui/venia-static

**Comment by awilcoxa** [comment]
Flagged for prioritization during backlog grooming

**Comment by tjwiebell** [comment]
From my investigation there are a few problems here:
* Runtime development assets are not available when loading `upward.yml` from root when doing `yarn watch` (requiring you to manually copy to get them working). Worth noting on first build, these assets are available when running `yarn start`, which loads the config from `/dist/upward.yml` where `/dist/venia-static` happens to be present.
* Assets are available inside of `/dist/venia-static` upon first build only. Subsequent builds do not copy this directory, even when manually copied.

This top level pattern matcher is what's causing this routing:
```
- matches: request.url.pathname
    pattern: '^/(robots\.txt|favicon\.ico|manifest\.json)'
    use: staticFromRoot
```

I see some recent changes where we renamed `venia-static` to `static` in `venia-concept`, so I'm getting the feeling we just never updated buildpack and the UPWARD config to copy and serve from this directory. Thanks for your report, we'll continue investigating and let you know when we have a fix ready to test.

**Comment by 0ctothorp** [comment]
I'm still encountering this behaviour :/ After `yarn build` and `yarn start` the manifest.json is not served. I tried creating `venia-static` and `static` directories in the project root and. Neither of them gets copied to the `dist`.

**Comment by tjwiebell** [comment]
@0ctothorp  - until we publish the fix to npm, you will still encounter this behavior. You can simulate pulling a new release from npm by running `DEBUG_PROJECT_CREATION=1 packages/create-pwa/bin/create-pwa` from the repo root. You should hopefully see `venia-static` now.

**Comment by 0ctothorp** [comment]
@tjwiebell thanks! I wasn't sure if it was published or not.
