### ISSUE TITLE
[bug]:Product detail page some products not retrieve data with query 

### ISSUE THREAD

**Issue by WaqasMumtaz** [magento/pwa-studio#2118]
(1 issue :) In RootComponents Products folder the issue is >>Uncaught TypeError: Cannot read property 'items' of undefined .

(1 issue :) Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http://ups/' cannot be created in a document with origin 'http://localhost:65039' and URL 'http://localhost:65039/'

(3 issue :) Main page data does not showing always this error show come >> 'That page could not be found . Please try again' 

So please someone guide me how to solve this issues i am very stuck in these issues last 20 days

**Comment by awilcoxa** [comment]
@WaqasMumtaz  can you provide additional information and detailed repro steps?

**Comment by sirugh** [comment]
As we haven't received a response in some time, I'm going to close this issue. If you still experience this please open a new ticket with some more details and steps to repro so that we can help debug. Thanks!
