### ISSUE TITLE
[bug]: A short, simple sentence describing the bug

### ISSUE THREAD

**Issue by gohoney** [magento/pwa-studio#2134]
after run sudo yarn run stage:venia successfuly and then open pwa store homepage. the circle small image only display one not five
my all version is recentely
how to fix it
GET /media/timeless.jpg?auto=webp&format=pjpg&width=80&height=100&fit=cover 404 68.649 ms - -
GET /media/outside.jpg?auto=webp&format=pjpg&width=80&height=100&fit=cover 404 103.650 ms - -
GET /media/carefree.jpg?auto=webp&format=pjpg&width=80&height=100&fit=cover 404 51.611 ms - -
GET /media/minimalist.jpg?auto=webp&format=pjpg&width=80&height=100&fit=cover 404 45.322 ms - -

**Comment by awilcoxa** [comment]
@gohoney can you please provide additional information here including an accurate description/title for the bug, screenshots of the behavior, and accurate repro steps?

**Comment by gohoney** [comment]
![QQ图片20200204170006](https://user-images.githubusercontent.com/53387016/73730423-b1516700-4771-11ea-8114-31e97210d292.png)
@awilcoxa   I step by step folowing the magento2 official tutorial to install pwa-studio
only MAGENTO_BACKEND_URL="https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" replace witn myself  domain of magentostore that have install sample data successfuly and can open no problem
![QQ图片20200204165635](https://user-images.githubusercontent.com/53387016/73730408-abf41c80-4771-11ea-8fc5-65cff7b110c9.png)

**Comment by gohoney** [comment]
![m2_issuse_001 md](https://user-images.githubusercontent.com/53387016/73730942-9b907180-4772-11ea-8663-d5bdd0e28bfb.png)
