### ISSUE TITLE
[bug]: Inconsistent handling of DEV_SERVER_SERVICE_WORKER_ENABLED

### ISSUE THREAD

**Issue by alexander-kaftan-techdivision** [magento/pwa-studio#2136]
In the documentation DEV_SERVER_SERVICE_WORKER_ENABLED is documented to be checked against 1.
But in packages/venia-ui/lib/util/swUtils.js the check is:
process.env.DEV_SERVER_SERVICE_WORKER_ENABLED === 'true';

Additionally I saw another check (in a index.js, but I don't find the code):
... if(... && process.env.DEV_SERVER_SERVICE_WORKER_ENABLED)

which is entirely wrong, because process.env.DEV_SERVER_SERVICE_WORKER_ENABLED is a string which evaluates always to true.

Recommendation, replace the checks by:
process.env.DEV_SERVER_SERVICE_WORKER_ENABLED == '1'

note the double =. This evaluates to true if process.env.DEV_SERVER_SERVICE_WORKER_ENABLED is 1, true or '1'

**Comment by awilcoxa** [comment]
Needs further review by @zetlen @revanth0212

**Comment by mrtuvn** [comment]
@sharkySharks

**Comment by awilcoxa** [comment]
closing this issue as resolved by #2148
