### ISSUE TITLE
[feature]: CMS pages should display Content Heading and update page title in <head> to reflect the page that a user is on

### ISSUE THREAD

**Issue by luke-denton-aligent** [magento/pwa-studio#2158]
**Is your feature request related to a problem? Please describe.**
I've created a new page using Page Builder, and loaded it through PWA Studio. I notice that Content Heading that I've set in the admin isn't displayed anywhere in the app. In Luma, this is displayed, so I would assume we'd want to retain that feature? Similarly, the title displayed in the browser tab remains as "Home Page - Venia", which is incorrect. Please see image below, the page being displayed is "About Us", but there is no way of knowing that.

![image](https://user-images.githubusercontent.com/18253422/74210472-d0a14480-4cdb-11ea-8e60-28090239c7c4.png)

**Describe the solution you'd like**
I'd like to see the title displayed in the tab update to match the title of the CMS page that I'm viewing, and to have the Content Heading displayed as a title on the page, so it's consistent with the data that is displayed on a Luma CMS page. Please see the simple update I've made below, that will update the document title to be `cmsPage.title`, and add the `cmsPage.content_heading` to the output, using a `h1`

![image](https://user-images.githubusercontent.com/18253422/74210459-c2ebbf00-4cdb-11ea-93c3-8027764b86c7.png)

**Describe alternatives you've considered**
Not updating the title nor displaying the content heading - I can possibly understand not displaying the content heading, but in that case we should update the admin to remove that input field, as I believe it then serves no purpose. The tab title should definitely be updated

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`

**Comment by awilcoxa** [comment]
Created in Jira backlog (PWA-383). During grooming team discussed that this needs additional research spike and currently marked as Priority 3.
