### ISSUE TITLE
[bug]: imageCacheHandler is not working on Firefox

### ISSUE THREAD

**Issue by larsroettig** [magento/pwa-studio#2161]
**Describe the bug**
The Image Cache will not be prepared on Firefox main problem  [effectiveType ](https://developer.mozilla.org/en-US/docs/Web/API/NetworkInformation/effectiveType)
is not supported there. 

Check for this Flag:
https://github.com/magento/pwa-studio/blob/dbda97e0e48147adfdbb2e20c2b4988d53fd4917/packages/venia-concept/src/ServiceWorker/Utilities/imageCacheHandler.js#L111

Implementation:
https://github.com/magento/pwa-studio/blob/develop/packages/venia-concept/src/ServiceWorker/Utilities/networkUtils.js

**To reproduce**
1.  Open Firefox Dev Console 
2.  Enter the following Code  
``` js
export const isFastNetwork = () =>
    navigator.connection && navigator.connection.effectiveType === '4g';
if(isFastNetwork())
{
    console.log('Fast Network detected')
}
else {
    console.log('Slow Network detected. Not pre-fetching images')
}
```  

**Expected behavior**
imageCacheHandler  should be working with Firefox and any device 

**Screenshots**

**Additional context**

**Possible solutions**
```  
const NetworkSpeed = require('network-speed');
const testNetworkSpeed = new NetworkSpeed();
 
getNetworkDownloadSpeed();
 
async function getNetworkDownloadSpeed() {
  const baseUrl = 'http://eu.httpbin.org/stream-bytes/50000000';
  const fileSizeInBytes = 50000000;
  const speed = await testNetworkSpeed.checkDownloadSpeed(baseUrl, fileSizeInBytes);
  console.log(speed);
}
```

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by revanth0212** [comment]
Nice catch @larsroettig 

I will look into that soon.

**Comment by awilcoxa** [comment]
Created in core backlog for grooming (PWA-370)
