### ISSUE TITLE
[bug]: Protocol "http:" not supported. Expected "https:"

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#2170]
**Describe my bug**
I am using pwa-studio version 5.0. I want to develop on my localhost, but when I put my localhost (without https), I received this error. How can I fix this?

**Comment by larsroettig** [comment]
@huykon we don't support HTTP with PWA Studio is better to use the command

**Comment by larsroettig** [comment]
@awilcoxa  can be closed works as expected

**Comment by huykon** [comment]
@larsroettig that mean I can not develop PWA on localhost?

**Comment by mrtuvn** [comment]
default project bring to you https work in local ! Do you get the latest code
When you at step 3 you create ssl cert in that so you will have test https cert in local

**Comment by codynguyen1** [comment]
For the 5.0 version, we can manually change it at:
pwa-studio/packages/pwa-buildpack/lib/Utilities/graphQL.js
by switching:
`const { Agent: HTTPSAgent } = require('https');`
to
`const { Agent: HTTPSAgent } = require('http');`

**Comment by hoangtrankeen** [comment]
@codynguyen1 I already modified this file as you said but with the latest version, it does not work.
How can i develop PWA on local machine ?

**Comment by codynguyen1** [comment]
@hoangtrankeen  a little tricky there, you'd need to run:
`yarn run build`
and then change the file at pwa-studio/packages/pwa-buildpack/lib/Utilities/graphQL.js
and then avoid running yarn run build again, just run watch and stage.
I tried and it works with both venia concept and our project packages

**Comment by awilcoxa** [comment]
Closing since it appears everything is working as intended and this is project specific. @hoangtrankeen @huykon if you need additional follow up also feel free to post in the community slack.

**Comment by ngocvon** [comment]
> @huykon we don't support HTTP with PWA Studio is better to use the command:
> https://magento.github.io/pwa-studio/venia-pwa-concept/setup/#step-3-generate-ssl-certificate
> 
> _**PS**_ If you are using Windows use the docker container
I use ubuntu dont work. Pls for me why 
![image](https://user-images.githubusercontent.com/5688818/105967804-dcd30d00-60b8-11eb-8c25-59ea5bb141bd.png)
