### ISSUE TITLE
[bug]: Using the Products content type in PageBuilder will break GraphQL queries for that page

### ISSUE THREAD

**Issue by luke-denton-aligent** [magento/pwa-studio#2186]
**Describe the bug**
I am attempting to create a home page for my PWA using PageBuilder. I've added a Products content type to the bottom of the page. In order to test what renders in the PWA, I've added a simple condition of price being greater than 2, and limiting the block to displaying only 5 items.

When attempting to load the home page through the PWA app, the page content simply shows `Page Fetch Error`.

Running the GraphQL query in the playground to load a CMS page, the response is actually
```
{
  "error": "Unexpected token < in JSON at position 8"
}
```
Removing just the Products block from the page, and re-running the query gets the HTML as we would expect.

**To reproduce**
1. Open admin and log in
2. Navigate to Content > Pages > Home Page
3. Edit the content, adding a new Column and then Products page type
4. Add the following condition to Products block (leaving all other values as defaults)
`Price greater than 2`
5. Open GraphQL playground
6. Run the query
```
{
  cmsPage(id: 2) {
    url_key
    content
    content_heading
    title
    page_layout
    meta_description
    __typename
  }
}
```
(assuming ID of 2 is the home page in your test environment also)

**Expected behavior**
The HTML for the entire page should be returned, including the products, and any other content types 

**Screenshots**
![image](https://user-images.githubusercontent.com/18253422/75001363-18308900-54b1-11ea-911e-49e1a5ac2cf1.png)

Response of GraphQL query in the Network tab when reloading the PWA in browser
![image](https://user-images.githubusercontent.com/18253422/75001430-37c7b180-54b1-11ea-98b9-0e908f555300.png)

![image](https://user-images.githubusercontent.com/18253422/75001446-40b88300-54b1-11ea-98ed-28ba18c7ab5c.png)

**Additional context**
I am using the Luma sample data in my database

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: All
 - OS [e.g. iOS8.1, Windows 10]: All
 - Browser [e.g. Chrome, Safari]: All
 - Browser Version [e.g. 22]: All
 - Magento Version: 2.3.3
 - PWA Studio Version: 5

**Please let us know what packages this bug is in regards to:**
- [x] `venia-ui` (I think the error will be coming from here, but could be from peregrine)
- [ ] `peregrine`

**Comment by davemacaulay** [comment]
Thanks for the bug report, this seems unrelated to our previous fix for Products using GraphQL: https://github.com/magento/magento2/blob/5f3b86ab4bd3e3b94e65429fed33f748d29c1bbe/app/code/Magento/CatalogGraphQl/etc/graphql/di.xml#L141

Are you able to provide us more details on what the "Internal server error" is that's being produced by the query? Looking into Magento's var/log and var/report folders should give you the full error.

**Comment by luke-denton-aligent** [comment]
Hi @davemacaulay, thanks for checking this out. I'm using a Magento Cloud instance to provide the data, so I'm not entirely sure how to check the `var` directory. Am I able to get to the logs through the admin?

**Comment by luke-denton-aligent** [comment]
Hi @davemacaulay, are you able to provide any more assistance with this?

Thanks

**Comment by davemacaulay** [comment]
Hey @luke-denton-aligent you'll be able to SSH into the Magento Cloud instance and view the contents of the `var` folder. You can retrieve the SSH host from the Magento Cloud UI.

**Comment by luke-denton-aligent** [comment]
Thanks @davemacaulay. Unfortunately it appears that the "Internal Server Error" message isn't _actually_ an internal server, it's instead a string that the GraphQL resolvers will output when there is an error. For that reason, nothing is appearing in the logs.
I've asked one of the BE devs if they can try and debug this, but I think it would be better if someone from Magento's side can step through and replicate the bug, then try to identify the reason

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
We have not seen a demand for this. Closing this issue
