### ISSUE TITLE
[feature]: change Dockerfile.env to env.Dockerfile

### ISSUE THREAD

**Issue by alonronin** [magento/pwa-studio#2198]
*Is your feature request related to a problem? Please describe.**
Using `Dockerfile.dev` or `Dockerfile.prod` you'll lose syntax highlighting as `Dockerfile` should be the extention.

**Describe the solution you'd like**
Changing to `dev.Dockerfile` and `prod.Dockerfile` etc. will be much more convenient.

**Comment by awilcoxa** [comment]
Created in Jira backlog for grooming/prioritization PWA-434
