### ISSUE TITLE
[bug]: GraphQL query to get categories returns categories that are "disabled" in admin

### ISSUE THREAD

**Issue by luke-denton-aligent** [magento/pwa-studio#2203]
**Describe the bug**

I have been trying to request all categories, categories' children, and categories' children's children (etc.) for my progressive web app, but the application is crashing when it tries to read `children_count` of the category in `useCategoryTree` (a talon in peregrine).

The issue appears to be that disabled categories that have children that _aren't_ disabled, are still returned from the query.

**To reproduce**
1. Go to Categories in the Admin
2. Disable one of the categories
3. Ensure that disabled category has a child category that isn't disabled
4. Run the GraphQL query to get all categories, including children and children of children, with `"id": 1`:
```
query navigationMenu($id: Int!) {
    category(id: $id) {
        id
        name
        children {
            children_count
            id
            include_in_menu
            name
            children {
                name
                id
                include_in_menu
              	children_count
                children {
                    name
                    id
                    include_in_menu
                    children_count
                }
            }
        }
    }
}
```
5. See that the returned data includes an entry with data similar to the following
```
{
  "name": null,
  "id": 29,
  "include_in_menu": null,
  "children_count": null,
  "children": [ ... ]
```

**Expected behavior**
(I think) The returned data should only return the top level categories that are enabled in admin, regardless of whether their children are also enabled.
If the intention _is_ to load top level categories when their children are active, then the data returned shouldn't be `null` for that top level category

**Screenshots**
The category structure in my admin (it's the Luma sample data)
![image](https://user-images.githubusercontent.com/18253422/75635469-31ca9100-5c66-11ea-9a0c-59a31e69cde1.png)

GraphQL query and response in Graphiql
![image](https://user-images.githubusercontent.com/18253422/75635475-460e8e00-5c66-11ea-96fd-fee7a53689ad.png)

*Behaviour when the same category is then enabled*

Admin category structure
![image](https://user-images.githubusercontent.com/18253422/75636038-24fc6c00-5c6b-11ea-8fae-f92a179a89e2.png)

GraphQL query and response in Graphiql
![image](https://user-images.githubusercontent.com/18253422/75636108-e3b88c00-5c6b-11ea-9672-c831cde50343.png)

**Possible solutions**
The `category` GraphQL query could be updated to allow us to specify an `include_in_menu` value in the query parameters

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: All
 - OS [e.g. iOS8.1, Windows 10]: All
 - Browser [e.g. Chrome, Safari]: All
 - Browser Version [e.g. 22]: All
 - Magento Version: 2.3.3
 - PWA Studio Version: 5.0.0

**Please let us know what packages this bug is in regards to:**
- [x] `peregrine`

**Comment by fooman** [comment]
Hey @luke-denton-aligent I believe you might get a quicker path to resolution posting GraphQl issues directly on the main Magento 2 repository [here](https://github.com/magento/magento2/issues) as I believe the PWA Studio team is not directly involved with that aspect (unless a fix involves adjusting the query before sending it which I believe is always less preferable than fixing the server response).

**Comment by luke-denton-aligent** [comment]
Thanks for the response @fooman, I completely agree. I shall create the issue over there and close this one
