### ISSUE TITLE
[feature]: Display category description (with PageBuilder support as well) on the category view

### ISSUE THREAD

**Issue by vasilii-b** [magento/pwa-studio#2209]
**Is your feature request related to a problem? Please describe.**
The category description is not shown to the users on the category view page.

**Describe the solution you'd like**
As a store owner, I'd like to show the description of the current category the customers are viewing.
It would be also nice so it supports the PageBuilder adjustments to the category description.

**Describe alternatives you've considered**
N/A

**Additional context**
The category description is not even provided by the talon `useCategoryContent`, so the developers can use the date.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by vasilii-b** [comment]
I have PR in progress for this, so please let me know whenever should there be any notes or something else I should consider.
Thank you!

**Comment by tjwiebell** [comment]
Looping in @soumya-ashok, as this has a UX element to it that would need approved. Do we have mocks that intend on supporting Category descriptions? These have typically been block level rich content areas that display above the product grid, so it would be a noticeable change.

**Comment by soumya-ashok** [comment]
@tjwiebell - Not entirely sure what "category description" is? Is it just text under the main header on the category landing page?

**Comment by tjwiebell** [comment]
It's a WYSIWYG-enabled content area, so it can be just text, or any html content. I've seen most sample data rely on Category Image, which is typically the image banner you see before products and would need a similar treatment, but this PR seems isolated to just Description content. I've added one on this instance so you can see it in Luma.

https://venia-cicd-lrov2hi-mfwmkrjfqvbjk.us-4.magentosite.cloud/venia-accessories/venia-belts.html
https://docs.magento.com/m2/ee/user_guide/catalog/categories-content-settings.html

**Comment by soumya-ashok** [comment]
@vasilii-b - Apologies for the long response time on this issue.

Please see attached screenshots for recommended placement of category text. As long as your work matches the placement, this is UX approved.

![Screen Shot 2020-04-30 at 10 15 56 AM](https://user-images.githubusercontent.com/25960021/81106964-066d5800-8edc-11ea-835f-6752fb4a37fd.png)
![Screen Shot 2020-04-30 at 11 05 48 AM](https://user-images.githubusercontent.com/25960021/81106974-0c633900-8edc-11ea-8bd9-6e7b52aef1e9.png)
