### ISSUE TITLE
[feature]: PDP - update price when quantity changes

### ISSUE THREAD

**Issue by vasilii-b** [magento/pwa-studio#2210]
# Description
It would be nice that the product price is updated once the quantity is changed on the PDP.

1. Go to a product page
2. See the product price
3. Scroll down to the "quantity" input
4. Change the quantity. E.g. 2
5. See the product price changes

**Describe the solution you'd like**
When the product quantity changes, the product price should adjust accordingly, so the customer knows right away how much it will cost, without seeing the total amount in the sliding cart.

![2020-03-04 13 09 30](https://user-images.githubusercontent.com/13456702/75876105-b4498100-5e1d-11ea-8fb1-ff3f12e262e2.gif)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Removed bug label as this is currently working as designed, this issue represents a feature request. 

Currently price on the PDP is designed to remain static and specific to a single unit. Price updates (based on quantity) are specific to cart/checkout interactions. 

Adding needs-ux label for design review of feature request.

**Comment by vasilii-b** [comment]
Thank you @awilcoxa!

**Comment by soumya-ashok** [comment]
@vasilii-b - Thanks for working on this.

Based on the many sites we have looked at, the standard and expected pattern is for the PDP to show unit price and for the cart to show price based on quantity.

The only time I have seen the unit price change on a PDP with retail sites is if one of the variants of a configurable product is on sale or has a promo associated, or if a larger size for example, costs more for a single unit.

The expectation for Venia is to follow standard patterns of interaction and best practices that serve a majority of use cases so for now, we will not be making a change to how the price displays on the PDP.

If you have specific examples of where you've seen this implemented on sites please do send them along so we can understand where and why this pattern is being used.
