### ISSUE TITLE
[bug]: The breadcrumbs have the bug if the product assigned only "default" category or isn't assigned anything category.

### ISSUE THREAD

**Issue by andrewbess** [magento/pwa-studio#2223]
**Describe the bug**
There is a problem in the talon "useProductFullDetail".
If a product isn't assigned anything category or assigned only "default" category, the system is showing the error and doesn't render frontend when a client tries to view the product by link.
Please take a look at the screenshots.

**To reproduce**
1. Unassign the categories from the product using the admin panel;
2. Copy the product link using URL-Key;
3. Try to view the product by link;
4. See error below;
5. Also, you can check this error in the console

**Expected behavior**
PDP must be rendered without error.

**Screenshots**
The error on the storefront 
<img width="1640" alt="error-on-front" src="https://user-images.githubusercontent.com/10788564/76080033-b3942480-5fae-11ea-9ac4-d1e7d571c7e6.png">

The error in the console
<img width="1413" alt="error-on-console" src="https://user-images.githubusercontent.com/10788564/76080025-b0993400-5fae-11ea-8268-47c660621bf7.png">

**Additional context**

**Possible solutions**
I have already fixed it on my project and I am going to create a PR here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: All
 - OS [e.g. iOS8.1, Windows 10]: All
 - Browser [e.g. Chrome, Safari]: All
 - Browser Version [e.g. 22]:
 - Magento Version: 2.3.4
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by andrewbess** [comment]
Hello.
I am going to fix it because I have already fixed this problem on my project.
Please assign it to me.
Thank you in advance.

**Comment by awilcoxa** [comment]
Created in Jira backlog for grooming/prioritization: PWA-430
