### ISSUE TITLE
[doc]: SH code not working with ctrl+c/ctrl+v

### ISSUE THREAD

**Issue by LucasCalazans** [magento/pwa-studio#2232]
**Describe the request**
SH code not working with ctrl+c/ctrl+v in the step 4 (Create the .env file)

**Devdocs Page**
https://magento.github.io/pwa-studio/venia-pwa-concept/setup/#step-4-create-the-env-file

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [x] Topic Change Request (ie. spelling, organization)

**Comment by jcalcaben** [comment]
@LucasCalazans Can you provide more details for this issue?

**Comment by LucasCalazans** [comment]
@jcalcaben oh, sorry. Actually I had opened a PR about that.

It is just a small change. This page https://magento.github.io/pwa-studio/venia-pwa-concept/setup/, has a code that we need to ctrl-c + ctrl-v on the terminal and it doesn't work without a slash (**\**).
