### ISSUE TITLE
[bug]: watcher runs out of memory

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#2237]
**Describe the bug**
After developing for some time, the watcher process fails after running out of memory.

This is happening with increasing frequency over the last few weeks as our project gets bigger. It happens maybe every other day now.

**To reproduce**
1. Start a watcher
1. Work for a long time
2. Eventually it'll run out of memory

**Expected behavior**
Infinite memory?

**Additional context**
Error code:

```
 ｢wdm｣: Compiling...
 97% [0] emitting HtmlWebpackPlugin
<--- Last few GCs --->

[36119:0x102806000] 50714109 ms: Mark-sweep 1378.1 (1412.4) -> 1377.7 (1412.4) MB, 427.4 / 0.0 ms  (average mu = 0.101, current mu = 0.018) allocation failure scavenge might not succeed
[36119:0x102806000] 50714557 ms: Mark-sweep 1378.9 (1412.4) -> 1378.4 (1412.4) MB, 421.7 / 0.0 ms  (average mu = 0.079, current mu = 0.058) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x14b676cdbe3d]
    1: StubFrame [pc: 0x14b676cdd3c6]
Security context: 0x0c541131e6e9 <JSObject>
    2: /* anonymous */(aka /* anonymous */) [0xc542ebb9921] [/Users/brendan/work/clients/xxxxxxxxxxx/xxxxxxxxxxx/repo-pwa/node_modules/webpack/lib/Stats.js:~567] [pc=0x14b67c9d00e0](this=0x0c54778826f1 <undefined>,reason=0x0c54e7ca6471 <ModuleReason map = 0xc5441e14d69>)
    3: arguments adaptor frame: 3->1
    4: ma...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003cff5 node::Abort() [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
 2: 0x10003d1ff node::OnFatalError(char const*, char const*) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
 3: 0x1001b8265 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
 4: 0x1005861c2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
 5: 0x100588c95 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
 6: 0x100584b3f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
 7: 0x100582d14 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
 8: 0x10058f5ac v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
 9: 0x10058f62f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
10: 0x10055ef74 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
11: 0x1007e7254 v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/brendan/.nvm/versions/node/v10.16.1/bin/node]
12: 0x14b676cdbe3d
13: 0x14b676cdd3c6
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /Users/brendan/.nvm/versions/node/v10.16.1/bin/node
Arguments: /usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js run watch
Directory: /Users/brendan/work/clients/xxxxxxxx/xxxxxxxxxxxxx/repo-pwa/packages/ce
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

** Internal JIRA**
https://jira.corp.magento.com/browse/PWA-472

**Comment by brendanfalkowski** [comment]
Note: this never happens when starting the watcher, and restarting always gets me back to work. Non-blocking but just seems undesired so reporting.

**Comment by Jordaneisenburger** [comment]
@brendanfalkowski I had the same running at 5.0.1 but i thought I'd probably messed up somewhere. This indeed only happens when you have your watcher running for 6-8+ hours without restarting.

**Comment by sirugh** [comment]
I think the leak is more obvious since the watcher doesn't have to be restarted as often.

**Comment by brendanfalkowski** [comment]
Agreed, super low priority. 6-8 hours (or overnight...) seems about right for the failure interval.

Just thought I'd post in case someone loves this kind of debugging challenges.

**Comment by awilcoxa** [comment]
Created in Jira backlog for grooming/prioritization

**Comment by awilcoxa** [comment]
Marked as P3S3.

**Comment by Jordaneisenburger** [comment]
Crashed again, But this only seems to happen when you as @brendanfalkowski said keep the watcher on overnight so at least 12+ hours.

extra debug info:
<--- Last few GCs --->

[87389:0x10264a000] 24052326 ms: Mark-sweep 1381.9 (1411.9) -> 1381.9 (1412.4) MB, 351.1 / 0.0 ms  (average mu = 0.136, current mu = 0.003) allocation failure GC in old space requested
[87389:0x10264a000] 24052642 ms: Mark-sweep 1382.9 (1412.4) -> 1382.6 (1412.4) MB, 270.3 / 0.0 ms  (average mu = 0.140, current mu = 0.145) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x314d7315be3d]
    1: StubFrame [pc: 0x314d7315a1dc]
Security context: 0x0a2f7d19e6e1 <JSObject>
    2: set [0xa2f7d1937b1](this=0x0a2f62c3e1b1 <JSWeakMap>,0x0a2f46f3b7e9 <Node map = 0xa2f04ec1f49>,0x0a2f5c2b1809 <JSArray[0]>)
    3: __addDeclaredVariablesOfNode [0xa2fd68dbae9] [/Users/jordan/experius/domains/galaxy-m2-frontend/node_modules/eslint-scope/lib/scope.js:387] [bytecode=0xa2fb6c23a39 offset=52](this=0x0a2...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003b1db node::Abort() [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
 2: 0x10003b3e5 node::OnFatalError(char const*, char const*) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
 3: 0x1001a86b5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
 4: 0x100573ad2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
 5: 0x1005765a5 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
 6: 0x10057244f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
 7: 0x100570624 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
 8: 0x10057cebc v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
 9: 0x10057cf3f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
10: 0x10054c2d6 v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
11: 0x1006b8a06 v8::internal::HashTable<v8::internal::ObjectHashTable, v8::internal::ObjectHashTableShape>::EnsureCapacity(v8::internal::Handle<v8::internal::ObjectHashTable>, int, v8::internal::PretenureFlag) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
12: 0x1006b206f v8::internal::ObjectHashTable::Put(v8::internal::Handle<v8::internal::ObjectHashTable>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
13: 0x1006b29b3 v8::internal::JSWeakCollection::Set(v8::internal::Handle<v8::internal::JSWeakCollection>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
14: 0x1007a93bc v8::internal::Runtime_WeakCollectionSet(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/jordan/.nvm/versions/node/v10.15.1/bin/node]
15: 0x314d7315be3d 
16: 0x314d7315a1dc 
17: 0x314d731d8b8f 
18: 0x314d731118d5 
19: 0x314d731118d5 
20: 0x314d731118d5 
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by huykon** [comment]
I have same issue:
`ℹ ｢wdm｣: Compiling...
 41% building 10/19 modules 9 active ...roductListing/CartItem/index.jsWarning: fragment with name CheckoutPageFragment already exists.
graphql-tag enforces all fragment names across your application to be unique; read more about
this in the docs: http://dev.apollodata.com/core/fragments.html#unique-names
 95% emitting CopyPlugin                                               
<--- Last few GCs --->

[34935:0x102807000] 18072117 ms: Mark-sweep 1354.8 (1417.0) -> 1353.4 (1400.1) MB, 354.1 / 0.0 ms  (average mu = 0.680, current mu = 0.000) last resort GC in old space requested
[34935:0x102807000] 18072480 ms: Mark-sweep 1353.4 (1400.1) -> 1353.4 (1400.1) MB, 363.0 / 0.0 ms  (average mu = 0.505, current mu = 0.000) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x15d4051878a1]
Security context: 0x356ef521e6e9 <JSObject>
    1: byteLength(aka byteLength) [0x356e16ff97f9] [buffer.js:~509] [pc=0x15d406957b90](this=0x356ed2b026f1 <undefined>,string=0x356e787b0d99 <Very long string[11876755]>,encoding=0x356ef523e9d9 <String[4]: utf8>)
    2: arguments adaptor frame: 3->2
    3: from [0x356e1cca0429] [buffer.js:~199] [pc=0x15d409b37ddc](this=0x356e16fd32b1 <JSFunction Buffer (sfi...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x10003d051 node::Abort() [/usr/local/bin/node]
 2: 0x10003d25b node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001b90e5 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x100587042 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x100590544 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 6: 0x100562334 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 7: 0x100693ea9 v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 8: 0x1001d6e7d v8::String::Utf8Length() const [/usr/local/bin/node]
 9: 0x1000516ab node::Buffer::(anonymous namespace)::ByteLengthUtf8(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
10: 0x15d4051878a1 
11: 0x15d406957b90 
12: 0x15d40518a5c3 
error Command failed with signal "SIGABRT".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.`

**Comment by Jordaneisenburger** [comment]
Mhh still happens even when watcher has been closed and restarted. PWA Studio v7.0
<img width="1646" alt="Screenshot 2020-10-21 at 11 04 15" src="https://user-images.githubusercontent.com/19858728/96698437-63c36b80-138d-11eb-8db8-08164a8bb6a7.png">

**Comment by ericerway** [comment]
Reviewed for STR and priority. Adding to FAQ in PWADocs. @jcalcaben can you please add?

**Comment by sirugh** [comment]
We will add this to our "known issues/troubleshooting" and provide a workaround (restart your watcher?).
