### ISSUE TITLE
[bug]: Wrong value type in useCategoryTree

### ISSUE THREAD

**Issue by danlupo** [magento/pwa-studio#2241]
**Describe the bug**
In the navigation, a Leaf maybe miss identified as a branch containing children, despite its children_count being 0

**To reproduce**
Create a sub-category under root, that has no children

**Expected behavior**
Should be a rendered as a Leaf

- [x] `peregrine`

See "@magento/peregrine/lib/talons/CategoryTree/useCategoryTree.js" line 52

`const isLeaf = category.children_count === '0'`
0 should be an integer, or category.children_count should be cast as a string

**Comment by awilcoxa** [comment]
Created in Jira backlog
