### ISSUE TITLE
 .env.dist is not present here

### ISSUE THREAD

**Issue by sumeet-synergytop** [magento/pwa-studio#2242]
.env.dist is not present here when get clone then  .env.dist is not in packages/venia-concept

**Comment by tjwiebell** [comment]
`.env` creation is a CLI command in buildpack, we do not distribute a `.env.dist`.

https://magento.github.io/pwa-studio/venia-pwa-concept/setup/#step-4-create-the-env-file

Closing as not a bug, but please let us know if there is outdated documentation somewhere that set this expectation.
