### ISSUE TITLE
[bug]: RadioGroup cannot pass a disabled attribute to the Radio component

### ISSUE THREAD

**Issue by mikhaelbois** [magento/pwa-studio#2270]
**Describe the bug**
When using the RadioGroup component, we cannot specify if its items are disabled or not.

https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/RadioGroup/radioGroup.js#L34
In the RadioGroup component, the items only accepts a label and a value.

**Expected behavior**
We should have a way to render the Radio items as disabled or not.

**Possible solutions**
We could pass additional attributes to the item via an _attributes_ key of the items prop.
```
const options = items.map(({ label, value, attributes }) => (
    <Radio
        classes={{
            label: classes.radioLabel,
            root: classes.radio
        }}
        key={value}
        label={label}
        value={value}
        {...attributes}
    />
));

/* --- */

const items = [
    { label: 'Enabled item', value: 'value_1' },
    {
        label: 'Disabled item',
        value: 'value_2',
        attributes: { disabled: true }
    }
];

/* --- */

<RadioGroup
    field="disabled_example"
    items={items}
/>
```

**Please complete the following device information:**
 - Magento Version: 2.3.4
 - PWA Studio Version: 5.0.1
 - NPM version: `6.11.3`
 - Node Version: `10.17.0`

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Good value add and relatively low LOE, moving to prioritized for pickup by interested community member(s)
