### ISSUE TITLE
[feature]: Provide a way to access top/intermediate level categories through left nav

### ISSUE THREAD

**Issue by hitesh-wagento** [magento/pwa-studio#2276]
**Is your feature request related to a problem? Please describe.**
We can't go on the first level category when clicking on left navigation but we can go when we will click on home page categories

**Describe the solution you'd like**
Left side navigation first-level categories should redirect to a category

I have created Issue in https://github.com/magento/pwa-studio/issues/2274 but @sirugh suggestion please create feature request so I have created a feature request

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Needs UX review to determine impact @soumya-ashok

**Comment by soumya-ashok** [comment]
@awilcoxa I've had a look at the issue. Will discuss with the team and update the issue.

**Comment by soumya-ashok** [comment]
@hitesh-wagento Thank you for raising the concern. This is an issue we are aware of, but there are technical and accessibility issues we would need to address before we can redesign the pattern for the main nav.

For now, the approach that @jimbo and I would like to take is to add an "All" link within each category nav. at the top and make the category landing page accessible that way.

**Mockup**
![Main Menu – 3](https://user-images.githubusercontent.com/25960021/80025233-ea15f800-84a5-11ea-9e48-552614e9d726.png)

**Comment by hitesh-wagento** [comment]
> @hitesh-wagento Thank you for raising the concern. This is an issue we are aware of, but there are technical and accessibility issues we would need to address before we can redesign the pattern for the main nav.
> 
> For now, the approach that @jimbo and I would like to take is to add an "All" link within each category nav. at the top and make the category landing page accessible that way.
> 
> **Mockup**
> ![Main Menu – 3](https://user-images.githubusercontent.com/25960021/80025233-ea15f800-84a5-11ea-9e48-552614e9d726.png)

Hi @soumya-ashok

For my understanding currently, when we will click on Bottoms we will add **All Bottoms** text with **venia-bottoms.html** links, Right ?

![image](https://user-images.githubusercontent.com/23443991/80056107-0c108880-8541-11ea-8797-ed531e5e0892.png)

**Comment by soumya-ashok** [comment]
@hitesh-wagento Yes, on the top level of the main menu, if a user clicks "Bottoms", this would show them a list of sub categories along with a link for "All Bottoms" like you have which would lead to venia-bottoms.html

**Comment by Frodigo** [comment]
Hi guys! 

I want to help you with this feature. Could somebody assign this issue to me?

**Comment by huykon** [comment]
@magento I am working on this
