### ISSUE TITLE
[feature]: Always scroll to top on a router change

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#2289]
**Is your feature request related to a problem? Please describe.**
When a long page links to a short page, the former scroll-y position doesn't exist, so the browser keeps the lowest scroll position possible. This means links from anywhere to anywhere can often land on the footer of a new page render.

**Describe the solution you'd like**
When routing (link or redirect) the page should always scroll to top so the user's context is reset.

**Describe alternatives you've considered**

**Additional context**
A fix was added for this in #832 but it only affects PDP. We have dozens of modules in our build it affects all of them, so the solution should be implemented at the router-level.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by brendanfalkowski** [comment]
I have code for this improvement (basically React router's recommended solution) and would like to PR if approved.

**Comment by Jordaneisenburger** [comment]
Yeah we've used the recommended solution as well and works great. see https://reacttraining.com/react-router/web/guides/scroll-restoration

**Comment by awilcoxa** [comment]
moving to prioritized for community contribution, @brendanfalkowski feel free  to open the PR and we'll get the team on review

**Comment by awilcoxa** [comment]
Jira story created and prioritized
