### ISSUE TITLE
[bug]: checkbox doesn't work with isRequired rule

### ISSUE THREAD

**Issue by mercs600** [magento/pwa-studio#2302]
**Describe the bug**
rule isRequired from `venia-ui/lib/util/formValidators.js` doesn't work with something else than string. 

**To reproduce**
1. Use checkbox in your templates with isRequired validate rule
```js
<Checkbox field="agreement" label="check this" validate={isRequired} validateOnChange/>
```

**Expected behavior**
Validate rule isRequired works with checkbox also.

**Additional context**
TypeError: (value || "").trim is not a function

**Possible solutions**
We should check types at least - not every field is string. 

**Please complete the following device information:**
Device Mac
OS Catalina 10.15.2
Browser Chrome
Browser Version 79.0.3945.130
Magento Version:
PWA Studio Version: develop
NPM version 6.13.4
Node Version v10.18.0

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by brendanfalkowski** [comment]
We implemented a similar change to catch number and boolean in that validator:

```
export const isRequired = value => {
    // When a <Select> is required, the normal validator fails on a number value.
    if (typeof value === 'number') {
        return SUCCESS;
    }

    // When a <Checkbox> is required, the normal validator fails on a boolean value.
    if (typeof value === 'boolean') {
        return (value) ? SUCCESS : 'The field is required.';
    }

    return (value || '').trim() ? SUCCESS : 'The field is required.';
};
```

**Comment by mercs600** [comment]
thanks @brendanfalkowski I pushed PR #2303 ;-)

**Comment by awilcoxa** [comment]
created in Jira backlog for prioritization/review

**Comment by awilcoxa** [comment]
@jimbo
