### ISSUE TITLE
[feature]: Add custom environment variables

### ISSUE THREAD

**Issue by LucasCalazans** [magento/pwa-studio#2304]
**Is your feature request related to a problem? Please describe.**
We would be able to add new env variables using the scaffolding project. Now when we add new env variables it is not loaded because this variable is not present in the envVarDefinitions.json

**Describe the solution you'd like**
I would like to add any variables possible to my PWA Studio project and have access to it.
Another feature is the create-env-file, I would like to use this command to generate a .env file with my new variables. Today this command ignores all variables that are not included in the definitions JSON.

**Describe alternatives you've considered**
1. A way to increment the envVarDefinitions.json in the project
2. Be free to add any variables in the .env file

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Created in Jira backlog for grooming/prioritization

**Comment by tjwiebell** [comment]
@LucasCalazans - This PR made `envVarDefinitions` targetable, and this functionality should now be possible. Take a peek at the `intercept.js` file in the `pagebuilder` package for a good example.

https://github.com/magento/pwa-studio/pull/2174

I think this would cover everything you've outlined, but please confirm, and then I'll close this request.

**Comment by zetlen** [comment]
@LucasCalazans Tommy is right; the `envVarDefinitions` target lets you define new required environment variables from a module, without manually importing them into your project configuration. Let me know if I can help you integrate this feature; the docs are still in process.
