### ISSUE TITLE
[bug]: Checkbox.css has an error in a variable usage

### ISSUE THREAD

**Issue by LucasCalazans** [magento/pwa-studio#2306]
**Describe the bug**
It has a small bug on the usage of a variable in the checkbox.css

**To reproduce**
1. Go to `packages/venia-ui/lib/components/Checkbox/checkbox.css`, line 23

This code has a syntax error `z-index: var(--base-z-index + 1, 1);`

**Expected behavior**
Just use the --base-z-index variable with a default value like `z-index: var(--base-z-index, 1);`

**Possible solutions**
`z-index: var(--base-z-index, 1);`

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
created in Jira backlog for prioritization/review
