### ISSUE TITLE
Disable address validation for PayPal Express Checkout

### ISSUE THREAD

**Issue by linhtv97** [magento/pwa-studio#2311]
I'm working with pwa and magento back end 2.3.4
When I pay by Paypal Express Checkout method using graphql api, If the user enters an incorrect address, paypal will not accept payment error.
Is there any way to turn this off in magento 2.3.4?
![Screenshot from 2020-04-04 20-09-00](https://user-images.githubusercontent.com/48935244/78451634-e5cd9a80-76b0-11ea-88d8-c8b0489d2eca.png)

**Comment by jcalcaben** [comment]
hi @linhtv97 ! we don't normally address implementation question in the issues forum, but you can post this question in our [community slack channel](https://magentocommeng.slack.com/archives/C71HNKYS2) and the community may be able to help.
