### ISSUE TITLE
[bug]: create-pwa can't handle a space in the folder hierarchy

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2317]
**Describe the bug**
If create-pwa is executed in a folder with a space it fails.

**To reproduce**

1. git clone git@github.com:magento/pwa-studio.git 'folder with space'
2. cd folder\ with\ space
3. git checkout release/6.0
4. yarn install
5. DEBUG_PROJECT_CREATION=1 packages/create-pwa/bin/create-pwa

```
Creating a PWA Studio project
? Project root directory (will be created if it does not exist) test-folder
? Short name of the project to put in the package.json "name" field test-folder
? Name of the author to put in the package.json "author" field Kristof Ringleff, Fooman <me@example.com>
? Magento instance to use as a backend (will be added to `.env` file) 2.3.3-venia-cloud
? Braintree API token to use to communicate with your Braintree instance (will be added to `.env` file) sandbox_8yrzsvtm_s2bg8fs563crhqzk
? NPM package management client to use npm
? Install package dependencies with npm after creating project Yes

Running command:

buildpack create-project test-folder --template "venia-concept" --name "test-folder" --author "Kristof Ringleff, Fooman <me@example.com>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "npm"


/bin/sh: /Users/kristof/Downloads/folder: No such file or directory
(node:35929) UnhandledPromiseRejectionWarning: Error: Command failed: /bin/sh -c /Users/kristof/Downloads/folder with space/packages/pwa-buildpack/bin/buildpack create-project test-folder --template "venia-concept" --name "test-folder" --author "Kristof Ringleff, Fooman <kristof@fooman.co.nz>" --backend-url "https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/" --braintree-token "sandbox_8yrzsvtm_s2bg8fs563crhqzk" --npm-client "npm"
    at makeError (/Users/kristof/Downloads/folder with space/node_modules/execa/index.
```

**Expected behavior**
Command succeeds

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version: 2.3.3
 - PWA Studio Version: 6.0.0-beta.2
 - NPM version `npm -v`: 6.13.4
 - Node Version `node -v`: v10.18.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

**Comment by awilcoxa** [comment]
created in Jira backlog for grooming/prioritization

**Comment by awilcoxa** [comment]
@zetlen

**Comment by zetlen** [comment]
Hey @fooman! At first I read this wrong and thought it was an issue with your shell usage, but now I see that it's `create-pwa` using the shell wrong. I'm on it.

**Comment by sirugh** [comment]
@zetlen It's been a bit - do you know if this was resolved?

**Comment by sirugh** [comment]
Couldn't find the original JIRA issue. Using the sync tool to get this on the board.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
