### ISSUE TITLE
Cannot use middleware other than express js.

### ISSUE THREAD

**Issue by dani97** [magento/pwa-studio#2325]
This is hard dependecy to express js framework. UPWARD can be  made to be used as middleware with servers other than express.

https://github.com/magento/pwa-studio/blob/c952de12fb5294223b41d380b47d0d8d62732ffa/packages/upward-js/lib/resolvers/DirectoryResolver.js#L3

**Comment by dani97** [comment]
creating middleware on express js and connect js both failed.

**Comment by awilcoxa** [comment]
Created in Jira backlog

**Comment by awilcoxa** [comment]
Marked as P2S2 @zetlen to follow up

**Comment by zetlen** [comment]
@dani97 We're only using the Express static server there, which should work with anything that follows the middleware pattern.

If it feels bad to be toting the `express` dependency when we're not using Express, we could try replacing it with https://www.npmjs.com/package/serve-static and doing a regression test. But I don't know if that will fix your problem.

Can you please post a little bit more detail about how it fails?

**Comment by dani97** [comment]
@zetlen Thanks for looking into this. I remember I just setup simple connect js server and installed upward and tried a minimal upward.yml config. Then it failed starting that it requires Express static, I didn't try installing express server or anything. I just felt that if this middleware is generic it shouldn't have express as dependency

**Comment by zetlen** [comment]
It's a fair point! We could reimplement the DirectoryResolver with a different static file server, or with the [send](https://www.npmjs.com/package/send) library directly, which is what express-static uses under the hood. 

However, it's not a high priority for us, and it sounds like you could fix the issue by installing Express as a dependency. It's only in use as a library here; installing it does not force you to use it over another server.

I still think it would be a good change; it's important to keep dependencies light. I would welcome a pull request which replaced express-static with `send` or something similar here.
