### ISSUE TITLE
Talons should only get every information as prop from venia

### ISSUE THREAD

**Issue by dani97** [magento/pwa-studio#2326]
Talon  should not import venia module, this makes talons dependent on venia-ui library, which is only a reference theme.
Every information to talon hook should be passed only as prop.

https://github.com/magento/pwa-studio/blob/c952de12fb5294223b41d380b47d0d8d62732ffa/packages/peregrine/lib/talons/ProductImageCarousel/useProductImageCarousel.js#L10

**Comment by sirugh** [comment]
This specific instance is resolved. If there are more, please open further issues!
