### ISSUE TITLE
[feature]: Add Sort Status lable also to Category Page 

### ISSUE THREAD

**Issue by larsroettig** [magento/pwa-studio#2331]
**Describe the solution you'd like**
PR #2294 was also a status text for sort added. We need to move this logic in a `useSort` Hook. Also, include them on the packages/venia-ui/lib/RootComponents/Category/categoryContent.js

A Good example of a hook you can find here: packages/peregrine/lib/hooks/usePagination.js

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
pulling onto community board for review
