### ISSUE TITLE
[bug]: Serviceworker is not strict enough in checking 'catalog' cache resources

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#2332]
**Describe the bug**
When the serviceworker is enabled it caches all the images on the catalog page into a cache layer named 'catalog'. It stores the full path to the image, for example: 
`'/media/catalog/product/cache/691e61e8e08ed9d562b3a62dd421fb27/5/x/5xb40.png?auto=webp&format=png&width=250&height=346'`

When switching to another category it loads new products and their images but since we use the `CacheFirst` strategy for the `createCatalogCacheHandler` it first checks the SW cache to see if there is already a image in the cache for that product. This all works great! But..

What if we have 2 images that are only slightly different in naming?

So let's say we have the following file path in the SW cache: 
`'/media/catalog/product/cache/691e61e8e08ed9d562b3a62dd421fb27/5/x/5xb40.png?auto=webp&format=png&width=250&height=346'`

If we than switch to another category that loads a product that requests the following image file name: `xb40.png?auto=webp&format=png&width=250&height=346`

It actually doesn't show the correct image which should be **xb40.png**  but the image that's already in SW cache which is **5xb40.png**

**Why does this happen?**
The reason this happens is because here:
https://github.com/magento/pwa-studio/blob/6f39c7af07219369783f700aa9cd3feba2c0dc25/packages/venia-concept/src/ServiceWorker/Utilities/imageCacheHandler.js#L37-L39

We filter an array and check if there is an URL in cache that includes the `requestedFilename` and in this case that would be `true` because:
`'/media/catalog/product/cache/691e61e8e08ed9d562b3a62dd421fb27/5/x/5xb40.png?auto=webp&format=png&width=250&height=346'` 
includes `xb40.png?auto=webp&format=png&width=250&height=346` and so it would return the wrong url since it has a match even when the actual url might be lower in the cache array.

**To reproduce**
check above section

**Expected behavior**
When we request a image we like to get back the correct image.

**Possible solutions**
So for out project I did a quick fix that seems to work below are the lines changed so now we basically strictly check for the file name 
```
    const requestedFilename = url.pathname
        .split('/')
        .reverse()[0]
        .split('.')[0];

    const cachedSources = await cachedURLs.filter(({ url }) => {
        const substring = url.substr(url.lastIndexOf('/') + 1);
        const fileName = substring.split('.')[0];
        return fileName === requestedFilename;
    });

```

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
created in Jira backlog

**Comment by awilcoxa** [comment]
Marked as P1S2
