### ISSUE TITLE
[feature]: Image component should have an optional 'ratio' prop

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#2333]
**Is your feature request related to a problem? Please describe.**
As a developer I'd love to re-use the `<Image/>` component for all custom components that render images. Unfortunately that's not ideal since images produced by the `<Image/>` component are always in a 4:5 ratio meaning that a banner image that needs to be 16:9 won't work properly.

**Describe the solution you'd like**
I'd like to see a solution where the implementation decides what ratio the image needs to be instead of the internal image logic forcing it to use a set ratio. Something like this would be sufficient:
`<Image ratio={4/3} />`

**Additional context**
This would tackle 2 problem:
1: Not having to overwrite the `images.js` util if you want to change the ratio on catalog images.
2: Being able to create all sorts of ratios for different scenarios 

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Created in Jira backlog for grooming
