### ISSUE TITLE
Support to change backend_url while webapp working

### ISSUE THREAD

**Issue by technicalopt** [magento/pwa-studio#2347]
Hi 

Thank for your useful tools :) 
I have a question:
Can we get BACK_END_URL from localStorage instead of ENV ? I want to use one webapp for specify backend store each time login.

**Comment by larsroettig** [comment]
@Jordaneisenburger what do think over this issue we definitely need more details.
I don't know if it makes sense maybe as plugin

**Comment by Jordaneisenburger** [comment]
Seems to me this is something very specific for that particular project and won't add any benefits to others using Studio. So therefore I would suggest closing this issue to prevent cluttering the backlog
