### ISSUE TITLE
[bug]: Variables in `.env` are not readable by components

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#2350]
**Describe the bug**
We want to use the `.env` file in our package to hold simple key:value pairs. Examples:

- API key for service XYZ
- feature flag if something is enabled or disabled

Typically this would be stored in Magento admin config, but...

1. We don't want to slow down the user querying for this, so it made sense (to us) to store it as environment variables.
1. We don't want to write a backend module, just for simple config that only developers will adjust.

We are finding that environment variables sometimes can/cannot be read from components, and it's not clear why that is.

**To reproduce**
1. Edit `packages/{yourPackage}/.env`
2. Add something like `SOME_API_KEY=abc123`
3. Try to read that from a component like `process.env.SOME_API_KEY`

The value is `undefined`.

`console.log(process.env)` is also an empty object.

**Expected behavior**
We can add values to the environment file and use them in our components.

**Actual Behavior**
Creating the env vars:

![Screen Shot 2020-04-21 at 3 37 53 PM](https://user-images.githubusercontent.com/214924/79920953-1b2ef380-83e6-11ea-8c32-6656dd9873b4.png)

Logging the env vars from a component (output in comments):

![Screen Shot 2020-04-21 at 3 38 00 PM](https://user-images.githubusercontent.com/214924/79920956-1cf8b700-83e6-11ea-88f1-06a50c4ad4e3.png)

**Additional context**
There are some weird edge cases here.

I created one env var in this way, and it works (still does) but I cannot change its value now. All env vars created after this are always undefined.

It feels like the values are cached somewhere low in the build tools.

Restarting the watcher, and stopping, rebuilding, restarting the watcher do not have an effect.

If I introduce a blatant error in the `.env` syntax the watcher will fail, so it is read at least.

**Please complete the following device information:**

 - Magento Version: 2.3.4
 - PWA Studio Version: 2019-12-02 from develop
 - NPM version `npm -v`: 6.9.0
 - Node Version `node -v`: 10.16.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by brendanfalkowski** [comment]
Well, figured out the edge cases with some help from Slack.

Turns out the reason that `ENABLE_AHRI` worked is not that it was written first or cached somewhere in build, but my teammate implemented this a while back and actually figured it out.

Editing `packages/pwa-buildpack/envVarDefinitions.json` works to prevent that env var being stripped out. That allows access from a component like `console.log(process.env.ENABLE_AHRI)` but this file's purpose actually appears to be for generating a blank `.env` file.

Considering this involves editing a core file, it's probably not better developer UX than just having a constants file in our root that components can import at will. That's simpler than jumping through the build's hoops, but we lose the environment-specific config.

On the fence a bit here.
- Short-term we'll probably be moving some not-environment-specific values into a plain `/packages/{us}/websiteConfig.js` file.
- Long-term it sounds like PWA Studio v6 has some interception capability for adding environment config. We're not ready for another upstream merge so need to revisit later.

**Comment by awilcoxa** [comment]
created in Jira backlog for grooming

**Comment by zetlen** [comment]
Hey @brendanfalkowski. You are exactly right that we don't expose all environment variables in the Node build process for use in the built frontend bundle. This is not obvious behavior and it needs documenting. Let me try to describe it briefly first.

>Buildpack uses the Webpack [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/) to let you use _known_ environment variables in frontend code. You can only use environment variables that have been explicitly defined by interceptors on the `envVarDefinitions` target (including the many built-in variables defined in PWA Studio internals).
>
>Note that this is not equal to the contents of your `.env` file. The `.env` file is a convenient way to set environment variables in the Node process; Buildpack treats it the same as any environment variable set by the outer shell or process.
>
>In turn, merely setting a new environment variable—e.g. `THIRD_PARTY_KEY=abc123`—is not an officially supported way of storing PWA Studio configuration. That value would be available in Node as `process.env.THIRD_PARTY_KEY`, but it would _not_ be available to the frontend JavaScript, and it would not be included in the [smart config object returned by `loadEnvironment()`.](https://magento.github.io/pwa-studio/pwa-buildpack/configuration-management/#configuration-object).
>
>To create a custom environment variable that will be supported in the frontend and available in config objects, you must add it to the [`envVarDefinitions` object](https://magento.github.io/pwa-studio/pwa-buildpack/configuration-management/#project-environment-definitions) used by Buildpack. There exists a Target for that purpose: the `envVarDefinitions` target gives your project, or your third-party extension, the chance to update the official configuration schema before validating the current environment.

(Okay. Not that brief. If this is something you and @jcalcaben judge useful, I'm sure he would be able to tighten it right up.)

My big followup question, though, is: **is this too weird?** There are very good reasons not to expose any environment variable to the frontend: above all, it's a big security hole. But I can understand how you'd be surprised that your additions to `.env` didn't work; it sure seems like `.env` is where project configuration goes.

I resolve this in my head by thinking of `.env` as just a convenience for setting environment variables any old way--like in Docker or AWS, for instance. It's not special.

Still, if it really appeals to you, I can give `.env` special behavior, wherein it does let anything explicitly defined in `.env` become available to the build just as officially defined variables are. I'd probably want to throw a deprecating warning while supporting this, but if we did support it, I wonder if fewer developers would get as confused as you initially were.

What do you think, @brendanfalkowski ? Should I hack it to be less surprising? Or should we just find a way to simply and clearly explain this environment setup and the need to extend the schema?

**Comment by zetlen** [comment]
Hey Brendan, I'm gonna close this because you solved the mystery yourself, but this this issue crystallized the fact that we need a simple how-to for putting an environment variable in the bundle.

We'll probably wanna preserve the limitation that you have to declare, describe, and document a variable as an `envVarDefinition` before it makes it into the build, **BUT** we'll make that clear and do a two-step tutorial for it. We have a backlog item for env var tutorials and I'm linking that item to this issue.
