### ISSUE TITLE
[bug]: Serviceworker requests wrong file chunks

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#2351]
**Describe the bug**
This is a bug that sometimes happens after a deploy to a running server. We don't yet know the exact cause for this issue, but there are 2 theories discussed in the slack channel.

**Theory 1**
Everytime the `index.html` is requested, the SW will first return the `index.html` that it has cached and fetch the new file in the background. Once the file is downloaded if they happen to be different, byte wise, the SW sends a message to the UI to update, that is when you see the toast to refresh.

`index.html` has links to the JS bundles that the app needs. Like mentioned above, client and vendor JS bundles to name couple. If their contents have changed in the new version/deployment, their file name should have changed and the `index.html` should be diff from the cached version hence the UI should have shown a refresh toast.

The problem as I understand above is, the bundle names are not changing but the sub bundles names are changing internally so when the UI after a new deployment returns the new index.html file it happens to be the same byte wise to the prev version so no refresh occurs. Similarly the vendor and client JS files are not deleted because their names stay the same, so when the browser tries to fetch those files, SW will intercept the call and return the JS bundles it has cached, unfortunately those bundles are pointing to sub bundles that don't exist any more. Hence the app might be failing.

All this theory is based on the fact that bundle names are not changing even if their sub bundles/modules are changing. That usually is not the case.
To test this, a normal deployment, load the app and make sure the SW has cached everything. Now go to the dist folder and change the name of a sub bundle, and try to go to a diff URL which has to load that new sub module. It should have failed because the file does not exists. I am assuming this is what happening during a deployment. `Chunk names` might be the culprit.

**Theory 2**
The handling for the update notification is part of `index.js`, see `registerSW()`. `index.js` itself is a part of the client-bundle after building. If you look at `index.html`, the client-bundle gets loaded AFTER the vendor bundle, which makes sense. BUT the `index.html` file is part of the service-worker cache. So after a new release, if you visit the site, the “old” `index.html` it used which loads some vendor-bundle which loads some old chunks that don’t exist anymore on the server. Thus the JS crashes and therefore the whole app

**Expected behavior**
Never show a blank page

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by Jordaneisenburger** [comment]
Mhh I did some testing but it's really hard to get some valuable test cases that consistently provide a white screen after deploy.

But we also have another issue described below.

1. Open terminal run `yarn start`
2. Open homepage in the browser (don't navigate, but keep the tab active)
3. Change something in a sub bundle thats loaded on the category page
4. Open a new terminal and run `yarn build`
5. Now navigate from you homepage (that should still be open) to a category page (use a router link, not a reload)
6. This makes a request to a sub bundle that has a changed name since we made change to that file.

What worries me here is that the site has no way of knowing that something has changed and therefore always fails this case.

**Comment by Jordaneisenburger** [comment]
Found another issue that might have something todo with all this.

1. Open terminal run yarn start
2. Open homepage in the browser 
3. Change something in `src/index.js` for example add `console.log('blabla')`
4. Open a new terminal and run yarn build
5. Now close the homepage tab and reopen the homepage in a new tab
6. Open the chrome console, you should see the following error

![Screenshot 2020-04-22 at 15 31 29](https://user-images.githubusercontent.com/19858728/79987962-5c8ad600-84ae-11ea-911e-4681dd7bf6b2.png)

**Comment by Jordaneisenburger** [comment]
Since I couldn't upload it here, check: https://www.youtube.com/watch?v=IzNF-vv4Kow

**Comment by BigCX** [comment]
I can confirm this. Its really annoying... after deployment user gets blank page... there should be a solution asap.

`function __webpack_require__(n) {
        if (t[n])
            return t[n].exports
        var a = t[n] = {
            i: n,
            l: !1,
            exports: {}
        }
          , r = !0
        try {
            e[n].call(a.exports, a, a.exports, __webpack_require__),
            r = !1
        } finally {
            r && delete t[n] <----- JS debugger stops here
        }
        return a.l = !0,
        a.exports
    }`

**Comment by awilcoxa** [comment]
Created in Jira Backlog for grooming

**Comment by guilhermeamadowj** [comment]
@Jordaneisenburger Any news on this? We are having the same problem here.
