### ISSUE TITLE
Use storybook in scaffolded app

### ISSUE THREAD

**Issue by niklaswolf** [magento/pwa-studio#2352]
**Describe the bug**
It's not directly a bug, but it isn't a new feature either, it's somethingin between, maybe a featug ;)
Anyway, this came up in the slack chat: currently it's not possbile to show the stories from `venia-ui` in a scaffolded app. It would be great to include the storybook configuration in the scaffolding template (`venia-concept`), maybe it would even encourage more people to write stories (see #1591)
As shown in the slack thread, I have worked out a solution which is fairly easy and would be happy to provide this as a PR.

**Expected behavior**
Storybook can start from a scaffolded app and shows all defined stories from the "parent" implementation (`venia-ui`)

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
created in Jira backlog

**Comment by awilcoxa** [comment]
Marked as a P2S3 feature request and @zetlen to review PR.
