### ISSUE TITLE
Bug in CheckoutPage: useShippingMethod missing useEffect to call onSave

### ISSUE THREAD

**Issue by joturako** [magento/pwa-studio#2357]
**Describe the bug**

When an user completed choosing shipping method (step2) and refresh the page. The page is in inconsistent state: because the 2nd step is completed, the form is not show. But because the onSave is not called, the 3rd step (payment info) is not automatically shown. Thus to continue the checkout process, user have to press Edit and then Update on the Shipping Method modal.

This does not happen on 2nd step because `useShippingInformation.js` has this block which is missing from `useShippingMethod.js`

```
useEffect(() => {
        if (doneEditing) {
            onSave(doneEditing);
        }
    }, [doneEditing, onSave]);
```

**To reproduce**
1. Add a product to cart and go to checkout page
2. Complete shipping information step
3. Complete shipping method step
4. Stay at payment information step and refresh browser
5. See the steps in a corrupted state: no step is open for editing.

**Expected behavior**
The payment information step should be opened as before the browser is refreshed.

**Screenshots**
![checkout_corrupted_censored](https://user-images.githubusercontent.com/4680820/80177375-c4aff800-8625-11ea-96c6-4e04fc0dd303.png)
 

**Additional context**

**Possible solutions**
```
useEffect(() => {
        if (doneEditing) {
            onSave(doneEditing);
        }
    }, [doneEditing, onSave]);
```
The same logic should be added to `useShippingMethod.js`

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
 - OS [e.g. iOS8.1, Windows 10]: Mac
 - Browser [e.g. Chrome, Safari]: Chrome
 - Browser Version [e.g. 22]: 81
 - Magento Version: 2.3.4
 - PWA Studio Version: 5.0.1
 - NPM version `npm -v`: 6.14.4
 - Node Version `node -v`: 12.16.2

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by tjwiebell** [comment]
@joturako - Thank you for the bug report. The CheckoutPage is not accessible in the app yet, so I would not expect it to be completely bug free until we've actually made it routable in the app. This is a known problem (especially with features being developed in parallel) and there is already a PR up that resolves, #2354 ([fix here](https://github.com/magento/pwa-studio/pull/2354/files#diff-e8b160b5283e3e60da4aee000580e0bcR186-R190))

We appreciate you being excited about the release of these new features, but please keep in mind in the future that until we've made them routable, we do not consider them production ready. You may notice in the upcoming `6.0` release, CartPage components existed, but got feature toggled completely out of the app.

Closing this out, but please let us know if you discover any additional issues once this page is production ready.
