### ISSUE TITLE
[bug]: Expired token results in graphql errors in mini cart

### ISSUE THREAD

**Issue by dani97** [magento/pwa-studio#2378]
**Describe the bug**
Cart query cached by apollo in local storage needs to be purged after token expired.

**To reproduce**
1. Login as customer add products to cart
2. Wait for token expiry time, https://venia.magento.com is 1 hour I believe
3. After token  is expired, open the site and check the cart, the minicart will show items in cart but when you open it, graphql error will be thrown, denying permission to access customer's cart 
4. Either you can clear local storage to continue/ login to continue.

**Expected behavior**
Cart cache should be cleared once token is expired.

**Screenshots**
![Screenshot from 2020-05-02 19-06-05](https://user-images.githubusercontent.com/13298685/80867110-fd983e80-8caf-11ea-9f47-8b94b4860cd6.png)
![Screenshot from 2020-05-02 19-06-32](https://user-images.githubusercontent.com/13298685/80867116-025cf280-8cb0-11ea-8602-27130c43253d.png)

**Additional context**
https://github.com/magento/pwa-studio/pull/2322.  This PR handles only on signIn, signOut and other customer triggered scenarios, we have to handle other scenarios like token expiry.

**Possible solutions**
Whenever app is launched, cartDetails query should be fetched and if it fails because of cart permission, cart section should be cleared like above PR

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:PC
 - OS [e.g. iOS8.1, Windows 10]:ubuntu 18.04
 - Browser [e.g. Chrome, Safari]: Firefox
 - Browser Version [e.g. 22]: 
 - Magento Version: 2.3.4
 - PWA Studio Version: 6.0.1
 - NPM version `npm -v`:
 - Node Version : 10

**Please let us know what packages this bug is in regards to:**
- [X] `venia-concept`
- [X] `venia-ui`
- [ ] `pwa-buildpack`
- [X] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by dani97** [comment]
@sirugh @jimbo @supernova-at , This bug could affect UX of customers. @larsroettig @Jordaneisenburger @awilcoxa  please proritize this issue.

**Comment by sirugh** [comment]
Just to clarify, did you mean cart expiration or login token expiration? Either way this sounds pretty important. I'll see what we can do. Thanks for reporting this @dani97!

**Comment by sirugh** [comment]
We set the auth token expiry to 60 minutes manually when we first set it. After 60 minutes, if a user refreshes and the app goes through initialization it _should_ delete the old user token **(it does, I just checked**) and the mini cart logic _should_ re-fetch as a guest user and allow. (**it does not, the old cart id, for the old token, persists**).

Perhaps we should be expiring the cart id after 1 hour. Is it valid to expire the cart id for all users after that time or should we only expire authorized carts after 1 hour and leave guest carts to whatever they were before?

**Comment by dani97** [comment]
@sirugh I have seen guest carts expire in luma store but not sure that applies for PWA. But authorized carts should be expired once token is expired.

**Comment by sirugh** [comment]
Adding the error to the invalid check is easy enough, I do it in #2379. But I do notice there are some other visual discrepancies to handle. 

If a user leaves the PC and comes back an hour later and attempts some action like adding an item to the cart it will now work **however** the cart trigger item count and the user data in the left drawer will persist incorrectly.

If the user refreshes the page when they return after the token expiry the cart trigger item count is wrong but the user data in the left drawer won't be there.

The reason this happens is because the apollo cache is not reset when the user's auth token is invalidated. We don't do any cache reset within the redux action functions.

**Comment by dani97** [comment]
This is from magento frontend where they achieve it via persistant cookie https://docs.magento.com/m2/ce/user_guide/sales/cart-persistent.html. Since cookie should not be used for authentication in pwa, only increasing token expiry time is an option for guest users. Registered users on the other hand can retrieve their cart by merge carts mutation (should be using nonce or something like that)

**Comment by awilcoxa** [comment]
created in Jira Backlog
