### ISSUE TITLE
[feature]: React-refresh to improve reloading components at development

### ISSUE THREAD

**Issue by dani97** [magento/pwa-studio#2391]
**Is your feature request related to a problem? Please describe.**
PWA Studio currently uses `react-hot-loader` for reloading components, styles when developing.
React introduced `fast refresh` last year to improve browser reloading. We have to remove react-hot-loader and add react-refresh improving developer experience, also hot loader will be deprecated in favor of react-refresh

**Describe the solution you'd like**
Update dependencies to react-refresh 

**Additional Context**
I just came to know about it. This is new and many have not adopted to it, **may not be a requirement for PWA studio at this time**, opening this to watch for future improvements

**Please let us know what packages this feature is in regards to:**
- [X] `venia-concept`
- [ ] `venia-ui`
- [X] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [X] `create-pwa`

**Comment by awilcoxa** [comment]
created in Jira backlog (PWA-653)

**Comment by awilcoxa** [comment]
Marked as P3S4 and will require further follow up

**Comment by awilcoxa** [comment]
Moved to P2 and In Review for core team
