### ISSUE TITLE
[bug]: Too strict peerdependency requirements

### ISSUE THREAD

**Issue by paales** [magento/pwa-studio#2411]
**Describe the bug**

I'm installing the `@magento/peregrine` and `@magento/venia-ui` packages but it seems lots of packges are defined with a tilde `~`

```
warning " > @magento/peregrine@6.0.0" has incorrect peer dependency "react@~16.9.0".
warning " > @magento/peregrine@6.0.0" has incorrect peer dependency "react-dom@~16.9.0".
warning " > @magento/venia-ui@3.0.0" has incorrect peer dependency "apollo-client@2.6.4".
warning " > @magento/venia-ui@3.0.0" has incorrect peer dependency "react@~16.9.0".
warning " > @magento/venia-ui@3.0.0" has incorrect peer dependency "webpack@~4.41.2".
```

**To reproduce**
Install the packages on an existing node project

**Expected behavior**
I'd expect the dependencies be less strict.

**Possible solutions**
Since most packages are following semver strictly they dont have to be required using a `~` and can be installed with a `^`

It might also be interesting to install something like dependabot to regularly update the dependencies of this project.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by paales** [comment]
I see that dependabot is already installed: https://github.com/magento/pwa-studio/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies but dependabot isn't able to handle peerDepenencies properly it seems: https://github.com/dependabot/dependabot-core/issues/1242

**Comment by awilcoxa** [comment]
Created in Jira backlog for triage (PWA-657)

**Comment by awilcoxa** [comment]
Marked as P3S3 in backlog

**Comment by paales** [comment]
Not sure what P3S3 means, is there documentation available somewhere? Maybe create a label with a description in GitHub?

**Comment by davemacaulay** [comment]
@paales this means priority 3 and severity 3, it's how we track the importance of issues to help with triaging.

We're tracking this item internally with the following ticket: https://jira.corp.magento.com/browse/PWA-657
