### ISSUE TITLE
Feedback on page: /technologies/theme-vs-storefront/

### ISSUE THREAD

**Issue by Eddcapone** [magento/pwa-studio#2413]
Can you develope an online shop and have both: PWA and a normal website with a normal magento theme for the same shop? Or do you have to choose one approach?

**Comment by dani97** [comment]
Are you looking something like this https://github.com/magento-research/magento2-upward-connector#front-name-whitelist

**Comment by sirugh** [comment]
Closing as this is more of a question. Please use the discussions tab or the public slack in the future!

**Comment by Eddcapone** [comment]
@sirugh , yes it is a question, one were I expected the answer in the documentation so I pointed out that this question remains unanswered in it.
