### ISSUE TITLE
Feedback on page: /tutorials/pwa-studio-fundamentals/add-a-static-route/

### ISSUE THREAD

**Issue by sivakumarkoduru** [magento/pwa-studio#2419]
Dear Community,

To just add  simple route and component so many files need to modify, is there any simple way to get things done.

**Comment by Jordaneisenburger** [comment]
Hi, Best bet is to ask the question in the community slack. We want to keep these issues to Feature requests / Bug reports or Documentation Request. Right now the way to add a route is the way it's written in the mentioned docs.
