### ISSUE TITLE
Incorrect Item Price display in mini cart

### ISSUE THREAD

**Issue by shikhamis11** [magento/pwa-studio#2424]
**Describe the bug**
Incorrect Item Price display in mini cart

**To reproduce**
1. Go to any configurable Product Page which has multiple options with different prices
2. Click on add to cart
3. In mini cart the it is showing default price not the exact one of that particular item
4. the same issue occurs when any catalog price rule is applied 

**Expected behavior**
Mini cart should always show the final price of the item with all discount applied and exact option price value in case of configurable product

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
 - OS [e.g. iOS8.1, Windows 10]: Linux
 - Browser [e.g. Chrome, Safari]: Chrome
 - Browser Version [e.g. 22]: 83
 - Magento Version: Magento 2.3.5
 - PWA Studio Version: 6
 - NPM version `npm -v`: 6.4.1
 - Node Version `node -v`:10.15.3

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Created in Jira backlog for triage (PWA-659)

**Comment by awilcoxa** [comment]
Needs review.
