### ISSUE TITLE
Error if product is out of stock

### ISSUE THREAD

**Issue by shikhamis11** [magento/pwa-studio#2426]
**Describe the bug**
Error if product is out of stock

**To reproduce**
1. Go to Product Page of any out of stock product
2. Make sure in magento backend the below setting is set to `NO` 
    Store->Configuration->Catalog->Inventory->Display Out of Stock Products
3. Error on Product Page 

**Expected behavior**
It should show message `This Product is currently out of stock. Please try again later.` as set in root Component

**Screenshots**
![image](https://user-images.githubusercontent.com/25526037/82727703-c2ff5000-9d09-11ea-9669-9001bb275806.png)

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
 - OS [e.g. iOS8.1, Windows 10]: Linux
 - Browser [e.g. Chrome, Safari]: Chrome
 - Browser Version [e.g. 22]: 83
 - Magento Version: 2.3.5
 - PWA Studio Version: 6
 - NPM version `npm -v`: 6.4.1
 - Node Version `node -v`: 10.15.3

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by Jordaneisenburger** [comment]
If it's set to "No" it should say that the product or url does not exists and therefor give a 404. Because we don't want people to be able to access a url that should not be accessible.

**Comment by shikhamis11** [comment]
Hi @Jordaneisenburger 
Thanks for the feedback. I also think it should show 404 page, don't know why there is message written in product root component for the out of stock condition

**Comment by awilcoxa** [comment]
Created in Jira backlog for triage (PWA-660)

**Comment by sirugh** [comment]
I agree here. If the configuration specifies not to show out of stock products then we should show a 404 or that the url does not exist.

I would have expected something to catch that before you even get to the product root component. I'm curious how graphql behaves when you have it set to "no". Should we even be rendering the product component? Does the product query made return an error signifying this?
