### ISSUE TITLE
can't import custom fonts in css files

### ISSUE THREAD

**Issue by lfaz** [magento/pwa-studio#2435]
I am having difficulties to import custom fonts into css files, for some reason webpack complains that there is no file loader configured, I could not find in the documentation something related to this.

I know how to configure for normal projects the file loader for webpack, but kinda seems abit different the webpack under venia-concept/.

I tried to modify and add something like this on the webpack.config.js just after 

> config.module.noParse = [/braintree\-web\-drop\-in/];

 :

```
    config.module = {
        rules: [
            {
                test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: '[name].[ext]',
                            outputPath: 'fonts/'
                        }
                    }
                ]
            }
        ]
    }
```

not working, how does one is able to import custom fonts when working with pwa studio app?

CSS:
```
@font-face {
    font-family: SBonusDisplay;
    src: url('./assets/fonts/SBonusDisplay-Black.woff');
}
```

```
.root {
    --sbonus-display-black: SBonusDisplay, sans-serif;
}
```
ERROR:

> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by awilcoxa** [comment]
Created in Jira backlog for triage (PWA-663)

**Comment by awilcoxa** [comment]
Marked feature request as P2S3, @zetlen will jump in to help you with your immediate questions @lulzimfazlija

**Comment by Jordaneisenburger** [comment]
So this might not be the preferred solution but it should work just fine. 

**Step 1**
```
// template.html

 <style type="text/css">
     @font-face {
         font-family: 'SBonusDisplay';
         src:  url('/static/fonts/SBonusDisplay-Black.woff2') format('woff2'),
         url('/static/fonts/SBonusDisplay-Black.ttf') format('ttf');
     }
</style>
```
**Step 2**
Create `/fonts/SBonusDisplay-Black.woff2` and `/fonts/SBonusDisplay-Black.ttf` in your `PROJECT_ROOT/static`

**Step 3**
In upward.yml add ttf and woff2 to fileExtension like shown below
```
    - matches: fileExtension
      pattern: '(js|json|png|svg|ico|css|txt|ttf|woff2)'
      use: veniaStatic
```

**Comment by JuanPagola** [comment]
I'm facing the same issue, and the steps suggested by @Jordaneisenburger did not fix the issue unfortunately.

**Comment by michalburda3** [comment]
@lulzimfazlija 
The below solution worked for me:

- create `src/fonts.css` and import this file in `src/index.css` (or declare font-faces directly in `index.css`)
- create `static/fonts/` folder in the root folder and add your font files
- add font-face declarations, for example:
```
@font-face {
    font-family: 'your_font_family_name';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: url("../static/fonts/your-font-folder/your-font.woff2") format("woff2");
}
```
- to webpack, add config 
```
config.module.rules.push(
        // Font files
        {
            test: /\.(woff|woff2|ttf|otf)$/,
            loader: 'file-loader',
            include: [/fonts/],
            options: {
                name: '[hash].[ext]',
                outputPath: 'css/',
                publicPath: url => '../css/' + url
            }
        }
    );
```
- delete `<style>` tag with default font-face declarations inside `template.html`

**Comment by zetlen** [comment]
I'm unassigning myself because @Jordaneisenburger and @michalburda3 gave better answers than I could. Better font handling could be built into the core Buildpack code by adding the suggested loaders.

**Comment by realadityayadav** [comment]
We cannot make this work, can someone suggest  a working solution for adding custom fonts  please?
