### ISSUE TITLE
[bug]: The venia-static directory is not being removed from dist

### ISSUE THREAD

**Issue by svalveson** [magento/pwa-studio#2437]
**Describe the bug**
The **venia-static** folder keeps being generated in the `./dist` folder, even when the `veniaStaticIncludes` is redefined with an own static folder (e.g. **customxyz-static**).

**To reproduce**
1. Edit the `./upward.yml` replacing the veniaStaticIncludes directory from **./venia-static** to **./customxyz-static**
2. Create the folder **customxyz-static** in the project root.
3. Replace **venia-static** for **customxyz-static** in `./template.html`
4. Run the `$  yarn build:prod` command.

**Expected behavior**
After run the  `$  yarn build:prod` command, the **venia-static** folder should be removed automatically and added the **customxyz-static** folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/13263535/83079803-008a1300-a053-11ea-8952-ff537e866293.png)

**Additional context**
Buildpack adds the UpwardIncludePlugin to Webpack, which looks through every upward.yml file for files and folders referenced, it copies those files and folders in and it does not notice when they've been overwritten

**Please complete the following device information:**
 - Device: Mac
 - OS: macOS 10.4.4
 - Magento Version: 2.3.5
 - PWA Studio Version: 6.0.1
 - NPM version: 6.11.3
 - Node Version: 10.16.3

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by tjwiebell** [comment]
@svalveson - I was unable to reproduce this on `develop` so I believe this to be fixed. I did notice there are two spots in `packages/venia-ui/upward.yml` that reference `venia-static`, so its possible the second reference is why you still saw that in the build.

Going to close as no longer a bug, but please re-open if you're still able to reproduce against `develop`.
