### ISSUE TITLE
[bug]: ProductSort/CategorySort component shouldn't be conditional on filters being present

### ISSUE THREAD

**Issue by luke-denton-aligent** [magento/pwa-studio#2441]
**Describe the bug**
The `ProductSort`/`CategorySort` component (it seems to have had a name change recently?) is rendered in a `.headerButtons` container, which is defined in `venia-ui/lib/RootComponents/Category/categoryContent.js` on line 44. This means that if there are no filters available, then sorting is also unavailable.

This appears to be left over logic from when the only header button was a Filters toggle button. At that point it made sense to make the header buttons conditional on there actually being filters to toggle, but now that a sort by button is in there, I don't think it makes sense anymore

**To reproduce**
1. Open `venia-ui/lib/RootComponents/Category/categoryContent.js` on line 44. This means that if there are no filters available, then sorting is also unavailable.`
2. Remove `filters` from the `talonProps` destructure
3. Add `const filters = false;` to the line directly under the `talonProps` destructure
4. Load up app
5. See that not only the Filters toggle button is removed, but also the sort by button

N.b. Obviously this is hacking the code to force a certain situation, but I figured it's the easiest way to demonstrate, rather than having to modify the BE in order to remove all filters

**Expected behavior**
When there aren't any filters available, then _only_ the Filters toggle button should be hidden

**Screenshots**
Filters disabled
![image](https://user-images.githubusercontent.com/18253422/83201157-10554480-a184-11ea-80ee-77f68694eba6.png)

Filters enabled
![image](https://user-images.githubusercontent.com/18253422/83201252-3da1f280-a184-11ea-9d9a-2bac575bc519.png)

**Possible solutions**
Instead of wrapping the entirety of the header buttons in a conditional check on `filters`, _only_ the Filters toggle button should be.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: All
 - OS [e.g. iOS8.1, Windows 10]: All
 - Browser [e.g. Chrome, Safari]: All
 - Browser Version [e.g. 22]: All
 - Magento Version: All
 - PWA Studio Version: 6
 - NPM version `npm -v`: All
 - Node Version `node -v`: All

**Please let us know what packages this bug is in regards to:**
- [*] `venia-ui`

**Comment by awilcoxa** [comment]
Created PWA-664

**Comment by larsroettig** [comment]
@magento I am working on this

**Comment by larsroettig** [comment]
@magento add to contributors team

**Comment by larsroettig** [comment]
@magento I am working on this

**Comment by awilcoxa** [comment]
Marked P2S3, in review
