### ISSUE TITLE
[bug]: Filterable product attributes wrong language/store

### ISSUE THREAD

**Issue by danlupo** [magento/pwa-studio#2442]
**Describe the bug**
Have multiple storefronts in different languages (default english + french). Create a custom searchable/filterable product attribute and configure it's different labels.

In PWA Studio will access the default/english store, however the labels are french

**To reproduce**
1. Go to category listing page
2. Click on filters
3. Scroll down to see your filter options
4. See labels in wrong language

**Expected behavior**
Labels should be in the same language as the store

**Screenshots**
![Screen Shot 2020-05-29 at 4 22 18 PM](https://user-images.githubusercontent.com/46357040/83303515-2803eb80-a1cb-11ea-9931-3fcd60407f70.png)
![Screen Shot 2020-05-29 at 4 39 51 PM](https://user-images.githubusercontent.com/46357040/83304010-10793280-a1cc-11ea-8295-6b303e17bf1f.png)

**Additional context**
We've applied the elasticsearch patch described [here](https://support.magento.com/hc/en-us/requests/307714?flash_digest=cba2b3eebbb2c49e5f3a440f61080aa89438aea7) also, but it seems unrelated. We suspect that it might be a graphql bug.

**Please complete the following device information:**
 - Device: Mac
 - OS macOs 10.14.6
 - Browser: Chrome
 - Browser Version: 83.0.4103.61
 - Magento Version: 2.3.5
 - PWA Studio Version: 6.0.1
 - NPM version `npm -v`: 6.13.4
 - Node Version `node -v`: v10.19.0

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-ui`
- [ ] `peregrine`

**Comment by lano-vargas** [comment]
@danlupo I have the same issue! I have 5 store view and I played around with the labels with store view when I leave all of them empty it will pick the Admin Value. 
But What I notice if I started adding them back one at the time and loading the PWA I noticed that it seem to be picking it up some sort of alphabetically order.

**I've added for IE store view and here is the setup:**
<img width="1509" alt="Screenshot 2020-08-18 at 11 11 26" src="https://user-images.githubusercontent.com/3495481/90501206-e5a3d800-e143-11ea-8410-79b60a0a69ae.png">

**Here is the result on PWA :**
<img width="356" alt="Screenshot 2020-08-18 at 11 14 35" src="https://user-images.githubusercontent.com/3495481/90501331-24399280-e144-11ea-84ef-5e010de721a3.png">


**Next I've added  for German de store view see the results:**
<img width="1244" alt="Screenshot 2020-08-18 at 11 18 26" src="https://user-images.githubusercontent.com/3495481/90501636-8f836480-e144-11ea-887c-d9be05ca4bd9.png">

<img width="351" alt="Screenshot 2020-08-18 at 11 16 45" src="https://user-images.githubusercontent.com/3495481/90501559-75e21d00-e144-11ea-8f1f-6a5c56522633.png">

**Now DE store view shows in the filter hmmm interesting `de` as d comes f4 the letter  i fro `ie` store view it seems picking it up alphabetically.**

**Next NL reload the page  and guess. it still showing DE label. see result:**
 
<img width="1197" alt="Screenshot 2020-08-18 at 11 23 58" src="https://user-images.githubusercontent.com/3495481/90502262-73cc8e00-e145-11ea-9e64-3caf7674c170.png">
<img width="348" alt="Screenshot 2020-08-18 at 11 24 39" src="https://user-images.githubusercontent.com/3495481/90502301-7f1fb980-e145-11ea-9718-15973dc6d2e0.png">

**NOTES: Clear Cache, and reload PWA in incognito every time testing it!**


I think this should be re-open to look at it again is seem and issue with query Order By or something else.

**Comment by danlupo** [comment]
@lano-vargas we actually moved this issue to magento support as it was not a PWA studio issue. Moreover we found the source and provided a patch there. Please check it out below. I hope this helps solve your issue.

`--- a/vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php	2020-06-22 14:52:49.421201000 +0000
+++ b/vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/Builder/Attribute.php	2020-06-22 14:52:41.762499000 +0000
@@ -71,7 +71,7 @@
      */
     public function build(AggregationInterface $aggregation, ?int $storeId): array
     {
-        $attributeOptions = $this->getAttributeOptions($aggregation);
+        $attributeOptions = $this->getAttributeOptions($aggregation, $storeId);

         // build layer per attribute
         $result = [];
@@ -133,10 +133,11 @@
      * Get list of attributes with options
      *
      * @param AggregationInterface $aggregation
+     * @param int $storeId
      * @return array
      * @throws \Zend_Db_Statement_Exception
      */
-    private function getAttributeOptions(AggregationInterface $aggregation): array
+    private function getAttributeOptions(AggregationInterface $aggregation, int $storeId): array
     {
         $attributeOptionIds = [];
         $attributes = [];
@@ -154,6 +155,6 @@
             return [];
         }

-        return $this->attributeOptionProvider->getOptions(\array_merge(...$attributeOptionIds), $attributes);
+        return $this->attributeOptionProvider->getOptions(\array_merge(...$attributeOptionIds), $storeId, $attributes);
     }
 }

--- a/vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php	2020-06-22 14:56:58.633549000 +0000
+++ b/vendor/magento/module-catalog-graph-ql/DataProvider/Product/LayeredNavigation/AttributeOptionProvider.php	2020-06-22 14:53:00.977201000 +0000
@@ -41,11 +41,12 @@
      * Get option data. Return list of attributes with option data
      *
      * @param array $optionIds
+     * @param int $storeId
      * @param array $attributeCodes
      * @return array
      * @throws \Zend_Db_Statement_Exception
      */
-    public function getOptions(array $optionIds, array $attributeCodes = []): array
+    public function getOptions(array $optionIds, int $storeId, array $attributeCodes = []): array
     {
         if (!$optionIds) {
             return [];
@@ -76,6 +77,7 @@
             );
 
         $select->where('option_value.option_id IN (?)', $optionIds);
+        $select->where('option_value.store_id = ?', $storeId);
 
         if (!empty($attributeCodes)) {
             $select->orWhere(
`
