### ISSUE TITLE
Content for bots

### ISSUE THREAD

**Issue by rowan-m** [magento/pwa-studio#247]
## This issue is for the following packages:

- [x] `venia-concept`
- [x] `pwa-buildpack`
- [x] `peregrine`
- [x] `pwa-module`
- [ ] `pwa-devdocs`

## This issue is a:

- [ ] Bug
- [x] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | `2.3-develop` |
| Operating System + version  | `Ubuntu 18.04.1 LTS` |
| node.js version (`node -v`) | `10.4.1` |
| npm version (`npm -v`)      | `6.2.0` |

## Description

Non-browser clients, e.g. search engines, link unrollers, etc. only see the initial `<div id="root"></div>` response without any content.

## Expected result:

Pages should return a meaningful response for these clients.

## Possible solutions:

- Metadata in initial response - good for link unrolling, not great for indexing
- Server side rendering for initial response - good, but the cost of hydration needs to be considered
- Server side render for bots - brittle as UA sniffing is a constant maintenance overhead

**Comment by zetlen** [comment]
#248 is the architectural change that takes care of this, but it doesn't fully resolve this issue--we need to determine what constitutes a meaningful response in a largely client-rendered application. @rowan-m Assuming that full server-side render would be cost-prohibitive, do you feel that it's adequate to have a page header and copious metadata in the HEAD tag? @ericerway How would you feel about converting this to an epic which covers metadata population code for each content type?

**Comment by awilcoxa** [comment]
Will include in updated epic for SSR solution, @zetlen to link into new epic

**Comment by zetlen** [comment]
Related to #1529.

**Comment by awilcoxa** [comment]
Closing legacy issue as we've addressed SEO via multiple recent tickets. We'll create new tickets to address current PWA Studio gaps for SEO.
