### ISSUE TITLE
[bug]:request.headers.user-agent should be useable in upward

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2485]
**Describe the bug**
It's currently not possible to use the following
```
  resolver: conditional
  when:
    - matches: request.headers.user-agent
```
due to the `-` character.

**To reproduce**
1. Create upward rule with the above

**Expected behavior**
see pull request #2484 

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [x] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by tjwiebell** [comment]
Created in internal JIRA for grooming: PWA-689
