### ISSUE TITLE
[bug]: Disable Apollo RetryLink when offline ? 

### ISSUE THREAD

**Issue by mercs600** [magento/pwa-studio#2489]
**Describe the bug**
When we are offlline and when we're trying to open some cached page then we will get the cached page, but after this ApolloRetryLink is trying to call some requests and after then we get Data Fetch Error

**To reproduce**
1. Being online go to some product page 
2. Switch browser to offline mode 
3. Open the same product page (must be cached)
4. You see product page
5. In the background, you are able to see graphql retry requests 
6. After some tries you will see "Data Fetch Error" instead of product page 

**Expected behavior**
Should we use apollo-retry link when client is being offline ?

**Screenshots**

![ezgif-4-2d2e07fceced](https://user-images.githubusercontent.com/7935392/84774565-4bf26a00-afde-11ea-9454-a07268c30ac4.gif)
![ezgif-4-5a490eebc7bf](https://user-images.githubusercontent.com/7935392/84774664-70e6dd00-afde-11ea-8a52-74c74778b2f5.gif)

**Additional context**
The newest version of develop branch, but also visible on master 

**Possible solutions**
Use apollo retry link only when client is being offline ? 

**Please complete the following device information:**
 - Device  Mac
 - OS The newest one
 - Browser Chrome, safari
 - Browser Version the newest one
 - Magento Version: doesn't matter 
 - PWA Studio Version: develop / 6.01 
 - NPM version `npm -v`:  doesn't matter 
 - Node Version `node -v`: doesn't matter 

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
This is definitely a bug but I don't think we should disable the link when offline. The retry link is actually intended for situations where the app goes offline. Check out the [docs](https://www.apollographql.com/docs/link/links/retry/), they say this:

> One such use case is to hold on to a request while a network connection is offline and retry until it comes back online.

What might be better is if we try to understand why the `Data Fetch Error` is being shown. I would expect cached data to display until the app comes back online.

**Comment by mercs600** [comment]
@sirugh Ya, you re right, generally we should avoid displaying the error if we have already product data from apollo cache. That small PR fix this https://github.com/magento/pwa-studio/pull/2490
