### ISSUE TITLE
Feedback on page: /technologies/basic-concepts/client-side-caching/

### ISSUE THREAD

**Issue by kiennguyen1101** [magento/pwa-studio#2501]
The link in the last line: "Caching for Apollo is set up in the `src/drivers/adapter.js` file." which leads to: https://github.com/magento/pwa-studio/blob/master/packages/venia-concept/src/drivers/adapter.js is invalid. It returns a 404 page.

Also, it would be great if a document is added on the default setup of apollo-cache-persist (how Magento PWA is using this lib) and how to prioritize on network-first (detects online environment and automatically renew data)

**Comment by awilcoxa** [comment]
Created PWA-728 in Jira backlog for grooming
