### ISSUE TITLE
[feature]: Make the pwa handle redirect urls

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#2502]
As a merchant I'd like to be able to make use of magento's redirect urls, right now those are not being handled by PWA Studio

**Describe the solution you'd like**
I'd like to see a solution where urls get redirected to the right page when there is a redirect set in magento.

**Additional context**
I will submit a PR, so this issue is just for reference.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by Jordaneisenburger** [comment]
@magento I am working on this

**Comment by awilcoxa** [comment]
Created PWA-729 for tracking
