### ISSUE TITLE
[bug]: pwa-studio section missing from packages.json

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2515]
**Describe the bug**
pwa-studio section missing from packages.json when installed via create-pwa

**To reproduce**
Note comment in `local-intercept.js`
```
 * This project has a section in its package.json:
 *    "pwa-studio": {
 *        "targets": {
 *            "intercept": "./local-intercept.js"
 *        }
 *    }
```
try to locate the above in a project based on create-pwa.

**Expected behavior**
The above should exist.

**Possible solutions**
https://github.com/magento/pwa-studio/pull/2514

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

**Comment by Jordaneisenburger** [comment]
Hi @fooman ,

I think this happens because create-pwa scaffolds from 6.0.1 hence this is not included in the `package.json`.

**Comment by awilcoxa** [comment]
Created PWA-730 in Jira backlog for grooming

**Comment by fooman** [comment]
@awilcoxa I'd probably take the severity down on this one. It's possible to manually copy this into one's own package.json and there would currently be nothing in existence that would break due to it missing. Longer term it has more an educational impact on introducing a common way to customise pwa studio via targets.

**Comment by wokakira** [comment]
How would you use the local-intercept.js file?

**Comment by fooman** [comment]
@wokakira you could for example add a new route
```
function localIntercept(targets) {
    targets.of('@magento/venia-ui').routes.tap(routes => [
        ...routes,
        {
            name: 'Blog New',
            pattern: '/blog/:urlKey?',
            exact: false,
            path: '../../../../../../src/RootComponents/Blog'
        }
    ]);
}
```

module.exports = localIntercept;

**Comment by quynhvv** [comment]
@wokakira: You can try with steps as followings:
**1**. In the file at path: **path_to_your_custom_project/**package.json
you declare as the following:
`"pwa-studio": {
    "targets": {
      "intercept": "./local-intercept.js"
    }
  }`
**2**. In the file at path: **path_to_your_custom_project/**local-intercept.js
you declare as the following:
`function localIntercept(targets) {
    targets.of('@magento/venia-ui').routes.tap(routes => [
        ...routes,
        {
            name: 'Custom Title',
            pattern: '/custom-route',
            exact: true,
            path: '**path_to_your_custom_project/**src/components/CustomComponent'
        }
    ]);
    return targets;
}
module.exports = localIntercept;`

**Comment by wokakira** [comment]
Thanks @quynhvv @fooman
