### ISSUE TITLE
[bug]: Cache Storage increased substantially

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2534]
**Describe the bug**
Comparing the cache storage from current development to last release shows a big increase.

**To reproduce**
1. Visit https://venia.magento.com/venia-dresses.html
2. Open dev tools
3. Clear storage
4. Hard page reload - take note of cache storage value
5. Repeat for a current PR

**Expected behavior**
Similar numbers for the same page.

**Screenshots**
Current
![image](https://user-images.githubusercontent.com/455508/86851538-408aee00-c107-11ea-978d-86dedb28d6f2.png)

New 
![image](https://user-images.githubusercontent.com/455508/86851598-5ac4cc00-c107-11ea-85a5-6b2566e8f215.png)

**Additional context**
There was a workbox upgrade - maybe related how it's counted?

**Possible solutions**
?

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Created PWA-745 in backlog for grooming

**Comment by revanth0212** [comment]
Hey @fooman, thanks for reporting the issue.

I would like to point out that this is expected behavior. Part of the changes we have published as part of #2390, [is adding all the assets emitted by webpack into the precache manifest of the SW](https://github.com/magento/pwa-studio/pull/2390/files#diff-6930053b68fa55d460ac81bc09551108R28).

The advantage is, the app always has all the assets it needs to render itself even if it is not connected to the internet.

Well, it comes with a disadvantage, which you just pointed out.

**Comment by fooman** [comment]
Glad to hear some of is anticipated.

I believe I might have narrowed this down a bit more (but not visible on https://pr-2558.pwa-venia.com/). It seems that when the back-end doesn't provide CORS headers and the PWA is using as media backend the back-end url we end up with 'opaque' responses for the images. These, irrespective of actual size, are padded to 7MB which adds up quickly, especially since the cache can hold a few variations of the same image.

![image](https://user-images.githubusercontent.com/455508/87991988-5a7ef480-cb3b-11ea-8be7-238ac2ea4a52.png)


https://developers.google.com/web/tools/chrome-devtools/progressive-web-apps#opaque-responses

**Comment by revanth0212** [comment]
Yeah, I have noticed it. As you mentioned, it depends on the backend handling of resources.

I am going ahead and closing the issue for now. If you notice anything out of order, feel free to open this or create a new one.

Thanks for documenting the issue with the details, might helps future devs.
