### ISSUE TITLE
[bug]: Can't add product to cart if another out of stock product is in the cart

### ISSUE THREAD

**Issue by drc0** [magento/pwa-studio#2536]
**Describe the bug**
If I add a product to the cart, and then this products goes out of stock, I cannot add more products to cart, no error message is shown but the api returns this error `{"errors":[{"message":"Some of the products are out of stock.","extensions":{"category":"graphql-input"}}],"data":{"addSimpleProductsToCart":null}}`

**To reproduce**
1.Add product to cart
2. Set the inventory for this product to 0 (no backorders)
3. Try to add another product to cart
4. No product is added to cart and graphql query returns that error above

**Expected behavior**
Product is added to cart, and error for previous product is shown

 - Magento Version: 2.3.5
 - PWA Studio Version: 6.0.1 (development 0837e212a81312473f365cd17d4ff7530ed2ce15)

**Comment by Jordaneisenburger** [comment]
I can confirm this is an issue indeed. Pretty sure we did some graphQL changes to return the product even when it's out of stock but then check it's stock status and show a message/disable checkout buttons

**Comment by awilcoxa** [comment]
Created PWA-746 in backlog for grooming
