### ISSUE TITLE
[bug]: Minicart container is preventing filters to be used on category pages

### ISSUE THREAD

**Issue by jemoon** [magento/pwa-studio#2546]
**Describe the bug**
Latest minicart changes introduce issue on each category page while browsing on mobile devices - filters button doesn't trigger Filters Modal anymore.

**To reproduce**
1. Visit category page on mobile device (480px width for example)
2. Click on 'Filters'

**Expected behavior**
Modal with filters should be shown

**Screenshots**
https://www.dropbox.com/s/932ei1s2yd7clce/Screen%20Recording%202020-07-10%20at%2012.52.38.mov?dl=0

**Possible solutions**
Minicart should use display (none/block) instead of visibility (hidden/visible) on close/open actions on larger screens.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Dev Tools with Device toolbar set to On and with resolution set to 480px width
 - OS [e.g. iOS8.1, Windows 10]: MacOs
 - Browser [e.g. Chrome, Safari]: Chrome
 - Browser Version [e.g. 22]: 84.0.4147.85

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
I'm unable to repro this on my Windows 10 box using Chrome@ 83.0.4103.116 (Official Build) (64-bit) or on my Pixel 3 with Chrome.

If you are able to repro consistently could you record and share a video of the steps from a fresh page load with a clean cache?

**Comment by tjwiebell** [comment]
I ran into this today reviewing some mobile views, his suggestion seems correct; I don't understand why some elements remain clickable, but likely some z-index luck.

![](https://gyazo.com/c7969b1efe586c2d270c017d9805ee68.gif)

**Comment by sirugh** [comment]
OH! I saw this happen then, but on product page. When I selected the right most color option on a product, then selected the one to the left, the right most option would stop being clickable. 

It stopped happening after a while so I just figured my mac had a problem.

**Comment by dpatil-magento** [comment]
I can reproduce it on reduced window size, part of button is not clickable.

<a href="https://gyazo.com/a2e5849ddb6110ff65889660764e884d"><img src="https://i.gyazo.com/a2e5849ddb6110ff65889660764e884d.gif" alt="Image from Gyazo" width="1000"/></a>

**Comment by supernova-at** [comment]
Thanks for reporting, I can fix this quickly.

**Comment by awilcoxa** [comment]
Created PWA-748 in backlog

**Comment by sirugh** [comment]
Should be resolved with https://github.com/magento/pwa-studio/pull/2547
