### ISSUE TITLE
[doc]:How to add custom route on express level - upward proxy

### ISSUE THREAD

**Issue by mercs600** [magento/pwa-studio#2552]
**Describe the request**
Hi, I would like to create custom endpoint on express server for robots.txt file - solution from venia it doesn't fit for us, because this is one static file and I need multiple configuration of robots per environment. 
Generally I have stuck. There is no problem to express config, but what should I setup in upward.yml to allow connect to node server directly ? 

My server.js with upward config 

```js
 const upwardServerOptions = Object.assign(
        // defaults
        {
            bindLocal: true,
            logUrl: true
        },
        config.section('upwardJs'),
        stagingServerSettings, // overrides upward options
        {
            env: process.env,
            before(app) {
                addImgOptMiddleware(app, {
                    ...config.section('imageOptimizing'),
                    ...config.section('imageService')
                });
                app.use(bestPractices());
                app.get('/robots.txt', function(req, res) {
                    res.sendStatus(200);
                    res.send('Test')
                });
            }
        }
    );
```

**Comment by jcalcaben** [comment]
@mercs600 
you may get the answer you need by posting this question in our community slack channel:

https://magentocommeng.slack.com/archives/C71HNKYS2

**Comment by TheRealHunzik** [comment]
Hello There @mercs600 & @jcalcaben 

do you have found any solution for this?
