### ISSUE TITLE
[bug]: Please reopen #2351

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2561]
There seem to be at least 2 comments indicating that https://github.com/magento/pwa-studio/issues/2390 is not a complete fix for https://github.com/magento/pwa-studio/issues/2351 - can we please reopen it.

**Comment by sirugh** [comment]
@fooman We lost track of this - do you have any idea if this is still an issue?

**Comment by fooman** [comment]
I suspect there could be, but it could also be my CDN settings masking something. Need to investigate.

I suspect it is an ongoing consideration with PWAs on how to force them to update and how to monitor I would suggest the following ideas as improvements for PWA Studio:

- implement some diagnostics being sent from each PWA build. Maybe modifying the user agent to include a build number/date if that doesn't interfere with anything else
- some way for the server to communicate that a forced update of the service worker is required

**Comment by fooman** [comment]
@sirugh There may now be another issue potentially masking this one. In recent months we have added default caching headers to static files served from a directory. This also applies to sw.js

![image](https://user-images.githubusercontent.com/455508/106830020-1bd51400-66f2-11eb-9f4a-98b637052537.png)

From my current understanding this would mean that even if the server has an updated sw.js the browser will only check in its local cache for seven days before getting the latest version.

**Comment by sirugh** [comment]
We investigated this a bit internally and found that while the `cache-control` header was present, the service worker was always being refetched. We did create an internal issue. https://jira.corp.magento.com/browse/PWA-1396, to remove the cache-control header from sw.js _just_ to be safe, but it looks like browsers don't respect the cache-control header on the sw file unless you explicitly tell it to. We will keep an eye on this going forward, but could we close this issue and re-open 2351 as you originally requested?

**Comment by fooman** [comment]
hey @sirugh not really concerned if this gets closed or the other reopened. Just glad to hear it is on your radar. This discussion https://github.com/GoogleChrome/workbox/issues/1528#issuecomment-443228522 seems to indicate that cache-control headers on sw.js can be an issue.
