### ISSUE TITLE
[feature]: CSS with jpg files

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2563]
**Is your feature request related to a problem? Please describe.**
`background-image: url("./bg_image.jpg");` should just work. Webpack already places them into the root folder as well as adds them to the assets-manifest.json. From there they aren't accessible as they are missing an upward entry. It works when using the webpack dev server.

**Describe the solution you'd like**
#2562

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Created PWA-772
