### ISSUE TITLE
[feature]: Customer account - Newsletter Subscription

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#2570]
**Is your feature request related to a problem? Please describe.**
The customer account functions are necessary in PWA Studio, while Newsletter Subscription page is one of them.

**Describe the solution you'd like**
Define new Magento route in PWA Studio

**Additional context**
I will submit a PR, so this issue is just for reference.

## Story Description
Sign up for email/newsletter 

Design should account for sign up and managing opt-in/out not only in the "my account" section but also a general sign up form that could be located in a header/footer/content page

**Note**: Mocks seem to call for multiple Newsletter subscriptions but it seems the GraphQL response as of 2.4.0 only supports the single newsletter tied to `is_subscribed`. 

## Mocks
Desktop:
![M_Venia_Account_Communications_changesToSave_02](https://user-images.githubusercontent.com/462953/88405899-809fd100-cd95-11ea-8777-46e302111c51.png)
Mobiles:
![M_Venia_Account_Communications_changeToSave_02](https://user-images.githubusercontent.com/462953/88405900-81386780-cd95-11ea-8ff3-74a54df7b6b3.png)

Here are mocks of where you would find this link now as well; the Account menu has changed in this Epic.

![Venia_Home_AuthAcct_Menu_04](https://user-images.githubusercontent.com/462953/88406073-c3fa3f80-cd95-11ea-8c7e-db5496afe3ce.png)
![M_Venia_AcctMenu_04](https://user-images.githubusercontent.com/462953/88406085-c6f53000-cd95-11ea-8433-c005fc097415.png)

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by huykon** [comment]
@magento I am working on this

**Comment by huykon** [comment]
@magento add to contributors team

**Comment by tjwiebell** [comment]
@huykon - We appreciate the feature request and quick PR, but you need to check in with in an internal team member before you pick up feature work that isn't groomed and prioritized on the [Community Board](https://github.com/magento/pwa-studio/projects/3). This does not adhere to the mocks we have for this feature, and we also have a lot of My Account work in flight that is going to change how this view functions (#2550 is the first PR up for this epic that the whole team has started working on).

Given that this view is pretty close, I'm going to see what I can do about letting the Community own this Story, but I can't make any promises. If there are any other features you're interested, please let us know, and we'll do our best to make sure it doesn't overlap with work we already have in flight internally.

**Comment by huykon** [comment]
@tjwiebell  Thanks for your response.

**Comment by tjwiebell** [comment]
@huykon - if you're willing to iterate on this a little bit, @awilcoxa has agreed to let you own this feature. Tomorrow morning I'll attach some mocks to follow, as well as some implementation guidance; and will give an initial pass through your PR. You might be blocked on some requirements given this Story's position in the Epic, but I'll try to break off what's ready to go. If you have any questions I'm available on the Community Slack.

**Comment by huykon** [comment]
@tjwiebell Thank you. I hope to contribute this feature and my ideas for magento PWA Studio. I always here and Community Slack to see your and team core responding.

**Comment by awilcoxa** [comment]
Linked to PWA-285
