### ISSUE TITLE
[bug]: Server Response Error on Venia Demo App

### ISSUE THREAD

**Issue by andhikaribrahim** [magento/pwa-studio#2581]
**Describe the bug**
The API calls returns 500 error on https://venia.magento.com as its backend URL pointing to this address: https://jnz3dtiuj77ca.dummycachetest.com/

It seems like the backend URL is blocked by CORS policy

**To reproduce**
1. Go to https://venia.magento.com
2. Open Browser Console, see errors on console/network tabs.

**Expected behavior**
Backend URL shouldn't blocked by cors

**Screenshots**
![Screenshot from 2020-07-28 15-38-15](https://user-images.githubusercontent.com/12978835/88640636-5ed18180-d0e8-11ea-9ea7-eb045a855528.png)

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
@andhikaribrahim can you still reproduce this issue?

**Comment by andhikaribrahim** [comment]
@awilcoxa nope, it looks good now. Closing issue, thank you!

**Comment by bilalyaqoob** [comment]
how to fix this issue?
