### ISSUE TITLE
[bug]: Sticky register form at Receipt screen is overwritten by footer on resolution 1440px

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#2586]
**Describe the bug**
[Desktop resolution: 1440x900] After place order with guest successfully. At the Receipt screen, scroll page to the bottom the we found the right register form is overwritten by footer.

**To reproduce**
1. Add product to cart
2. Go to checkout page
3. Fill all required fields and Place order
4. At Receipt screen, scroll to bottom 
5. See error in the right page

**Expected behavior**
Fill background for register form section or make it bellow the footer.

**Screenshots**
<img width="1427" alt="Screen Shot 2020-07-29 at 3 31 55 PM" src="https://user-images.githubusercontent.com/9253798/88780452-3794b600-d1b5-11ea-8f56-88195e664bfd.png">

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Macbook
 - OS [e.g. iOS8.1, Windows 10]: MacOS 10.14.6
 - Browser [e.g. Chrome, Safari]: Chrome 
 - Browser Version [e.g. 22]:
 - Magento Version: 2.4
 - PWA Studio Version: 7.0.0
 - NPM version `npm -v`: 6.9.0
 - Node Version `node -v`: v10.16.0

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by huykon** [comment]
@magento I am working on this

**Comment by tjwiebell** [comment]
We recently picked this up internally, and should be resolved by #2582.

**Comment by huykon** [comment]
@tjwiebell  Ok. Thanks
