### ISSUE TITLE
incomplete guide with pwa-studio publish on server

### ISSUE THREAD

**Issue by prakashsaran** [magento/pwa-studio#2589]
hi Team i all most step complete developent,
now i have issue with 
How to publish my pwa website on server ?
i`m searching on google from 5 days. i couldn`t found any solution.
Please me with this issue 😫  😫. 😫. 😫. 😫  😫  😫

**Comment by sirugh** [comment]
Closing as this is a question - in the future use the discussions tab or the public slack, thanks!
