### ISSUE TITLE
Custom Route not found error on PWA

### ISSUE THREAD

**Issue by sruthitechfriar** [magento/pwa-studio#2597]
I need to create a custom route in PWA and i followed below documentation

https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/add-a-static-route/

but I'm getting "That page could not be found. Please try again." error.

- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Created PWA-823 to validate the existing tutorial

**Comment by larsroettig** [comment]
Can be closed tutorial is updated and works

**Comment by larsroettig** [comment]
@sruthitechfriar is updated 
Thank you for your contributions

kind regards, 

Lars

------- 
Magento PWA Community Team
