### ISSUE TITLE
.env missing?

### ISSUE THREAD

**Issue by wdhrudra** [magento/pwa-studio#2603]
Hi, 

In this new git clone, "packages/venia-concept/.env" is missing? or anything modified?

Kindly update me.

**Comment by Jordaneisenburger** [comment]
Hi,

If you want to work with the monorepo you need to run `yarn prepare` from root. This will prepare the packages and create a .env file for you to use. After that you can run the watch command `yarn watch:venia`

**Comment by awilcoxa** [comment]
closing issue. @wdhrudra if you have any additional questions please follow up.
