### ISSUE TITLE
Liaison pwa-studio et magento2.3.5

### ISSUE THREAD

**Issue by jaballah-dorsaf** [magento/pwa-studio#2604]
bonjour ,
j'ai installé magento2.3.5 dans Ubuntu 16.04 et pwa-studio 6.0.1 mais j'ai un problème comment je peut faire la liaison entre pwa-studio et magento2 .
merci

**Comment by Jordaneisenburger** [comment]
Hi @jaballah-dorsaf,

If you have any questions, issues, or suggestions, please join the #pwa Slack channel at magentocommeng.slack.com or take a look at https://magento.github.io/pwa-studio/

ps: keep it english
