### ISSUE TITLE
[feature]: Customer account - Account Information

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#2613]
**Is your feature request related to a problem? Please describe.**
The customer account functions are necessary in PWA Studio, while Edit Account Information page is one of them.

**Describe the solution you'd like**
Define new Magento route in PWA Studio

**Additional context**
I will submit a PR, so this issue is just for reference.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by huykon** [comment]
@magento I am working on this

**Comment by tjwiebell** [comment]
@huykon We are working on this Story internally as part of the My Account epic in progress, so please hold off on this. I'm going to work on funneling some more feature work into the [Community Backlog](https://github.com/magento/pwa-studio/projects/3), but I think #2276 could be a good next feature for you if you're interested. Mocks are in the comments.
