### ISSUE TITLE
[feature]: offline add to cart?

### ISSUE THREAD

**Issue by mattmast** [magento/pwa-studio#2617]
**Is your feature request related to a problem? Please describe.**
I'm not sure if it's possible, but is there capability of adding to the cart while offline.  If not any suggested approaches? I tried joining the slack channel to ask but don't have the right email domain. It would be nice if I could add to the cart without a requiring a network connection.

**Describe the solution you'd like**
...

**Describe alternatives you've considered**
...

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Hi @mattmast as of now we haven't specifically included a method for offline add to cart but will explore doing so in a future epic (offline add to cart is one of the primary use cases for the upcoming epic). We are planning on revisiting online/offline capabilities later this year (see roadmap) so stay tuned! I'll close this request out for now.
