### ISSUE TITLE
[doc]: Custom footer not success render

### ISSUE THREAD

**Issue by mrtuvn** [magento/pwa-studio#2623]
**Describe the request**
run the scaffolding
Follow this doc but after the end i can't render page. We should update this doc too
https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/modify-site-footer/

**Possible solutions**
How would you word this addition or change?

**Screenshots**
If applicable, add screenshots to help explain the problem.
Compile success, but browser render blank white page

<img width="1771" alt="Screen Shot 2020-08-13 at 17 31 53" src="https://user-images.githubusercontent.com/1908873/90124640-f0005380-dd8a-11ea-91a8-900ee9d9c13f.png">

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by larsroettig** [comment]
@magento I am working on this

**Comment by mrtuvn** [comment]
@larsroettig i found missing minicart import
in file src/components/App/app.js
import MiniCart from '@magento/venia-ui/lib/components/MiniCart';

**Comment by larsroettig** [comment]
@mrtuvn This tutorial from point of view updated should be removed is not good praxis to overwrite 3 components to get a different Footer

**Comment by mrtuvn** [comment]
thanks for your response. But i think we should update content (correct some wrong path) and possible add some related links for new guys

**Comment by larsroettig** [comment]
@jcalcaben what do think we should mark this Tutorials as outdated or remove the outdated tutorials I don't like that we referencing not good approaches in official docs

**Comment by jcalcaben** [comment]
I agree. Outdated tutorials are not a good developer experience. I try to identify and update content as they become outdated, and I also appreciate the community's help with this. I'm happy work with anyone who wants to help fix our docs.

**Comment by awilcoxa** [comment]
Created PWA-863
