### ISSUE TITLE
[doc]: Add a static route should be update to extensibility framework

### ISSUE THREAD

**Issue by larsroettig** [magento/pwa-studio#2624]
**Is your feature request related to a problem? Please describe.**
The site: 
https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/add-a-static-route/

Should be updated to https://github.com/magento/pwa-studio/blob/release/7.0/CHANGELOG.md#extensibility-framework

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by larsroettig** [comment]
@magento I am working on this

**Comment by awilcoxa** [comment]
Created PWA 864
