### ISSUE TITLE
[bug]: ERR_INVALID_PROTOCOL

### ISSUE THREAD

**Issue by AmaanKulshreshtha** [magento/pwa-studio#2625]
I was following [this](https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/project-setup/) to setup the project. Now I am getting an 

`INVALID_PROTOCOL ERROR; Protocol "http:" not supported. Expected "https:"`

**Steps to reproduce the behavior:**

1. `yarn create @magento/pwa`
    1.1. For the question, magento instance to use as a backend, I put my local magento instance
    1.2. Url for that instance; http://localhost/magento
2. After completing the setup, enter the project dir
3. Run `yarn watch`

**Expected behavior**
This command should start the development server at http://0.0.0.0:10000/

**Please complete the following device information:**
 - Device : MBP 2018
 - OS : Mac OS Mojave
 - Magento Version: 2.3.5-p2
 - PWA Studio Version: latest
 - NPM version : 6.14.5
 - Node Version : 14.3.0

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

**Comment by huykon** [comment]
That mean your magento url should be supported by https protocol.

**Comment by AmaanKulshreshtha** [comment]
I did try generating the certificate as given [here](https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/project-setup/#add-a-custom-hostname-and-ssl-cert), but that didn't work

Also the thing with the other #2170 is that it does not provide a solution for when the setup is done using the [scaffolding tool](https://magento.github.io/pwa-studio/pwa-buildpack/scaffolding/), and the scaffolding [project structure](https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/project-structure/) doesn't have this path: `pwa-studio/packages/pwa-buildpack/lib/Utilities/graphQL.js`.

**Comment by AmaanKulshreshtha** [comment]
Solved the issue by running the local magento instance with ssl. Closing this issue.
