### ISSUE TITLE
[doc]: Add Page Builder integration videos

### ISSUE THREAD

**Issue by bdenham** [magento/pwa-studio#2631]
**Describe the request**

This issue's PR adds the long lost Page Builder videos to the overview page of the Page Builder integration docs.

**Possible solutions**
Done in PR #2632 

**Screenshots**

![image](https://user-images.githubusercontent.com/1828494/90339061-e9a0f000-dfb3-11ea-968b-1d52128056f9.png)

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [x] Topic Change Request (ie. spelling, organization)

**Comment by bdenham** [comment]
@magento I am working on this

**Comment by awilcoxa** [comment]
Created PWA-867
