### ISSUE TITLE
[bug]: Category didn't refresh data when click back previous or next page of browser

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#2638]
**Describe the bug**
Click to an category have more than 1 page in left navigation, then click to page 2 of this category. After that, click to back on browser (not at pagination at bottom)
<img width="1079" alt="Screen Shot 2020-08-18 at 12 00 54 PM" src="https://user-images.githubusercontent.com/9253798/90472387-93b28080-e14a-11ea-9826-8509846602b0.png">
The data of page 1 is not loaded.

**To reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]: Chrome Version 84.0.4147.125
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by huykon** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
Took a screen capture of the issue:

[![Image from Gyazo](https://i.gyazo.com/c55cfc262136ee68e5a26ac7c8305bf7.gif)](https://gyazo.com/c55cfc262136ee68e5a26ac7c8305bf7)

**Comment by awilcoxa** [comment]
Created PWA-870, prioritizing for review
