### ISSUE TITLE
[feature]: Validate Widget Template 

### ISSUE THREAD

**Issue by lano-vargas** [magento/pwa-studio#2639]
**Not sure this is already implemented so I'm just assuming is a feature request.**

**Is your feature request related to a problem? Please describe.**
I have set it up PWA with my custom instance Backend Url in my home I have a widget for a product list and get invalid template.

`Error filtering template: Invalid template file: 'product/widget/content/grid.phtml' in module: 'Magento_CatalogWidget' block's name: 'product\productslist_0' `

**Describe the solution you'd like**
Capability to load widget templates in CSM,CATEGORY,PRODUCT pages.

**Describe alternatives you've considered**
I've considered striping out widget if not supported.

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
Created PWA-871
