### ISSUE TITLE
[feature]: Support configured URL suffix across entire app

### ISSUE THREAD

**Issue by tjwiebell** [magento/pwa-studio#2644]
**Is your feature request related to a problem? Please describe.**
As a developer using PWA Studio, there's too many manual code changes required to support cleaner looking URLs that don't contain a hard-coded `.html` suffix. If all URLs were driven by configuration, I could simply just update my configuration in the backend to get the URL behavior I want. 

**Describe the solution you'd like**
- Audit all places in the app that are currently hard-coding `.html` as a suffix (doing a code search for that string should be suitable enough to find all components that need fixed).
- Additionally, components that have already started using this configuration appear to have made a bad assumption about the response from GraphQL. It seems removing the suffix in the backend will result in `null` being returned, instead of an empty string, which is triggering some non-truthy logic and falling back to hard-coded suffix value. eg. [useBreadcrumbs](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/Breadcrumbs/useBreadcrumbs.js)

**Additional context**
We don't have a great solution for sourcing config once at the app root with mechanisms for busting the cache on value change, so it's reasonable for each component to query for this config as needed for now.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by huykon** [comment]
I think GraphQl `storeConfig` should be called to get config from backend

**Comment by fooman** [comment]
Just to note the suffix can be configured independently for category and product pages in the admin.

**Comment by awilcoxa** [comment]
Created PWA-872
