### ISSUE TITLE
[bug]: Searching product

### ISSUE THREAD

**Issue by ArunKathir98** [magento/pwa-studio#2648]
**Describe the bug**
While entering product name on search field . It displays list of keyword products and when i am clicking 
**To reproduce**
1. Go to 'search product'
2. Click on 'product keyword' then enter and it list products
3. Scroll down to 'click on any products'

**Expected behavior**

**Screenshots**

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

![image](https://user-images.githubusercontent.com/43820797/90894610-857c9280-e3de-11ea-896b-15def98c4a27.png)

![image](https://user-images.githubusercontent.com/43820797/90894689-a04f0700-e3de-11ea-8870-2171e9ac29d2.png)

**Comment by ArunKathir98** [comment]
> I'm not sure I understand the issue here - can you add a video of the problem?
> 
> On develop.pwa-venia.com I searched for "shirt" and clicked both the product suggestion but also the entry "shirt in Tops" and neither resulted in an error.

When i am pointing to cloud  back end URL it is working fine, but if i changed URL to magento local back-end it shows above error.

**Comment by larsroettig** [comment]
@ArunKathir98 I can not reproduce this issue maybe something with your local instance.

I close this issue pls reopen with better steps to reproduce.

kind regards, 

Lars
