### ISSUE TITLE
[doc]: A short, simple sentence describing the doc request

### ISSUE THREAD

**Issue by luke-denton-aligent** [magento/pwa-studio#2661]
**Describe the request**
The upgrade instructions in the README for people who have npm packages as dependencies isn't as clear as it could be. The suggestion in the README essentially says to manually edit the `package.json` file, which I think adds unnecessary risk of breaking things

**Possible solutions**
Update the README.md upgrade instructions to provide a simple command that can be run, that will both update the `package.json` automatically, as well as installing the latest version of the packages

**Please let us know whether this is a new topic or a topic change request:**
 - [x] Topic Change Request (ie. spelling, organization)

**Comment by luke-denton-aligent** [comment]
@magento I am working on this

**Comment by awilcoxa** [comment]
Added to PWA-883
