### ISSUE TITLE
[feature]: My Account: Account Information

### ISSUE THREAD

**Issue by tjwiebell** [magento/pwa-studio#2668]
## Description
As a shopper, I want to see all associated information for my account so that I can view/edit/delete data (contact info, billing, address, etc.) saved to my profile. 

In-scope:

Create the page for my account information with all necessary components for both desktop and mobile views.

My Account page, should include (components or  links for) : 
* Name
* Email
* Password
  * Change Password

## Implementation Guidance
* Use the `Dialog` component for the edit views
* Redirect to Home Page if user is not signed in
* Look at recent implementations of Order History for examples of data fetch/loading/error states (!data + loading = full page loading indicator, data + loading = page header loading indicator, fetch error = "Something went wrong. Please refresh and try again.")
* Use `FormError` component for edit dialog errors from mutations, should be at the top of the form and prevent dialog from closing
* I don't see guidance on any confirmation messages on successful save, so just close the dialog and render the new data. Existing patterns outline that your mutation should return the same fragment rendered on the read-only view, but we'll need to experiment with fetch policies to see the best way to make this work, given Account Info doesn't change much. I would probably want to see `fetchPolicy: 'cache-and-network'` and `nextFetchPolicy: 'cache-only'` for now.

## Mocks

note: `Forgot Password?` links can be ignored, we're going to defer that feature for now.

### Desktop
Default View
![DT_Venia_AcctInfo_01](https://user-images.githubusercontent.com/462953/91766576-68934c80-eba0-11ea-9844-98a931b699c3.png)

Edit Dialog
![DT_Venia_AcctInfo_Edit_modal_02](https://user-images.githubusercontent.com/462953/91766685-94163700-eba0-11ea-94d8-c8e5d4591acd.png)

Edit Dialog (Change Password Active)
![DT_Venia_AcctInfo_ChangePassword_modal_03](https://user-images.githubusercontent.com/462953/91766625-7d6fe000-eba0-11ea-9def-eacef94ead38.png)

### Mobile
Default View
![M_Account_Info_Read_01](https://user-images.githubusercontent.com/462953/91766722-a3958000-eba0-11ea-928d-c75e66d23a7e.png)

Edit Dialog
![M_Account_Info_Edit_02](https://user-images.githubusercontent.com/462953/91766742-ac865180-eba0-11ea-9c92-6e4f6edc3aa0.png)

Edit Dialog (Change Password Active)
![M_Account_Info_ChangePassword_03](https://user-images.githubusercontent.com/462953/91766787-bd36c780-eba0-11ea-83b0-5b8cc83def73.png)

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by tjwiebell** [comment]
@magento assign to @huykon

**Comment by huykon** [comment]
@magento I am working on this. Thanks @tjwiebell
