### ISSUE TITLE
[bug]: Filter and Sort buttons should display at same time

### ISSUE THREAD

**Issue by tjwiebell** [magento/pwa-studio#2677]
**Describe the bug**
URL - https://develop.pwa-venia.com/

Steps -
1. Go to any category and observe button display

Expected - Sort and FIlter buttons should display at sametime.
Actual - Sort button displays first and then Filter.

Note - Looks like it does work on Search page.

Suggestion - (Stephen Rugh)
The filter data is based on a query but the data is passed as a prop. We could wait for the filter query to resolve before rendering.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by tjwiebell** [comment]
Linked to internal JIRA [PWA-751](https://jira.corp.magento.com/browse/PWA-751).

**Comment by huykon** [comment]
@magento I am working on this
