### ISSUE TITLE
[bug]: Zip does not get cleared on switching country

### ISSUE THREAD

**Issue by tjwiebell** [magento/pwa-studio#2678]
**Describe the bug**
URL - https://develop.pwa-venia.com/

Steps -
1. Add product to Cart and go to /cart page
2. Enter shipping details for USA and get available shipping methods.
3. Now change the country

Expected - State/Region and Zip should get cleared And Get Shipping Options button should displayed.
Actual - Zip does not get cleared.

Note -
1. This needs UX review. Attached screen has actual and expected UI.
2. Also Check if say user goes back to already selected country then show results instead of again showing "Get Shipping Options" button.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by tjwiebell** [comment]
Linked to internal JIRA issue [PWA-672](https://jira.corp.magento.com/browse/PWA-672).

**Comment by huykon** [comment]
@magento I am working on this
