### ISSUE TITLE
[feature]: Replace ProductQuantity on Product Page with QuantityFields stepper

### ISSUE THREAD

**Issue by tjwiebell** [magento/pwa-studio#2679]
### Description
The quantity selector on PDP and cart don't currently match either in the way they look or in the way they behave.

The cart stepper is the latest design, and the quantity selector on PDP should be updated to match this.

### Acceptance Criteria
- ProductQuantity is deprecated and replaced with quantity stepper component currently on CartPage (you will want to use `QuantityFields`, much like the product edit usage)
- Unit tests are updated to reflect expected view changes
- (Optional) The quantity stepper is probably general use enough that it can be moved to the components directory so it becomes API. Discuss with @tjwiebell if interested in this re-factor. 

### Internal JIRA Links
* [[PWA-591](https://jira.corp.magento.com/browse/PWA-591)] Replace quantity selector on PDP to match cart stepper

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by huykon** [comment]
@magento I am working on this

**Comment by awilcoxa** [comment]
Linked to JIRA [PWA-918](https://jira.corp.magento.com/browse/PWA-918)
