### ISSUE TITLE
Feedback on page: /venia-pwa-concept/component/add-to-wishlist/

### ISSUE THREAD

**Issue by larsroettig** [magento/pwa-studio#2682]
Outdate or needs to implement?

**Comment by larsroettig** [comment]
@jcalcaben

**Comment by jcalcaben** [comment]
This is really old content that shouldn't be published anymore. This and other topics under `/venia-pwa-concept/component` should be deprecated and removed.

**Comment by larsroettig** [comment]
Can be close is done by #2682
