### ISSUE TITLE
[feature]: Create a hook for createAccount's signIn

### ISSUE THREAD

**Issue by jpmii** [magento/pwa-studio#2713]
**Is your feature request related to a problem? Please describe.**
I wanted to wrap all talons that dealt with a user signing into their account. I noticed when someone registers a new account it logs them in. I attempted to wrap createAccount/useCreateAccount.js's handleSubmit > signIn. I was able to wrap createAccount/useCreateAccount.js's handleSubmit just fine but couldn't capture that actual signIn event.

**Describe the solution you'd like**
I spoke to @zetlen and he mentioned creating a hook for useSignIn and move the mutation behind that.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [X ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
@jpmii can you provide any extra details about why you were unable to capture the signin event? I was hoping something like [this](https://github.com/magento/data-services-pwa-recs/pull/16/files#diff-68d33e0c399fa21053752c4d6332f845R41-R43) would work for you, as it is the expected approach. If it's not working, I'd like to know why.

**Comment by jpmii** [comment]
@sirugh I had a debugger on the createAccount/useCreateAccount/handleSubmit talon and the signIn/useSignIn talon. When creating an account the page logged in before the debugger was triggered so I couldn't capture the event. This was a few months ago so I'm not sure if something changed since then.

**Comment by sirugh** [comment]
Ah, well I think the new extensibility api should suffice so I'm going to close this for now. If you find a need for this again, and are unable to accomplish it with the extensibility api, please re-open a ticket and we will investigate further :)
