### ISSUE TITLE
[discussion] i18n ID format

### ISSUE THREAD

**Issue by davemacaulay** [magento/pwa-studio#2720]
We have started our implementation of `react-intl`, part of it's API requires an ID within the code to identify which string you wish to present on the page in the users designated language. We've identified the need to define the format of these ID's and we've formed 2 potential solutions.

## Use `en_US` version of string 
The first option aligns with the translation implementation of Magento Core, and looks to utilize the English version of the string as the ID.

**Component:**
```js
<FormattedMessage id={'Translated string'} defaultMessage={'Translated string'} />
```
**en_US.json**
```json
{
    "Translated string": "Translated string"
}
```

### Pros:
- Familiar to existing Magento developers.

### Cons
- Identical strings in different contexts would be translated to the same string.

## Generate ID's based on the component purpose / context
This option uses more computer friendly ID's to identify which string we want to present in the UI.

**Component:**
```js
<FormattedMessage id={'component.translatedString'} defaultMessage={'Translated string'} />
```
**en_US.json**
```json
{
    "component.translatedString": "Translated string"
}
```

### Pros:
- Provides unique identifiers for all strings regardless of their location / context.
- Enables languages where context changes language to correctly translate phrase. 

### Cons:
- Results in potential duplication of strings within locale pack if the strings translation is identical. _(could be potentially resolved with build time optimization of duplicated strings)._

**Comment by sirugh** [comment]
I kinda prefer this issue rather than holding the convo within the #669 PR but its too late!

**Comment by plamenh** [comment]
@davemacaulay what was the final decision here? I am ready to take the initiative and localize all jsx files. I would vote for the ids (much easier to reuse ids in components, e.g. label.checkout.agreement.question is much easier  to remember (and type) than ‘Do you agree with ...’). Plus, IDs give the possibility of sorting the translation files and having all related strings one next to the other (better context). 

Finally, if IDs are chosen, we need to decide on the logic of strings (e.g., label.checkout vs checkout.label).
