### ISSUE TITLE
[bug]: Minicart is missing on /checkout

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#2733]
**Describe the bug**
When you go to /checkout you are not able to edit your cart. I'm aware this is done on purpose probably for the reason of the "no distractions in checkout" rule. But In that case I feel you either need to minimize the whole header or keep the minicart trigger in the header. Pretty sure most agencies are gonna swap it back anyway.

This is for example how we've done it.
![Screenshot 2020-09-28 at 13 47 38](https://user-images.githubusercontent.com/19858728/94428649-5998bd80-0191-11eb-9e1e-77b86124c22a.png)

**To reproduce**
1. Add item to cart
2. Go to checkout
3. Try to edit your cart

**Expected behavior**
I'd expect there to be a option to edit my cart in the checkout.

**Screenshots**

**Additional context**

**Possible solutions**
Also show the minicart on the checkout page

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
As you already stated, we [intentionally hide](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/Header/useCartTrigger.js#L49-L51) the mini cart trigger on the checkout page. We went back and forth on it but I think the decision was honestly split. It would be trivial to add back but I think we need to consider the options such as:

a) hiding the entire header on /checkout
b) hiding all clickable/actionable elements from the header on /checkout

So I would not consider this a bug but a feature request. And for folks who want to display the mini cart trigger, they just need to extend the talon and always return `hideCartTrigger: false` or customize their component and ignore the boolean return from the talon.

**Comment by Jordaneisenburger** [comment]
Your right it should be a feature request since it was intentionally hidden. I personally don't see why removing this functionality would improve checkout experience. But then again I'm not a UX designer so if you guys have already had discussions about we can close this.
