### ISSUE TITLE
[bug]: function retreiveAvailableShippingMethods has wrong spelling

### ISSUE THREAD

**Issue by alitonia** [magento/pwa-studio#2743]
**Describe the bug**
Function ```retreiveAvailableShippingMethods``` in ```packages/peregrine/lib/store/actions/checkout/asyncActions.js``` has wrong spelling ( _retreive_ instead of _retrieve_)

**To reproduce**
1. Go to ```packages/peregrine/lib/store/actions/checkout/asyncActions.js```
2. Check on line 15 and 350.

**Expected behavior**
Method name is ```retrieveAvailableShippingMethods``` instead of ```retreiveAvailableShippingMethods```

**Screenshots**
![alt text](https://i.imgur.com/l1XI9P2.png)

**Possible solutions**
Rename 2 occurences at line 15 and 350.

**Please complete the following device information:**
 - Magento Version: 7.0

**Please let us know what packages this bug is in regards to:**
- [x] `peregrine`

**Comment by alitonia** [comment]
@magento I am working on this

**Comment by sathiyaaa** [comment]
@magento add to contributors team

**Comment by sathiyaaa** [comment]
@magento I am working on this
