### ISSUE TITLE
[feature]: Create new buildpack command `create-extension`

### ISSUE THREAD

**Issue by larsroettig** [magento/pwa-studio#2750]
**Is your feature request related to a problem? Please describe.**
As developer, I want to scaffold easily new PWA-Studio extensions. 

**Describe the solution you'd like**

For this would be a template the best approach. 
The template should contain the followings files and should create a standalone extension:

**package.json:**
```js
{
  "name": "{vendor-name/module-name}",
  "version": "0.0.1",
  "main": "src/index.js",
  "author": "{author}",
  "license": "",
  "pwa-studio": {
    "targets": {
      "intercept": "src/intercept.js"
    }
  },
  "scripts": {
    "prettier": "prettier --loglevel warn --ignore-path .gitignore 'src/**/*.@(css|graphql|js)' '*.js'",
    "prettier:check": "yarn run -s prettier -- --check",
    "prettier:fix": "yarn run -s prettier -- --write",
    "lint": "eslint --ignore-path .gitignore 'src/**/{*.js,package.json}'"
  },
  "peerDependencies": {
    "@magento/pwa-buildpack": ">=6.0.0",
    "react": "*",
  },
  "devDependencies": {
    "@magento/eslint-config": "latest",
    "babel-eslint": "~10.0.1",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^6.0.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-package-json": "^0.1.4",
    "eslint-plugin-react": "^7.9.1",
    "eslint-plugin-react-hooks": "^1.6.0",
    "prettier": "^1.9.2",
    "prettier-check": "^2.0.0"
  }
}
```

Example starter repo:
https://github.com/larsroettig/pwa-studio-extension-starter

    
**Describe alternatives you've considered**

**Additional context**
Do you need currently much detail knowable 

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by chris-brabender** [comment]
Great concept, something that could kickstart dev for some people for sure.

Would this maybe be better as a tool similar to 'npm create @magento/pwa' rather than a buildpack command? Ideally the extension would not reside in the project directory anyway?

**Comment by larsroettig** [comment]
https://github.com/larsroettig/create-pwa-studio-extension
