### ISSUE TITLE
[feature]: Add to Cart support for Virtual products

### ISSUE THREAD

**Issue by shikhamis11** [magento/pwa-studio#2768]
**Add to Cart support for Virtual products**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by shikhamis11** [comment]
#dmcdindia2020

**Comment by tjwiebell** [comment]
See https://github.com/magento/pwa-studio/pull/2769#issuecomment-712416440
