### ISSUE TITLE
[bug]: Clicking on Label should focus Input

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2773]
**Describe the bug**
Add a product to the cart, head to checkout. Clicking on any label should put the focus on the associated input.

**To reproduce**
1. add product to cart
2. navigate to checkout
3. click on Email
![image](https://user-images.githubusercontent.com/455508/95798784-571c9300-0d4f-11eb-81ed-52f9aaf35f5e.png)

**Expected behavior**
Keyboard focus on associated for input field

**Screenshots**
![image](https://user-images.githubusercontent.com/455508/95798830-73b8cb00-0d4f-11eb-9936-313a85eacba1.png)

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]: Chrome
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version: develop
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by tjwiebell** [comment]
@magento export issue to Jira project PWA as Story

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. GitHub repo magento/pwa-studio is not supported in JIRA project PWA and type Story.

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. GitHub repo magento/pwa-studio is not supported in JIRA project PWA and type Story.

**Comment by magento-engcom-team** [comment]
:x: Cannot export the issue. GitHub repo magento/pwa-studio is not supported in JIRA project PWA and type Story.

**Comment by huykon** [comment]
😮
