### ISSUE TITLE
How can I add social login links to the PWA

### ISSUE THREAD

**Issue by technikhil314** [magento/pwa-studio#2775]
I am using [miniorange sso login plugin](https://plugins.miniorange.com/magento-oauth-single-sign-sso) as I have to support SSO for PWA using our authentication server (using keycloak). How can I do it in PWA studio? Any help, link much appreciated. 

Can some one please remove bug label and add help wanted label. I am not able to do it.

**Comment by Jordaneisenburger** [comment]
Hi @technikhil314, This feels like a very specific question related to your setup. Best chance is asking the question in the #pwa slack channel.
