### ISSUE TITLE
How can I use the newest version of the pwa-studio?

### ISSUE THREAD

**Issue by Skavengerr** [magento/pwa-studio#2776]
I am using the release version, but I want to use version 8.0.0, what is the best way to do this?

**Comment by huykon** [comment]
@Skavengerr checkout [this](https://github.com/magento/pwa-studio/tree/release/8.0)

**Comment by tjwiebell** [comment]
Our pre-releases are tagged in GitHub and published to npm, so you can get them either of those ways (pull pre-release tag or update your package.json dependencies to pre-release package versions). We will be releasing alongside Magento core in a couple days, but there should be no functional difference besides version bumps w/o pre-release suffix.

Going to close this out as a general question. In the future, you can ask general questions in our [Slack channel](https://magentocommeng.slack.com/archives/C71HNKYS2), where the community would be glad to assist with questions like this.
