### ISSUE TITLE
[bug]: Data Fetch Error after going to <product>.html

### ISSUE THREAD

**Issue by fkrawczyk** [magento/pwa-studio#2784]
I have installed Magento 2.4 and Magento PWA Studio. Connected them in .env file 
_MAGENTO_BACKEND_URL=https://magento-b2c.localhost/_

Everything works as it should but cannot access product page.

![image](https://user-images.githubusercontent.com/72493812/96262749-838c1580-0fc2-11eb-82dc-97c97c376fd0.png)
![image](https://user-images.githubusercontent.com/72493812/96262775-8be45080-0fc2-11eb-8dbc-e244bfb5e159.png)

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by Jordaneisenburger** [comment]
You wanna check the chrome console and check the network tab as well. There might be an internal server error coming back from graphQL due to mismatch in schema's.

**Comment by fkrawczyk** [comment]
> You wanna check the chrome console and check the network tab as well. There might be an internal server error coming back from graphQL due to mismatch in schema's.

Hi, thanks for feedback
![image](https://user-images.githubusercontent.com/72493812/96564422-6f4a6000-12c3-11eb-8414-f47f1d560872.png)

Config element \"ImageSwatchData\" is not declared in GraphQL schema

seeing this error doesn't really help me, still no idea how to fix :(

**Comment by Jordaneisenburger** [comment]
What version of PWA Studio are you on and what version of Magento are you using. There seems to be a mismatch between Magento and PWA studio versions.

**Comment by fkrawczyk** [comment]
Magento 2.3.4
PWA Studio 8.0

Just found [Magento compatibility](https://magento.github.io/pwa-studio/technologies/magento-compatibility/)
Thanks, gonna update Magento to 2.4 and check if it's working then!

**Comment by Jordaneisenburger** [comment]
Yeah you need to upgrade indeed.

**Comment by fkrawczyk** [comment]
It's working now, thank you!
