### ISSUE TITLE
[bug]: create-pwa installs old version

### ISSUE THREAD

**Issue by 1200rist** [magento/pwa-studio#2790]
**Describe the bug**
`yarn create @magento/pwa` installs pwa-studio 7.0, not 8.0.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [X] `create-pwa`

**Comment by Jordaneisenburger** [comment]
Hi @1200rist, 

I think you're running into yarn cache so you might want to clean that. Also it might be confusing but some packages are at v7.x.x this doesn't mean it's pwa studio version 7.0.

**Comment by 1200rist** [comment]
I ran `yarn cache clean , but it still installs the old version. Tried on a different computer and it installed the correct version. Either yarn cache clean doesn't work or there's some other cache somewhere.

**Comment by Jordaneisenburger** [comment]
Mhh not sure why this happens to you, seems like something just happening on your machine and not related to PWA Studio itself.
