### ISSUE TITLE
[feature]: Re-factor Edit Product to use Dialog

### ISSUE THREAD

**Issue by tjwiebell** [magento/pwa-studio#2797]
### Description
Re-factor the Edit Product component on the CartPage to use the Dialog component. This will ensure that all modals and dialogs in the app have a consistent look at feel.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by Frodigo** [comment]
@magento I’m working on it

**Comment by Frodigo** [comment]
@magento I am working on this
