### ISSUE TITLE
[feature]: Update manifest with new Venia theme/background color

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#2802]
**Is your feature request related to a problem? Please describe.**
Manifest needs to be updated to reflect the new Venia brand/design refresh. This is currently orange and not blue.

**Describe the solution you'd like**
Replacement of theme_color and review of others in manifest so that it appears correctly in app. Color should be HEX #1F39FF / RGB: 31 57 255. 

**Describe alternatives you've considered**

**Additional context**

![2020-10-21_14-14-16](https://user-images.githubusercontent.com/2686596/96771789-cc1f4680-13a7-11eb-83f6-c0cfb665a402.png)

**Please let us know what packages this feature is in regards to:**
- [X] `venia-concept`
- [X] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by huykon** [comment]
@magento I am working on this
