### ISSUE TITLE
[feature]: Auto-suggest installation of "Add to Home" for Venia

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#2803]
**Is your feature request related to a problem? Please describe.**
Early version of Venia included an option to "add to home" and splash screen which is common for PWA. Please see Starbucks example as a reference. Functionality is mostly done and can be seen/tested on Android devices.

**Describe the solution you'd like**
Configuration (manifest?) to suggest "add to home" upon first visit of Venia. This is no longer happening. As a reference, Venia should have this functionality and ability to turn off by configuration.

**Describe alternatives you've considered**
None.

**Additional context**

![image](https://user-images.githubusercontent.com/2686596/96772547-e574c280-13a8-11eb-9fd6-0f05e03ce2ba.png)

**Please let us know what packages this feature is in regards to:**
- [X] `venia-concept`
- [X] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
I definitely saw this recently on develop.pwa-venia.com. Maybe it is caching the response and not asking again?

**Comment by huykon** [comment]
Like @sirugh comment, I saw A2H popup always show on android browsers when we come the website at the first time. Unfortunately, the browser on IOS have not support A2H so we could not found it.

**Comment by sirugh** [comment]
Just checked on venia.magento.com after the latest release on my mobile Chrome browser. Rendered!
