### ISSUE TITLE
[feature]: Add "maskable icon" to Venia for Google Lighthouse [PWA]

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#2804]
**Is your feature request related to a problem? Please describe.**
Recent changes to Google Lighthouse v6 require a "maskable icon" as a proper PWA. 

**Describe the solution you'd like**
Venia icon needs to be added to the manifest. SVG image for Venia is attached. This request should involve fixing the manifest and verifying with Google Lighthouse and addresses the requirements in PWA-959. 

**Describe alternatives you've considered**

**Additional context**

![2020-10-01_08-18-08](https://user-images.githubusercontent.com/2686596/96773079-a6933c80-13a9-11eb-97e0-3f6670a5e778.png)

[venia-logo.svg.zip](https://github.com/magento/pwa-studio/files/5418323/venia-logo.svg.zip)

**Please let us know what packages this feature is in regards to:**
- [X] `venia-concept`
- [X] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by larsroettig** [comment]
![maskable_icon (2)](https://user-images.githubusercontent.com/5289370/96992070-a6ba4600-1529-11eb-8a7c-e58e2bba77e7.png)

**Comment by konarshankar07** [comment]
@magento I'm working on this
