### ISSUE TITLE
[feature]: Improved Windows local development support for PWA Studio

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#2810]
**Is your feature request related to a problem? Please describe.**
Windows local development (often using Docker) and troubleshooting PWA Studio is reported as more challenging than other environments. This feature request intends to improve this experience with help from those familiar with it.

**Describe the solution you'd like**
Review, analysis and suggestions (vis PR) to improve the Windows local development experience to match other environments. Teams primarily work in UNIX-based environments including Darwin (MacOX) and others.

**Additional context**
Improvement of the Windows local development experience will help adoption and lower TCO/TTM for new projects.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Much has changed since we last attempted to fix this, but #898 and #899 _may_ have some helpful info.

**Comment by CallMeSudhanshu** [comment]
@sirugh @ericerway what is the progress on this issue ? the windows development environment still seem to have issues related to webpack and other compilation issues in the latest develop branch
