### ISSUE TITLE
PWA Studio 4.0 Release : Request Timeout when exceed more than 2 minutes

### ISSUE THREAD

**Issue by vijaythummar** [magento/pwa-studio#2845]
**Describe the bug**
If any API request exceeds more than 2 minutes than I am getting gateway timeout error. It could be issue of default timeout configuration of nodeJS.

**Expected behavior**
There should be no timeout.

**Possible solutions**
There should be no timeout or How I can increase timeout value to 5 minutes?

**Please complete the following device information:**
 - Device: PC
 - OS : Windows 10
 - Browser [e.g. Chrome, Safari]: Chrome
 - Browser Version : Version 86.0
 - Magento Version: 2.3.3
 - PWA Studio Version:  4.0
 - NPM version `npm -v`:
 - Node Version `node -v`: 10.x

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [X] `venia-ui`
- [ ] `pwa-buildpack`
- [X] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by huykon** [comment]
try this: https://github.com/apollographql/apollo-client/issues/1751

**Comment by vijaythummar** [comment]
> try this: [apollographql/apollo-client#1751](https://github.com/apollographql/apollo-client/issues/1751)

Thanks Huy Kon, 
But I am not sure how that will help? As far I know PWA4.0 uses windows Fetch API for request. 
Where I can change timeout in appllo client?

Regards,
Vijay

**Comment by vijaythummar** [comment]
I have fixed issue by updating proxy settings of upward.

Thanks.
