### ISSUE TITLE
Connect Magento 2.3.5-p2 with Magento PWA studio 8

### ISSUE THREAD

**Issue by MichalMichniewiczEpoint** [magento/pwa-studio#2849]
I need connect Magento 2.3.5-p2 with Magento PWA studio 8. What can be processed to make it work?

**Comment by huykon** [comment]
Magento pwa studio 8 supported the lowest magento version 2.40. You can see the compatible version of pwa studio [here](https://github.com/magento/pwa-studio/blob/b38e983f9e62223313304160c27def84f795d556/magento-compatibility.js#L7)

**Comment by irajneeshgupta** [comment]
@MichalMichniewiczEpoint i had similar issue with my magento store and in my case it was klarna payment was causing some issue.

you may easily debug it by viewing in `packages/pwa-buildpack/lib/Utilities/graphQL.js:32`

Body :

`{"query":"query availableStoresConfigData {\n    availableStores {\n        code\n        id\n        store_name\n        default_display_currency_code\n    }\n}\n"}`

Response should be like this: 
`{
    "data": {
        "availableStores": [
            {
                "code": "default",
                "id": 1,
                "store_name": "Default Store View",
                "default_display_currency_code": "USD"
            }
        ]
    }
}`

**Comment by sirugh** [comment]
As @huykon pointed out, 2.3.5 is compatibile with PWA Studio v7. Please upgrade your backend according to the compatibility matrix.
