### ISSUE TITLE
[doc]: Scaffolded project i18n intercept

### ISSUE THREAD

**Issue by 1200rist** [magento/pwa-studio#2851]
**Describe the request**
There's no example of how to add translation files in your scaffolded project. I haven't found a way of doing it with targets, only by importing my own localeProvider in the App component.

**Possible solutions**
Add a section for describing how to add translations to your base package without modifying venia-ui files.

**Please let us know whether this is a new topic or a topic change request:**
 - [X] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by jcalcaben** [comment]
@1200rist 
this topic provides an overview of how the i18n feature works: https://magento.github.io/pwa-studio/technologies/basic-concepts/internationalization/

the project also includes a sample language package as an example of what a language package project looks like: https://github.com/magento/pwa-studio/tree/develop/packages/extensions/venia-sample-language-packs
