### ISSUE TITLE
[bug]: Repeated component in bundle from simple import

### ISSUE THREAD

**Issue by JordanDDisch** [magento/pwa-studio#2858]
When building our app and analysing the bundles generated, there is repeat of a component in two different bundles only after importing 'react-tabs'.

Not sure if this is expected behaviour, but I would imagine that importing a node_module into a component would not cause this issue.

With `import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';`

<img width="503" alt="Screen Shot 2020-11-11 at 10 44 47" src="https://user-images.githubusercontent.com/4076759/98747323-66a10180-240b-11eb-9e0a-1bc4448a93cd.png">

Removing import statement
<img width="510" alt="Screen Shot 2020-11-11 at 10 44 38" src="https://user-images.githubusercontent.com/4076759/98747332-6b65b580-240b-11eb-96c7-18833d06a311.png">

Ribbon is a custom component, this happens for a few other components as well.

 - PWA Studio Version: 6.0.0
 - Node Version `12.16`:

- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
@JordanDDisch can I get a little more info? To which component(s) are you adding the `import`? I agree, this is odd, but I. need more info before we can call this a bug with PWA Studio.

**Comment by sirugh** [comment]
Closing for lack of response. If you feel this is still an issue please reopen and provide some more info :)
