### ISSUE TITLE
[feature]: "price" attribute to "price_range"

### ISSUE THREAD

**Issue by KevinGorjan** [magento/pwa-studio#2866]
**Is your feature request related to a problem? Please describe.**
I would like to use features like discounts, special prices, minimum and maximum prices. Therefore I suggest we need to create a new <PriceRange /> component and rewrite some of the GraphQL queries. 

**Describe the solution you'd like**
When there is a discount or special price, I would like to see this on the category-, product-page and in the search. 
Also when the product contains a different minimum or maximum price, show this on the category-, product-page and the lowest price in the search

**Describe alternatives you've considered**
none

**Additional context**
![image](https://user-images.githubusercontent.com/789614/99362022-377b0c00-28b3-11eb-8b3a-bb768a05d1de.png)
![image](https://user-images.githubusercontent.com/789614/99361991-2d590d80-28b3-11eb-92aa-4d04b44aecc9.png)

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [x] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by ericerway** [comment]
@schensley can you take a look? We should add this to our special pricing/promos work. Thanks! 👍

**Comment by sirugh** [comment]
To add, we may want to have this scope encompass _all_ areas of venia that use price:

* cart
* mini cart
* product page
* search page
* search box (autocomplete results)
* category page.
* wishlist

**Comment by huykon** [comment]
I have seen in document that price attribute is deprecated. So is that right?
<img width="1187" alt="Screen Shot 2020-11-19 at 8 30 37 PM" src="https://user-images.githubusercontent.com/9253798/99672583-2a723e80-2aa6-11eb-8b0c-ec59bcf9d9ce.png">

**Comment by huykon** [comment]
as I checked [price_rage](https://devdocs.magento.com/guides/v2.4/graphql/interfaces/product-interface.html#PriceRange) documentation, so :
1. Should we use maximum_price or minimum_price or both?
2. Which mockup or design UX for situations display price(discount, promotion rule, ...) ?

**Comment by ericerway** [comment]
@jcalcaben can you take a look at the docs question? Thanks!

**Comment by KevinGorjan** [comment]
> as I checked [price_rage](https://devdocs.magento.com/guides/v2.4/graphql/interfaces/product-interface.html#PriceRange) documentation, so :
> 
> 1. Should we use maximum_price or minimum_price or both?
> 2. Which mockup or design UX for situations display price(discount, promotion rule, ...) ?

Hi @huykon 

I think we should use the **minimum_price** for simple products.
When it comes to configurable products, we add the **maximum_price**

For example this GraphQL query.

```json
query productDetailBySku($sku: String) {
  products(filter: { sku: { eq: $sku } }) {
    items {
      __typename
      name
      sku
      price_range {
        minimum_price {
          final_price {
            value
            currency
          }
        }
      }
      ... on ConfigurableProduct {
        price_range {
          maximum_price {
            final_price {
              value
              currency
            }
          }
        }
      }
    }
  }
}
```

the response is like

```json
{
  "data": {
    "products": {
      "items": [
        {
          "__typename": "ConfigurableProduct",
          "name": "Teton Pullover Hoodie",
          "sku": "MH02",
          "price_range": {
            "minimum_price": {
              "final_price": {
                "value": 50,
                "currency": "USD"
              }
            },
            "maximum_price": {
              "final_price": {
                "value": 70,
                "currency": "USD"
              }
            }
          }
        }
      ]
    }
  }
}
```

Based on this, you need to some comparing on the frontend ;-)

**Comment by huykon** [comment]
@jcalcaben @ericerway can you give me an exactly answer?

**Comment by wesleyalmd** [comment]
Any news regarding this implementation?

**Comment by huykon** [comment]
What is the decision for this issue ? @ericerway @jcalcaben @sirugh

**Comment by jcalcaben** [comment]
@huykon @wesleyalmd @KevinGorjan This feature is currently on our roadmap. We are still weighing our options for an optimal solution and UX mocks are still in development. Since this feature is already being tracked internally in an upcoming epic, I'm closing this issue.
