### ISSUE TITLE
[bug]: resolveUnknownRoute.js does not work with a custom GraphQL endpoint.

### ISSUE THREAD

**Issue by mhaack** [magento/pwa-studio#2876]
**Describe the bug**
resolveUnknownRoute.js does not work with a custom GraphQL endpoint.

https://github.com/magento/pwa-studio/blob/df8720144f6e0e275c30d4adc3b8feb79e776394/packages/peregrine/lib/Router/resolveUnknownRoute.js#L114 seams wrong as the `opts.apiBase` already contains the absolute URL to the GraphQL endpoint. `apiBase` is constructed in index.js in venica-concept. If I pass `https://www.xyz.com/api` for example `opts.apiBase` already includes `/graphql`.
This code circumvents the Apollo Link URL.

**Expected behavior**
resolveUnknownRoute.js works with none standard GraphQl endpoints.

**Possible solutions**
Change line in question to `const url = new URL(opts.apiBase);`

**Please complete the following device information:**
 - Magento Version: 2.4.1
 - PWA Studio Version: 
 - Yarn version `npm -v`: 1.22.0
 - Node Version `node -v`: v12.13.0

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by jimbo** [comment]
@mhaack Thanks for opening this issue.

The code and concepts in `resolveUnknownRoute` are some of the oldest in PWA Studio, so they're definitely more manual and outdated than the rest of our GraphQL-related code. [We recently merged a PR](https://github.com/magento/pwa-studio/pull/2859) to `develop` that deprecates this file and moves its responsibilities into a normal GraphQL query to be executed by ApolloClient. Does this solve the problem from your perspective?

**Comment by mhaack** [comment]
Yes thanks that will solve the issue. Also, I saw #2877 was merged now.
