### ISSUE TITLE
Update "Data Fetch Error" page to improve user experience

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/pwa-studio#2883]
Current Data Fetch Error is not useful and should be replaced with a friendlier page/route based on recommendation from UX. Merchant and shopper see this as an "404" error instead of an incorrect page.

<https://github.com/magento/pwa-studio/search?q=%22data<ins>fetch</ins>error%22>

categoryList
cmsBlock
category
product

Desired:

* Implement 404 page as a component.
* Use 404 page in place of error view (or wrapped in). This is shown when you navigate to a route that doesn't exist.
* Use 404 page in place of "data fetch error" from components listed above.

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/PWA-1032

**Comment by huykon** [comment]
@schensley Do you have any design for error page?

**Comment by sirugh** [comment]
This was resolved in #2936
