### ISSUE TITLE
Update react-feather dependency

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#2884]
https://github.com/magento/pwa-studio/pull/2533

2.03 -> latest

**Acceptance Criteria**

1. All icons should work
2. Bundle should not be much larger.

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/PWA-1175) is successfully created for this issue.
