### ISSUE TITLE
[feature]: Path array for venia-ui routes pattern

### ISSUE THREAD

**Issue by papiliond** [magento/pwa-studio#2892]
**Is your feature request related to a problem? Please describe.**
Passing an array of paths to the `pattern` field of venia-ui route definition does not work. This value is passed as a string value in BabelRouteInjectionPlugin.js (86:76). It should also accept an array, as react-router path does (see [docs](https://reactrouter.com/web/api/Route/path-string-string)).

**Describe the solution you'd like**

```
veniaTargets.routes.tap(routes => [
        {
            name: 'Home Page',
            pattern: ['/home', '/'],
            exact: true,
            path: '@components/HomePage'
        },
    ]);
```

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by papiliond** [comment]
@magento I am working on this

**Comment by papiliond** [comment]
@magento add to contributors team

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/PWA-1181) is successfully created for this issue.
