### ISSUE TITLE
[bug]: yarn buildpack create-custom-origin . errors

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2898]
**Describe the bug**
`yarn buildpack create-custom-origin .`  produces error 

```
➜  pwa-frontend git:(main) yarn buildpack create-custom-origin .
yarn run v1.22.10
$ buildpack create-custom-origin .
  ⓧ  projectConfig.section is not a function
  ⓧ  Error: projectConfig.section is not a function
error Command failed with exit code 1.
```

**To reproduce**
1. latest develop
2. run scaffold command
3. remove @magento/venia-sample-backends package
4. run  `yarn buildpack create-custom-origin . `

**Expected behavior**
custom origin created

**Screenshots**
see #2897

**Additional context**

**Possible solutions**
see #2897

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [x] `create-pwa`

**Comment by fooman** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Bug

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/PWA-1184) is successfully created for this issue.
