### ISSUE TITLE
[bug]: Adding a trailing comma on run prettier:fix command

### ISSUE THREAD

**Issue by dankhrapiyush** [magento/pwa-studio#2899]
**Describe the bug**
On run `yarn run prettier:fix` command, it's adding a trailing comma under an array

**To reproduce**
1. In packages/venia-concept directory
2. Run `yarn run prettier:fix your-custom-extension-directory` command
3. Check file update history
4. It is adding a trailing comma under an array
```
    const { data, error, loading } = useQuery(GET_BLOG_POST, {
        variables: { id: id },
    });
```

**Expected behavior**
It should not add a trailing comma
```
    const { data, error, loading } = useQuery(GET_BLOG_POST, {
        variables: { id: id }
    });
```

**Possible solutions**
See #2900

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - OS [e.g. iOS8.1, Windows 10]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version:
 - PWA Studio Version:
 - NPM version `npm -v`:
 - Node Version `node -v`:

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by dankhrapiyush** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
The `prettier.config.js` file in the root of the pwa studio repo should handle this already. Do you have any thoughts on why it might not be working for your use case? It looks like there is a `venia-concept/prettier.config.js` so maybe it's overwriting instead of extending the root config. I'd be interested in a resolution to this issue that includes consolidating the configs.

**Comment by dankhrapiyush** [comment]
@sirugh I am facing this issue on the scaffolding `yarn create @magento/pwa`.

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Task

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/PWA-1281) is successfully created for this issue.
