### ISSUE TITLE
[feature]: Upgrade style-loader

### ISSUE THREAD

**Issue by papiliond** [magento/pwa-studio#2905]
**Is your feature request related to a problem? Please describe.**
It would be great to upgrade style-loader to `2.0.0` and leverage the loader options. Currently the version `~0.23.1` is used.

The main thing that would improve the style loading is the `injectType: singletonStyleTag` option, which would place the bundled styles into a single style tag.

**Describe the solution you'd like**
- Upgrade style-loader package to `~2.0.0`
- Add the following loader options to .css files:
```
{
                    loader: 'style-loader',
                    options: { injectType:'singletonStyleTag' }
},
```

**Additional context**

*Current result of the style-loader*
![image](https://user-images.githubusercontent.com/22502609/101643601-948e5b80-3a34-11eb-8f5b-0956f87380b6.png)

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by papiliond** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/PWA-1283) is successfully created for this issue.
