### ISSUE TITLE
[bug]: PageBuilder is not extensible

### ISSUE THREAD

**Issue by 0m3r** [magento/pwa-studio#2923]
I try to add my richContentRenderers
something like [here](https://github.com/magento/pwa-studio/blob/develop/pwa-devdocs/src/pwa-buildpack/extensibility-framework/index.md#example)

and some logic in [richContent.js](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/RichContent/richContent.js#L29) is weak (wrong) in my opinion  
if I add my custom richContentRenderers PageBuilder doesn't work anymore :(
```js
for (const Renderer of richContentRenderers) {
        const { Component, canRender } = Renderer;
        if (canRender(rendererProps.html)) {
            return <Component {...rendererProps} />;
        }
    }
```
and also look like Pagebuilder always override plainHtmlRenderer (if /data-content-type=/.test(content) equals true)

**Expected behavior**
I expect then all richContentRenderer will work together 
parse HTML and replace responsible parts of HTML

**Possible solutions**

**Please let us know what packages this bug is in regards to:**
- [x] `pagebuilder`
- [x] `venia-concept`
- [x] `venia-ui` 
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Hi @0m3r, I'd like to help but I'm a little unsure of how to repro your issue. Can you provide specific repro steps including your custom rich content renderer as well as your "targeting" code? It would also help if we had some error messages or other information that would help us debug. "Doesn't work anymore" can only get you so far :)

**Comment by 0m3r** [comment]
Step to reproduce 
1) [Create your own Module](https://larsroettig.dev/getting-started-with-pwa-studio-extensibility)

package.json
```package.json
{
  "name": "@vendor/module",
  "version": "1.0.0",
  "publishConfig": {
    "access": "public"
  },
  "description": "Provides demo of extending richContent for PWA Studio.",
  "main": "./intercept.js",
  "scripts": {
    "clean": " "
  },
  "license": "(OSL-3.0 OR AFL-3.0)",
  "peerDependencies": {
     "@magento/pagebuilder": "*",
    "@magento/pwa-buildpack": "~7.0.0",
    "@magento/venia-ui": "~5.0.0"
  },
  "pwa-studio": {
    "targets": {
      "intercept": "./intercept"
    }
  }
}
```
intercept.js
```js
module.exports = targets => {

    const builtins = targets.of('@magento/pwa-buildpack');

    builtins.specialFeatures.tap(flags => {
        flags[targets.name] = {
            esModules: true,
            cssModules: true,
            i18n: true
        };
    });

     targets
        .of('@magento/venia-ui')
         .richContentRenderers.tap(richContentRenderers => {
            richContentRenderers.add({
                 componentName: 'SomeComponent',
                importPath: require.resolve("../lib/components/SomeComponent/index.js")
            });
        });
}
```

/lib/components/SomeComponent/index.js
```js
export { default } from './someComponent';
export { default as Component } from './someComponent';
export { default as canRender } from './detectSomeComponent';
```

detectSomeComponent.js
```js
/**
 *
 * @param content
 * @returns {boolean}
 */
export default function detectSomeComponent(content) {
    return /SomeComponent/.test(content);
}
```
someComponent.js
```js
import React from 'react';

const SomeComponent = props => {
     return {'Some Component'}
}

export default SomeComponent;

````
2) add to cms page content
  - add any data-content-type= (data-content-type="html")
  - add SomeComponent string
  
3) Check what will be rendered (only SomeComponent or only PageBuilder component(s) )

**Comment by sirugh** [comment]
Thanks for providing these detailed steps! I'll see if we can repro and prioritize this issue from here.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Hi @0m3r, thanks for the write-up! Page Builder _should_ be extensible now, with your contribution here: https://github.com/magento/pwa-studio/pull/3307
