### ISSUE TITLE
[feature]: Adding a product to Wishlist from the PDP

### ISSUE THREAD

**Issue by Frodigo** [magento/pwa-studio#2934]
Issue is re-opened to unify experience across all storefront areas: catalog/CMS/PDP

### Story

**Preconditions**
* Wishlist is enabled in Magento Admin Panel>Stores > Settings > Configuration > Customers > Wish List
* User is on Venia storefront PDP
* User is not logged in

**Precondition 1 - single wishlist**
* Magento doesn't have multiple wish-list (CE) or multi-wishlist is disabled in Stores > Settings > Configuration > Customers > Wish List>Enable Multiple Wish Lists (EE)

**Precondition 2 - multiple wishlist**
* Multi-wishlist is enabled in Stores > Settings > Configuration > Customers > Wish List>Enable Multiple Wish Lists (EE)

**Acceptance Criteria**
* User sees an indication to add product to the wishlist 
* User initiates adding product to the wishlist and gets prompt to log in/create account (as adding to wish list requires authentication).
* If user is logged in, no prompt is shown, see next AC
* In case of **Precondition 1**:
  * After user successfully logged in, user sees the indication of product added to the wishlist.
* In case of **Precondition 2**:
  * After user successfully logged in, user sees a dialogue to choose a wishlist to add a product to.
  * User creates a wishlist or selects one created before
  * Once wishlist selected/created, User sees the indication of product added to the wishlist
* User sees the indication of the product to be part of the wishlist when they reload a PDP. If a configurable variation is wish listed, we consider the configurable product to be wish listed.

As a user I want to be able to:
* add to a wishlist from the product page, optionally needing to
* create a wishlist from the product page

#### Test Plan
1. Navigate to PDP
1. Favorite the product
1. Select an existing wishlist
1. Verify that the product is added to the wishlist (verify success and error handling in error scenario)
1. Navigate to separate PDP
1. Favorite the product
1. Create a new wishlist (verify error scenario)
1. Verify that the product is added to the newly created wishlist (verify error scenarios)
1. Repeat above scenario's for Configurable and Simple products.
1. Repeat above for CE and verify that when you favorite the product it is immediately added to the only wishlist (no dialog is shown)
1. Verify UI of overlay for Minimum (no saved lists) and Maximum (Many saved lists)
1. Verify Functionality of Cancel and X icon.
1. Run MFTF
1. Verify UI in different browsers and devices.

 

Question - 
1. Cart page Kebab menu also gives option for adding to Favourite lists, should that flow also be covered?
  1. Good question, I'll create a separate story for this: PWA-1495.

**Comment by huykon** [comment]
@magento I am working on this

**Comment by huykon** [comment]
@schensley do you have any design for this?

**Comment by sirugh** [comment]
We should have the ability to do this starting in Magento 2.4.2.

FYI @huykon might be better to pick up tickets that have been groomed. We don't normally add detail until then, and we don't normally evaluate necessity or feasibility until then.

Thanks!

**Comment by huykon** [comment]
@sirugh thank for your response. I push a draft PR in [2939](https://github.com/magento/pwa-studio/pull/2939)

**Comment by sirugh** [comment]
I have created internal ticket to track this work, [PWA-1267](https://jira.corp.magento.com/browse/PWA-1267)
