### ISSUE TITLE
[feature]: Add option to use custom https certificates with buildpack

### ISSUE THREAD

**Issue by arturtreiberg** [magento/pwa-studio#2945]
**Describe the solution you'd like**
Add option to add custom https certificates to buildpack serve

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by arturtreiberg** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/PWA-1284) is successfully created for this issue.

**Comment by 0m3r** [comment]
https://community.magento.com/t5/Magento-2-x-PWA-Theming-Layout/How-to-set-custom-certificate-for-Node-in-Magento-PWA/m-p/127137#
