### ISSUE TITLE
Multiple theme inheritance ?

### ISSUE THREAD

**Issue by gabs77** [magento/pwa-studio#2947]
I know how to create a theme on pwa-studio with the create-pwa command.
But i'm looking for to build multiple 2 themes with a double dependencies.
Example : 
- 1st theme : packages/my-abstract-theme-vanilla depends by venia-concept
- 2nd theme : packages/my-final-theme depends by packages/my-abstract-theme-vanilla 
- 3nd theme : packages/my-second-final-theme by packages/my-abstract-theme-vanilla 

Is it possible ?
Have we some options to do that ? Or is not recommended ?

**Comment by sirugh** [comment]
@jimbo might have some thoughts on the subject.

I'd also recommend taking this question to the public slack channel where you're more likely to get help :) I'm going to close this as it's more a question than a bug/feature request.
