### ISSUE TITLE
[bug]: Can't use shipping address in checkout step.

### ISSUE THREAD

**Issue by Kein1945** [magento/pwa-studio#2949]
Hi, everyone!

**Describe the bug**
Short: I get error in JS console: Guest checkout is not allowed. Register a customer account or login with existing one
Long: I'm trying to look at new features in 8.0.0 release like order history, but can't complete checkout.
I'm using fresh version of pwa-sudio and newly installed Magento 2.4.0 as backend.

**To reproduce**
1. Authorize, add product to cart and go to checkout page
2. Existing one address not added to checkout page (I checked admin section with this user, each checkout try add new address)
2. Get message above Guest checkout is not allowed. Register a customer account or login with existing one
3. Fill address information and press "add"
4. Nothing happen

**Expected behavior**
1) Previous saved address apear in checkout
2) Checkout is completing

**Additional context**
GraphQL request getCustomerAddress return response with existing addresses:
`{"data":{"customer":{"id":null,"addresses":[{"id":6 ... }],"__typename":"Customer"}}} `- i'm just curious - is customer.id === null is correct here?
I'm using clone of master, but installing venia scaffolding tool didn't show me any order history in navigation - but packages versions is correct: venia-ui - 5.0, peregrine: 8.0

** possible solution**
I'm new one at Magento backend, may be there is some option that I should turn on or off. Sorry if solution is so simple.

**Please complete the following device information:**
 - Device: Laptop
 - OS: Manjaro Linux
 - Browser: Chrome
 - Browser Version: 87.0
 - Magento Version: 2.4.0
 - PWA Studio Version: 8.0
 - NPM version `npm -v`: 6.14
 - Node Version `node -v`: 15.3

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Hi @Kein1945 thanks for reporting this issue. Would you be able to provide more context here? Error messages from the graphql calls or your browser developer console would be very helpful. Adding a video/screenshots capturing the issue would also go a long way.

As for whether `customer.id` can be `null`, well I tried on develop.pwa-venia.com and saw the same response but a functioning UI, so I think there may be some misconfiguration in your back end.

[![Image from Gyazo](https://i.gyazo.com/656c457c128392ccc6ae66ad6682636e.png)](https://gyazo.com/656c457c128392ccc6ae66ad6682636e)

**Comment by sirugh** [comment]
Closing for lack of response. If you feel this is still an issue please reopen and provide some more info :)

**Comment by HaidarZ** [comment]
> Hi @Kein1945 thanks for reporting this issue. Would you be able to provide more context here? Error messages from the graphql calls or your browser developer console would be very helpful. Adding a video/screenshots capturing the issue would also go a long way.
> 
> As for whether `customer.id` can be `null`, well I tried on develop.pwa-venia.com and saw the same response but a functioning UI, so I think there may be some misconfiguration in your back end.
> 
> [![Image from Gyazo](https://camo.githubusercontent.com/9c1e2f933d830a3812ba3c5e613e31b100c7098a2250b76ffa6ab4924415af90/68747470733a2f2f692e6779617a6f2e636f6d2f36353663343537633132383339326363633661653636616436363832363336652e706e67)](https://gyazo.com/656c457c128392ccc6ae66ad6682636e)

What is the best backend proper configuration for pwa ?

**Comment by Kein1945** [comment]
Apologize, I forgot how I solved that. But that was some configuration
option at admin panel

**Comment by mikeoloughlin** [comment]
Just ran into this issue and correct you have to enable guest checkout or patch this file
`vendor/magento/module-quote-graph-ql/Model/Cart/CheckCartCheckoutAllowance.php`

Which is doing an exact match on a getter which returns a string.
```php
        if (false === $quote->getCustomerIsGuest()) {
            return;
        }
```

**Comment by daniloaldm** [comment]
@Kein1945 @mikeoloughlin 

What worked for me was modifying the file:
`vendor/magento/module-quote-graph-ql/Model/Cart/CheckCartCheckoutAllowance.php`

```
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
declare(strict_types=1);

namespace Magento\QuoteGraphQl\Model\Cart;

use Magento\Checkout\Helper\Data as CheckoutHelper;
use Magento\Framework\GraphQl\Exception\GraphQlAuthorizationException;
use Magento\Quote\Model\Quote;

/**
 * Checks if guest checkout is allowed.
 */
class CheckCartCheckoutAllowance
{
    /**
     * @var CheckoutHelper
     */
    private $checkoutHelper;

    /**
     * @param CheckoutHelper $checkoutHelper
     */
    public function __construct(
        CheckoutHelper $checkoutHelper
    ) {
        $this->checkoutHelper = $checkoutHelper;
    }

    /**
     * Check if User is allowed to checkout
     *
     * @param Quote $quote
     * @return void
     * @throws GraphQlAuthorizationException
     */
    public function execute(Quote $quote): void
    {
        if (!$quote->getCustomerIsGuest()) {
            return;
        }

        $isAllowedGuestCheckout = (bool)$this->checkoutHelper->isAllowedGuestCheckout($quote);
        if (false === $isAllowedGuestCheckout) {
            throw new GraphQlAuthorizationException(
                __(
                    'Guest checkout is not allowed. ' .
                    'Register a customer account or login with existing one.'
                )
            );
        }
    }
}

```
