### ISSUE TITLE
[feature]: Extensibility point (new target) to Pagebuilder setContentTypeConfig 

### ISSUE THREAD

**Issue by 0m3r** [magento/pwa-studio#2968]
Now we have a good way to add pagebuilder content type with setContentTypeConfig 

https://github.com/magento/pwa-studio/blob/develop/packages/pagebuilder/lib/config.js#L29

https://github.com/magento/pwa-studio/issues/2130
https://github.com/magento/pwa-studio/pull/2131

but setContentTypeConfig is hard to using 

I must use my custom babel plugin to insert my "component" before each <RichContent ... />
 in "@magento/venia-ui/lib/RootComponents/CMS/cms", etc.
it is the wrong way because I need to find every <RichContent> usage

so I think the next good step will be to add (declare) pagebuilder target to this point

API 
intercept.js in custom module
```js
module.exports = targets => {
targets
        .of('@magento/pagebuilder')
        .contentTypes.tap(contentTypes => {
            contentTypes.add({
                componentName: '[some]ContentType',
                importPath: './lib/[some]'
            });
        });
};
```

some.js
```
import React from 'react';
import { setContentTypeConfig } from '@magento/pagebuilder/lib/config';

import Component from './component';
import configAggregator from './configAggregator';

setContentTypeConfig('some', {
    configAggregator,
    component: Component
});
```

**Please let us know what packages this feature is in regards to:**
- [x] pagebuilder
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [x] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by LucasCalazans** [comment]
This would be a great feature.

I'm creating a content type for a Dynamic Blocks type. It's working using the `setContentTypeConfig` but I need to call it in some component (Or in `index.js`).

But I would love to create an extension that is ready to use after the `yarn add`, and this idea would  help in this scenario

**Comment by 0m3r** [comment]
@LucasCalazans You can use this workaround. it works for all RichContent components in project

In your extension, you need to add fake richContentRenderer

https://magento.github.io/pwa-studio/venia-ui/reference/targets/#richContentRenderers 

intercept.js
```js
module.exports = targets => {
      targets
        .of('@magento/venia-ui')
        .richContentRenderers.tap(richContentRenderers => {
            richContentRenderers.add({
                componentName: 'FakeComponent',
                importPath: require.resolve("../lib/components/FakeComponent/index.js")
            });
        });
}
``` 
lib/components/FakeComponent/index.js
```js
export { default } from './fakeComponent'; 
export { default as Component } from './fakeComponent';
export { default as canRender } from './detectFakeComponent';
```

detectFakeComponent.js must always return false 
```js 
/**
 * @param content
 * @returns {boolean}
 */
export default function (content) => {return false;}
```

Now In fakeComponent.js you can call setContentTypeConfig
and add your content type
```js
import React from 'react';

import { setContentTypeConfig } from '@magento/pagebuilder/lib/config';
import CustomSliderContentTypeConfig from './ContentTypes/CustomSlider';

// add custom page builder content type
//https://github.com/magento/pwa-studio/pull/2131

export default () => {
    setContentTypeConfig('CustomSlider', CustomSliderContentTypeConfig)
};

const fakeComponent = (props) => {
    return null;
};

export default fakeComponent;
```

```js
import CustomSlider from './slider';
import configAggregator from './configAggregator';

export default {
    configAggregator,
    component: CustomSlider
}
```

CustomSlider - your real component
configAggregator - example (here)[https://github.com/magento/pwa-studio/blob/develop/packages/pagebuilder/lib/ContentTypes/Banner/configAggregator.js]

**Comment by supernova-at** [comment]
@magento export issue to JIRA project PWA as Story
