### ISSUE TITLE
[feature]: When create sitemap in Magento there should be option to add PWA url and generate urls from upward server.

### ISSUE THREAD

**Issue by nadeefit6** [magento/pwa-studio#2970]
**Is your feature request related to a problem? Please describe.**
Magento2 create sitemap.xml files through cron. Need this feature on PWA.
**Describe the solution you'd like**
When create sitemap in Magento there should be option to add PWA url and generate urls from upward server.

**Describe alternatives you've considered**
A quick fix is really appriciated

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
I'm not quite sure what this is asking. @tjwiebell or @eug123 are you guys familiar with magento site map generation? Do you understand what the ask is here?

**Comment by eug123** [comment]
Hello @nadeefit6, you can try to set your PWA url as `Base URL` for your store view scope, and generate sitemap for this store view.

**Comment by sirugh** [comment]
Closing for lack of response.
