### ISSUE TITLE
[bug]:  Could not setup development domain:Error: Command failed: openssl

### ISSUE THREAD

**Issue by ngocvon** [magento/pwa-studio#2975]
I have setup pwa studio but to step three show error Could not setup develop domain:
Error: Command failed: openssl
![image](https://user-images.githubusercontent.com/5688818/105964306-94b1eb80-60b4-11eb-97ba-a992ac1bcf9d.png)
Veryone let help me please. I installed node v10.15.1 and yarn -v 1.17.3
![image](https://user-images.githubusercontent.com/5688818/105961616-50711c00-60b1-11eb-970d-4f6a3a2088fd.png)

**Comment by sirugh** [comment]
There looks to be some permissions errors in your error log. Can you check permissions on your `certificate.cert` file? They should be `read`.

This is mine, that I use for my local development:
![](https://i.gyazo.com/2c5e0d9b105547968a0511c75dda1f79.png)

**Comment by fooman** [comment]
seems the same as this https://github.com/magento/pwa-studio/issues/2318

**Comment by sirugh** [comment]
Closing for lack of response.
