### ISSUE TITLE
[feature]: Switch to font with cyrillic support (Muli (font) does not support)

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#2976]
**Describe the bug**
Default font has no cyrillic support, so cyrillic characters default to a sans font.

**To reproduce**
1. Setup shop
2. Translate into a cyrillic-based language

**Expected behavior**
Font is consistent between latin and cyrillic characters.

**Additional context**
Yes, I know we can change that with template and CSS changes, but it does not make sense to use a default font that excludes > 300 million people.

**Possible solutions**
Use a font that supports cyrillic.

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Implementation Guidance:

* Use `Open Sans` font.
* Update `default-font-include.mst` and `venia-concept/template.html` using output of `https://fonts.googleapis.com/css?family=Muli:400&display=swap`. Be sure not to remove the `Source Serif` lines.
* Update all other references from `Muli` to `Open Sans`

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Story

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Task

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Story

**Comment by larsroettig** [comment]
@magento I am working on this

**Comment by tkacheva** [comment]
@plamenh Thanks for bringing this issue to our attention. Certainly lack of support of Cyrillic (as well as other alphabets like Chinese or Arabic) is a miss. however changing the default font from one to another won't solve the problem as there is no option that works for all. We are currently working on the new theming concept for PWA and I make sure to include that as a requirement.
