### ISSUE TITLE
[bug]: Refused to load the stylesheet because it violates the following Content Security Policy

### ISSUE THREAD

**Issue by sergeycherepanov** [magento/pwa-studio#2979]
**Describe the bug**
I enabled the SASS support by the official guide and it works in debug/watch mode. But after yarn build && yarn start the styles where broken and the console says:

```
Refused to load the stylesheet 'blob:http://0.0.0.0:8080/8e286dcc-c3ec-445d-aab8-0ad3e322891a' because it violates the following Content Security Policy directive: "style-src 'self' https: 'unsafe-inline' https://m2.hm2.space/". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.
```

**To reproduce**

1.  Enable the saas support by the following guide: https://magento.github.io/pwa-studio/tutorials/enable-sass-less-support/
2.  Rename the index.css to index.scss and import in the index.js file. 
3.  Build the project by the following command: `yarn build`
4.  Start the project by the following command: `yarn start` 
 
**Expected behavior**

No errors in the console and styles loaded properly.

**Please complete the following device information:**
 - Device [PC, Mac]:
 - OS [MacOs, Windows 10]:
 - Browser [Chrome]:
 - Browser Version [e.g. 22]:
 - Magento Version: 2.4
 - PWA Studio Version: 8
 - NPM version `npm -v`: 6.14.10
 - Node Version `node -v`: v12.20.1

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [x] `pwa-devdocs`
- [x] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
Thanks for reporting this! For what it's worth the headers are defined in the `upward-security-headers` extension. The solution will probably have to do with modifying the headers to allow `blob`.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as bug

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
