### ISSUE TITLE
[bug]: Page redirects to Luma theme after clicking account confirmation mail

### ISSUE THREAD

**Issue by mohanelamurugan** [magento/pwa-studio#2993]
**After clicking the account confirmation link on confirmation mail, It redirects the customer to Luma theme instead of Venia store**

**To reproduce**

1.     Login to admin panel
2.     Navigate to Stores > Configuration
3.     Go to Customers > Customer Configuration
4.     Click “Create New Account Option“
5.     Set “yes” in Require Email Confirmation
6.     Save the configuration.

**Expected behavior**

After recieving the email, Clicking on the confirmation link should take us to Venia store

**Actual behavior**

After recieving the email, Clicking on the confirmation link takes us to Luma store

**Comment by sirugh** [comment]
@revanth0212 @tjwiebell I recall there was some discussion around this when we implemented the "forgot password" piece. Did we account for confirmation emails?

**Comment by revanth0212** [comment]
Not that I can recall. We only worked on the Forgot Password part.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by tjwiebell** [comment]
FYI - there is no GraphQL support for this feature yet, so there's nothing we can do here until an email confirmation mutation is added.
