### ISSUE TITLE
Wrong verbiage in account create warning

### ISSUE THREAD

**Issue by mohanelamurugan** [magento/pwa-studio#2994]
**After enabling account confirmation through email, Warning message verbiage is wrong**

**To reproduce**

  

1.   Login to admin panel
2.     Navigate to Stores > Configuration
3.     Go to Customers > Customer Configuration
4.     Click “Create New Account Option“
5.     Set “yes” in Require Email Confirmation
6.     Save the configuration.
7.     Register a new account from storefront.
7.      Now, After registering a new account, Instead of saying "Account is not confirmed", It says "Account is locked". Exact verbiage is given below

**Expected behavior**
The warning verbiage should be 
"This account is not confirmed. <a href=""%1"">Click here</a> to resend confirmation email.","This account is not confirmed. <a href=""%1"">Click here</a> to resend confirmation email."

**Actual behavior**
The warning verbiage is
"The account sign in was incorrect or your account is disabled completely. please wait and try again later"

**Screenshot**

![emailreg](https://user-images.githubusercontent.com/13690499/107038478-9715f300-67e2-11eb-9221-f8ec02e8a429.png)

**Comment by sirugh** [comment]
Hi @mohanelamurugan thanks for reporting this issue. Unfortunately, this is not a bug with PWA Studio but is an issue with the magento graphql response to the `signIn` mutation. Please open an issue against the [magento2](https://github.com/magento/magento2) repo. You can reference this issue if you like. I would also suggest adding the graphql response from the network tab in your developer tools after you attempt the sign in. It should contain the error message in the response.
