### ISSUE TITLE
[bug]: Image cache max size not working

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#2999]
**Describe the bug**

PWA studio sets a max entry for number of images in cache of 60. This does not seem to happen.

**To reproduce**

1. Navigate venia.magento.com, be sure to select multiple different products with images
2. Open developer tools, 
3. see total entries go above 60

**Expected behavior**

max size of 60 is enforced
https://github.com/magento/pwa-studio/blob/7bb1f49ecf26c320634f468eb03f1d83301c9c4c/packages/venia-concept/src/ServiceWorker/Utilities/imageCacheHandler.js#L164

To note venia.magento.com is using a separate cache for catalog, with develop using images. Both exhibit this behaviour.

**Screenshots**

![image](https://user-images.githubusercontent.com/455508/107307030-d433fb00-6aea-11eb-8a34-4e0e98d98700.png)

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by fooman** [comment]
Also to note there is a performance impact where it the service worker images have response times in the 1-2 second range.

![image](https://user-images.githubusercontent.com/455508/107307865-6dafdc80-6aec-11eb-9dcc-87dcdc0dec6b.png)

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by larsroettig** [comment]
@magento I am working on it
