### ISSUE TITLE
[GraphQl] Category page results in error page when using the main navigation if category URL Rewrite entry changed

### ISSUE THREAD

**Issue by vasilii-b** [magento/pwa-studio#3017]
**Describe the bug**

When using the main navigation to land on a category page it results in an error page. It happens in case the URL Rewrite for the chosen category is changed from the default one (generated by the magento system).

![image](https://user-images.githubusercontent.com/13456702/108376265-7d75a200-720b-11eb-8da3-6ea08424dc7c.png)

**To reproduce**

1. Chose a category to visit on the storefront. E.g. Men Tops (on a magento instance with sample data installed)
2. Navigate to the category on the storefront.
3. See the products for the category (or at least the category page, no error page)
4. Go to the admin area -> URL Rewrites
5. Find the entry for the chosen category
6. Adjust the URL Rewrite. E.g _Request path_ from `men/tops-men.html` to `tops-men.html`
7. Run reindexing and flush the caches
8. Visit the storefront and navigate to the chosen category using the store navigation. E.g. Men -> Tops -> All Tops.
9. See the error page
10. Notice the URL key is the old one. E.g instead of `tops-men.html` it is `men/tops-men.html`

**Expected behavior**

**Screenshots**
URL Rewrite before adjustments
![image](https://user-images.githubusercontent.com/13456702/108375248-74d09c00-720a-11eb-964d-4204c1a22d5d.png)

URL Rewrite adjusted
![image](https://user-images.githubusercontent.com/13456702/108375720-e6a8e580-720a-11eb-906b-6061fffb9f7d.png)

**Possible solutions**

The navigation component builds the URLs based on the category's `url_path` instead of `url_key`.

**Debug Report**

N/A

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: any
-   Browser [e.g. Chrome, Safari]: any
-   Browser Version [e.g. 22]: any
-   Magento Version [e.g Magento Commerce 2.4]: Magento Commerce 2.4.2

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
Thanks for clear repro steps @vasilii-b! I'll get this into our internal backlog. In the meantime, if you have a solution, we would love a PR!

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by vasilii-b** [comment]
#### Update

After a quick investigation, I've found the issue is on the GraphQl side.
The mentioned issue can be reproduced in the Breadcrumbs as well.

**Comment by sirugh** [comment]
Thanks for that info! I have asked in some channels how to handle this and will try to come back and update this asap.

**Comment by vasilii-b** [comment]
Thank you, @sirugh!

**Comment by sirugh** [comment]
I have spoken to the GQL team and this is a GQL issue in their backlog. Same linked JIRA issue.
