### ISSUE TITLE
Feedback on page: /tutorials/create-taglist-component/

### ISSUE THREAD

**Issue by CoutoDev** [magento/pwa-studio#3020]
I was trying to follow the PWA Studio Tutorial to learn something about it, but then I found some outdated sections, like [#edit-the-graphql-query](https://magento.github.io/pwa-studio/tutorials/create-taglist-component/#edit-the-graphql-query) for example. The `packages/venia-ui/lib/queries/getProductDetail.graphql` file doesn't exists so I wasn't able to keep following through this tutorial. If someone could please update this and review all other sections, I would apreciate a lot.

**Comment by sirugh** [comment]
Thanks for the report @CoutoDev. I'll bring this into our backlog but in the meantime we would love a contribution if you happen to be up for it.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Task

**Comment by sirugh** [comment]
cc @jcalcaben

**Comment by CoutoDev** [comment]
@sirugh Ok, I can do this but how should I proceed?

**Comment by jcalcaben** [comment]
@CoutoDev 
you can update the contents of this markdown file:

https://github.com/magento/pwa-studio/blob/develop/pwa-devdocs/src/tutorials/create-taglist-component/index.md

**Comment by sirugh** [comment]
See my guidance in comment above.

**Comment by larsroettig** [comment]
@magento I am working on it

**Comment by sirugh** [comment]
Lars and I discussed this morning - the original tutorial is no longer valid and needs to be re-written using a scaffold approach rather than clone. Lars will update :)

**Comment by CoutoDev** [comment]
Thanks a lot! I was trying to figure out how to rewrite this section because many things are now different from the tutorial. I appreciate that you guys are going to rewrite.

**Comment by larsroettig** [comment]
@jcalcaben you take it over ?

**Comment by jcalcaben** [comment]
yes I am working on this
