### ISSUE TITLE
[doc]: Instructions on how to display backend homepage (from CMS) as a homepage for Venia

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3033]
**Describe the request**
Currently, there are no instructions on how to set the homepage to either a concrete CMS page from the backend or the designated (backend) homepage. This is very important for anyone not using EE and Page Builder.

**Possible solutions**
In order to use a CMS page as a home page you need to:
1. XXX
2. YYY
3. ...

**Please let us know whether this is a new topic or a topic change request:**
 - [x] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by sirugh** [comment]
@plamenh thank you for this request - I have created linked it to our internal backlog and we will get to it when we can :)

**Comment by plamenh** [comment]
I found the source of the confusion (at least for me):

useCmsPage Line 62:

```
// TODO: we shouldn't be validating strings to determine if the page has content or not
    const hasContent = useMemo(() => {
        return (
            cmsPage &&
            cmsPage.content &&
            cmsPage.content.length > 0 &&
            !cmsPage.content.includes('CMS homepage content goes here.')
        );
    }, [cmsPage]);
```

I think this line should go. If it does not, we need this in the docs.

**Comment by sirugh** [comment]
Are you talking about the static text `CMS homepage content goes here.`? I believe that comes from the back end, which means that if you had customized your cms (and replaced that string) it would no longer be present, so your custom homepage would render.

**Comment by plamenh** [comment]
Yeah, I understood that, but I don't get the reasoning behind it. Why not just display the homepage content there regardless of whether it's been changed from default or not? I spent a few hours trying to figure out how to display my homepage when all I had to do is change a text that is stored in the db. Does not make any sense. I mean, why would frontend logic depend on a string of text stored in the database?

**Comment by sirugh** [comment]
>  I mean, why would frontend logic depend on a string of text stored in the database?

@plamenh Apologies! I forgot to respond. ~17 months ago we made a change to this file in this PR: https://github.com/magento/pwa-studio/pull/1872. There was a [comment](https://github.com/magento/pwa-studio/blame/d4dd9dc1dfa1777857ccabb11b1fb533c6e16604/packages/venia-ui/lib/RootComponents/CMS/cms.js#L32) which seems to have been lost: `Only render <RichContent /> if the page isn't empty and doesn't contain the default CMS Page text.`

So it appears that the original intent was literally to prevent the default CMS page text from rendering, but I don't know _why_ we wanted to prevent it. I'm sorry it was confusing - I will see if we can remove that line.

**Comment by sirugh** [comment]
Ok I spoke to @davemacaulay who reminded me that the reason for this code is so we can render our venia-ui `CategoryList` component in the event users have not configured the default cms content. Basically, it is a fall back component rendered specifically in that case.

**Comment by plamenh** [comment]
It's all good, just that comment is now missing, it would be great if it's back there. Someone might just skim through line 36 w/out investing much thought (as I did).

**Comment by sirugh** [comment]
https://github.com/magento/pwa-studio/pull/3062/files

done
