### ISSUE TITLE
[feature]: Advanced Search

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3036]
**Is your feature request related to a problem? Please describe.**
There is no advanced search functionality similar to classic Magento.

**Describe the solution you'd like**
A component similar to FilterModal with an interface that respects Magento's attribute settings (e.g., a dropdown/select for dropdowns, text input for text, etc.) and can be placed anywhere in store (therefore, it should not depend on props to get available attributes, but rather fetch them or get them from context)

**Describe alternatives you've considered**
Modify the FilterModal, but this is unlikely to effectively yield the result I am after. 

**Additional context**

<img width="425" alt="Screenshot 2021-03-03 at 15 27 57" src="https://user-images.githubusercontent.com/14073311/109812752-20c7ad80-7c35-11eb-9bd1-77432c199b7a.png">

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by sirugh** [comment]
@plamenh thank you for this request - I have created linked it to our internal backlog and we will get to it when we can :)

**Comment by sirugh** [comment]
@plamenh are you on the public slack? I can try to hop on a chat and help you debug.

In the meantime, [these lines](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/FilterModal/useFilterModal.js#L109-L141) may be of interest. The filter state is really maintained entirely in the url. When the drawer opens, we read from the url and set the items accordingly. When the drawer closes, we replay the updates to the url.

**Comment by plamenh** [comment]
It worked, thanks a lot.

**Comment by supernova-at** [comment]
We checked with our internal search team who advised us that this can be closed: based on their research, there are no plans to add advanced search as part of our new search offering.
