### ISSUE TITLE
[bug]: Special (discounted) price missing on catalog and product page.

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3037]
**Describe the bug**

Product page not showing discounted price.

**To reproduce**

1. Add special price to product
2. Open catalog or product
3. Regular price is displayed, instead of discounted price.

**Expected behavior**

Actual discounted price is displayed.

**Possible solutions**

I checked the graphql query (peregrine) and it only includes regular price. So, we need to change that and also modify productFullDetail (+ catalog product component) to include a second <Price /> component with discounted price.

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sirugh** [comment]
@plamenh thank you for this request - I have created linked it to our internal backlog and we will get to it when we can :)

**Comment by hoangss** [comment]
hi @sirugh do we have any update for this?

**Comment by plamenh** [comment]
The issue is 15 months old. It’s quite possible it was rectified somewhere along the way. I wrapped up the project more than a year ago with a manual fix.

**Comment by glo82145** [comment]
Thanks for your reply @plamenh. As it is not reproduced anymore hence we are closing this ticket. 
Please feel free to reopen if you have anymore update on the same.
