### ISSUE TITLE
[doc]: Reference to @apollo/react-hooks breaks

### ISSUE THREAD

**Issue by sta1r** [magento/pwa-studio#3038]
**Describe the request**
In this tutorial https://magento.github.io/pwa-studio/tutorials/intercept-a-target/modify-talon-results/ there is a line that needs updating. 
```
import { useQuery } from "@apollo/react-hooks";
```

The package.json above does not list a dependency on `@apollo/react-hooks` so this breaks the demo. 

**Possible solutions**
Replace the line with:
```
import { useQuery } from "@apollo/client";
```

and update the dependency in package.json to `"@apollo/client": "~3.0.0"`.

**Screenshots**
![Screenshot 2021-03-03 at 17 23 29](https://user-images.githubusercontent.com/77671/109845575-347b1000-7c45-11eb-94e3-e16c9b0fb541.png)

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [x] Topic Change Request (ie. spelling, organization)

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Task
