### ISSUE TITLE
[bug]: Shipping information: All countries are always available to choose from regardless of restrictions

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3042]
**Describe the bug**

When countries are disabled in Magento backend, they are still available to choose on checkout.

**To reproduce**

1. Disable all countries except one in m backend
2. Initiate the checkout process
3. Try to estimate shipping costs
4. Choose a country which is disabled in backend
5. Get stuck at 'Loading regions...'.

**Expected behavior**

Only allowed countries are shown as choices.

**Screenshots**

<img width="640" alt="Screenshot 2021-03-04 at 8 23 57" src="https://user-images.githubusercontent.com/14073311/109920499-0805d900-7cc3-11eb-9b8d-6cb3ae7e2cb3.png">

**Possible solutions**

Modify gql query to get allowed countries only. Currently, this is the query:

```
export const GET_COUNTRIES_QUERY = gql`
    query GetCountries {
        countries {
            id
            full_name_english
            two_letter_abbreviation
        }
    }
`;
```

Since probably we won't be able to filter in the query itself, I think we should also fetch store configuration data. However, current GraphQL docs don't show any allowed_countries prop. Do you know, if the docs are exhaustive or just examples?

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
I would expect that the `countries` query response is dynamic and responds to the changes made to the country options in the back end. What magento back end version are you using?

cc @cpartica

**Comment by plamenh** [comment]
2.4.1 here.

**Comment by cpartica** [comment]
I tested this on 2.4.1 and 2.4-develop and the country query it seems to work and obey the store settings.
```
countries {
            id
            full_name_english
            two_letter_abbreviation
        }
```
this will return only allowed countries.
When you're saying `Try to estimate shipping costs` what are the queries you're using for this? do you re-query countries?
Did you cache initially countries before restricting countries?

**Comment by plamenh** [comment]
@cpartica Website restrictions do not work here. I checked all available settings (Default Config, Main Website, Default View) and they are all restricted. However, on the frontend (not only in estimating shipping costs but on the checkout page as well) I see all countries. Apparently, this query:

export const GET_COUNTRIES_QUERY = gql`
    query GetCountries {
        countries {
            id
            full_name_english
            two_letter_abbreviation
        }
    }
`;

returns all countries regardless of restrictions. The query is the default one included in PWA Studio. I am using the latest version of pwa and m2 (2.4.1).

**Comment by cpartica** [comment]
It's interesting because I did test with 2.4.1 and does restrict, except for the case I posted above, including default country. So you can't reproduce my posted query response correct? it always returns everything? Have you tried clearing cache? What I am after is to know a cache config problem or a server caching problem. Are you using get or post? Can you clear Magento cache ?

**Comment by tjwiebell** [comment]
The `Country` component uses the default fetch policy which is `cache-first`, so @cpartica is correct in that after you updated these settings in the backend, your browser still had the full list in it's cache. At the time of building we didn't feel this setting would change much and used a fetchPolicy that saves us a network call, but if you want the frontend to react to the backend changing, just use a `cache-and-network` or `network-only` fetchPolicy.

**Comment by sirugh** [comment]
@plamenh unfortunately I was able to get the query to work on my back end and the `countries` query only returns allowed countries now. So at this point it seems like you might have an issue with your back end or cache as @cpartica suggested.

As for the other issues you might be seeing with the shipping estimator, let's not confuse this specific topic. Please open new issues for other bugs you might be seeing so we can keep this topic related to your initial problem.

**Comment by plamenh** [comment]
Sorry for not answering for a long time, I was offline. I will check the cache (it probably is the culprit) and will report back.

**Comment by plamenh** [comment]
It was cache indeed. However, there's another issue - when only one country is available and selected by default, the form gets stuck at 'Loading Regions...'. I'll open a new ticket, though. Thanks everyone for the input. In any case, it's a good idea to make it known this query has a cache-first policy (comments maybe?).
