### ISSUE TITLE
[bug]: Cannot place order again after initial order was declined

### ISSUE THREAD

**Issue by mikhaelbois** [magento/pwa-studio#3046]
**Describe the bug**

When placing an order, if the initial order is declined and cause a Checkout Error, we won't be able to try again without reloading the page.

**To reproduce**

1. Create an order that will be de declined.
 In our case, we are using Braintree in sandbox mode and had an order between 2000.00 - 2999.99.
 <https://developers.braintreepayments.com/reference/general/testing/php#transaction-amounts>
1. Place order and get the Checkout Error stating your order was declined.
1. Update your payment information.
1. Place order and see that nothing happens.

**Expected behavior**

We should be able to place a new order when our first try was declined.

**Possible solutions**

In [useCheckoutPage.js](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/CheckoutPage/useCheckoutPage.js#L203) we are listening to `placeOrderCalled`.
 Initially it is set to `false`.
 Then when we try to place an order, the value is set to `true`.
 However, in the case we get an error with the `placeOrderMutation`, `placeOrderCalled` will still be set to `true`.
 So we won't be able to place a new order.
 Refreshing the page will reset that value to `false`.

Here's an opened issue that relates to this kind of behavior: <https://github.com/apollographql/apollo-feature-requests/issues/170]

**Please let us know what packages this bug is in regards to:**
 - [ ] `venia-concept`
 - [ ] `venia-ui`
 - [ ] `pwa-buildpack`
 - [x] `peregrine`
 - [ ] `pwa-devdocs`
 - [ ] `upward-js`
 - [ ] `upward-spec`
 - [ ] `create-pwa`

**Acceptance Criteria**
1. Users can submit an order after an initial order is declined

**Test Plan**
1. Create an order that will be de declined.
 In our case, we are using Braintree in sandbox mode and had an order between 2000.00 - 2999.99.
 [https://developers.braintreepayments.com/reference/general/testing/php#transaction-amounts>
1. Place order and get the Checkout Error stating your order was declined.
1. Update your payment information.
1. Place order and see that it works.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by fooman** [comment]
As a sidenote Braintree does not support (confirmed with their support) using different credit card numbers to illicit a different payment gateway response. As such it will not be possible to test the following

1. enter not working credit card details
2. braintree declines
3. enter working credit card details
4. braintree accepts and order is placed

without navigating away (or some other action to update the cart total) between step 3 and 4 thereby altering state.

¯\_(ツ)_/¯
