### ISSUE TITLE
[bug]: Shipping Information Form Stuck at 'Loading Regions...'

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3059]
**Describe the bug**

Guest Shipping Information Form Stuck at 'Loading Regions...'

**To reproduce**

1. Make a store with only one country available and the same default country. (Not "United States")
2. Try to enter your address in guest checkout.
3. Scroll down 'Region' and try to select a region.
4. The select/dropdown is stuck at 'Loading Regions'.

**Expected behavior**

You should be able to select a region.

**Screenshots**

<img width="689" alt="Screenshot 2021-03-15 at 16 12 07" src="https://user-images.githubusercontent.com/14073311/111166851-3760f380-85a9-11eb-9384-624c8a50981d.png">

**Possible solutions**

N/A

**Debug Report**

N/A

**Please complete the following device information:**

-   Device: Mac
-   Browser: Chrome and Safari
-   Browser Version: Latest
-   Magento Version: 2.4.1

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sirugh** [comment]
Thanks for reporting this - in the meantime if you think you might know of a fix, we would love a contribution. Thanks!

**Comment by plamenh** [comment]
I am on it. Any idea what might be causing this?

`[GraphQL error]: Message: The country isn't available., Location: [object Object], Path: country`

**Comment by plamenh** [comment]
Ok, apparently, fieldState value is not synced in the Select component. See screenshot (left is logged in user, right is no-user).

<img width="1279" alt="Screenshot 2021-03-22 at 13 21 16" src="https://user-images.githubusercontent.com/14073311/111982455-a9898900-8b11-11eb-82e0-9a486a0ebe17.png">

**Comment by plamenh** [comment]
I found (one of )the issue(s) - line 49 of @magento/peregrine/lib/talons/CartPage/PriceAdjustments/ShippingMethods/useShippingMethods.js:

```
let selectedShippingFields = {
        country: 'US',
        region: '',
        zip: ''
    };
```

In order to fix it we need to put the default store config country. Can someone direct me as to how I can get store config from context?

**Comment by sirugh** [comment]
Not at my computer right now, but you can check other components where we make a store config query, like the store switcher. Use a query to fetch the value, which is essentially context :)

**Comment by plamenh** [comment]
I just used countries {} query and picked the first available country. Now it works fine. Changed that in CartPage and CheckoutPage. Just wondering why we need two different components for essentially the same task, though (AddressForm in CheckoutPage and ShippingForm in CartPage). 

Would you like me to put these changes in a PR? It's kind of messy (though it works).

**Comment by sirugh** [comment]
> I just used countries {} query and picked the first available country.

I'd ask first whether we are hoping to auto-select the _default_ country or the user's preferred country. Using the `countries` query and picking the first sounds like a good way to have a default selection, though I'm not confident that whether that is a documented intent of the query (first item === default?). I'd prefer if there was a `storeConfig.default_country` value like there is for `storeConfig.locale`.

Regardless, if you are seeing a reproducible bug in the code, we would happily take a pull request. If you do open one, please make sure to sign the Adobe CLA.

**Comment by plamenh** [comment]
Yeah, I was looking for the same,  but couldn’t find it in the GraphQL docs.

**Comment by HaidarZ** [comment]
> > I just used countries {} query and picked the first available country.
> 
> I'd ask first whether we are hoping to auto-select the _default_ country or the user's preferred country. Using the `countries` query and picking the first sounds like a good way to have a default selection, though I'm not confident that whether that is a documented intent of the query (first item === default?). I'd prefer if there was a `storeConfig.default_country` value like there is for `storeConfig.locale`.
> 
> Regardless, if you are seeing a reproducible bug in the code, we would happily take a pull request. If you do open one, please make sure to sign the Adobe CLA.

Hello,
I'm facing the same issue here, I've implemented a solution to read default country from environment variables.  
Unfortunately, I wasn't able to find any other proper way to do that. Magento doesn't return the default country neither from the graphql nor from the rest api.  
I need to refactor my code before opening a pull request. Is it preferred to explicitly access the process.env for each occurence of the country, or inject it as a global variable inside webpack `DefinePlugin({...})`.  
I would appreciate hearing your thoughts on this.

**Comment by sirugh** [comment]
Here's a gif of what you might see: 

[![Image from Gyazo](https://i.gyazo.com/92485ba3024b3368a8e68a3f63a027f7.gif)](https://gyazo.com/92485ba3024b3368a8e68a3f63a027f7)

**Comment by sirugh** [comment]
Also looks like we have https://jira.corp.magento.com/browse/PWA-1687, to add `defaultCountry` :)

**Comment by sirugh** [comment]
Oh no, sorry I was just noting this for the paper trail. We have an internal ticket for adding this to the GQL schema.
