### ISSUE TITLE
[doc]: describe in detailse configs requerents for webpack.config.js

### ISSUE THREAD

**Issue by mmwogwdk** [magento/pwa-studio#3060]
the problem is, that I'm getting error at the production  when setting an ServiceWorkerPlugin  configs:
```
config.plugins = [
        ...config.plugins,
        new ServiceWorkerPlugin({
            mode:  currentMode,
            paths:{
                src:  path.resolve(__dirname, 'src/ServiceWorker'),
                output: path.resolve(__dirname,'web')
            },
            enableServiceWorkerDebugging: true,
            serviceWorkerFileName: 'sw.js',
            runtimeCacheAssetPath: 'https://cdn.url'
        }),
        new DefinePlugin({
            /**
             * Make sure to add the same constants to
             * the globals object in jest.config.js.
             */
            POSSIBLE_TYPES: JSON.stringify(possibleTypes),
            STORE_NAME: JSON.stringify('Venia'),
            STORE_VIEW_CODE: process.env.STORE_VIEW_CODE
                ? JSON.stringify(process.env.STORE_VIEW_CODE)
                : JSON.stringify(storeConfigData.code),
            AVAILABLE_STORE_VIEWS: JSON.stringify(availableStores)
        }),
        new HTMLWebpackPlugin({
            filename: 'index.html',
            template: './template.html',
            minify: {
                collapseWhitespace: true,
                removeComments: true
            }
        }),
        new EnvironmentPlugin(projectConfig.env)
    ];
   ```
there is an error like
```
ERROR in Please check your GenerateSW plugin configuration:
"globDirectory" is not allowed
````
but this directory are not global - I guess.
And I dig around this question - did'nt get success. Can you please  explain me  what could be a problem in this case.

**Describe the request**
A clear and concise description of the documentation request or where the documentation can be improved.

**Possible solutions**
How would you word this addition or change?

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by sirugh** [comment]
Hi @mmwogwdk, given the error you are seeing, it is possible your versions are not correct, but difficult to say without more detail. There is a script we provide that should get this output - `yarn build:report`. Please run that and bring the output and your question to the public slack channel where you are likely to get help.
