### ISSUE TITLE
[bug]: Configurable product specific image

### ISSUE THREAD

**Issue by Karlasa** [magento/pwa-studio#3064]
**Describe the bug**
Cart Page and minicart is showing base image instead of configuration specific image. 

**To reproduce**

Go https://venia.magento.com/default/karena-halter-dress.html
Select color Latte. 
Add product to the cart
Go to the Cart page/Check minicart

**Expected behavior**
Product has configuration specific image (in Latte colours)

**Screenshots**

**Possible solutions**

**Debug Report**

**Please complete the following device information:**

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by dpatil-magento** [comment]
Its controlled via admin configs - 

![image](https://user-images.githubusercontent.com/40405790/113763026-d4153d80-96de-11eb-9455-91824a9599ef.png)
