### ISSUE TITLE
[bug]: placeholder image for products not served properly

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3069]
**Describe the bug**

placeholder image for products not served properly from path /static/...

**To reproduce**

1. Create a product w/out image.
2. Open category
3. Scroll down to product
4. See missing image icon

`Error: ENOENT: no such file or directory, stat '/Users/XXX/dev/projects/pwa9/static/version1611738522/frontend/Magento/luma/bg_BG/Magento_Catalog/images/product/placeholder/small_image.jpg'`

This does not happen with /media/catalog/... paths.

**Expected behavior**

Placeholder image is located properly

**Possible solutions**

No idea here. For some reason assets from /media/catalog/... are served properly while /static/... are not.

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by plamenh** [comment]
This appears to be caused by missing placeholder images. When there are no placeholder images set, Magento apparently falls back to frontend/Magento/luma/xx_XX/Magento_Catalog/images/product/placeholder/small_image.jpg, which is not served properly.

**Comment by itm-development** [comment]
> This appears to be caused by missing placeholder images. When there are no placeholder images set, Magento apparently falls back to frontend/Magento/luma/xx_XX/Magento_Catalog/images/product/placeholder/small_image.jpg, which is not served properly. So, just uploading your own placeholder image(s) fixes the issue.

this looks the only solution for now

**Comment by zexperto** [comment]
> This appears to be caused by missing placeholder images. When there are no placeholder images set, Magento apparently falls back to frontend/Magento/luma/xx_XX/Magento_Catalog/images/product/placeholder/small_image.jpg, which is not served properly. So, just uploading your own placeholder image(s) fixes the issue.

this looks the only solution for now

**Comment by duongducanh** [comment]
Hi, you can fix it by update to the upward.yml file as follows (add 'static')
`veniaResponse:
  resolver: conditional
  when:
    - matches: request.url.pathname
      pattern: '^/(graphql|rest|media|static)(/|$)'
      use: veniaProxy`

or another way is to change <Image> in the item.js file using the 'src' prop instead 'resource' prop
` <Image
     ...
      src={smallImageURL}
    />`
