### ISSUE TITLE
[bug]: Enabling product image watermarking replaces all category product images with placeholder

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3074]
**Describe the bug**

When watermarking is enabled, category product images are all replaced with the placeholder image.

**To reproduce**

1. Enable watermarking
2. Open any category with products that have images
3. See all product images replaced with placeholder image

**Expected behavior**

If not seeing watermarked images, at least see regular product images.

-   [x] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
