### ISSUE TITLE
[bug]: Product images do not load in product view, because mediaBackend is wrong.

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3076]
**Describe the bug**

Product images do not load, because local browser cache is not populated properly.

**To reproduce**

1. Open a product

**Expected behavior**

Images show fine

**Possible solutions**
 
makeUrl util cannot read the base media url, because local cache is not populated.

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sirugh** [comment]
@plamenh can you provide some more clarification? You can see product images just fine on develop.pwa-venia.com, so I'm not sure how we can repro with the steps you have provided.

**Comment by plamenh** [comment]
I think this might be an issue with my environment, maybe Magento backend. I think it went wrong when I updated to 2.4.2. I will try to pin it down. If not, I will close the issue.

**Comment by supernova-at** [comment]
@plamenh any luck investigating this one?

**Comment by plamenh** [comment]
@supernova-at, see the pull request above.

**Comment by tjwiebell** [comment]
@plamenh - I reviewed the linked PR, and as that warning indicates, that line should be unreachable and was a fallback for an unnecessary work around for testing. The `AVAILABLE_STORE_VIEWS` global is populated at build time by making `availableStores` gql requests, so if the current logic is not working as expected, there's something going on at buildtime.

I suggest manually running [this buildtime query](https://github.com/magento/pwa-studio/blob/develop/packages/pwa-buildpack/lib/queries/getAvailableStoresConfigData.graphql) to see how your backend is responding, and working your way from there. If you still need help debugging, I would also suggest posting in the #pwa channel on the Community Slack.

Going to close this ticket, but please re-open if you can come up with a repeatable way to reproduce.
