### ISSUE TITLE
[bug]: browser back buttons isn't responsive

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#3077]
**Describe the bug**

The browser back button isn't responding properly when a user clicks the button.

**To reproduce**

1. Go to <https://venia.magento.com/default/venia-tops/venia-blouses.html?page=1]
1. Add some filters
1. Now click on the browser back button **once**
1. You should see nothing changed and we are still on the same url.

**Expected behavior**

When a user clicks the back button they expect to be routed back to the previous page/state

**Screenshots**

**Possible solutions**

Check PR ....

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version [e.g Magento Commerce 2.4]:

[!-- Complete the following sections to help us apply appropriate labels! --]

**Please let us know what packages this bug is in regards to:**
 - [ ] `venia-concept`
 - [ ] `venia-ui`
 - [ ] `pwa-buildpack`
 - [x] `peregrine`
 - [ ] `pwa-devdocs`
 - [ ] `upward-js`
 - [ ] `upward-spec`
 - [ > `create-pwa`

Test Plan
* Go to a category page
* Add a filter
* See the results change
* Use the browser back button to click once
* Url should change to the previous history state

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
