### ISSUE TITLE
[bug]: Modifying Routes component breaks routing for default routes

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3081]
**Describe the bug**

When I tried modifying the Routes component (so I can get a custom homepage), cart and checkout routes return not found.

**To reproduce**

1. Copy Routes from `@magento/venia-ui/lib/components` to `src/components`
2. Change Routes import path in (already copied) app.js from `@magento/venia-ui/lib/components/Routes` to `../components/Routes`
3. Update imports in routes.js from ../ to @magento/venia-ui/lib/components
4. Reload, add a product to cart and try to open cart or checkout
5. Get not found

**Expected behavior**

Cart and checkout open fine

**Screenshots**

**Possible solutions**

No idea. This should not happen, as @magento/venia-ui/lib/components/Routes/routes.js and `../components/Routes/routes.js` are virtually identical.

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by plamenh** [comment]
I suspect for some reason route injection fails in this case, as both routes are supposed to be coming from defaultRoutes.json. Any thoughts?

**Comment by plamenh** [comment]
By the way, all default routes are not working, so the issue is definitely there.

**Comment by supernova-at** [comment]
> If the above is true (can't replace routes.js), feel free to close the issue.

Yes, the recommended approach at this time is to tap the routes target instead:

```js
targets.of("@magento/venia-ui").routes.tap(routes => {
    routes.push({
      name: "MyGreetingRoute",
      pattern: "/greeting/:who?",
      path: require.resolve("../components/GreetingPage/greetingPage.js")
    });
    return routes;
  });
```

See the [add a static route tutorial](https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/add-a-static-route/?itm_source=pwa-devdocs&itm_medium=search_page&itm_campaign=federated_search&itm_term=route#tap-into-the-extensibility-framework) for more information.

**Comment by plamenh** [comment]
Another question then - how do I customise the ErrorView component? AFAIK it goes through Routes, doesn't it?
