### ISSUE TITLE
Feedback on page: /pagebuilder/custom-components/add-component/

### ISSUE THREAD

**Issue by coresh** [magento/pwa-studio#3085]
During detailing steps request

An example:

```Step 1: Add local props and prop-types```

`Full /path/to/pwa/root/theCurrentFileName.js` -> would be useful.

Conclusion:

`theCurrentFileName.js`

Expected the full file path/name

Thank you

**Comment by jcalcaben** [comment]
Thanks for the feedback @coresh 

This topic is part of a tutorial set that begins with: https://magento.github.io/pwa-studio/pagebuilder/custom-components/overview/

If you follow the topics in sequence, the details about the file path for the `ExampleQuote` component is provided during the [component setup](https://magento.github.io/pwa-studio/pagebuilder/custom-components/setup-component/) phase.

Let me know if this helps!
