### ISSUE TITLE
[bug]: Broken sizing of small product images

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3088]
**Describe the bug**

On the category landing page, when product image is low resolution (e.g., 225x351), it is stretched and spills over into other components (both product view and catalog view)

**To reproduce**

1. Add a small product image to your catalog and assign it to a category
1. Open the category that the product belongs to on Venia
1. See image spills over onto other elements below

**Expected behavior**

Image is properly sized (not stretched) and does not spill over into other components.

**Screenshots**

<img width="833" alt="Screenshot 2021-03-27 at 20 16 37" src="https://user-images.githubusercontent.com/14073311/112730358-d25ab580-8f39-11eb-8e66-7e2d1f634fa5.png">
 <img width="426" alt="Screenshot 2021-03-27 at 20 16 21" src="https://user-images.githubusercontent.com/14073311/112730362-d5ee3c80-8f39-11eb-82e6-ad2791ccb1fe.png">

**Possible solutions**

Change how Carousel works.

**Please let us know what packages this bug is in regards to:**
 - < > `venia-concept`
 - <x> `venia-ui`
 - < > `pwa-buildpack`
 - < > `peregrine`
 - < > `pwa-devdocs`
 - < > `upward-js`
 - < > `upward-spec`
 - < > `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
