### ISSUE TITLE
[feature]: Email field validation

### ISSUE THREAD

**Issue by Karlasa** [magento/pwa-studio#3094]
**Is your feature request related to a problem? Please describe.**
Currently Email field validation is done on backend side.

**Describe the solution you'd like**
Improve form validators with email specific validation in frontend

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by Karlasa** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by sirugh** [comment]
@Karlasa thanks for opening this issue, but we've actually gone in circles around this and have decided not to implement email validation in the front end. You can see [this PR](https://github.com/magento/pwa-studio/pull/2157) where we removed it for context:

> Reviewed this task with team lead, and it turns out this feature should have never been implemented in the first place. There is little value in doing client-side validation, and the most we should do in our app is validate the email address isn't in use, which isn't currently possible with the form library we're using. He requested we strip this out, which we're doing in the scope of this task now. Article for reference: https://medium.com/hackernoon/the-100-correct-way-to-validate-email-addresses-7c4818f24643

As such, I am closing this issue and related PR. At least now we have an issue that is easy to find :)
