### ISSUE TITLE
[bug]: Babel JSX Plugin Dependency Mismatch

### ISSUE THREAD

**Issue by evan-burrell** [magento/pwa-studio#3097]
**Describe the bug**

Babel plugin for parsing JSX has the incorrect dependency. 

**To reproduce**

1. Create a new PWA Studio project using the scaffolding tool `yarn create @magento/pwa`
2. Use latest tag (10.x)
3. Once installed, remove the storybook directory, and uninstall `@storybook/react`
4. Run `yarn build` or `yarn watch`, see build failures. 

To see dependency `yarn why babel-plugin-syntax-jsx`

**Expected behavior**

The correct Babel JSX Plugin is used to parse JSX. 

**Error Message**

`Error: Provided JSX fragment does not parse as a valid JSX Element: <Switch />: Error: Cannot find module 'babel-plugin-syntax-jsx'`

**Possible solutions**

Update dependency in `JSXSnippetParser.js`

**Debug Report**

```
  ℹ  Inspecting Dependencies
    Found 9 @magento dependencies in yarn.lock
    @magento/pwa-buildpack @ 9.0.0
    @adobe/apollo-link-mutation-queue @ 1.0.2
    @magento/babel-preset-peregrine @ 1.1.0
    @magento/eslint-config @ 1.5.2
    @magento/pagebuilder @ 5.0.0
    @magento/peregrine @ 10.0.0
    @magento/upward-security-headers @ 1.0.3
    @magento/venia-adobe-data-layer @ 1.0.0
    @magento/venia-ui @ 7.0.0

  ℹ  Inspecting Magento Backend
    Using sample backend: https://venia-develop-ccewfjy-mfwmkrjfqvbjk.us-4.magentosite.cloud/
    Backend is UP!

  ℹ  Inspecting System
    OS: Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64
    Node Version: v12.18.2
    NPM Version: 6.14.5
```

**Please complete the following device information:**

- Recreated on Node 12.8.2 / 14.16.0 & yarn 1.22.5

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
