### ISSUE TITLE
[bug]: Broken Add to Cart for logged in users

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3100]
**Describe the bug**

when a guest cart is merged with an user's cart, the new item quantity becomes the sum of the item quantities from the individual carts. If it goes beyond the item's stock quantity, GQL responds with "The requested qty is not available".

Also, once this happens, logged in user cannot add any other products to the cart, it always gives back error 'the requested qty is not available'.

**To reproduce**

1. Add product to cart
1. Sign in with an existing user
1. Try to add a product to cart
1. See error - qty not available

**Expected behavior**

The item quantity to the max stock if it exceeds available stock during merge cart.

**Test Plan**

**Scenario 1:**
1. As an admin create a simple product with a stock of 100
1. As a guest user add the simple product to the cart with a quantity of 60 
1. Merge the guest cart to a user's cart
1. Create another guest cart with the same product with a quantity of 60
1. Merge the guest cart to the same user's cart
1. The user cart should have the item with a quantity of 60.
1. Verify that a second product can be added to the above cart without any error returned.

Automate the above with WebAPI tests

 

**Please let us know what packages this bug is in regards to:**
 - < ] `venia-concept`
 - [x] `venia-ui`
 - [ ] `pwa-buildpack`
 - [x] `peregrine`
 - [ ] `pwa-devdocs`
 - [ ] `upward-js`
 - [ ] `upward-spec`
 - [ > `create-pwa`

**Comment by plamenh** [comment]
The issue appears to be with two open tabs/browsers. One browser had the same user logged in and it had a cart with items added. The other was firing that error all the time. Do you think this is even possible?

**Comment by sirugh** [comment]
@plamenh can you provide exact repro here? Also please run `yarn build:report` so we know what versions you are running. The use case you described is one that we test often so I'd be surprised if it was just broken without some special edge case.

At the core of this is the code that runs when you log in. An authed user only has one cart in the database. We perform a `mergeCart` mutation, which takes the guest cart (with items) and merges it with the customer's cart. There are no "push" or "subscription" events that occur from the backend, so if you change data on one tab it would take something to refetch data on the other tab, such as refreshing the page, opening the `/cart` page, etc.

**Comment by plamenh** [comment]
Another idea: could me clearing app cache manually somehow break cart fetching? The funny thing in the whole situation is that the cartTrigger was showing quantity (e.g., 12), but when the miniCart was triggered or the CartPage was open, it was empty. total_quatity in both places was different.

**Comment by plamenh** [comment]
Ok, I found the edge case (not that edge, by the way). You can see it on https://venia.magento.com/:

1. Add 999 pcs. of Candace Dress/Peach/XS (https://venia.magento.com/default/candace-dress.html);
2. Sign in
3. Sign out
4. Add 999 pcs. of Candace Dress/Peach/XS (https://venia.magento.com/default/candace-dress.html);
5. Sign in
6. Broken cart - it shows 99+ as quantity on accountTrigger, the miniCart is empty, the cartPage is empty and you cannot add any other product to the cart (it always tells you there's not enough qty)

So the gist of it is:

If a logged in user adds the whole available qty of a product, logs out, ads one more piece of it and logs back in, everything goes to hell. This user can no longer buy anything from the store. This is major.

**Comment by codynguyen1** [comment]
This is more like a GraphQl issue, but from the frontend, should we still show the cart items to give customers the ability to remove the out-stock product? The same problem could happen if we add a product to the cart, and then it goes out of stock, and we refresh the cart.
![image](https://user-images.githubusercontent.com/16347586/113530079-58889300-95ef-11eb-9fc3-4ffae47a40f5.png)

**Comment by plamenh** [comment]
That’s a good idea. It works similarly in the cart page when you try to add more quantity than available - it shows you a warning. 

The other option would be for the frontend client to do this automatically (reduce cart quantity to the max available).

**Comment by sirugh** [comment]
> This is more like a GraphQl issue, but from the frontend, should we still show the cart items to give customers the ability to remove the out-stock product?

So we originally blocked the UI on errors but in certain situations, such as this, it can lead to impassible conditions. We also want to be in the practice of showing people the data we do have _and_ letting them make a decision about what to do next. So your idea here would be the right direction, and is what we've tried to do in [other parts of the app](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/RootComponents/Product/product.js#L26-L28) (not blocking on `error`, so long as there is `data`).

I will follow up with the team when we return tomorrow.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sirugh** [comment]
@codynguyen1 

> should we still show the cart items to give customers the ability to remove the out-stock product?

Unfortunately I don't think this will be possible if the `items` array contains a `null` entry for the OOS product. In order for the front end to provide a way forward to the user we would need the item id so we could remove it from the cart. This is most likely going to need to be fixed in the backend/GQL layer.

**Comment by plamenh** [comment]
Not meaning to complain, just wanted to figure out what the standard procedure and timing for the project is: Does it usually take such a long time to address such (major in my opinion) bugs for pwa studio? This issue has been staying in 'ready for grooming' for almost 2 weeks now. I've already encountered slow progress for non-critical issues, but I was kind of expecting a bit better progress for critical stuff.

**Comment by sirugh** [comment]
Hi @plamenh, apologies. We've had some folks out on PTO lately and this got lost in all of that. I've pinged some folks internally and will try to get some update on this. For what it's worth I would suggest opening an issue against magento2 as well.

https://devdocs.magento.com/contributor-guide/contributing.html#report

**Comment by sirugh** [comment]
@plamenh looks like we're getting a fix in GQL:

> A solution agreed with Nishant Kapoor for this is to set the item quantity to the max stock if it exceeds available stock during merge cart.
