### ISSUE TITLE
[feature]: EditModal should not depend on CreditCard

### ISSUE THREAD

**Issue by larsroettig** [magento/pwa-studio#3102]
**Is your feature request related to a problem? Please describe.**
* The `EditModal` for Payment is coupled to the credit card component and contain hardcoded information about the Braintree payment see [editModal.js](https://github.com/magento/pwa-studio/blob/40247e2651b37b5d41b96deaccc5879a3d618603/packages/venia-ui/lib/components/CheckoutPage/PaymentInformation/editModal.js#L33)

**Describe the solution you'd like**
* Create a new Target for EditablePayments
* Refactore and cleanup the `EditModal`

**Describe alternatives you've considered**
* none

**Additional context**

**Please let us know what packages this feature is in regards to:**
 - < ] `venia-concept`
 - [x] `venia-ui`
 - [x] `pwa-buildpack`
 - [x] `peregrine`
 - [ ] `pwa-devdocs`
 - [ ] `upward-js`
 - [ ] `upward-spec`
 - [ > `create-pwa`

 

**Test Plan:** 
1. Run MFTF (This includes payment edit overlay check for US address)
1. Verify Braintree payment edit module for UK address - (!) Fails on develop: https://jira.corp.magento.com/browse/PWA-1823
1. Verify payment edit model for billing address different than shipping 
1. Verify checkmo extension still works (Test locally by adding extension yarn venia add -D <extension name>, make sure respective backend has check/money order enabled)
1. Verify edit overlay UI in Chrome, FF, Safari and device (android or iOS)
1. Verify Edit all three shipping info, method and payment one after other then place order

**Comment by larsroettig** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story
