### ISSUE TITLE
Queries fire multiple times

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#3112]
**Describe the bug**

Whilst I was updating my project to PWA Studio 8.0 I noticed that some queries run twice. Couldn't directly see why this was happening so decided to check https://venia.magento.com/ where the same issue occurred.

**To reproduce**

1. Go to https://venia.magento.com/
2. Open the chrome network tab and set the filter to XHR + graphql
3. Click in the menu on 'Accessories'
4. You should see the following results:
![Screenshot 2021-04-09 at 15 29 03](https://user-images.githubusercontent.com/19858728/114187501-5d7b7880-9948-11eb-9bb8-d611bc005383.png)

As you can tell the `GetCategories` query is running twice. I've checked to see if there is a difference and but request (including params) are exactly the same.

I'm not sure if this is actually a bug or intended behaviour, hope someone can clarify?

**Expected behavior**
-

**Screenshots**
-

**Possible solutions**
-

**Debug Report**
-

**Please complete the following device information:**
-

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by tjwiebell** [comment]
@Jordaneisenburger 
Keen eye, this seems pretty easily reproducible. This query [fires in an effect](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/RootComponents/Category/useCategory.js#L121:L157) with a pretty big dependency list, so it's likely the query fires, one of those deps change, and it fires again. This query is luckily cacheable, but definitely something that should be remedied.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sirugh** [comment]
Copied curl for both `GetCategories` calls and they are identical.

**Comment by glo80771** [comment]
Issue is reproducible and hence confirming the issue.

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug
