### ISSUE TITLE
[bug]: useCmsPage nextFetchPolicy: 'cache-first'? (also cmsBlock)

### ISSUE THREAD

**Issue by plamenh** [magento/pwa-studio#3114]
**Describe the bug**

You load a CMS page/block once and it stays like that forever.

**To reproduce**

1. Load a CMS page
2. Change content of CMS page
3. Reload CMS page
4. Old content

**Expected behavior**

Fresh content

**Possible solutions**

Change policy to something that makes sense (e.g., cache-and-network). CMS content changes. It's true it happens infrequently, but anyway, I am not aware of a way to force clients to clear their application cache (the only way to get fresh data now).

With cmsBlock we can switch policy, but given the inability to use a custom routing component (see https://github.com/magento/pwa-studio/issues/3081#issuecomment-812389729), there's no proper way to change the useCmsPage talon right now. I have to edit directly in node_modules.

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by huykon** [comment]
that's right

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
