### ISSUE TITLE
[feature]: Desktop optimization for the layered navigation

### ISSUE THREAD

**Issue by tkacheva** [magento/pwa-studio#3115]
As a Merchant I want filtering products by their attributes on product listen page to be optimized to the viewport that shopper is using *so that* I deliver better customer experience while reducing TCO 

*Preconditions*

- Website with products that have product attributes "use in layered navigation ti be set to "filterable with results" created 
- Customer is browsing a website on a desktop device 
- Customer is on product listing page

*Acceptance Criteria* 
* User sees an options to filter products on the listing page by their attributes 
* User sees product attributes collapsed by default 
* User opens the product attribute they want to filter by and sees the filtering options. Product attribute stays open until user collapses it back. 
* User selects the value of the attribute to filter by
* User sees the selected value added to the filter and product listing updated with the matching products  
* User can open another product attribute and select another attribute value to filter by. 
* User  sees the product listing updated on each attribute selection 
* User removes one of the selected values and sees the result updated
* User can change the sorting order of the product listing with the filters applied
* User can collapse or open all the product attributes

**Comment by JustinConabreeAbsolunet** [comment]
@magento I am working on this

**Comment by JustinConabreeAbsolunet** [comment]
@magento add to contributors team

**Comment by JustinConabreeAbsolunet** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by tkacheva** [comment]
@sirugh, do we have a cloud instance with the changes deployed?

**Comment by sirugh** [comment]
I don't believe so.

**Comment by fooman** [comment]
Isn't this https://pr-3137.pwa-venia.com/venia-dresses.html?page=1  it?

**Comment by sirugh** [comment]
@fooman you're right, I think I got confused. @tkacheva that should work.
