### ISSUE TITLE
Venia, PLP, filters, Color, Results show up wrong color

### ISSUE THREAD

**Issue by orienteed** [magento/pwa-studio#3116]
Test case:
1) Open PLP: https://venia.magento.com/default/venia-dresses.html
2) Filter by color: "Latte": https://venia.magento.com/default/venia-dresses.html?page=1&fashion_color%5Bfilter%5D=Latte%2C73
3) The results show up dresses in different colours

Taking as example the first product 
"Karena Halter Dress"
It seems it is reported in the results because it has, as variant, the color "Latte" but in the PLP it shows always the color "Mint" (despite the filter ask for color "Latte").

**Comment by sirugh** [comment]
@orienteed as far as I know the plp displays the "default" image for a product, not the filtered color for that product. This sounds like a feature request, so I'll close this for now but please feel free to create a new issue using the feature request template provided.
