### ISSUE TITLE
[bug]: Payment is currently unavailable in checkout default

### ISSUE THREAD

**Issue by arielapaula** [magento/pwa-studio#3117]
**Describe the bug**

Payment methods aren't showing in PWA checkout. 
I already enabled them in the Magento 2 backend as you can see in the second screenshot

**To reproduce**

1. Create pwa studio app with `yarn create @magento/pwa`
2. Change enviroment variable in `.env`
3. Allow payment methods in the backend
4. Upgrade and compile magento backend 
5. See error in PWA studio checkout

**Expected behavior**

PWA Studio checkout with payment methods allowed

**Screenshots**

![image](https://user-images.githubusercontent.com/36748003/114590227-dd625500-9c5e-11eb-872c-b03a15d08c5d.png)

![image](https://user-images.githubusercontent.com/36748003/114590356-0a166c80-9c5f-11eb-8d54-c693126843ee.png)

**Possible solutions**

**Please complete the following device information:**

-   Device: PC Linux Mint
-   Browser: Chrome
-   Browser Version : Versión 89.0.4389.90 (Build oficial) (64 bits)
-   Magento Version: Magento CLI 2.4.2

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-ui`

**Comment by wesleyalmd** [comment]
You need have extensions that add the payment method using the `checkoutPagePaymentTypes` entry point. PWA Studio offers an offiline checkmo payment extension. Have you already added it to your project?

Repo: https://github.com/magento/pwa-studio/tree/develop/packages/extensions/venia-sample-payments-checkmo

`yarn add @ magento / venia-sample-payments-checkmo`

You must create a new extension for each payment method you want to use.

**Comment by sirugh** [comment]
@arielapaula can you confirm whether your payment types have included the necessary extensions? For example, the [venia-ui](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/targets/venia-ui-intercept.js#L32-L37 intercept adds the braintree type. Any additional type will need an extension/implementation.

**Comment by sirugh** [comment]
Closing for lack of response. Please reopen and provide the info requested if you continue to have an issue.
