### ISSUE TITLE
[bug]: Configurable product selectable variation out of stock

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#3120]
**Describe the bug**

We still selectable product variation out of stock in configurable product. I think it should be make disable like magento default

**To reproduce**

1. Go to backend and make a product variation out of stock
2. Navigate on pwa site to this configurable product
3. Select out of stock variation
4. See we still selectable out of stock options.

**Expected behavior**

Disable out of stock product variation

**Screenshots**

On Magento default:
![Screenshot](https://user-images.githubusercontent.com/9253798/114690236-b4b28c00-9d40-11eb-8b31-35502f463316.png)

On PWA detail page:
<img width="1025" alt="Screen Shot 2021-04-14 at 4 37 20 PM" src="https://user-images.githubusercontent.com/9253798/114690295-c005b780-9d40-11eb-89c5-560fb896df92.png">

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: Macbook
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: 89.0.4389.128
-   Magento Version [e.g Magento Commerce 2.4]: 2.4.1

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by wesleyalmd** [comment]
@huykon Are you work on the solution? I have a modification of the useProductFullDetail talon using wrapWith that solves this problem. I could contribute here. 

![Previw](https://i.imgur.com/ocDBu1Q.png)

**Comment by nikatvaimo** [comment]
@wesleyalmd could you share an example of your talon wrapper?

**Comment by huykon** [comment]
@wesleyalmd Please contribute your solution 👍

**Comment by chatart** [comment]
@wesleyalmd Will you tackle on this one? :)

**Comment by wesleyalmd** [comment]
Yes, I'm already working on the solution

**Comment by chatart** [comment]
@wesleyalmd is there a chance that you provide the solution anytime soon ? :D

**Comment by wesleyalmd** [comment]
In a few days I will present the solution for peregrine and venia-ui. I created a module to intercept the productFullDetail talon and add an unavailable button, maybe useful to provisionally solve problem.

https://github.com/wesleyalmd/pwa-studio-product-unavailable

**Comment by sirugh** [comment]
Closing as there appears to be a solution.
