### ISSUE TITLE
[bug]: Default Category sort set to by position

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#3124]
**Describe the bug**

The category default sort order should align with the default back-end sort order.

**To reproduce**

1. open category page
2. note order of products

**Expected behavior**
Products ordered by position in ascending order 

**Screenshots**

![image](https://user-images.githubusercontent.com/455508/114962128-485d9700-9ebe-11eb-80fd-bc77e7c46eb8.png)

![image](https://user-images.githubusercontent.com/455508/114962544-f8330480-9ebe-11eb-984c-dc677202b893.png)

**Possible solutions**

see PR

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by fooman** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sirugh** [comment]
@fooman I'm assuming the other options for "product listing sort by" might include "relevance" or whatever other options are included in the dropdown?

The issue suggests that this code will now match the backend, but it will only do so if the backend has selected "position", right?

**Comment by fooman** [comment]
@sirugh this PR is about aligning out of the box behaviour of Magento and PWA Studio.

For open source I am seeing these options:
![image](https://user-images.githubusercontent.com/455508/116626014-b44ffd00-a99e-11eb-88f5-ad6c315772ae.png)

With position being the default. I do not know where relevance comes from.

As an additional feature request PWA Studio could implement the values which seem to be available via graphql:

![image](https://user-images.githubusercontent.com/455508/116626445-5839a880-a99f-11eb-960b-67891c1fe0db.png)

**Comment by fooman** [comment]
> The issue suggests that this code will now match the backend, but it will only do so if the backend has selected "position", right?

correct with position being the default on a vanilla Magento install
