### ISSUE TITLE
[bug]: Page max width is inconsistent and not compatible with PageBuilder full bleed

### ISSUE THREAD

**Issue by chris-brabender** [magento/pwa-studio#3127]
**Describe the bug**

Venia content is globally contained in a div (in Main) that implements the --venia-global-maxWidth. This restricts Page Builder content from respecting the Full Bleed option administrators may select.

![Screenshot 2021-04-16 093813](https://user-images.githubusercontent.com/5144830/115032856-ca869500-9e97-11eb-892a-8e7f51138d37.png)

Removing the max width on the Main component causes flow on issues on all other pages as they do not implement their own max width for example:

- Category Pages
- Product Pages

![Screenshot 2021-04-16 093926](https://user-images.githubusercontent.com/5144830/115032866-cd818580-9e97-11eb-9777-98b63a0ec02e.png)

_Some_ pages do implement their own max width but it is inconsistent across the overall app.

Pages with no max width:
- Order history
- Favourites
- Communications
- Account information

Pages with max width:
- Address book
- Saved payments

**To reproduce**

1. Create a new Page Builder home page with full bleed content
2. Browse to PWA site (home page)
3. See content does not extend to full bleed

1. Remove max-width on Main component
2. Browse to Category page
3. See content extends to full width without containment

**Expected behavior**

Page Builder should be able to define full bleed content while allowing other pages / content areas to be contained with a max-width.

**Possible solutions**

Follow a similar structure with Address book / Saved payments for max-width implementation.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: Desktop
-   Browser [e.g. Chrome, Safari]: All
-   Browser Version [e.g. 22]: Any
-   Magento Version [e.g Magento Commerce 2.4]: N/A

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [X] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by glo80771** [comment]
Hi chris-brabender,

Can you please give the detailed expected behavior of this ticket?

**Comment by glo82145** [comment]
We waited for more than 14 days for update on this issue, hence we are closing it. 

Please feel free to reopen if you are still have any update on the same.
