### ISSUE TITLE
[bug]: fix quantity field warning

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#3143]
**Describe the bug**

This warning is spammed several times when you load a (product?) page:

![](https://user-images.githubusercontent.com/1278869/116105745-38407700-a677-11eb-84ec-99d54bcbd3f7.png)

**To reproduce**

1. Go to `/default/night-out-collection.html`
1. Look at console warnings

**Expected behavior**

Should not see this warning in console.
### Acceptance Criteria
* Visiting the product page does not cause warnings to be logged to the browser console
* Root cause analysis: does this happen on all product pages? If not, why not?

### Test Plan
1. Visit a PDP for each product type (simple, configurable, virtual, bundled)
  1. `Bundled: /night-out-collection.html`
1. Open the browser console and verify that no warnings of the above type appear

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by volodymyrDashuk** [comment]
@magento I am working on this

**Comment by supernova-at** [comment]
@volodymyrDashuk how is this going? Are you still working on this?

**Comment by KostiantynFandeliuk** [comment]
Good afternoon everyone. 

@sirugh As far as I noticed, we are working with informed.
When I disabled the code with input fields, this notification disappeared for me. Also in the developer's repository there is a mention of this error.
We can try to apply it in solving this problem. https://github.com/joepuzzo/informed/issues/287
