### ISSUE TITLE
[bug]: Venia doesn't work with base Magento instance

### ISSUE THREAD

**Issue by MajorKuprich** [magento/pwa-studio#3144]
**Describe the bug**

Venia doesn't work with base Magento instance with sample data.

**To reproduce**

1. Install Magento 2.4.1 with sample data.
1. Install Venia 10.0.0.
1. Set up .env file for PWA (point MAGENTO*BACKEND*URL param to Magento app).
1. Build modules & start storefront server: `yarn build && yarn watch:venia`.
1. Reindex & flush cache from Magento side.
1. Many of images & categories not loading. Can't get any product page due to 404 errors.

**Expected behavior**

Storefront works correctly:
* images displaying for all products & categories
* access to categories & products as in raw Magento instance

**Screenshots**

Homepage (missing some categories pictures, many GraphQL error messages):

![](https://i.imgur.com/zxuN4Mr.png)

Category (missing products, many GraphQL error messages):

![](https://i.imgur.com/6es0iAZ.png)

Product (404 code, many GraphQL error messages):

![](https://i.imgur.com/dnlteWa.png)

**Possible solutions**

Fix GraphQL errors.

**Debug Report**

`yarn watch:venia`:

![](https://i.imgur.com/Qj81bio.png)

Magento exception log:
``{{
<2021-04-27 08:51:58> main.ERROR: Cannot query field "store*group_code" on type "StoreConfig". {"exception":"<object> (GraphQL\\Error\\Error(code: 0): Cannot query field \"store_group*code\" on type \"StoreConfig\". at /var/www/magento/vendor/webonyx/graphql-php/src/Validator/Rules/FieldsOnCorrectType.php:56)"} <]
[2021-04-27 08:51:58> main.ERROR: Cannot query field "store*group_name" on type "StoreConfig". Did you mean "store_name"? {"exception":"<object> (GraphQL\\Error\\Error(code: 0): Cannot query field \"store_group_name\" on type \"StoreConfig\". Did you mean \"store*name\"? at /var/www/magento/vendor/webonyx/graphql-php/src/Validator/Rules/FieldsOnCorrectType.php:56)"} <] 
[2021-04-27 08:51:58> main.ERROR: Cannot query field "store*sort_order" on type "StoreConfig". {"exception":"<object> (GraphQL\\Error\\Error(code: 0): Cannot query field \"store_sort*order\" on type \"StoreConfig\". at /var/www/magento/vendor/webonyx/graphql-php/src/Validator/Rules/FieldsOnCorrectType.php:56)"} <]
[2021-04-27 08:51:58> main.ERROR: Cannot query field "configurable*thumbnail_source" on type "StoreConfig". {"exception":"<object> (GraphQL\\Error\\Error(code: 0): Cannot query field \"configurable_thumbnail*source\" on type \"StoreConfig\". at /var/www/magento/vendor/webonyx/graphql-php/src/Validator/Rules/FieldsOnCorrectType.php:56)"} <]
[2021-04-27 08:51:59> main.ERROR: Cannot query field "store*group_name" on type "StoreConfig". Did you mean "store_name"? {"exception":"<object> (GraphQL\\Error\\Error(code: 0): Cannot query field \"store_group_name\" on type \"StoreConfig\". Did you mean \"store*name\"? at /var/www/magento/vendor/webonyx/graphql-php/src/Validator/Rules/FieldsOnCorrectType.php:56)"} <]
[2021-04-27 08:51:59> main.ERROR: Cannot query field "uid" on type "ConfigurableProductOptionsValues". {"exception":"<object> (GraphQL\\Error\\Error(code: 0): Cannot query field \"uid\" on type \"ConfigurableProductOptionsValues\". at /var/www/magento/vendor/webonyx/graphql-php/src/Validator/Rules/FieldsOnCorrectType.php:56)"} <]
}}``

**Please complete the following device information:**

-   Device: PC
-   Browser: Chrome 90, Firefox 77
-   Magento Version: Magento Open Source 2.4.1

[![](-- Complete the following sections to help us apply appropriate labels) -->

**Please let us know what packages this bug is in regards to:**

-   <x> `venia-concept`
-   <x> `venia-ui`
-   < > `pwa-buildpack`
-   < > `peregrine`
-   < > `pwa-devdocs`
-   < > `upward-js`
-   < > `upward-spec`
-   < > `create-pwa`

**Comment by fooman** [comment]
PWA Studio 10.0.0 is only compatible with Magento 2.4.2
source https://github.com/magento/pwa-studio/blob/develop/magento-compatibility.js#L7

**Comment by sirugh** [comment]
Thanks for providing that link @fooman. 

@MajorKuprich please report back and reopen if you have problems running with 2.4.2

**Comment by MajorKuprich** [comment]
@sirugh @fooman 
Thank You for Your help.
I've reopened topic due to still persist errors with 404 on existing category page.
Testing with Magento 2.4.2 instance.

1. Homepage not render some of categories images:
![](https://i.imgur.com/Lral0pM.png)

2. Can't access to some of categories (these which not load properly images on homepage):
![](https://i.imgur.com/bONp3fw.png)

3. Configurable/bundle product type out of stock when should be available (related issue https://github.com/magento/pwa-studio/issues/3120):
![](https://i.imgur.com/L69YLIF.png)

4. PWA report:
![](https://i.imgur.com/7p6bMT8.png)

No errors from Magento side.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by tjwiebell** [comment]
@MajorKuprich - thank you for the clarification after upgrading to 2.4.2. We've spun a couple internal bugs and stories off of this, and will leave it open to track progress. We primarily work with our own Venia Sample Data, but as you've discovered, the Luma sample data does expose some unsupported features.

1. We do not support placeholder assets served from the `/static` directory of the backend and currently don't have a client-side fallback. This is related to the second problem you found, where Categories with no products won't have an image, so it falls back to using the placeholder. This whole Category page is going to see a big refresh, and we've linked this bug to that Epic so we at least render a placeholder image here.
2. The Men Category in this sample data is configured to render a static block only, which are not yet supported, and the app correctly displays that this Category has no products. Blocks and Widgets are tightly coupled to the Luma frontend, so this paradigm likely to be replaced by PageBuilder content support only. This will also fall into that big Category page refresh.
3. We currently only support Simple and Configurable products. Bundle/Downloadable/Virtual Product support is on the roadmap, but this behavior is expected for now.

Thanks again for bringing this to our attention. We'll reach out if we have any additional questions.

**Comment by alvin3206** [comment]
> @magento
> 
> **Describe the bug**
> 
> Venia doesn't work with base Magento instance 2.4.3-p2
> 
> **To reproduce**
> 
> Steps to reproduce the behavior:
> 
> * Install Magento 2.4.3-p2 by composer on server.
> * Install Venia 12.3.0 on local.
> * Set up .env file for PWA (point MAGENTOBACKENDURL param to Magento app).
> * Install metapackage on magento side.
> * Reindex & flush cache from Magento side.
> * Build modules & start storefront server: yarn build && yarn watch:venia.
> * Can't get home page & any product page due to 404 errors.
> 
> **See screenshot**
> 
> ![pwa](https://user-images.githubusercontent.com/58581228/169785713-f6381671-80b2-4d1e-a07f-f1c4f5a46091.png)


> @magento
> 
> **Describe the bug**
> 
> Venia doesn't work with base Magento instance 2.4.3-p2
> 
> **To reproduce**
> 
> Steps to reproduce the behavior:
> 
> * Install Magento 2.4.3-p2 by composer on server.
> * Install Venia 12.3.0 on local.
> * Set up .env file for PWA (point MAGENTOBACKENDURL param to Magento app).
> * Install metapackage on magento side.
> * Reindex & flush cache from Magento side.
> * Build modules & start storefront server: yarn build && yarn watch:venia.
> * Can't get home page & any product page due to 404 errors.
> 
> **See screenshot**
> 
> ![pwa](https://user-images.githubusercontent.com/58581228/169785713-f6381671-80b2-4d1e-a07f-f1c4f5a46091.png)

Did you find the way to solve the issue?

**Comment by glo80771** [comment]
Hi @MajorKuprich ,

As per testing, we are not able to reproduce the issue with the latest Magento version - 2.4.6, and Venia version - 13.2.0.
PFA for the screenshot:
<img width="1440" alt="Screenshot 2023-07-26 at 6 55 45 PM" src="https://github.com/magento/pwa-studio/assets/127736464/86df082a-e66e-4cee-a6bb-22307401faa3">

Please let us know if we are missing anything

**Comment by glo42707** [comment]
as per process waited more than 2 weeks hence clsoing tikcet since no reply from reporter.
please feel free to reopen in case still reproducible or any update required.
