### ISSUE TITLE
[feature]: Improved loading experience for Venia

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#3148]
**Purpose**

Determine if we can come up with an elegant way to "progressively" load page-level content.

Currently, we think we are stuck showing a full-page loading spinner until we get the results of the `urlResolver` query. After that, we can instrument the app to show page-level skeletons but they'll (usually) only be in view for a short time before actual page content appears. The combination of these two things results in a ton of layout shift for the user, as they navigate these three "stages" of the page loading.

Can we do better? What other options can we consider?

**Original Ask**

As a user I would prefer to see "shimmer loader" or an app skeleton that progressively hydrates rather than a loading spinner.

Don't worry about optimizing the display prior to receiving the response from the URL resolver.

One approach might be to render a skeleton specific to page type ie Category, Cart, PDP, etc.
 Another approach might be to have each component provide a skeleton view when loading (using nbsp, or "shimmer" components).

**Comment by Jordaneisenburger** [comment]
Haven't thought about it to much but I think adding a skeleton/shimmer for each component makes more sense than a general shimmer for a whole page type. For these reasons:
- When you change the component layout you're less likely to forget you also need to update the skeleton that lives in the same folder.
- If you have components that conditionally render based on query data you're not showing a skeleton that might not even render at all.
- It's easier for 3rth party modules to supply out of the box skeletons for their components.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by fnhipster** [comment]
> Just for clarification; the demo url provided is not a pwa studio storefront right ?

That's correct.
