### ISSUE TITLE
Feedback on page: /404.html

### ISSUE THREAD

**Issue by ak77-prime** [magento/pwa-studio#3149]
``Work with GraphQL`` page goes to 404

https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/work-with-graphql/?itm_source=pwa-devdocs&itm_medium=quick_search&itm_campaign=federated_search&itm_term=graphq

**Comment by jcalcaben** [comment]
@ak77-prime was this from a search result?

**Comment by ak77-prime** [comment]
that is correct

**Comment by jcalcaben** [comment]
it looks like you ran into on an old page that no longer exists. we've updated the search index so it won't show up again.

You can find GraphQL docs about PWA Studio on this page: https://magento.github.io/pwa-studio/technologies/basic-concepts/graphql/
