### ISSUE TITLE
WrongPackageManagerError: This project can only be used with the "yarn" package manager,

### ISSUE THREAD

**Issue by Amooryjubran** [magento/pwa-studio#3151]
Every time i run yarn install i get this error

yarn install v1.22.5
$ node -e 'process.env.CI||process.exit(1)' || npx npm-is yarn
/Users/omar/node_modules/npm-is/npm-is.js:67
    throw new WrongPackageManagerError(allowed, invoked);
    ^
<img width="1460" alt="Screen Shot 2021-04-29 at 9 04 05 PM" src="https://user-images.githubusercontent.com/54118716/116636080-70bdaa80-a92e-11eb-9bfa-0b71fe8ef76c.png">

**Comment by sirugh** [comment]
Please provide the output of your `yarn build:report` command (if possible). Otherwise, provide details as described in the original issue template ie Magento version, PWA Studio version, node, yarn, npm versions, etc.

**Comment by Amooryjubran** [comment]
> Please provide the output of your `yarn build:report` command (if possible). Otherwise, provide details as described in the original issue template ie Magento version, PWA Studio version, node, yarn, npm versions, etc.

Thank you for getting back to me.
This is what i'm getting when I do the command.

<img width="818" alt="Screen Shot 2021-04-30 at 12 59 52 PM" src="https://user-images.githubusercontent.com/54118716/116728473-f6d00480-a9b3-11eb-81c1-6ce55e80dd9b.png">

**Comment by sirugh** [comment]
> This is what i'm getting when I do the command.

Ok, perhaps you do not have that version of pwa studio. In that case we need you to provide all the info requested )

**Comment by Amooryjubran** [comment]
> > This is what i'm getting when I do the command.
> 
> Ok, perhaps you do not have that version of pwa studio. In that case we need you to provide all the info requested )

the pwa version is Magento 2.3.3,  Node is v16.0.0, yarn is 1.22.5, npm is 6.14.11.

<img width="688" alt="Screen Shot 2021-04-30 at 1 31 50 PM" src="https://user-images.githubusercontent.com/54118716/116731969-6e079780-a9b8-11eb-926a-06395e3e4b61.png">

**Comment by sirugh** [comment]
@revanth0212 didn't you notice a recent issue with this command? I forget the specifics.

**Comment by jmelkun** [comment]
@Amooryjubran Have you tried setting the version of yarn using this command:
`yarn set version berry`
This resolved the issue for me.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sirugh** [comment]
> @Amooryjubran Have you tried setting the version of yarn using this command:
yarn set version berry
This resolved the issue for me.

Did you try this?

**Comment by sirugh** [comment]
Closing this for now - there's not enough information for us to debug and there have been some solutions provided. If the problem persists, please open a new bug report and fill out the provided template in full. Thanks!
