### ISSUE TITLE
[bug]: No way to edit billing address once check/mo is selected and "review order" clicked

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#3152]
**Describe the bug**

Once a user has selected check/mo payment method and clicked "Review Order", there is no way to modify billing address unless they refresh the page and re-select/re-submit

**To reproduce**

1. Go to [https://venia.magento.com](https://venia.magento.com/)
1. Add a product to cart
1. Go to checkout (as guest).
1. Fill out details and select "check/mo" as your payment method.
1. Click "Review Order"

**Expected behavior**

You should be able to edit the payment method (to modify billing address) after "submitting" it.

**Screenshots**

[!https://i.gyazo.com/2e146c5614dccb0493ad76ea5da9910f.gif!](https://gyazo.com/2e146c5614dccb0493ad76ea5da9910f)

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**
 - Device <e.g. iPhone6, PC, Mac, Pixel3]:
 - Browser [e.g. Chrome, Safari]:
 - Browser Version [e.g. 22]:
 - Magento Version [e.g Magento Commerce 2.4]:

[!-- Complete the following sections to help us apply appropriate labels! --]

**Please let us know what packages this bug is in regards to:**
 - [ ] `venia-concept`
 - [ ] `venia-ui`
 - [ ] `pwa-buildpack`
 - [ ] `peregrine`
 - [ ] `pwa-devdocs`
 - [ ] `upward-js`
 - [ ] `upward-spec`
 - [ > `create-pwa`

 

**Acceptance Criteria**
* Check/mo option is editable, similarly to other edit components on the same page

**Test Plan**
* Perform steps reported in the issue and verify check/mo billing address is editable
* Verify check/mo billing address for US and non-US address is editable

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by LucasCalazans** [comment]
Hey @sirugh, I could not reproduce this issue on develop.

Is it missing some step?

Evidence:
https://www.loom.com/share/12343c3ef53a4b8d9565aa37532e9d33
