### ISSUE TITLE
[doc]: Better spliceSource documentation

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#3155]
**Describe the request**
As a developer the docs around the [spliceSource](https://magento.github.io/pwa-studio/pwa-buildpack/reference/targetables/TargetableModule/#targetablemodulesplicesourceinstruction--this) function are fairly slim and hard for me to figure out the actual API. The example below isn't valid because we need to supply `['after', 'at', 'before'`] which I personally don't understand when I look at the [spliceSource](https://github.com/magento/pwa-studio/blob/f770d170ddba4a05a688b8b2407267ec1c474307/packages/pwa-buildpack/lib/WebpackTools/loaders/splice-source-loader.js#L19) function

When we use this function is there a way for us to easily validate that the splice is done correctly at the right position ?

Example:
```
  useCategory.spliceSource({
      source: '// The search term changed.\n'+'setCurrentPage(1);',
      index: 45, // Probably way off
      insert: ',true',
  })
```

**Possible solutions**
I'd like to see a few example added just like the other functions like `insertAfterSource`.

**Screenshots**
-

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [x] Topic Change Request (ie. spelling, organization)

**Comment by jcalcaben** [comment]
@magento export issue to JIRA project PWA as Story
