### ISSUE TITLE
[feature]: Add the possibility to allow certain packages to change code outside their namespace

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#3156]
**Is your feature request related to a problem? Please describe.**
As an agency we sometimes need to change `@magento/package` code from within our own packages `@experius/package` as an example we need to change the way a part of pwa studio works or do a bugfix that's not yet in the current released version of PWA Studio.

A more concrete example would be [this](https://github.com/magento/pwa-studio/pull/3078) bugfix to the core. It's merged but wasn't shipped with 10.0. So I'd like to patch this file with a targetable for our projects from within our own package `@experius/ui`

Unfortunately this isn't allowed, we either need to have the same namspace `@magento/peregrine` or be inside the local project. This safety check is added for security reasons. But it's also limiting to agencies because we don't want to maintain default (meaning we need this for all our projects) targetables on 20 different projects inside the customers source.

**Describe the solution you'd like**
I'd love to see a way where the developer can explicitly tell webpack to also allow package x,y and z to change code from other packages. This way we are much more flexible but still keep the security as tight since the developer needs to manually allow a certain package in their local project's webpack.

**Describe alternatives you've considered**
-

**Additional context**
-

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by jerschipper** [comment]
Is it possible for me to take a look into this and create a PR for this issue? I would also like to have this feature, but i'm not sure on how the core team thinks about this enhancement?

**Comment by sirugh** [comment]
@jerschipper we welcome contributions! If you'd like to give it a shot, please do, and let us know that you are working on it.

**Comment by sirugh** [comment]
@jerschipper are you still working on this?

**Comment by jerschipper** [comment]
@sirugh I really would like to do this. But i'm having trouble finding the correct time for it. 
The idea i had to solve this was to make the 
` file: packages/pwa-buildpack/lib/WebpackTools/ModuleTransformConfig.js`
and in that file the isBuiltin method to not to check on the package.json name, but make it check on the pwa-studio key in the package.json. That key is required to make the logic work and should be in my opinion enough to allow such changes.

How do you think about this modification @sirugh ?
