### ISSUE TITLE
Feedback on page: /technologies/magento-compatibility/

### ISSUE THREAD

**Issue by dkozlowskianl** [magento/pwa-studio#3160]
How do we find the pwa studio version?

**Comment by jcalcaben** [comment]
@dkozlowskianl you can look at your project's `package.json` file and check the `@magento/peregrine` dependency. This dependency closely follows the PWA Studio version.

In the future I will include a table in the release notes detailing the different package version changes included in a release.

**Comment by sirugh** [comment]
In the future please use the [discussions tab](https://github.com/magento/pwa-studio/discussions) or the public slack to ask questions like this, thanks!
