### ISSUE TITLE
[bug]: price filter incorrectly fetches/displays

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#3161]
**Describe the bug**

In the event that a different price filter is applied after a price filter is already applied, the query will only be for the first price filter, not the combination of the two.

This behavior might be interpreted as a bug but is actually a mis-implementation of the UI for the price filter which _only_ allows a "range" ie `{ "from": "0", "to": "100" }`.

We have several options for "fixing" this, which I will detail below.

**To reproduce**

1. Go to https://develop.pwa-venia.com/default/venia-bottoms/venia-pants.html
2. Click Filters and select Price > 100-200 and "See Results"
3. Click Filters and select Price > 0-100 and "See Results" (don't clear the previous filter)
4. See that the products are still those for the 100-200 price filter. The network will also show that only the 100-200 filter is sent in the query.

**Expected behavior**

Either:

* The price filter should use a single select "radio" instead of a checkbox or
* The price filter should use a slider allowing values from `0` to `X` where `X` is the greatest value in the available price filters list (for example: $200, [in this case](https://i.gyazo.com/ffb8dbbc62741ea04d7672317fee36ce.png))

**Screenshots**

[![Image from Gyazo](https://i.gyazo.com/a5088698e2da05ada42f4d394a703c35.png)](https://gyazo.com/a5088698e2da05ada42f4d394a703c35)

**Possible solutions**

We should investigate possible solutions of combining filters into a range, if they are sequential such as `0-100` and `100-200` or if it is even possible to send more than one filter if they are not sequential, such as `0-100` and `200-300`.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by huykon** [comment]
@sirugh this should only 1 selected of that, right?

**Comment by sirugh** [comment]
I'm not sure if these are supposed to work like single select radios or multi select checkboxes. Two questions -

* Is it possible to query gql with two or more price filters?
* What does Luma do?

If we can answer those questions we will have a good idea of what we need to do here ☺️

**Comment by huykon** [comment]
1. I think price filters must 1
2. The Luma theme only support single select for this

**Comment by sirugh** [comment]
Ok I'll verify #1 and update this issue when I get back Tuesday :)

**Comment by sirugh** [comment]
Ok - I updated the description of this ticket. We still need to have our PM/UX evaluate this issue and provide guidance for desired solution.

**Comment by Sahilsks** [comment]
@magento I am working on this

**Comment by glo80771** [comment]
Able to reproduce the issue and hence the issue is confirmed

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug
