### ISSUE TITLE
Error: Command failed: yarn workspace graphql-cli-validate-magento-pwa-queries run prepare

### ISSUE THREAD

**Issue by shrimallamanoj** [magento/pwa-studio#3173]
Getting this kind of error when executing this command yarn install

Error: Command failed: yarn workspace graphql-cli-validate-magento-pwa-queries run prepare

**Comment by sirugh** [comment]
Closing this for lack of detail. Please follow the issue template and re-open if you continue to have problems.

**Comment by shrimallamanoj** [comment]
> Hi @shrimallamanoj. Thank you for your report.
> To help us process this issue please make sure that you provided sufficient information.
> 
> Please, add a comment to [assign the issue](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#assigning-an-issue): `@magento I am working on this`
> 
> * Join [Magento Community Engineering Slack](https://opensource.magento.com/slack) and ask your questions in [#github](https://magentocommeng.slack.com/messages/C7KB93M32) channel.

 - I have installed Node (version v16.0.0), yarn (version 1.22.10) and npm (version 7.10.0)
 - Tried to install yarn install command and faced this 
![image](https://user-images.githubusercontent.com/70339528/120077769-a38fc580-c0c9-11eb-89c9-6cd36e162f4d.png)

do you need any other details, please let me know?

**Comment by sirugh** [comment]
Are you developing on Windows or WSL? Im not sure windows will work at this time.
