### ISSUE TITLE
[bug]: Trying to create custom page using pwa studio not working

### ISSUE THREAD

**Issue by sreevidyaJ** [magento/pwa-studio#3174]
Hi Team,

I'm trying to create a custom page using pwa studio. I have followed exact same steps mentioned in https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/add-a-static-route/.

 i did yarn start, it throwing below error
  ⓧ  Could not configure or access custom host. Using loopback... Cannot read property 'staging' of undefined
  ℹ  Launching UPWARD server
http://0.0.0.0:57645/

when i hit /greeting/world, ui throws page not found. 

i have also tried following https://magento.github.io/pwa-studio/pagebuilder/custom-components/setup-component/, but i didn't find files exactly.

could you please help me.

Thanks,
Sreevidya

**Comment by sreevidyaJ** [comment]
it is working

**Comment by sirugh** [comment]
Hi @sreevidyaJ, do you mind adding a little detail about what the issue was and what you did to remedy it? Would be nice to add some helpful info incase someone else has a similar issue in the future.
