### ISSUE TITLE
[feature]: Support sass by default for styling

### ISSUE THREAD

**Issue by tuna2smc** [magento/pwa-studio#3183]
**Is your feature request related to a problem? Please describe.**

Sass now poplular but i don't see it's used in project. Any reason of that or core team already plan for that
https://magento.github.io/pwa-studio/tutorials/enable-sass-less-support/
found this but this is tutorial and we need some workarounds to make it work. So can we consideration to add support sass to code base

One of the most powerful features of Sass is being able to set flag values with !default. Code support variables, mixins.
Allow nest selector

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by supernova-at** [comment]
👋  @tuna2smc - thanks for your write up!

> https://magento.github.io/pwa-studio/tutorials/enable-sass-less-support/
found this but this is tutorial and we need some workarounds to make it work.

If you don't mind, can you share with us the workarounds you had to perform? We'd like to update our documentation as opposed to supporting Sass by default for now. Thanks!

**Comment by tuna2smc** [comment]
Tried tutorials but sass styles seem not load after all 
Followed exactly steps by steps
In my opinion docs seem not cover enough, we should add more details

**Comment by tuna2smc** [comment]
css module works totally fine. But i think use sass along with css would be great improvements

**Comment by tuna2smc** [comment]
"dependencies": {
    "node-sass": "^7.0.1",
    "sass": "~1.43.4",
    "sass-loader": "^10.0.0"
  }

**Comment by tuna2smc** [comment]
![sass](https://user-images.githubusercontent.com/82012895/162753119-f6464d2c-491d-446f-901e-d07947d967cb.png)

**Comment by tuna2smc** [comment]
This seem not work in my case
