### ISSUE TITLE
[bug]: Duplicate react component key props produced when selecting variants in product detail carousel

### ISSUE THREAD

**Issue by jh0l** [magento/pwa-studio#3185]
**Describe the bug**

This is my brief understanding but it seems at least in the sample store data, for each product it's default media entry is also a variant. So the variant that is the same as the default also has the same file and label attributes. This in turn causes the Thumbnail components for the default and the variant matching the default to have the same same key so react loses track of the list of thumbnails.
You can see that in carousel.js at #L55.

**To reproduce**

1. In a venia store with venia sample data, go to any product with colour variants
2. Click on the default colour variant (matches the colour of the selected product's default carousel thumbnails).
3. Click on an alternative colour, then click on the default colour again, repeat this
4. Duplicate thumbnails for the default colour variant will be produced

In the console react will warn that it has detected duplicate key props in the thumbnail list

**Expected behavior**

Should be no duplicate keys in the carousel's thumbnail list.

**Screenshots**

[here's a recording of this behaviour](https://i.imgur.com/GkpTSuo.mp4)

**Possible solutions**

I found that using the item's id as in ```key={item.id}``` instead of ```key={`${item.file}--${item.label}`}``` fixed the issue.

**Please complete the following device information:**

-   Device: Debian
-   Browser: Firefox
-   Browser Version: 88.0.1
-   Magento Version: 2.4

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by jh0l** [comment]
@magento I am working on this

**Comment by jh0l** [comment]
@magento add to contributors team

**Comment by jh0l** [comment]
@magento I am working on this

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug
