### ISSUE TITLE
build can fail due to graphql line comments 

### ISSUE THREAD

**Issue by shadyjamal** [magento/pwa-studio#3190]
Config:
```
"magento/product-community-edition": "2.3.3"
"PWA Studio": 4.0.0
```
Magento Core and PWA studio are in separate servers.

when running yarn build in PWA studio folder, i faced a FetchError.

**Expected behavior**

Build to finish

**Debug Report**

```
yarn run v1.22.10
$ yarn run build:prod
$ yarn run clean && yarn run load-env && webpack --no-progress --env.mode production
$ rimraf dist
$ node ../pwa-buildpack/bin/buildpack load-env --core-dev-mode .
{ FetchError: invalid json response body at https://********/graphql reason: Unexpected token < in JSON at position 0
    at /home/********/packages/pwa-buildpack/node_modules/node-fetch/lib/index.js:241:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message:
   'invalid json response body at https://********/graphql reason: Unexpected token < in JSON at position 0',
  type: 'invalid-json' }
FetchError: invalid json response body at https://********/graphql reason: Unexpected token < in JSON at position 0
    at /home/********d/packages/pwa-buildpack/node_modules/node-fetch/lib/index.js:241:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

after some debugging, i found out that the error happens during webpack bundling, at this line :
`const mediaUrl = await getMediaURL();`

so i decided to test if i can do a request to my backend from PWA studio server, and this command worked successfully :

`curl -H 'Content-Type: application/json' -X POST -d '{"query": "query {storeConfig{ id secure_base_media_url} }"}' https://********/graphql`

the query worked also in Altair GraphQL client.

last thing to mention, the build was successful when using the default backend as MAGENTO_BACKEND_URL env.

i tried to list all my debugging step, any help would be appreciated . 

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by shadyjamal** [comment]
> @shadyjamal you might have luck getting an answer in the community engineering slack. It's generally easier to find debug help there.
> 
> Please do report back if you can figure out what the problem is.

i figured out the problem, some firewall rules in the backend server were blocking the requests during build (getMediaUrl, getUnionAndInterfaceTypes) because of the comments in the queries:
`# Get the media URL from the store configuration.
`
`# Introspect the GraphQL schema to obtain information about its types.
`
so to fix it either change the rules, or remove these comments.

**Comment by sirugh** [comment]
Hmm according to the [spec](https://spec.graphql.org/June2018/#sec-Comments) these are valid graphql file comments. Would you mind giving me some more info about the firewall rule that was blocking requests?

Obviously we could just remove the comments but I'm more interested in solving this issue going forward, so we could:

a) prevent future comments from being added to any `.graphql` files via linting/query validation.
b) strip comments before queries are made in [fetchQuery](https://github.com/magento/pwa-studio/blob/develop/packages/pwa-buildpack/lib/Utilities/graphQL.js#L8)
c) understand what your firewall/backend was doing to block requests.

**Comment by shadyjamal** [comment]
> Hmm according to the [spec](https://spec.graphql.org/June2018/#sec-Comments) these are valid graphql file comments. Would you mind giving me some more info about the firewall rule that was blocking requests?
> 
> Obviously we could just remove the comments but I'm more interested in solving this issue going forward, so we could:
> 
> a) prevent future comments from being added to any `.graphql` files via linting/query validation.
> b) strip comments before queries are made in [fetchQuery](https://github.com/magento/pwa-studio/blob/develop/packages/pwa-buildpack/lib/Utilities/graphQL.js#L8)
> c) understand what your firewall/backend was doing to block requests.

first i'm still a beginner when its comes to Graphql, Magento2 architecture.
when i discovered that the firewall rule caused the problem and asked the sysAdmin, he said that these comments may lead to triggering SQL injection type attacks.

he may be wrong, but i decided to remove the comments and not to take any risk.

**Comment by sirugh** [comment]
That's fine - it should be trivial to strip comments from the imported string before transmission. I'll write up a PR.

**Comment by sirugh** [comment]
See https://github.com/magento/pwa-studio/pull/3196 for fix :)
