### ISSUE TITLE
[bug]: unhandled edgecase for path "/undefined"

### ISSUE THREAD

**Issue by Flyingmana** [magento/pwa-studio#3192]
**Describe the bug**

When accessing a page with the path `/undefined` like for example `https://venia.magento.com/undefined`, then this leads to a list of errors till the page breaks. (was posted by someone else in slack)

**To reproduce**

see description.

**Expected behavior**

getting the expected page for this url without errors.

**Screenshots**

!https://user-images.githubusercontent.com/237319/119545818-85595b00-bd93-11eb-976e-87b90643f72f.png!

**Possible solutions**

the cause for this error is located in 

https://github.com/magento/pwa-studio/blob/9a2f1d32bfa91d05f2e8a07b6d7a137e10f203c5/packages/peregrine/lib/talons/MegaMenu/useMegaMenu.js#L43-L50

the minifier transforms this into:
```
                 var t = e.url_path
                      , r = e.url_suffix
                      , a = "/".concat(t).concat(r || "")
                    return n.pathname === a
```
and as javascript is a bit special, it transforms an undefined variable into the string `undefined`, so: `"/".concat(undefined): "/undefined"`, which accidentially matches, if the url path is actually `/undefined`

So the solution would be an additional check if `url_path` is `undefined`

or alternativley in
https://github.com/magento/pwa-studio/blob/9a2f1d32bfa91d05f2e8a07b6d7a137e10f203c5/packages/peregrine/lib/talons/MegaMenu/useMegaMenu.js#L107-L118

to check if `activeCategory.path` is actually defined, but as one sees, it should not actually match as an `activeCategory`, as this category does not exist.

**Debug Report**

## 

**Please complete the following device information:**

-   Device <e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]:

[!-- Complete the following sections to help us apply appropriate labels! --]

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ > `create-pwa`

**Comment by sirugh** [comment]
Thanks for the bug report and debug! We would love a PR/fix if anyone feels up for it.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by huykon** [comment]
why the route is `/undefined` will different with `/not-found` ?
