### ISSUE TITLE
[feature]: source-mapped dependencies need to render properly

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#3200]
**Is your feature request related to a problem? Please describe.**
A dependency (such as [magento-storefront-event-collector](https://github.com/adobe/magento-storefront-event-collector)) might pre-minify and provide source maps for its assets. 

We (venia-concept) _also_ minify and provide source maps for content, effectively "double" minifying these dependency assets. 

A user may want to debug or view the source of a pre-minified dependency in the browser, but because we also minify and generate source maps, this won't work. The browser gets confused and displays the minified version of the dependency as the "source" rather than the true source.

[source-map-loader](https://www.npmjs.com/package/source-map-loader) solves this problem!

> The source-map-loader extracts existing source maps from all JavaScript entries. This includes both inline source maps as well as those linked via URL. All source map data is passed to webpack for processing as per a chosen source map style specified by the devtool option in webpack.config.js. This loader is especially useful when using 3rd-party libraries having their own source maps

**Describe the solution you'd like**

* Use `source-map-loader` in DEV mode builds of venia-concept.
* Ensure we properly configure the loader to avoid excessive/unnecessary inclusion (if any).
* No new/unknown warnings are generated during a prod or dev build.

**Describe alternatives you've considered**
None, yet :p

**Additional context**
@abrhim @bradgarropy and I have achieved success using `source-map-loader` in Abram's local dev environment to view the contents of the above dependency.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by anthoula** [comment]
Looks like there is a solution proposed above, that we would be interested in reviewing a PR.
