### ISSUE TITLE
Sidebar menu not filtering by include_in_menu attribute.

### ISSUE THREAD

**Issue by aagasi** [magento/pwa-studio#3209]
**Describe the bug**

Sidebar menu not filtering by include_in_menu attribute.

**To reproduce**

1. Go to Categories.
2. Make some of the categories **include_in_menu** false and some true.
3. Check your PWA
4. See how all of categories are visible instead of only the ones with **include_in_menu** seet to true.

**Expected behavior**

PWA sidebar menu should only show the **include_in_menu** categories.

**Possible solutions**

- A workaround could be early exiting on the `CategoryTree` component:
![image](https://user-images.githubusercontent.com/12599508/120533482-24470e00-c3b7-11eb-8b13-5b9ec9db1a46.png)

Or not return the children that doesn't apply in the **useCategoryTree** talon

**Please complete the following device information:**

- mobile devices.

**Please let us know what packages this bug is in regards to:**

-   [***** ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by aagasi** [comment]
@magento I am working on this

**Comment by aagasi** [comment]
@magento add to contributors team

**Comment by aagasi** [comment]
@magento I am working on this
