### ISSUE TITLE
[bug]: Query uses non existing WishlistVisibilityEnum in CE

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#3217]
**Describe the bug**

WishlistVisibilityEnum is used in a query but is not defined in a schema in CE.
https://github.com/magento/magento2/search?q=WishlistVisibilityEnum

**To reproduce**

1. Run `validate-queries` against a CE back-end - details here https://github.com/magento/pwa-studio/pull/3198#discussion_r645189203
2. Note output

**Expected behavior**

Only graphql types supported by the back-end are used. So far it complains about

- Cannot query field "name" on type "Wishlist" 
- Unknown type "WishlistVisibilityEnum". Did you mean "WishlistItem", "WishlistItems", or "WishlistItemInput"? 
- Cannot query field "enable_multiple_wishlists" on type "StoreConfig"    

**Debug Report**

```
$ buildpack generate-build-report
  ℹ  Generating build report for @fooman/pwa-frontend@0.0.1. This may take a moment.

  ℹ  Inspecting Dependencies
    Found 8 @magento dependencies in yarn.lock
    @magento/pwa-buildpack @ 9.0.0-fooman-canary-2021-22
    @magento/upward-js @ 5.1.0-fooman-canary-2021-22
    @adobe/apollo-link-mutation-queue @ 1.0.2
    @magento/babel-preset-peregrine @ 1.1.0-fooman-canary-2021-22
    @magento/eslint-config @ 1.5.2
    @magento/pagebuilder @ 5.0.0-fooman-canary-2021-22
    @magento/peregrine @ 10.0.0-fooman-canary-2021-22
    @magento/venia-ui @ 7.0.0-fooman-canary-2021-22

  ℹ  Inspecting Magento Backend
    Not using sample backend.
    Backend is UP!

  ℹ  Inspecting System
    OS: Unable to fetch OS Version.
    Node Version: v12.13.1
    NPM Version: 6.14.5


✨  Done in 7.14s.

```

**Please complete the following device information:**

-   Magento Version [e.g Magento Commerce 2.4]: CE 2.4.2

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by RaghavendraTirumalasetti** [comment]
Hi @fooman,
Thank you for reporting and collaboration.
Please provide us with the following information:

- Summary of the issue
- Steps to reproduce
- Expected and actual results

Thanks

**Comment by glo82145** [comment]
We waited for more than 2 weeks for update on this ticket. As we have not got any update on the same, hence closing this ticket.
