### ISSUE TITLE
[feature]: Save for later credit card on checkout page using Braintree

### ISSUE THREAD

**Issue by isibaguette** [magento/pwa-studio#3244]
Hello,

Is there a way to add the Save for later checkbox on the checkout page for a credit card? Indeed, I'm using Braintree and in the checkout page, I would like to have the ability to Save a payment for later. I've checked in the pwa-studio code and on braintree settings and I found no informations about that.

Thank you

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [X ] `venia-ui`
- [ ] `pwa-buildpack`
- [X ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by glo42707** [comment]
We have triaged the ticket and sent for PO confirmation if we can take it up.

**Comment by tkacheva** [comment]
No plans to implement this feature by product engineering.
