### ISSUE TITLE
PWA Studio with Stripe Payment Integration

### ISSUE THREAD

**Issue by maheshwaran-1343** [magento/pwa-studio#3258]
Hi Team,

I have configured PWA studio with Magento 2. Now, I want to know how to implement **stripe payment integration** with the PWA storefront? Could you please provide any guidance on how can I implement this?

Thanks.

https://github.com/magento/pwa-studio/issues/1963

**Comment by maheshwaran-1343** [comment]
Hi Team,

Do you have any update here?

Thanks.

**Comment by larsroettig** [comment]
@maheshwaran-1343 pls ask this question in community slack. 

You can use https://marketplace.magento.com/stripe-stripe-payments.html and need to implement frontend by your self-reference you could find here https://github.com/magento/pwa-studio/tree/develop/packages/extensions/venia-sample-payments-checkmo

**Comment by jlo2038** [comment]
Hello any update here? thank you.
