### ISSUE TITLE
User friendly form errors

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#3267]
## Summary

Forms sometimes have errors. Currently Venia shows the user the direct error returned from GraphQL:

https://user-images.githubusercontent.com/13182778/125478454-4167acf5-5fa8-4959-8a58-a4fbc6483795.png

We should show a user friendly message instead.

## How to Reproduce

Since this issue deals with errors in the backend, you can dig into core Magento GraphQL code to trigger an error but far simpler is to "fake" an error in Venia that will trigger a GraphQL server error.

I changed the following mutation: 

https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/CheckoutPage/ShippingInformation/AddressForm/guestForm.gql.js#L14-L19

and purposefully removed the `cartId` argument:

```js
setGuestEmailOnCart(input: { email: $email })
    @connection(key: "setGuestEmailOnCart") {
    cart {
        id
    }
}
```

To trigger this error:
1. `yarn watch:venia`
1. Ensure you are signed out (guest user)
2. Add an item to your cart
3. Go to the checkout page 
4. Attempt to set a shipping address.

You should be met with the following error:

![Screen Shot 2021-07-14 at 10 12 42 AM](https://user-images.githubusercontent.com/13182778/125646648-b876683f-073a-41f2-8993-5afb9d9165bb.png)

## Acceptance Criteria
 - When a form error occurs, show a generic user-friendly message instead of the literal error returned from the GraphQL backend. Something like "An error has occurred. Please check the input and try again.". This text should be available for localization / translation.
 - Output the error from GraphQL to the console instead (when `process.env.NODE_ENV === 'development'`) for debugging / development purposes
## Related Files

<https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/FormError/formError.js>
 <https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/FormError/useFormError.js>
 <https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/i18n/en_US.json>

An example of a localized message:
 <https://github.com/magento/pwa-studio/blob/1977f38305ff6c0e2b23a9da7beb0b2f69758bed/packages/venia-ui/lib/components/AddressBookPage/addressCard.js#L136-L138>

**Comment by pankhurigoel** [comment]
@mangento I am working on this

**Comment by supernova-at** [comment]
Hi @pankhurigoel , the original description mentions 

> Output the error from GraphQL to the console instead (when process.env.NODE_ENV === 'development')

but you actually don't need the guard around `console.log` statements. They will be stripped out in `production` via our Webpack configuration:

https://github.com/magento/pwa-studio/blob/develop/packages/pwa-buildpack/lib/WebpackTools/configureWebpack/getClientConfig.js#L254.

**Comment by supernova-at** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by supernova-at** [comment]
I accidentally synced to a new issue when there was already one created. See PWA-882.
