### ISSUE TITLE
[bug]: France Region/State in billing form is displaying as integer value instead of Name

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#3322]
URL - https://develop.pwa-venia.com/

### JIRA

https://jira.corp.magento.com/browse/PWA-1712

### To Reproduce 
1. Add product to cart and go to checkout form
2. Enter shipping address with **France** as country and select shipping method
3. Enter payment method, uncheck billing is same as shipping and enter France country but different address
4. Click on Review order button
5. Now observe the region in billing address

### Expected 
Region/State name should be displayed

### Actual 
Region/State Numeric ID is displayed, which is not at all useful for customer.

### Screenshot

In the following screenshot, notice that the **Payment Information** billing address shows the number "8" instead of the proper region (ex: "Ardèche"), that displays accurately in **Shipping Information**.

![Screen Shot 2021-08-05 at 12 06 30 PM](https://user-images.githubusercontent.com/13182778/128392201-0a34ba5a-9de1-4357-b359-c5e0d3b71373.png)

**Comment by pedrochiossi** [comment]
@magento I am working on this
