### ISSUE TITLE
Wrong redirect processing on product detail page

### ISSUE THREAD

**Issue by kirillvidyuk** [magento/pwa-studio#3327]
**Describe the bug**

Wrong redirect when visiting PDP by url_key + '/' character

**To reproduce**

1. Open Product Detail Page with url_key + '/' character at the end (e.g. /default/silver-amor-bangle-set.html -> /default/silver-amor-bangle-set.html**/**)

**Expected behavior**

1. Redirected to /default/silver-amor-bangle-set.html after page loading

**Screenshots**

https://drive.google.com/file/d/112ZwbmWUuunLemLOwVJAG74j-njXO9tQ/view?usp=sharing

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thank you for the feedback. If you have figured this out and would like to contribute your solution back to core, we'd gladly accept it!
