### ISSUE TITLE
[bug]: Background repeat not working on safari

### ISSUE THREAD

**Issue by antoine-fontaine** [magento/pwa-studio#3347]
**Describe the bug**

When creating a banner / column / row with a background, the background-repeat property is automatically set to true on safari

**To reproduce**

1. Create a CMS page
2. Insert a banner with an image with low width
3. Set the Background Repeat property to no
4. Save page
5. See the result in front on Safari

**Expected behavior**

The background-image should not repeat

**Possible solutions**

The problem is when creating props in parseStorageHtml.js with createContentTypeObject function, the property value returned with Safari is 'no-repeat no-repeat'. Then this value is tested in the getBackgroundImages function in utils.js like this: backgroundRepeat: node.style.backgroundRepeat !== 'no-repeat'. Which returns true because the current value is 'no-repeat no-repeat'.

First solution:

1. Change node.style.backgroundRepeat !== 'no-repeat' test in utils.js to just node.style.backgroundRepeat
2. Then change backgroundRepeat ? 'repeat' : 'no-repeat'; to backgroundRepeat; in banner.js, column.js, row.js; tabItem.js
3. Change propTypes and propTypes comments value in these same files

Second solution:

1. Change node.style.backgroundRepeat !== 'no-repeat' to node.style.backgroundRepeat !== 'no-repeat' && node.style.backgroundRepeat !== 'no-repeat no-repeat' in utils.js

**Please complete the following device information:**

-   Device : iPhone8, Mac and iPad Pro]:
-   Browser : Safari
-   Browser Version : Version 14.0.3 (16610.4.3.1.7)
-   Magento Version : Magento Commerce 2.4.2-p1

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [x] `pagebuilder`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by larsroettig** [comment]
@magento export issue to JIRA project PWA as Bug
