### ISSUE TITLE
[bug]: add to favorites icon is misaligned on category pages

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#3350]
**Describe the bug**

On category pages, such as https://develop.pwa-venia.com/default/venia-bottoms.html?page=1, the heart icon for the "add to favorites" is misaligned with the "add to cart" button. 

![image](https://user-images.githubusercontent.com/1278869/129816495-2bb1c8e2-db34-4d60-b81c-5458747089a0.png)

**To reproduce**

1. Go to https://develop.pwa-venia.com/default/venia-bottoms.html?page=1
2. See it.

**Expected behavior**

Aligned w/ center.

![image](https://user-images.githubusercontent.com/1278869/129816515-c2a2896f-02dd-43ec-ab14-0bb13a94e55e.png)

**Possible solutions**

`align-self: center;`, probably.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by larsroettig** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by supernova-at** [comment]
@magento export issue to JIRA project PWA as Bug
