### ISSUE TITLE
[doc]: A short, simple sentence describing the doc request

### ISSUE THREAD

**Issue by renatolovato** [magento/pwa-studio#3358]
**Describe the request**
Hey everyone,

On the page [Modify the Footer Component](https://magento.github.io/pwa-studio/tutorials/pwa-studio-fundamentals/modify-site-footer/) in the section **Import new App component** there is an error. It says in the file `src/index.js` the developer should change the imports

```diff
- import App, { AppContextProvider } from '@magento/venia-ui/lib/components/App';
+ import { AppContextProvider } from '@magento/venia-ui/lib/components/App';
+ import App from './components/App';
```

However, those lines are inside the Adapter Component.

**Possible solutions**
How would you word this addition or change?

It has to show how to create the Adapter component inside the directory `src/components` and change the imports on file adapter.js

```sh
mk -p src/components/Adapter && \
node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js src/components/Adapter
```

And then, change the import on adapter.js

```diff
- import App, { AppContextProvider } from '@magento/venia-ui/lib/components/App';
+ import { AppContextProvider } from '@magento/venia-ui/lib/components/App';
+ import App from '../App';
```

Create the index.js to import the default.

```diff
+ export { default } from './adapter';
```

And finally, on `src/index.js` change the imports below:

```diff
- import Adapter from '@magento/venia-ui/lib/components/Adapter';
+ import Adapter from './components/Adapter/adapter';
```

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [x] Topic Change Request (ie. spelling, organization)

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story
