### ISSUE TITLE
[bug]: GraphQL cacheable requests always have "Authorization Bearer" header

### ISSUE THREAD

**Issue by Rado-encoder** [magento/pwa-studio#3377]
Description:

Magento provides Varnish config to cache GraphQL requests see [here](https://devdocs.magento.com/guides/v2.4/graphql/caching.html)
And for customer specific requests, Varnish should not cache the response as per the following :

``{{
# Authenticated GraphQL requests should not be cached by default
if (req.url <sub> "/graphql" && req.http.Authorization </sub> "^Bearer") {
    return (pass);
}
}}``
As you can see, Varnish will look for "Bearer" in the Authorization header which is ok when the customer is logged in and the request returns customer specific data, BUT we found out that while the customer is logged in Magento PWA includes the "Authorization Bearer" in EVERY GraphQL request even if its a non customer specific request such as CMSPages, CMSBlocks, etc, which normally can be cached, which adds a lot of unnecessary load on the server since Magento PWA fires too many GraphQL requests on every page load.

I have tested this behaviour on the Venia demo store and found the same issue there, Magento PWA includes "Authorization Bearer" header on all GraphQL requests even if its a cachable requests.

**To reproduce**

Steps to reproduce the behaviour :

1- sign up.in Venia.magento.com or any PWA store
2- login
3- check network tab on any page and search for GraphQL requests which should be cached such as CMSPages
4- check the request header you will find Authorization Bearer header exist
5- Varnish will not cache that request's response.

**Expected behavior**

This request should be cacheable by Varnish, but since it has the "Authorization Bearer" header, Varnish will treat it as customer specific request and not cache it.

<img width="1671" alt="PWA3" src="https://user-images.githubusercontent.com/89572988/130922852-2a32b89c-a451-4455-9fbf-40f6a5d31179.png">

**Possible solutions**

Either: 

1- Exclude the "Authorization" header from the cacheable requests
2- Provide Varnish configuration to filter authorised cacheable requests

**Debug Report**

n/a

-   Device : Mac
-   Browser : Chrome
-   Browser Version : 92.0.4515.131
-   Magento Version : Magento Commerce 2.4

**Please let us know what packages this bug is in regards to:**

-   < > `venia-concept`
-   <*> `venia-ui`         
-   < > `pwa-buildpack`
-   < > `peregrine`
-   < > `pwa-devdocs`
-   < > `upward-js`
-   < > `upward-spec`
-   < > `create-pwa`

**Comment by Rado-encoder** [comment]
@alecarg nothing so far, not sure why haven't they looked into it yet!

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by Sahilsks** [comment]
@magento I am working on this

**Comment by glo82145** [comment]
We are able to reproduce this issue. Hence issue is confirmed

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug
