### ISSUE TITLE
[bug]: npx @magento/pwa-buildpack create-env-file missing dependency

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#3379]
**Describe the bug**

```
npx @magento/pwa-buildpack create-env-file --use-examples .
npx: installed 594 in 89.818s
Cannot find module 'compression'
```

**To reproduce**

as per devdocs from [here](https://magento.github.io/pwa-studio/pwa-buildpack/reference/buildpack-cli/create-env-file/)
1. `git clone`
2. `cd pwa-studio`
3. `npx @magento/pwa-buildpack create-env-file --use-examples .`
4. see error

**Expected behavior**

No error

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
-   Browser [e.g. Chrome, Safari]: N/A
-   Browser Version [e.g. 22]: N/A
-   Magento Version [e.g Magento Commerce 2.4]: N/A

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by papiliond** [comment]
Is there a workaround for this?

**Comment by fooman** [comment]
You can add the package manually, ie something like
`yarn add --dev compression`

**Comment by anthoula** [comment]
Thanks for your feedback. For additional support on your question, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us).
