### ISSUE TITLE
Feedback on page: /tutorials/pwa-studio-fundamentals/modify-site-footer/

### ISSUE THREAD

**Issue by david-ziffity** [magento/pwa-studio#3386]
Section - Import new App component
could not find the below line in src/index.js
import App, { AppContextProvider } from '@magento/venia-ui/lib/components/App';

**Comment by CoutoDev** [comment]
@david-ziffity Me neither, so I try to find it by myself. I found it after look for the exact sentence `import App, { AppContextProvider } from '@magento/venia-ui/lib/components/App';` in Venia-ui components, this line is in `node_modules/@magento/venia-ui/lib/components/Adapter/adapter.js`, so I override this file and change this line to fit the tutorial.. And then update the `Adapter` import in your own `index.js` file inside the `src` folder. Works fine now..

**Comment by sezio** [comment]
Faced the same problem today. 
@CoutoDev is right : the tutorial should be updated with exact steps he describes

Thanks @CoutoDev

**Comment by laurentlepee** [comment]
Still facing this issue. Tank's @CoutoDev for this working solution.
