### ISSUE TITLE
[feature]: connect graphql to nodejs orm implementation

### ISSUE THREAD

**Issue by sivamind** [magento/pwa-studio#3403]
I would like to use below nodejs orm instead of magento zend orm.

https://github.com/Genaker/nodejento

is there a way to connect this?

**Comment by sivamind** [comment]
if below statement is true, i would like to connect new orm such as eloquent orm or nodejs orm for magento.
Magento 2 has legacy code based on abandoned Zend Framework 1 with really ugly ORM on top of outdated Zend_DB. Zend_DB is not even in the latest version.
https://github.com/Genaker/laragento

**Comment by sivajik34** [comment]
Atleast for pwa we need to use latest orm by extending resolver classes.
Present front end is latest technology,but backend is legacy tech such as zend_db.
So can we do both backend and frontend latest technology?

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Thanks for your feedback! For additional support on your question, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us).
