### ISSUE TITLE
[feature]: Comparison products should be worked 

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#3415]
**Is your feature request related to a problem? Please describe.**
As a shopper I would like to have the comparison feature on Venia storefront like Magento default. Should we integrate this feature. 
![download](https://user-images.githubusercontent.com/9253798/133221750-c29c9e83-aafe-4a3b-8e14-8061a6549b4b.png)

**Describe the solution you'd like**
The api CRUD is available https://devdocs.magento.com/guides/v2.4/graphql/mutations/create-compare-list.html

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by dupadhyay3** [comment]
@magento I am working on this

**Comment by dupadhyay3** [comment]
@magento add to contributors team

**Comment by dupadhyay3** [comment]
@magento I am working on this

**Comment by dupadhyay3** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Thanks for your feedback. If you have figured this out and would like to contribute your solution back to core, we'd gladly accept it!
