### ISSUE TITLE
[feature]: Share product to friends via email should be worked

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#3416]
**Is your feature request related to a problem? Please describe.**
As a shopper, I would like to have feature share product via email to my friends like Magento default on PWA Venia storefront. The graphQl api is already and to show this feature we should enable this on backend

<img width="1287" alt="Screen Shot 2021-09-14 at 3 24 18 PM" src="https://user-images.githubusercontent.com/9253798/133223274-edfbf4c2-b947-4ef2-8f2e-972e6d0d7ce2.png">
<img width="885" alt="Screen Shot 2021-09-14 at 3 23 05 PM" src="https://user-images.githubusercontent.com/9253798/133223379-f08e6212-b838-4db9-98fa-c83760520d29.png">
<img width="1282" alt="Screen Shot 2021-09-14 at 3 23 52 PM" src="https://user-images.githubusercontent.com/9253798/133223413-1035d255-7d39-4ac7-a39f-09d00af97ae6.png">

**Describe the solution you'd like**
Share product to friends via email. The api mutation is already https://devdocs.magento.com/guides/v2.4/graphql/mutations/send-email-to-friend.html

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Thanks for your feedback. If you have figured this out and would like to contribute your solution back to core, we'd gladly accept it!
