### ISSUE TITLE
[feature]: ReOrder feature should have in storefront

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#3417]
**Is your feature request related to a problem? Please describe.**
As a shopper I would like to use re-order an order like Magento default on Venia storefront

**Describe the solution you'd like**
The api is available https://devdocs.magento.com/guides/v2.4/graphql/mutations/reorder-items.html

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by glo42707** [comment]
We have triaged the ticket and sent for PO confirmation if we can take it up.

**Comment by tkacheva** [comment]
No plans to implement this feature by product engineering.
