### ISSUE TITLE
[bug]: Dynamic Blocks GraphQL returns non-qualified blocks

### ISSUE THREAD

**Issue by chris-brabender** [magento/pwa-studio#3418]
**Describe the bug**

2.4.3 Introduced a new GraphQL query for Dynamic Blocks (https://devdocs.magento.com/guides/v2.4/graphql/queries/dynamic-blocks.html) which should return matching configured Dynamic Blocks for a customer. Dynamic blocks can be configured in several ways for eligibility including:

- Customer Segment (guest, registered or other configured attributes)
- Related Promotions (Cart Price Rule or Catalog Price Rule)

When a dynamic block is configured to match a specific cart price rule in Luma it is not returned in the /banner/ ajax call if the cart does not match the price rule qualifying logic. The GraphQL implementation returns these dynamic blocks regardless of qualified carts meaning incorrect banners could be shown to customers.

**To reproduce**

1. Create new Cart Price Rule (eg: Free Shipping > $50, such as the default sample data rule)
1. Create a new Dynamic Block matching all segments, specify matching Cart Price Rule
1. Load Luma instance and inspect /banner/ response, dynamic block is not returned
1. Execute GraphQL query, dynamic block is returned

Below responses show dynamic block with content "YOU QUALIFY FOR FREE SHIPPING".

**Luma /banner/ response:**
{{{"data":{"items":{"salesrule":<],"catalogrule":[],"fixed":{"1":{"content":"[style]#html-body [data-pb-style=HGFQ01F]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[\/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"HGFQ01F\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Test 1[\/h2][\/div][\/div]","types":["content"],"id":"1"},"4":{"content":"[style]#html-body [data-pb-style=S1HHDNR]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[\/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"S1HHDNR\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Welcome, sign up to win big![\/h2][\/div][\/div]","types":["content"],"id":"4"},"5":{"content":"[style]#html-body [data-pb-style=L4AIVX7]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[\/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"L4AIVX7\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Win big this month[\/h2][\/div][\/div]","types":["header"],"id":"5"}}},"store_id":"1"}}}}

**GraphQL Response**
{{{
    "data": {
        "dynamicBlocks": {
            "items": [
                {
                    "uid": "MQ==",
                    "content": {
                        "html": "[style]#html-body [data-pb-style=HGFQ01F]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"HGFQ01F\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Test 1[/h2][/div][/div]"
                    }
                },
                {
                    "uid": "Mg==",
                    "content": {
                        "html": "[style]#html-body [data-pb-style=G0W9HMJ]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"G0W9HMJ\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]YOU QUALIFY FOR FREE SHIPPING!@[/h2][/div][/div]"
                    }
                },
                {
                    "uid": "NA==",
                    "content": {
                        "html": "[style]#html-body [data-pb-style=S1HHDNR]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"S1HHDNR\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Welcome, sign up to win big![/h2][/div][/div]"
                    }
                },
                {
                    "uid": "NQ==",
                    "content": {
                        "html": "[style]#html-body [data-pb-style=L4AIVX7]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}[/style][div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"][div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"L4AIVX7\"][h2 data-content-type=\"heading\" data-appearance=\"default\" data-element=\"main\"]Win big this month[/h2][/div][/div]"
                    }
                }
            ],
            "page_info": {
                "page_size": 20,
                "current_page": 1,
                "total_pages": 1
            },
            "total_count": 4
        }
    }
}}}

**Example GraphQL query:**
{{{
  dynamicBlocks(
    input: { type: SPECIFIED, locations: [CONTENT, HEADER>}
  ) {
    items {
        uid,
        content {
            html
        }
    },
    page_info {
        page_size,
        current_page,
        total_pages
    }
    total_count
  }
}}}

**Expected behavior**

Only qualified dynamic blocks should be returned to GraphQL queries.

**Screenshots**

![Screenshot 2021-09-16 104727](https://user-images.githubusercontent.com/5144830/133635417-d7bfc494-b55e-44b1-bb5f-de2420a42f8f.png)

![Screenshot 2021-09-16 105617](https://user-images.githubusercontent.com/5144830/133635426-361dccc9-a50c-4fc9-8ee1-2243f39d35c6.png)

![Screenshot 2021-09-16 105642](https://user-images.githubusercontent.com/5144830/133635436-678b93fe-61ee-43b3-98d7-ac8fb020400d.png)

**Please let us know what packages this bug is in regards to:**

-   < ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ > `create-pwa`

**Test Plan**  Assuming we are dealing only with Graphql and not Luma.
* Have pre-condition setup and verify graphql response is correct.
* If Venia starts supporting dynamic blocks then test this on Venia UI as well.

**Comment by supernova-at** [comment]
@magento export issue to JIRA project PWA as Bug
