### ISSUE TITLE
setup magento pwa on windows local machine

### ISSUE THREAD

**Issue by amitmaurya1024** [magento/pwa-studio#3424]
Hello Masters,

**OS** - Windows 10
**Node version** - 12.13
**Yarn version** - 1.22

I'm trying to install the PWA on my localhost machine. During installation I've faced lot of issues and fixed those issue now issue is when I run yarn run watch:venia it gets run with 100% then gives this error and PWA hosted URL. This error coming on both ( browser and terminal
I'm getting the following issue on browser

```
Module parse failed: Bad character escape sequence (4:79)
File was processed with these loaders:
* ../../node_modules/webpack-inject-plugin/dist/webpack-inject-plugin.loader.js
You may need an additional loader to handle the result of these loaders.
| return async function getLocale(locale) {
| if (locale === "en_US") {
> return import(/* webpackChunkName: "i18n-en_US" */'C:\xampp\htdocs\newpwa2\pwa-studio\packages\venia-concept\en_US.json');
| }
|
```

Please help me to fix this issue. Any help would be appreciated. If someone provide any document to install this on windows system that will be very helpful for me. 

Note - I'm following the magento2 pwa studio docs for install the pwa in localhost.

Thanks

**Comment by anthoula** [comment]
Thanks for your feedback! For support on your question, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us).

**Comment by CallMeSudhanshu** [comment]
@amitmaurya1024 @anthoula is this issue resolved ? where can i find the solution ?

**Comment by anthoula** [comment]
> @amitmaurya1024 @anthoula is this issue resolved ? where can i find the solution ?

For support on your question, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us).
