### ISSUE TITLE
[bug]: Braintree Integrated Paypal, Apple Pay, Google Pay not showing in PWA

### ISSUE THREAD

**Issue by magento2demo** [magento/pwa-studio#3438]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by magento2demo** [comment]
We are using Magento ver. 2.4.3 commerce and integrated the Braintree.

but only a credit card is available as a payment option. but 
- Paypal not available with Braintree
- Google pay and apple pay not available with Braintree
- amazon pay not available with pwa 

How e can add in pwa please guide

**Comment by anthoula** [comment]
Thank you for the feedback. Only Braintree credit card payments are currently supported, but we will be adding extension points to enable other payment type support. We will gladly accept a PR for additional payment type support!

**Comment by sayoojvv** [comment]
We have an issue with the Braintree Paypal dropin.
We are hitting an error payment method not recognised.  The same is working with Storefront.
@anthoula

**Comment by sayoojvv** [comment]
![image](https://user-images.githubusercontent.com/24448012/190162075-18b217ac-7663-4c4f-b086-df27b5207504.png)
