### ISSUE TITLE
PWA Shop not working

### ISSUE THREAD

**Issue by aloksinha3110** [magento/pwa-studio#3439]
Hello
I have install PWA on my server and It's running on my server with 67.1.20.x:43204 but after some minutes its stop working. I don't know what is the issue. If I run the below cmd this starts working again. 
npm run build && NODE_ENV=production PORT=43024 npm run stage:venia

Can anyone suggest what's causing this issue?

**Comment by aloksinha3110** [comment]
yarn run v1.22.5
$ yarn workspace @magento/venia-concept start
$ buildpack serve .
  ℹ  PORT is set in environment: 43024
  ℹ  NODE_ENV=production, will not attempt to use custom host or port
  ℹ  Launching UPWARD server
http://:43024/
  ✔
     UPWARD server running.

but when I close the CLI terminal its stops working, How to fix it.

**Comment by 0m3r** [comment]
I think you terminate the PWA server when you close your terminal.

If you want to start your application permanently you need something PM2
https://stackoverflow.com/questions/12701259/how-to-make-a-node-js-application-run-permanently
https://swissuplabs.com/blog/how-to-start-using-magento-2-pwa-studio-on-your-hosting-a-complete-guide/#how-to-use-pwa-studio-with-pm2
