### ISSUE TITLE
[feature]: Magento B2B Commerce feature Not avilbale in PWA

### ISSUE THREAD

**Issue by magento2demo** [magento/pwa-studio#3442]
We are using Magento ver. 2.4.3 Commerce and we are developing the PWA. 

We are not able to use any B2B features in PWA for exp: Quote features

- So on the Cart page quote feature is not available 
- My account section no B2B features available 

Can you tell me when we will get its all features in pwa.

**Comment by anthoula** [comment]
B2B features are on our roadmap. Please see [Product Roadmap](https://github.com/magento/pwa-studio/wiki/Roadmap) for more details!
