### ISSUE TITLE
[bug]: Contact Us Page Feature not avilable in PWA

### ISSUE THREAD

**Issue by magento2demo** [magento/pwa-studio#3443]
We are using Magento ver. 2.4.3 commerce 

There is no feature available for the contact us page.

Please guide how we can add this page in pwa

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by tkacheva** [comment]
Contact Us page is added with PWA v12.2 release
https://venia.magento.com/contact-us
