### ISSUE TITLE
[feature]: Prevent the body of the page from scrolling while the menu is open

### ISSUE THREAD

**Issue by luke-denton-aligent** [magento/pwa-studio#3458]
**Is your feature request related to a problem? Please describe.**
Two related issues:
As a user, when I open the mobile menu, I find that I'm still able to scroll the background page.
As a user, when I open a modal, I find that I'm still able to scroll the background page.

**Describe the solution you'd like**
When the menu is open, lock the page from scrolling, so that I can only scroll the inner content of the menu.
Prevent repaint by compensating for the loss of the vertical scrollbar when 

**Additional context**
![Menu Background Page Still Scrolls](https://user-images.githubusercontent.com/18253422/135529827-5cf71dc5-55d2-43fc-a9e7-32f288f78f22.gif)

Please excuse this recording - I was trying to capture it against `veniw.magento.com`, however kept running into a bug that would cause the page to re-render, and not render cart items, despite items still being in my cart.
It is possible to see that as soon as the modal opens, the scrollbar for the background page is still visible
![Background Page Still Scrolls](https://user-images.githubusercontent.com/18253422/135529837-2bee136f-d5de-46f4-ad9d-b5cfb60522a3.gif)

**Please let us know what packages this feature is in regards to:**
- [x] `venia-ui`

**Comment by luke-denton-aligent** [comment]
I have been looking into the code for this, and can see that scroll lock is implemented, but commented out. So now I'm a bit confused what the expected behaviour is

**Comment by drpayyne** [comment]
Can someone please look into this? It seems rather simple. Thank you.

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Thank you for the feedback. From a UX perspective, it is ok to lock the background from scrolling when side menu is open.We are tracking this internally but it is assigned a low priority.  If you have figured this out and would like to contribute your solution back to core, we'd gladly accept it!

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Story
