### ISSUE TITLE
[doc]: guide for setup tailwind

### ISSUE THREAD

**Issue by mrtuvn** [magento/pwa-studio#3462]
**Describe the request**
Any documents related with setup this feature ? 
Thanks

Added file tailwind.css in packages/venia-concept/src/ and import some basic components but after build seem class styles not applied
Example ultility class from tailwind
![markup](https://user-images.githubusercontent.com/1908873/135755590-fb6f19ec-7164-4ee7-b78d-c4a930d5059b.png)

Is this feature under development or ready to use ?

**Possible solutions**
How would you word this addition or change?

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by mrtuvn** [comment]
close because team already integrated tailwindcss

**Comment by itka0526** [comment]
> How did you integrate it? Please let me know
