### ISSUE TITLE
Region is required in PWA although this option is disabled in Magento , and is not required on normal storefront .

### ISSUE THREAD

**Issue by Watch3ruk** [magento/pwa-studio#3468]
Region is required in PWA although this option is disabled in Magento , and is not required on normal storefront . 

Set default country to United Kingdom , disable State is Required for UK .
Try to create order , in SHIPPING INFORMATION - state will be required , 

**Screenshots**

![Checkout - Garden Haven - Google Chrome 06_10_2021 21_01_01](https://user-images.githubusercontent.com/48841019/136284126-a6134811-f4b1-4e5b-9350-126794618859.png)
![Checkout - Garden Haven - Google Chrome 06_10_2021 20_59_29](https://user-images.githubusercontent.com/48841019/136284143-307c200f-e6c0-42ef-ab59-4b3d0ee0abf4.png)

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]: magento CE 2.4

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by Sahilsks** [comment]
@magento I am working on this

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug
