### ISSUE TITLE
[bug]: Duplicate splitChunks configuration

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#3492]
**Describe the bug**
Whilst investigating #3490 I noticed that there is a duplicate configuration of the splitChunks functionality.

**To reproduce**
https://github.com/magento/pwa-studio/blob/4aaef469edf797cfb17823316229646425004e52/packages/pwa-buildpack/lib/WebpackTools/configureWebpack/getClientConfig.js#L149 is also configured on https://github.com/magento/pwa-studio/blob/4aaef469edf797cfb17823316229646425004e52/packages/pwa-buildpack/lib/WebpackTools/configureWebpack/getClientConfig.js#L228

**Expected behavior**
Just have one splitChunks definition 

**Possible solutions**
Since L149 is the base config I would remove the config at L228

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by Jordaneisenburger** [comment]
@magento I am working on this

**Comment by supernova-at** [comment]
@magento export issue to JIRA project PWA as Story
