### ISSUE TITLE
[feature]: Possible wrong usage of useMemo

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#3503]
**Is your feature request related to a problem? Please describe.**
Inside the Product Talon I believe that the `useMemo` used for the `productUrlSuffix` is too agressive since we're not doing any expensive calculations inside the `useMemo`,  since there is a cost of using `useMemo` I believe this to have a negative impact on the performance.

https://github.com/magento/pwa-studio/blob/1ea34ff5dcc7a3c99f10ea6a5dfea27a33ad4027/packages/peregrine/lib/talons/RootComponents/Product/useProduct.js#L43

**Describe the solution you'd like**
Remove the `useMemo` and just assign a normal const

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- < > `venia-concept`
- < > `venia-ui`
- < > `pwa-buildpack`
- <x> `peregrine`
- < > `pwa-devdocs`
- < > `upward-js`
- < > `upward-spec`
- < > `create-pwa`

##Test Plan
1. Run Cypress
1. Verify url suffix for category product still works on default and French store view
1. Check Apollo cache still working properly

**Comment by wesleyalmd** [comment]
maybe the `storeConfig` query data should be in a context, like for example:

```
const [{ storeConfig }, appApi] = useAppContext();

const {
    product_url_suffix,
    category_url_suffix
} = storeConfig;
```
