### ISSUE TITLE
frontend problem (home page)

### ISSUE THREAD

**Issue by jaballah-dorsaf** [magento/pwa-studio#3512]
hi, I installed pwa-concept v12 and I am using Magento 2.4.3-p1 backend, I noticed that pwa displays the same magento homepage, I want to separate magento2 and pwa frontend (exp: frontend magento2 = home page 2 and frontend pwa = home page 3) , thank you for your help
<img width="928" alt="home2" src="https://user-images.githubusercontent.com/55697769/138691389-2994d3eb-75c3-4ed3-86c6-4324e37b8a47.PNG">
<img width="805" alt="home3" src="https://user-images.githubusercontent.com/55697769/138691874-42a82c18-1d83-4ad5-8dbf-a994d3836587.PNG">

**Comment by 0m3r** [comment]
would you like to have a different theme for each store view?

**Comment by jaballah-dorsaf** [comment]
> Souhaitez-vous avoir un thème différent pour chaque vue de magasin ?

@0m3r ,  yes i like to have a different theme for each store view?

**Comment by 0m3r** [comment]
@jaballah-dorsaf I can give you my workaround but it requires modification both in Magento 2 and PWA-studio

```.graphqls
type Query {
    getThemeDataByStore : ThemeData @resolver(class: "YourVendor\\PwaStudioIntegration\\Model\\Resolver\\ThemeDataResolver")
    @doc(description: "The theme data")
}
type ThemeData @doc(description: "The type contains information about a store config") {
    theme_id : Int @doc(description: "The ID number assigned to the theme")
    store_id : Int @doc(description: "The STORE ID number assigned to the theme")
    code : String @doc(description: "A code assigned to the theme")
    area : String @doc(description: "A area (frontend) assigned to the theme")
    theme_path : String @doc(description: "A path (code) assigned to the theme")
    theme_title : String @doc(description: "A title assigned to the theme")
}
```

**Comment by 0m3r** [comment]
https://github.com/magento/pwa-studio/milestone/26

**Comment by anthoula** [comment]
Theming is a feature on our roadmap that we are aiming to release soon. Please see our [Product Roadmap](https://github.com/magento/pwa-studio/wiki/Roadmap) for more details!
