### ISSUE TITLE
[feature]: Hidden payload request in PWA

### ISSUE THREAD

**Issue by MinhOmega** [magento/pwa-studio#3517]
**Hidden query params string or payload in header request**
Had some reason so i need to hidden or encode this. 
![image](https://user-images.githubusercontent.com/49482201/138803195-4cd32896-789a-4748-b3d9-e8b1681cd6de.png)
Image 1: I use pwa version 10 and in future will upgrade to 11 & 12. With use option `useGETForQueries: true`
![image](https://user-images.githubusercontent.com/49482201/138803237-4f50dd12-75f9-4455-a568-fc0ae213a2c8.png)
Image 2: I use older version pwa, current is 7. without `useGETForQueries` in adapter file config.

**Comment by supernova-at** [comment]
Hi @MinhOmega , I'm not quite sure what you're asking for here, would you mind providing more detail? I'm assuming these are screenshots of the network tab?

**Comment by LordZardeck** [comment]
I'm actually not sure what exactly the author is saying, but I'm actually curious as to why `useGETForQueries` was set to true. Especially since there's a limitation with URL length limits.

**Comment by anthoula** [comment]
Thank you for the feedback. We would need some additional information. Closing until further information is provided. For additional support, please see our Slack channel: https://magentocommeng.slack.com/messages/C71HNKYS2
