### ISSUE TITLE
[bug]: Yarn bundlesize is failing on the SERVER chunk

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#3554]
**Describe the bug**

When running the bundleSize checker it fails on the SERVER chunk

**To reproduce**

1. from root run yarn bundlesize
2. Notice it fails on SERVER.js chunk

**Expected behavior**

It passes the chunk size checks

**Possible solutions**

A simple fix would be to exclude the server chunk from the main glob pattern like so:
`./packages/storefront/dist/{client,vendors,sw}.!(*.SERVER).js`

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by supernova-at** [comment]
@magento export issue to JIRA project PWA as Bug
