### ISSUE TITLE
[bug]: Product Price do not display properly when Offer price is added, on Product details page.

### ISSUE THREAD

**Issue by gitamitgit** [magento/pwa-studio#3558]
**Describe the bug**

Product Price do not display properly when Offer price is added, on Product details page.

**To reproduce**

1. Install Magento 2.4.3
2. Create new product and assign price for example - $ 255.
3. Inside Advanced Pricing assign $240 to Wholesale Customer Group.
4. create a new customer or assign `Wholesale` customer group to a customer.
5. Now in Venia Theme, Open this new Product , you will see the price $255
6. login with the customer to which we assign `Wholesale` customer group.
7. It should show offer price $240 with regular price $255 , but nothing happens on product detail page and continue to show price $255.
8. if you add this same product to cart , then you will see correct offer price is added and displayed there. 

**Expected behavior**

It should show offer price $240 with regular price $255 , but nothing happens on product detail page and continue to show price $255.

**Screenshots**

https://nimb.ws/A6v4CQ
https://nimb.ws/h1E0an

**Possible solutions**

Looks like the customer authorization is missing some where while getting response , due to which offer price is missing.

**Please complete the following device information:**

-   Device [PC]:
-   Browser [Chrome]:
-   Browser Version [Version 94.0.4606.71 (Official Build) (64-bit)]:
-   Magento Version [Magento Commerce 2.4.3]:

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by gitamitgit** [comment]
@magento-admin , same price issue for customer group offer price is coming on Product Listing page.

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thanks for the feedback, we recently fixed Product Pricing: https://github.com/magento/pwa-studio/pull/3760/
