### ISSUE TITLE
[bug]: Cannot find field "newsletter_enabled" on type StoreConfig, while building the pwa-studio

### ISSUE THREAD

**Issue by JDhere** [magento/pwa-studio#3565]
**Describe the bug**

I have installed all the dependencies for the installation and have cloned the repo and gave `yarn install`.

I change the base url in the .env to my ip. 
`MAGENTO_BACKEND_URL=http://192.168.x.xx/`

Then I ran the `yarn build` command

Then this error is coming:

> As of version 12.1.0, PWA Studio requires the appropriate PWA metapackage to be installed on the backend.
For more information, refer to the 12.1.0 release notes here: https://github.com/magento/pwa-studio/releases/tag/v12.1.0
Error: Cannot query field "newsletter_enabled" on type "StoreConfig". (... 1 errors total)
    at /var/www/html/magento243_v1/pwa-base/pwa-studio/packages/pwa-buildpack/lib/Utilities/graphQL.js:54:21
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/var/www/html/magento243_v1/pwa-base/pwa-studio/packages/venia-concept/webpack.config.js:61:29)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /usr/share/yarn/lib/cli.js run build
Directory: /var/www/html/magento243_v1/pwa-base/pwa-studio/packages/venia-concept
Output:
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I have also installed the metapackages from [here](https://developer.adobe.com/commerce/pwa-studio/metapackages/open-source/)
Still no use the same error comes...

And also I tried with the default backend url MAGENTO_BACKEND_URL=https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/ and it this https://magento-venia-concept-xxxx.local.pwadev:8474/ 
But that page showed this error:
![image](https://user-images.githubusercontent.com/94677353/142592525-e7a79348-5faf-440c-a330-fb5351415eee.png)

**To reproduce**

1. Clone the repo
2. cd dir
3. yarn install
4. Now change the value of .env file inside pwa-studio/packages/venia-concept/.env 
5. MAGENTO_BACKEND_URL=http://192.168.x.xx/
6. yarn build

**Expected behavior**

It should have installed the theme and have shown on the frontend.

**Screenshots**

![Screenshot from 2021-11-19 14-06-35](https://user-images.githubusercontent.com/94677353/142592125-e7d7f8b7-c940-4e9f-b74e-4280b87a4cec.png)

**Possible solutions**

No idea

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: Version 96.0.4664.45 (Official Build) (64-bit)
-   Magento Version [e.g Magento Commerce 2.4]: Magento Community 2.4.3

**Please let us know what packages this bug is in regards to:**

-   [x] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [x] `create-pwa`

**Comment by JDhere** [comment]
@magento I am working on this

**Comment by Gokul19919** [comment]
Iam also facing this issue

**Comment by Watch3ruk** [comment]
in magento root  : 
`composer require magento/pwa`
then :
`php bin/magento module:enable --clear-static-content Magento_ContactGraphQlPwa
php bin/magento module:enable --clear-static-content Magento_NewsletterGraphQlPwa
php bin/magento module:enable --clear-static-content Magento_QuoteGraphQlPwa`

**Comment by TeddyMageplaza1** [comment]
Thank you!

**Comment by spjoshis** [comment]
When i was installing `magento/pwa`, it gave below error
```
 Problem 1
    - magento/module-contact-graph-ql-pwa 0.2.0 requires php ~7.3.0||~7.4.0 -> your PHP version (8.1.4) does not satisfy that requirement.
    - magento/pwa 0.2.0 requires magento/module-contact-graph-ql-pwa 0.2.* -> satisfiable by magento/module-contact-graph-ql-pwa[0.2.0].
    - Installation request for magento/pwa ^0.2.0 -> satisfiable by magento/pwa[0.2.0].
```

Below are the environment details
Magento: 2.4.4
PHP: 8.1.4

**Comment by Watch3ruk** [comment]
ok , and you need help with ? says it all . 
magento/module-contact-graph-ql-pwa 0.2.0 requires php ~7.3.0 you have 8.1.4 , rest fails on this . wait till pwa 12.4 they will have php 8.1 support . 
or fork  magento/pwa ^0.2.0 , made the changes install from the fork.

**Comment by spjoshis** [comment]
Thanks

**Comment by chrom** [comment]
Magento 2.4.4
`
 composer require magento/pwa
Info from https://repo.packagist.org: #StandWithUkraine

In PackageDiscoveryTrait.php line 375:
                                                                                                                                                                                                                 
  Could not find a matching version of package magento/pwa. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable). `

**Comment by Vasile-Peste** [comment]
> 

`Error 503 Backend fetch failed`
Right after enabling the modules...

**Comment by Vasile-Peste** [comment]
> in magento root :
> `composer require magento/pwa`
> then :
> `php bin/magento module:enable --clear-static-content Magento_ContactGraphQlPwa`
> `php bin/magento module:enable --clear-static-content Magento_NewsletterGraphQlPwa`
> `php bin/magento module:enable --clear-static-content Magento_QuoteGraphQlPwa`

`Error 503 Backend fetch failed`
Backend response right after enabling the components...

**Comment by danmooney2** [comment]
> Magento 2.4.4
> 
> ```
>  composer require magento/pwa
> Info from https://repo.packagist.org: #StandWithUkraine
> 
> In PackageDiscoveryTrait.php line 375:
>                                                                                                                                                                                                                  
>   Could not find a matching version of package magento/pwa. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable). 
> ```

Running `composer config --no-interaction --ansi repositories.venia-sample-data composer https://repo.magento.com` beforehand fixed the issue for me

**Comment by danmooney2** [comment]
Also Magento_QuoteGraphQlPwa seems to have been removed and merged into core https://github.com/magento/magento2-pwa/commit/96c5f5f2ed31865f0b87f096221ddb9245f194da
