### ISSUE TITLE
[bug]: Price filter not showing currency symbol

### ISSUE THREAD

**Issue by drpayyne** [magento/pwa-studio#3570]
**Describe the bug**

Is there a reason why the price filter doesn't display the currency symbol? This is something I'm happy to contribute if someone gives me a 👍🏽. It seems too basic that I feel something is blocking this?

**Screenshots**

<img width="154" alt="image" src="https://user-images.githubusercontent.com/22623301/142743731-ef4cb8c7-25a7-492c-a329-e87340e0c800.png">

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by drpayyne** [comment]
@magento I am working on this

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
If you have figured this out and would like to contribute your solution back to core, we'd gladly accept it!

**Comment by drpayyne** [comment]
Hello, yes. I will get around to contributing this back in the next couple of weeks. Thank you!

**Comment by denyskuz** [comment]
@magento I am working on this

**Comment by Sahilsks** [comment]
@magento I am working on this

**Comment by denyskuz** [comment]
@magento I am working on this

**Comment by glo80771** [comment]
Issue is reproducible and hence confirming the issue

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by glo82145** [comment]
This issue is resolved by merging PR https://github.com/magento/pwa-studio/pull/4173.
