### ISSUE TITLE
Problem access a product 

### ISSUE THREAD

**Issue by jaballah-dorsaf** [magento/pwa-studio#3581]
Hi , I installed the v12.0 version of a pwa with a magento v2.4.3-p1 back-end , I get an error if I access a product , can you help me 
<img width="927" alt="fiche produit" src="https://user-images.githubusercontent.com/55697769/143589085-eba82518-d61b-4c4e-8e30-dd4ea73b87c5.PNG">
<img width="959" alt="venia product" src="https://user-images.githubusercontent.com/55697769/143589434-89f79764-a95a-4d7c-9bbd-597a248b42de.PNG">

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thank you for the feedback. Please provide additional details for your issue, including steps to reproduce. If issue still occurs with steps, please reopen as a Bug.
