### ISSUE TITLE
[doc]: Could not find a matching version of package magento/venia-sample-data.

### ISSUE THREAD

**Issue by ronytran** [magento/pwa-studio#3582]
Hello everyone,

**Describe the request**
I have installed venia-sample-data on my local by following this guide https://developer.adobe.com/commerce/pwa-studio/guides/packages/venia/sample-data/, but I got an issue in **step 2** below:

[InvalidArgumentException]                                                                                                                                                                                                
Could not find a matching version of package magento/venia-sample-data. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).

**System**
OS: Linux Ubuntu 20.04
Magento EE ver. 2.4.3-p1

**Screenshots**

![image](https://user-images.githubusercontent.com/82105233/143658145-8fa424a5-b06f-4f98-9618-2dd945b52731.png)

Can anyone help me?

**Comment by laurentlepee** [comment]
Hi @ronytran ,

got same issue, I don't know if I/We miss something or there is a real issue.
To get around you can add content of `requires` and `repositories` like in https://github.com/magento/pwa-studio/issues/261#issuecomment-427603993 in your composer.json, it will do the job.

I hope this helped

**Comment by ronytran** [comment]
Hi @laurentlepee sure, thanks for your comment.

**Comment by santiagozky** [comment]
hello,
Im having the same issue with no luck. executing that script from #261 does not seem to have worked. the composer.json seems updated, but I dont see any venia stuff  being installed.

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Thanks for your feedback, these docs have recently been updated. For additional support, please see our Slack channel: https://magentocommeng.slack.com/messages/C71HNKYS2
