### ISSUE TITLE
[bug]: Order history crash on order items that have no image

### ISSUE THREAD

**Issue by codynguyen1** [magento/pwa-studio#3585]
Order history crashes when an order contains items that have no image
### Preconditions
1. Product is created with no image associated with it.
1. Product is configured to show up in the storefront.

### Steps to reproduce the behavior:
1. Login to Venia
1. Place order with the product that has no image
1. View order history

### Expected behavior

Can view the order normally
### Actual

Application crashes with error
### Screenshots

[Error Screenshot](https://user-images.githubusercontent.com/16347586/144031051-d7e788de-5097-4821-9f3b-f5e19ebd9d77.png)

 
### Test Plan 
 Precondition - 
 - Create a simple product with image
 - Create configurable product with images.
 - Create simple product without image
 - Create configurable product  without image (both parent and child)
 - Create configurable product  with image for child but not parents
 - Create configurable product  with image for parent but not for childs
 - On store view 1  go to Stores > configurations > Sales > Checkout > Configurable Product Image set to parent (Default)
 - On store view 2  go to Stores > configurations > Sales > Checkout > Configurable Product Image set to Child image

Execute - 
 - Add all above products to cart on store view 1 and place order and verify Order in Order history page for data and right images as per configs.
 - Verify above on store view 2 as well.
 - Run existing cypress suite

### Cypress test coverage
 - It's very rare to get this kind of code issues so no cypress test needed. But try automate cases in Unit tests.

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug
