### ISSUE TITLE
[bug]: Breadcrumbs 'Shop' link redirects to '/shopnull'

### ISSUE THREAD

**Issue by chiranjeevi-cj** [magento/pwa-studio#3602]
**Describe the bug**

1. In magento admin, if we set an empty value to Category URL Suffix(Stores->configuration->catalog->catalog->search engine optimization)
1. When we call storeConfig query it will return null.
`query{storeConfig{id<ins>category*url_suffix</ins>_*typename`}}
{{{
    "data": {
        "storeConfig": {
            "id": 1,
            "category*url*suffix": null,
            "__typename": "StoreConfig"
        }
    }
}}} 
1. Null is not validated for parent category

**To reproduce**

1. Go to admin and unset the value of Category URL Suffix'admin->Stores->configuration->catalog->catalog->search engine optimization'
1. Save the configuration 
1. open a storefront and click on any category and click on any product
1. in breadcrumbs click on the shop category(which is the parent category to all the categories)
1. now 404 page will be displayed
1. check the URL it should be /shop but it will be /shopnull

**Expected behavior**

**Screenshots**

<img width="974" alt="Screenshot 2021-12-07 at 12 09 58 PM" src="https://user-images.githubusercontent.com/52098385/144979296-5ed72473-1028-4396-84fd-074d3e7a4c16.png"]

**Possible solutions**

Add validation in https://github.com/magento/pwa-studio/blob/8f9ccd26c35c015cc16bc709c31f474556cd6261/packages/peregrine/lib/talons/Breadcrumbs/useBreadcrumbs.js#L15

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]:

[!-- Complete the following sections to help us apply appropriate labels! --]

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ > `create-pwa`

**Comment by chiranjeevi-cj** [comment]
@magento I am working on this

**Comment by chiranjeevi-cj** [comment]
Hi @mikhaelbois, Have a look at this issue.  I faced this issue in my project. I have raised a PR(simple and small fix).

**Comment by supernova-at** [comment]
@magento export issue to JIRA project PWA as Bug
