### ISSUE TITLE
[bug]: UpwardServerError: Request did not evaluate to a valid response

### ISSUE THREAD

**Issue by hardikKgn** [magento/pwa-studio#3610]
UpwardServerError: Request did not evaluate to a valid response, because: 
Error: Context value 'veniaPageTypeNonce' not defined in {
  veniaResponse: {
    resolver: 'conditional',
    when: [ [Object], [Object], [Object] ],
    default: 'veniaAppShell'
  },
  staticFromRoot: { inline: { status: 200, headers: [Object], body: [Object] } },
  contentTypeFromExtension: {
    when: [ [Object], [Object], [Object] ],
    default: { inline: 'text/html' }
  },
  fileExtension: {
    resolver: 'conditional',
    when: [ [Object] ],
    default: { inline: '' }
  },
  veniaProxy: {
    resolver: 'proxy',
    target: 'env.MAGENTO_BACKEND_URL',
    ignoreSSLErrors: { when: [Array], default: [Object] }
  },
  veniaAppShell: {
    resolver: 'inline',
    inline: { status: [Object], headers: [Object], body: [Object] }
  },
  veniaStatic: {
    resolver: 'directory',
    directory: { resolver: 'inline', inline: '.' }
  },
  veniaStaticIncludes: {
    resolver: 'directory',
    directory: { resolver: 'inline', inline: './venia-static' }
  },
  veniaSecurityHeaders: {
    resolver: 'inline',
    inline: {
      'content-security-policy': [Object],
      'strict-transport-security': [Object],
      'x-content-type-options': [Object],
      'x-frame-options': [Object],
      'x-xss-protection': [Object]
    }
  },
  status: 'veniaResponse.status',
  headers: 'veniaResponse.headers',
  body: 'veniaResponse.body'
}.
    at ResolverVisitor.upward (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/ResolverVisitor.js:46:19)
    at /home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/ResolverVisitor.js:19:38
    at Array.map (<anonymous>)
    at ResolverVisitor.downward (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/ResolverVisitor.js:18:44)
    at Context.get (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/Context.js:80:40)
    at ResolverVisitor.upward (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/ResolverVisitor.js:66:33)
    at /home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/resolvers/TemplateResolver.js:53:40
    at Array.map (<anonymous>)
    at TemplateResolver.resolve (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/resolvers/TemplateResolver.js:51:49)
    at ResolverVisitor.upward (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/ResolverVisitor.js:57:29)
    at /home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/resolvers/InlineResolver.js:22:40
    at Array.map (<anonymous>)
    at InlineResolver.resolve (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/resolvers/InlineResolver.js:20:37)
    at ResolverVisitor.upward (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/ResolverVisitor.js:57:29)
    at /home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/ResolverVisitor.js:19:38
    at Array.map (<anonymous>)
    at Object.html (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/middleware.js:101:33)
    at ServerResponse.res.format (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/webpack-dev-server/node_modules/express/lib/response.js:675:13)
    at UpwardDevServerPlugin.<anonymous> (/home/kgn-pc/Desktop/KGN/pwa-studio-fundamentals/node_modules/@magento/upward-js/lib/middleware.js:93:25)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by sonnybooth-amp** [comment]
Did you ever find a solution? Came across the same error myself.

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by sonnybooth-amp** [comment]
Adding (Magentos)

```
veniaPageTypeNonce:
  resolver: inline
  inline:
    nonce:
      resolver: computed
      type:
        resolver: inline
        inline: pageTypeNonce
```

to my projects upward.yml fixed this issue but now I have the error  "Error: Unrecognized resolver type: computed"

**Comment by ankitseepossible** [comment]
@magento any solution ? I also have the error.

**Comment by ankitseepossible** [comment]
@sonnybooth-amp : I just solved error by replacing old project's `venia-ui/upward.yml` with new project's `venia-ui/upward.yml`.

veniaResponse:
    resolver: conditional
    when:
        - matches: request.url.pathname
          pattern: '^/(graphql|rest|media)(/|$)'
          use: veniaProxy
        - matches: request.url.pathname
          pattern: '^/(robots\.txt|favicon\.ico|manifest\.json)'
          use: staticFromRoot
        - matches: fileExtension
          pattern: '(js|json|png|jpg|gif|svg|ico|css|txt)'
          use: veniaStatic
    default: veniaAppShell

staticFromRoot:
    inline:
        status: 200
        headers:
            resolver: inline
            inline:
                content-type: contentTypeFromExtension
                cache-control:
                    when:
                        - matches: env.NODE_ENV
                          pattern: 'production'
                          use:
                            inline: public, max-age=604800
                    default:
                        inline: no-cache, no-store, must-revalidate
        body:
            resolver: file
            parse:
              inline: text
            encoding:
              inline: binary
            file:
                resolver: template
                engine: mustache
                provide:
                    filename: request.url.pathname
                template:
                    resolver: inline
                    inline: './venia-static/{{ filename }}'

contentTypeFromExtension:
    when:
        - matches: fileExtension
          pattern: '^ico$'
          use:
              inline: image/x-icon
        - matches: fileExtension
          pattern: '^txt$'
          use:
              inline: text/plain
        - matches: fileExtension
          pattern: '^json$'
          use:
              inline: application/json
    default:
        inline: text/html

fileExtension:
    resolver: conditional
    when:
        - matches: request.url.pathname
          pattern: '\.(.*)$'
          use: $match.$1
    default:
        inline: ''
veniaProxy:
    resolver: proxy
    target: env.MAGENTO_BACKEND_URL
    ignoreSSLErrors:
      when:
          - matches: env.NODE_ENV
            pattern: 'production'
            use:
              inline: false
      default:
        inline: true

veniaAppShell:
    resolver: inline
    inline:
        status:
            resolver: inline
            inline: 200
        headers:
            resolver: inline
            inline:
                content-type:
                    inline: text/html
                cache-control:
                    inline: s-maxage=60
        body:
            resolver: file
            file:
                resolver: inline
                inline: './index.html'

veniaStatic:
    resolver: directory
    directory:
        resolver: inline
        inline: '.'

veniaStaticIncludes:
    resolver: directory
    directory:
        resolver: inline
        inline: './venia-static'

**Comment by anthoula** [comment]
Thank you for the feedback. The current compatibility matrix are versions: PWA Studio 12.2.0, Magento 2.4.3, and Upward Connector 2.0.0. If issue still occurs with current compatible modules, please reopen as a Bug.

**Comment by liezsm** [comment]
> @sonnybooth-amp : I just solved error by replacing old project's `venia-ui/upward.yml` with new project's `venia-ui/upward.yml`. Here is updated `venia-ui/upward.yml` file I have
> 
> ```
> # This is a top-level object used to set values for the root `status`,
> # `headers`, and `body` properties.
> # It is the first branch in an abstract decision tree, which ultimately
> # resolves to an object that contains values for its own 'status', 'headers',
> # and 'body' properties.
> # This object uses a ConditionalResolver to determine the object value based
> # on the URL pattern in the request object.
> veniaResponse:
>     resolver: conditional
>     when:
>         # Requests to graphql/rest endpoints, the media library, and cache are
>         # handled by the top-level 'veniaProxy' object, which is a ProxyResolver
>         # that passes the request through to the backing Magento server.
>         - matches: request.url.pathname
>           pattern: '^/(graphql|rest|media)(/|$)'
>           use: veniaProxy
>         - matches: request.url.pathname
>           pattern: '^/(robots\.txt|favicon\.ico|manifest\.json)'
>           use: staticFromRoot
>         - matches: fileExtension
>           pattern: '(js|json|png|jpg|gif|svg|ico|css|txt)'
>           use: veniaStatic
>     default: veniaAppShell
> 
> # A FileResolver for serving certain files directly from document root,
> # even though they are published to the `static` folder in build assets.
> staticFromRoot:
>     inline:
>         status: 200
>         headers:
>             resolver: inline
>             inline:
>                 content-type: contentTypeFromExtension
>                 cache-control:
>                     when:
>                         - matches: env.NODE_ENV
>                           pattern: 'production'
>                           use:
>                             inline: public, max-age=604800
>                     default:
>                         inline: no-cache, no-store, must-revalidate
>         body:
>             resolver: file
>             parse:
>               inline: text
>             encoding:
>               inline: binary
>             file:
>                 resolver: template
>                 engine: mustache
>                 provide:
>                     filename: request.url.pathname
>                 template:
>                     resolver: inline
>                     inline: './venia-static/{{ filename }}'
> 
> contentTypeFromExtension:
>     when:
>         - matches: fileExtension
>           pattern: '^ico$'
>           use:
>               inline: image/x-icon
>         - matches: fileExtension
>           pattern: '^txt$'
>           use:
>               inline: text/plain
>         - matches: fileExtension
>           pattern: '^json$'
>           use:
>               inline: application/json
>     default:
>         inline: text/html
> 
> # Contains the file extension--the part after the dot--of the URL path.
> fileExtension:
>     resolver: conditional
>     when:
>         - matches: request.url.pathname
>           pattern: '\.(.*)$'
>           use: $match.$1
>     default:
>         inline: ''
> 
> # A ProxyResolver object that passes a request to the backend Magento
> # server defined in the MAGENTO_BACKEND_URL environment variable.
> # An UPWARD server infers this object as a ProxyResolver due to the presence
> # of the 'target' property.
> veniaProxy:
>     resolver: proxy
>     target: env.MAGENTO_BACKEND_URL
>     # A local Magento install may have SSH configured and untrusted,
>     # which is not a major concern for this one origin, especially if
>     # containerized. Clients which require trust may proxy through UPWARD.
>     ignoreSSLErrors:
>       when:
>           - matches: env.NODE_ENV
>             pattern: 'production'
>             use:
>               inline: false
>       default:
>         inline: true
> 
> # Page type data for initial render
> veniaPageType:
>   resolver: inline
>   inline:
>     data:
>       resolver: conditional
>       when:
>         - matches: env.SCRIPT_NAME
>           pattern: '.*\.php$'
>           use:
>             resolver: computed
>             type:
>               resolver: inline
>               inline: pageType
>             additional:
>               - type: product
>                 fetch: '__typename,id'
>               - type: cms_page
>                 fetch: 'identifier'
>               - type: category
>                 fetch: 'id'
>       default:
>         inline: ''
> 
> # Nonce for page type inline script
> veniaPageTypeNonce:
>   resolver: inline
>   inline:
>     nonce:
>       resolver: conditional
>       when:
>         - matches: env.SCRIPT_NAME
>           pattern: '.*\.php$'
>           use:
>             resolver: computed
>             type:
>               resolver: inline
>               inline: pageTypeNonce
>       default:
>         inline: ''
> 
> # Webpack chunks to preload on page based on page type
> veniaWebpackChunks:
>   resolver: inline
>   inline:
>     scripts:
>       resolver: conditional
>       when:
>         - matches: env.SCRIPT_NAME
>           pattern: '.*\.php$'
>           use:
>             resolver: computed
>             type:
>               resolver: inline
>               inline: webpackChunks
>       default:
>         inline: ''
> 
> # The veniaAppShell object resolves to a response that returns server-side
> # rendered HTML containing the PWA application shell.
> # For SEO purposes, the appropriate meta tags in the HTML head element are also
> # set based on information about the resource.
> # This object uses properties in the top-level 'veniaResponse' object to return
> # the appropriate response values.
> veniaAppShell:
>     resolver: inline
>     inline:
>         status:
>             resolver: inline
>             inline: 200
>         headers:
>             resolver: inline
>             inline:
>                 content-type:
>                     inline: text/html
>                 cache-control:
>                     inline: s-maxage=60
>         body:
>           resolver: template
>           engine: mustache
>           provide:
>             pageType: veniaPageType.data
>             pageTypeNonce: veniaPageTypeNonce.nonce
>             webpackChunks: veniaWebpackChunks.scripts
>           template:
>             resolver: file
>             file:
>               resolver: inline
>               inline: './index.html'
> 
> 
> # The veniaStatic object is a DirectoryResolver that allows access to the files
> # inside the project's compiled './dist' directory.
> veniaStatic:
>     resolver: directory
>     directory:
>         resolver: inline
>         inline: '.'
> 
> # These are no-ops at runtime; nothing refers to these context values in the
> # rest of this file. They exist to declare that the files in the `./static`
> # directory are required and should be copied into the build assets by the
> # UpwardIncludePlugin. Since they are not directly mentioned elsewhere in this
> # file or any other upward.yml file in the build, the UpwardIncludePlugin would
> # fail to copy them if they were not mentioned here.
> 
> # The static directory includes files which don't need to be compiled.
> # They are served by the `veniaStatic` DirectoryResolver, along with the
> # bundles and other assets, but since that resolver serves the `.` dist
> # directory, the UpwardIncludePlugin will not copy it to avoid circular
> # dependency. TODO: This is kind of confusing.
> veniaStaticIncludes:
>     resolver: directory
>     directory:
>         resolver: inline
>         inline: './venia-static'
> 
>  
> ```

this works for me. Thanks!
