### ISSUE TITLE
Need "infinite scrolling" feature in product listing page 

### ISSUE THREAD

**Issue by jinojacob15** [magento/pwa-studio#3614]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by tkacheva** [comment]
No plans to implement this feature by product engineering.
