### ISSUE TITLE
[bug]: Widget\Link does not convert the link for PWA

### ISSUE THREAD

**Issue by jdperez128** [magento/pwa-studio#3618]
**Describe the bug**

If I have one cms page/block and I create one Widget\Link for one category for example, and I get this page/block in my PWA Studio I receive one url with the Magento Domain, not the link of my PWA domain.

**To reproduce**
Magento Admin: https://{admin_magento.com}
PWA Studio: https://{pwa_studio.com}

1.- Go to _Magento Admin_, Content -> Pages.
2.- Edit Home page, for example.
3.- Add this content
```
<p>Content example</p>
<p>{{widget type="Magento\Catalog\Block\Category\Widget\Link" template="category/widget/link/link_inline.phtml" id_path="category/3"}}</p>
```
4.- Now load my _PWA Studio_
5.- In the home I see my page home, and I see the widget link with https://{admin_magento.com}/category/view/id/3

**Expected behavior**

I expected see this link: https://{pwa_studio.com}/category/view/id/3 (/category/view/id/3 -> this is one example, my bug report is for the domain)

**Screenshots**

**Possible solutions**

.

**Debug Report**

.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: v96.0.4664.110
-   Magento Version [e.g Magento Commerce 2.4]: 2.4.3

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug
