### ISSUE TITLE
[bug]: Page builder product collection's price+currency is not updating on currency changes.

### ISSUE THREAD

**Issue by VijayKH** [magento/pwa-studio#3621]
**Describe the bug**

While changing currency from the header dropdown, prices in page builder product collections are not getting updated.

**To reproduce**

1. Go to 'Veni Home page'
1. Change currency from header dropdown.
1. Scroll down to 'Top Sellers' section
1. You can see prices are not updated in chosen currency.

**Expected behavior**

Prices should be displayed in user's preferred currency.

**Screenshots**

<img width="1376" alt="Screenshot 2021-12-22 at 3 49 33 PM" src="https://user-images.githubusercontent.com/7091771/147077213-75b443e6-f895-4ef0-a859-c3b2ff11fb0d.png">

<img width="1376" alt="Screenshot 2021-12-22 at 3 46 34 PM" src="https://user-images.githubusercontent.com/7091771/147077002-2ea946f6-56a2-442e-bddf-c903041ec47c.png">

### Test Plan - 
 - Verify the direct fix for Default store and French store
 - Verify direct fix with store code url enabled
 - Run existing cypress. suite (Localization test automated)

#### Test Coverage -
 - Add unit tests  
 - Update cypress localization test include this check

**Possible solutions**

N/A

**Debug Report**

Paste the output of {{{}yarn build:report{}}}, and any other context about the problem, here.

**Please complete the following device information:**
 - Device <e.g. iPhone6, PC, Mac, Pixel3>:
 - Browser <e.g. Chrome, Safari>:
 - Browser Version <e.g. 22>:
 - Magento Version <e.g Magento Commerce 2.4>:

<![](-- Complete the following sections to help us apply appropriate labels) -->

**Please let us know what packages this bug is in regards to:**
 - < > `venia-concept`
 - < > `venia-ui`
 - < > `pwa-buildpack`
 - < > `peregrine`
 - < > `pwa-devdocs`
 - < > `upward-js`
 - < > `upward-spec`
 - < > `create-pwa`

**Comment by KostiantynFandeliuk** [comment]
@magento I am working on this

**Comment by KostiantynFandeliuk** [comment]
@magento add to contributors team

**Comment by KostiantynFandeliuk** [comment]
To fix the issue it is needed to add:

/node_modules/@magento/pagebuilder/lib/ContentTypes/Products/products.js

```
    const { loading, error, data } = useQuery(GET_PRODUCTS_BY_URL_KEY, {
        variables: { url_keys: urlKeys, pageSize: urlKeys.length }, 

       //Add in useQuery
        fetchPolicy: 'cache-and-network',
        nextFetchPolicy: 'cache-first'
    });
```

As a result, we have correct currency displayed in the Top block after switching the currency

**Comment by anthoula** [comment]
@magento create issue from PR

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug
