### ISSUE TITLE
[bug]: PWA multiple wishlist:  storefront still showing create whishlist button when reach max number of allowed wishlists configured in magento

### ISSUE THREAD

**Issue by mywebcom** [magento/pwa-studio#3632]
**Describe the bug**

When customer creates certain number of wishlist and reach the max number of allowed wishlist configured in magento admin.

<https://docs.magento.com/user-guide/marketing/wishlist-configuration.html>

create a list button is still showing on the storefront. logically, the button should be removed once the max number is reached.

**To reproduce**

1. Go to PWA storefront
1. Login as a customer
1. Go to Wishlist
1. Add 5 wishlist lists as configured in Magento admin
1. See the "Create a list" button still showing

**Expected behavior**

"Create a list button" should be hidden.

**Screenshots**
![](https://user-images.githubusercontent.com/753781/148134167-60f49ac1-e1df-4d6a-94ec-d0750e077447.png)

 

**Test Plan** 

 - Verify single wishlist for commerce edition

 - Verify single wishlist for Community edition

 - Verify Multiple wishlist for 2 and 5 wishlist as config and make sure Venia UI respects the backend configs.

 - Verify in Chrome , FF, Safari and Mobile device

 - Update Multiple wishlist mock data cypress test to include this fix test coverage

**Comment by supernova-at** [comment]
@magento export issue to JIRA project PWA as Bug
