### ISSUE TITLE
[bug]: {"error":"No definition for env.MAGENTO_BACKEND_URL"} upward PHP

### ISSUE THREAD

**Issue by Watch3ruk** [magento/pwa-studio#3635]
Upward php ( Magento_UpwardConnector) throws {"error":"No definition for env.MAGENTO_BACKEND_URL"} upward js works fine on this same instance . 

**To reproduce**

1. run latest all up to date PWA on magento instance using upward php and upward js .  

**Expected behavior**

in both cases we will have a store view of Venia 

**Screenshots**

![https___store ostoya co uk - Google Chrome 06_01_2022 10_04_37](https://user-images.githubusercontent.com/48841019/148365904-2ed17cc4-9a16-4ff8-b2f0-c9e025a6b035.png)
upward js
![https___store ostoya co uk - Google Chrome 06_01_2022 10_04_24](https://user-images.githubusercontent.com/48841019/148365954-2b20445d-5d96-4c4d-a54a-2389c377232b.png)
upward php

**Possible solutions**

changes made to Magento_UpwardConnector when 12.0 or 12.01 was released 

**Please complete the following device information:**

-   Device : all
-   Browser : All
-   Magento Version : 2.4.3-p1
- PWA : 12.1.0

**Please let us know what packages this bug is in regards to:**

-   [X ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [X] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by tjwiebell** [comment]
Any runtime variables needed by the application will need to be configured at the web server layer, they will not be automatically injected from the `.env`. For nginx I would expect to see lines like `fastcgi_param MAGENTO_BACKEND_URL https://venia.magento.com;`.

https://developer.adobe.com/commerce/pwa-studio/tutorials/production-deployment/checklist/#important-environment-variables
