### ISSUE TITLE
Graphql not found for below queries

### ISSUE THREAD

**Issue by svgroup4501** [magento/pwa-studio#3643]
Magento: 2.4.3
PWA: release 12.0.1

test@test:~/pwa-studio$ yarn validate-queries
yarn run v1.22.4
$ graphql validate --keepClientFields --noStrictFragments

error
in /pwa-studio/packages/peregrine/lib/talons/Wishlist/WishlistDialog/CreateWishlistForm/createWishlistForm.gql.js:
 - Unknown type WishlistVisibilityEnum.
 - Cannot query field createWishlist on type Mutation.
error
in /pwa-studio/packages/peregrine/lib/talons/Wishlist/WishlistDialog/wishlistDialog.gql.js:
 - Cannot query field name on type Wishlist.
 - Cannot query field enable_multiple_wishlists on type StoreConfig.
 - Cannot query field maximum_number_of_wishlists on type StoreConfig.
 - Cannot query field name on type Wishlist.
error
in /pwa-studio/packages/peregrine/lib/talons/WishlistPage/createWishlist.gql.js:
 - Unknown type CreateWishlistInput. Did you mean CreateCompareListInput or createEmptyCartInput?
 - Cannot query field createWishlist on type Mutation.
 - Cannot query field enable_multiple_wishlists on type StoreConfig.
error
in /pwa-studio/packages/peregrine/lib/talons/WishlistPage/wishlist.gql.js:
 - Unknown type WishlistVisibilityEnum.
 - Cannot query field updateWishlist on type Mutation.

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thank you for the feedback. The modules it's looking exist in Enterprise Edition. Please check that your backend is using an EE version. If issue still occurs with compatible backend version, please reopen as a Bug.
