### ISSUE TITLE
[bug]: Cannot query field "newsletter_enabled" on type "StoreConfig"

### ISSUE THREAD

**Issue by jaydubb12** [magento/pwa-studio#3652]
**Describe the bug**
When building v12.1.0, branch = develop on my local machine, I noted the following fatal error" Error: Cannot query field "newsletter_enabled" on type "StoreConfig". 

This error was thrown via the error protocol  in the following file /magento-pwa-studio/packages/pwa-buildpack/lib/Utilities/graphQL.js:54, while running line 62 const ``` storeConfigData = await getStoreConfigData()```  via webpack.config.js

A revised entry was made by Conabree on 11/15/21 via PWA-2005, Github issue#3538 on following file packages/pwa-buildpack/lib/queries/getStoreConfigData.graphql:9.  To validate that this was the cause of the build error, I tested removing the entry on line 9, and tested the compilation and it worked without failure

![Screen Shot 2022-01-19 at 6 47 13 AM](https://user-images.githubusercontent.com/21325640/150124020-b7aed3f9-9d3a-43b9-83ab-3a0d1f67195f.png)

**To reproduce**

1. Clone develop branch
2. Set .env config in venia-concept
3. Run command "yarn watch"

**Expected behavior**

Initial build of the code would be completed without error

**Possible solutions**

Refactor the solution provided via #3538 by adding entries as needed to...
webpack.config.js
jest.config.js
useStoreSwitcher.spec.js
useStoreSwitcher.js
storeSwitcher.gql.js

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

MacOS
IntelliJ Idea IDE

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [x] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thank you for the feedback. The current compatibility matrix are versions: PWA Studio 12.2.0, Magento 2.4.3, and Upward Connector 2.0.0.

**Comment by Jay991** [comment]
@Magento Having the same problem. How can I work around this? create the module from scratch?

**Comment by siddiquicha** [comment]
@magento I am using Magento 2.4.5 versions getting same issue when setup PWA.
