### ISSUE TITLE
[bug]: Venia cached on Macbook M1

### ISSUE THREAD

**Issue by MaxTa91** [magento/pwa-studio#3699]
**Describe the bug**

I am using Macbook 1 and Google Chrome browser. 
When I visit this url https://venia.magento.com/ ---> It is showing the old homepage. (Tried to close tab and reopen a new tab). 
![Screen Shot 2022-02-11 at 10 19 20](https://user-images.githubusercontent.com/11706605/153532730-a02a90f2-1445-4708-86a2-903b519809cf.png)

However, I open this URL on Incognito Window. It is showing fine. 
![Screen Shot 2022-02-11 at 10 20 13](https://user-images.githubusercontent.com/11706605/153532808-56bf05c0-7d3c-43c3-9a4b-5e5a956bc57c.png)

**To reproduce**

1. Go to https://venia.magento.com/  
2. I am not sure, if you are a tech guy, you can change the data at homepage from Admin 
3. Refresh or reopen  the current tab. 

**Expected behavior**

Need to load the new content as this screenshot
![Screen Shot 2022-02-11 at 10 20 13](https://user-images.githubusercontent.com/11706605/153532969-971541a1-acf2-4193-9125-92d3bb27f75a.png)

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thank you for the feedback. It looks like the first screenshot shows that a user navigated to the Second Store View using the Store Switcher, and the other incognito screenshot displays the Default Store View. Persisting the last visited store view is expected behavior.
