### ISSUE TITLE
Update networkUtils.js to check saveData mode

### ISSUE THREAD

**Issue by GeKVe** [magento/pwa-studio#3708]
**Describe the request**

 

Add data saver verification before prefetching images.

[Data Savers](https://source.android.com/docs/core/data/data-saver) allow users to signal to a site if they would prefer lighter data-usage where possible. PWA Studio respects Save-Data preferences where `navigator.connection.saveData` is supported by the browser.

**Comment by butterfly1924** [comment]
@magento I am working on this

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by glo82145** [comment]
https://github.com/adobe export issue to Jira project PWA as story

**Comment by glo82145** [comment]
@adobe export issue to Jira project PWA

**Comment by glo42707** [comment]
hi @GeKVe 

could you please let me know the steps to reproduce it and the impact how you are facing.

**Comment by GeKVe** [comment]
hi @glo42707 github-jira-sync-bot has done a bad jub when updating this issue. My original issue was regaring lack of documentation.
Notice how the title is wrong for this same URL? ...That was my original issue title.
﻿
![image](https://github.com/magento/pwa-studio/assets/8438650/f19768fb-f08a-4a9d-b314-11bb5bff2d97)

**Comment by glo42707** [comment]
hi @GeKVe 

thanks for responce reaching out.
as per your last coment I went through that ticket 3281 and I see your question listed as below snapshot
![image](https://github.com/magento/pwa-studio/assets/84493875/129ad73a-3a5d-42fd-8c3b-9ea73b40e4f5)


Answer to you query -- we can setup pwa project with 2 ways either using git clone or using sacfholding process as it is defined so far for any of PWA projects. other than that I did not seen any refference so far for any other way settingup PWA studio.

how ever you can read official doumentation for detailed information --> https://developer.adobe.com/commerce/pwa-studio/

for extension development -->  https://developer.adobe.com/commerce/pwa-studio/tutorials/extensions/

closing the ticket with this comment and feel free to create new tickets in case any more issue or clarifiction needed.
