### ISSUE TITLE
[doc]: Luma and Venia cloud deployment

### ISSUE THREAD

**Issue by oefterdal** [magento/pwa-studio#3714]
From the release notes, I can read this "_Luma and Venia can now be deployed to the same cloud environment — This deployment option makes it easier for customers to deploy their PWA site alongside their existing Luma site while they migrate from Luma to Venia._"

But how do we actually configure it on the cloud enviornment?

**Comment by ryantfowler** [comment]
@oefterdal here's the related commit which appears to enable this feature: https://github.com/magento/magento2-upward-connector/commit/cffe292c3b81951457f1edb03c138b84a1623287 . User Athar brought this up in the following Slack comment: https://magentocommeng.slack.com/archives/C71HNKYS2/p1647015768346209.

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Hi @oefterdal . Thanks for your feedback. Please take a look at the [Developer Docs for Multi-Sites](https://developer.adobe.com/commerce/pwa-studio/guides/packages/upward/multi-site/), and feel free to message us in our [Slack Channel](https://magentocommeng.slack.com/messages/C71HNKYS2) if you need any clarifications on this.
