### ISSUE TITLE
[bug]: favicon.ico, manifest.json 404 (Not Found) and error {{#pageTypeNonce}} show on footer

### ISSUE THREAD

**Issue by hiepnhaht** [magento/pwa-studio#3728]
I have setup a storefront project, after run yarn run build. When I access url: https://ania-pwa.arrowhitech.net/
1. favicon.ico, manifest.json 404 (Not Found) 
https://ania-pwa.arrowhitech.net/manifest.json 404 (Not Found)
23Manifest: Line: 1, column: 1, Syntax error.
favicon.ico:1          GET https://ania-pwa.arrowhitech.net/favicon.ico 404 (Not Found)
2. In footer showing error like below
{{#pageTypeNonce}}{{#webpackChunks}}{{/webpackChunks}} {{/pageTypeNonce}}
So, can you help me fix? Thanks!

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thank you for the feedback. We would need some additional information and steps to reproduce. For additional support, please see our Slack channel: https://magentocommeng.slack.com/messages/C71HNKYS2
