### ISSUE TITLE
how to add NextJs to pwa-studio to extend with nextjs features?

### ISSUE THREAD

**Issue by naag-pal** [magento/pwa-studio#3732]

**Comment by OneCricketeer** [comment]
Hi @naag-pal . There is internal effort to add NextJS. Stay tuned!

**Comment by naag-pal** [comment]
That's nice. 

Can you please provide some details, 
what changes might required - to try from my side, so that I can try extending it from my side as well. 

Would be nice few details regarding this, what the best way to extend NextJs on top of pwa studio.

**Comment by OneCricketeer** [comment]
If you look at our `package.json`, there is no dependency on `next` library, or scripts at this time, so there is nothing to add/extend yet. It will be a migration effort from the existing scripts and libraries that our team has prioritized.

**Comment by OneCricketeer** [comment]
The team has pivoted to newer initiatives. I've not heard any updates, otherwise.
