### ISSUE TITLE
[issues]: Warning when complie and run in local about `maximumFileSizeToCacheInBytes`

### ISSUE THREAD

**Issue by MinhOmega** [magento/pwa-studio#3744]
**Describe the bug**

**To reproduce**

1. Run `yarn venia run watch`
2. Issues warning showing in console but site still loading withou problem

**Expected behavior**

Compiled successfull withou warning.

**Screenshots**

![image](https://user-images.githubusercontent.com/49482201/159233822-c3ed3906-7cf8-4fd3-9bb5-cbfb6997db72.png)

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

```
WARNING in /client.js is 10.6 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.

WARNING in /vendor~client.2abc975751104bc8bf12.js is 4.65 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.

```

**Please complete the following device information:**

-   Device: Ubuntu 21.10
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: Version 99.0.4844.82 (Official Build) (64-bit)
-   Magento Version [e.g Adobe Commerce 2.4]: Magento ver. 2.4.2

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
Thank you for the feedback. We would need some additional information. If it is happening in production as well, please reopen. For additional support, please see our Slack channel: https://magentocommeng.slack.com/messages/C71HNKYS2
