### ISSUE TITLE
[doc]: Sass support not work as expected

### ISSUE THREAD

**Issue by tuna2smc** [magento/pwa-studio#3758]
**Describe the request**
A clear and concise description of the documentation request or where the documentation can be improved.
Old topic (Closed)
https://github.com/magento/pwa-studio/issues/3183
Details added in old link topic

**Possible solutions**
How would you word this addition or change?

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by dobooth** [comment]
@tuna2smc Let me know what you think of the changes in the PR above. If you have a specific version for npm (or any other changes), please let me know.

**Comment by tuna2smc** [comment]
added details in my previously post. But seem now docs changed. I will give it a try later
