### ISSUE TITLE
Homepage slider creates unexpected GET-requests

### ISSUE THREAD

**Issue by arendarenko** [magento/pwa-studio#3762]
**Describe the bug**

Hello,
I noticed unexpected GET-request to `{hostname}/null` on the homepage during first website load. Sometimes it's taking 0.5-1 sec which impacting overall load speed. 

Most likely this issue is caused by image slider on homepage, considering it's not reproducible on the other pages and when you click on the circle to open next slide - another `/null` request is being sent.

**To reproduce**

1. Go to [venia.](https://venia.magento.com/) with dev console open
2. Open "Network" tab and filter by "null"
3. Review "Network" tab results

**Expected behavior**

No requests with "/null"

**Screenshots**

<img width="841" alt="image" src="https://user-images.githubusercontent.com/42036143/163414247-335e4a94-b814-4994-8be9-26e2b1ad2765.png">

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by butterfly1924** [comment]
@magento I am working on this

**Comment by butterfly1924** [comment]
@magento I am working on this

**Comment by butterfly1924** [comment]
@magento add to contributors team

**Comment by butterfly1924** [comment]
@magento I am working on this

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by huykon** [comment]
@magento I am working on this

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
This issue is closed by https://jira.corp.adobe.com/browse/PWA-3055
