### ISSUE TITLE
[bug]: Product details not displaying when product url suffix is trailing slash

### ISSUE THREAD

**Issue by Dave-W** [magento/pwa-studio#3764]
**Please let us know what packages this bug is in regards to:**
 - < > `venia-concept`
 - < > `venia-ui`
 - < > `pwa-buildpack`
 - <x> `peregrine`
 - < > `pwa-devdocs`
 - < > `upward-js`
 - < > `upward-spec`
 - < > `create-pwa`

**Comment by butterfly1924** [comment]
@magento I am working on this

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by RaghavendraTirumalasetti** [comment]
@magento I am working on this

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by RaghavendraTirumalasetti** [comment]
Hi @Dave-W,
Thank you for reporting and collaboration.
Please provide us with the following information:

1. Summary of the issue
2. Steps to reproduce
3. Expected and actual results
Thanks

**Comment by glo82145** [comment]
We waited for more than 14 days for update on this issue, hence we are closing it. 
Please feel free to reopen if you are still have any update on the same.
