### ISSUE TITLE
[bug]: A short, simple sentence describing the bug

### ISSUE THREAD

**Issue by amareshtiwari** [magento/pwa-studio#3765]
I am getting an error when I run the below command

yarn buildpack create-custom-origin packages/venia-concept

  ⓧ  error:0308010C:digital envelope routines::unsupported
  ⓧ  Error: error:0308010C:digital envelope routines::unsupported
error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

PHP     : 8.1
Magento : 2.4.4
Node    : v17.8.0
NPM     : 8.5.5
![WhatsApp-Image-2022-04-17-at-5-10-20-PM](https://user-images.githubusercontent.com/14758163/163712890-906a7f49-f664-4613-9cd6-959b6f027080.png)

**Comment by butterfly1924** [comment]
@magento I am working on this

**Comment by butterfly1924** [comment]
@amareshtiwari Hello amareshtiwari, this is caused by the latest version of Node.js version 17.8.0. You can check out the same issue here https://github.com/webpack/webpack/issues/14532. You can try adding a new node option `--openssl-legacy-provider`. You may also downgrade your node.js to v16 LTS version, which will fix this issue.

**Comment by amareshtiwari** [comment]
Hi @butterfly1924 ,

The issue has been resolved but after running this command `yarn run build && yarn run stage:venia` I didn't see any changes in my frontend.

![WhatsApp Image 2022-04-18 at 2 03 29 PM](https://user-images.githubusercontent.com/14758163/163781468-d1dec0ae-0f0c-4bf2-8006-056acd310601.jpeg)
![image](https://user-images.githubusercontent.com/14758163/163781511-516bc6f6-36df-4984-9b0e-165e79e5166f.png)

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thank you for the feedback. Node v17 & 19 are not supported. Please downgrade to Node v16.

**Comment by amareshtiwari** [comment]
Hi @anthoula ,

I have downgraded the node version from v17.8.0 to v16.14.2

So kindly check again and let me know

Thanks!

**Comment by amareshtiwari** [comment]
@anthoula  Why we are getting {{#pageTypeNonce}}{{#webpackChunks}}{{/webpackChunks}} {{/pageTypeNonce}}
After installation of PWA ?
