### ISSUE TITLE
[feature]: Remove increase/decrease buttons of quantity selector from the tab index

### ISSUE THREAD

**Issue by luke-denton-aligent** [magento/pwa-studio#3766]
**Is your feature request related to a problem? Please describe.**
Currently when tabbing through a PDP, a user has to tab twice to get passed the quantity selector. If the value in the quantity selector is greater than 1, then the user will have to tab 3 times to get passed it:

First tab press: Decrease button
Second tab press: quantity input
Third tab press: Increase button
Forth Tab press: next element in the DOM

Further, the increase/decrease buttons don't have any focus state currently either, so a user isn't able to visually see that they are focused on those elements (which we don't have to fix, as we're going to remove those buttons from the tab index)

**Describe the solution you'd like**
Keyboard users already have access to the keyboard, so that can enter the number for the quantity they like, without having to use the increase/decrease buttons. By removing the buttons from the tab order, we can make the usability of the app much better, without sacrificing any accessibility, as the input field is still focusable.
Unfortunately due to the current implementation of the quantity input itself, a user isn't able to use the up/down arrow keys to change the value, which I'll create another issue for.

Removing the buttons from the tab index would be done by simply adding `tabindex="-1"` to them.

**Describe alternatives you've considered**
-

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [x] `venia-ui`

**Comment by luke-denton-aligent** [comment]
@Jordaneisenburger Can you please review

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Thanks for your feedback! We are planning to include accessibility improvements to the quantity stepper in an upcoming feature epic that is currently `In Progress`, and will include this feedback for review.

**Comment by Sahilsks** [comment]
@magento I am working on this

**Comment by Tarun50745** [comment]
Followed steps to replicate issue, Issue confirm.

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
As we have waited for more than 14 days for response hence we are closing this issue.
Please feel free to reopen incase of any update.
