### ISSUE TITLE
Magento 2 : How to show search bar for always in PWA venia-ui`

### ISSUE THREAD

**Issue by Imran4191** [magento/pwa-studio#3768]
Now search bar is showing after clicking the search icon. But I want to show the search bar for always, don't need to click the search icon. How can I do that?

**Comment by Imran4191** [comment]
@magento I am working on this

**Comment by Imran4191** [comment]
@magento add to contributors team

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thanks for your feedback! For additional support on your question, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us).
