### ISSUE TITLE
[doc]: A deployment of dist folder using upward-js and node+express - graphql is failing

### ISSUE THREAD

**Issue by naag-pal** [magento/pwa-studio#3771]
PWA Studio has a 
MAGENTO_BACKEND_URL is : http://XXXXXXX.compute-1.amazonaws.com/

yarn build and copied /dist to a folder where upward-js and node+express is exist. 

using @magento/upward-js and express on the node server 

const { createUpwardServer } = require('@magento/upward-js');

async function serve() {
  await createUpwardServer({
    port: '8082',
    bindLocal: true,
    logUrl: true,
    upwardPath: './dist/upward.yml'
  });
}

serve();

When I run the server node server.js 

http://XXXXXXX.compute-1.amazonaws.com:8082/ is the url loading fine. 

But the magento calls are failing with 500 internal server. 

so the data from local it is not loadig fine. 

When I run "yarn watch" on pwa-studio folder with same MAGENTO_BACKED_URL - graphql loading fine. 

Need help on getting details of what's wrong here or 
any document referral which has clear instruction so that /dist folder can be hosted.

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thanks for your feedback! For additional support on your question, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us).
