### ISSUE TITLE
[bug]: CartPage - Update item is not taking the proper colour 

### ISSUE THREAD

**Issue by isibaguette** [magento/pwa-studio#3772]
**Describe the bug**

On the cart page, when editing a item, changing the size without updating the colour, it takes an other colour. 

**To reproduce**

1. Go to 'Tops' category, Select the product "Phoebe Cardigan"
2. Choose colour and size (ex: Rain/L)
3. Add to Cart
4. Go to cart page (click on "Edit shopping cart" in the minicart)
5. Edit item: Select a new colour and a size (ex: Mint/XS), click on "Update"
6. Edit item again: Select only a size (ex: M)
7. You can see that the colour changed by Khaki (supposed to be Mint/M)

**Expected behavior**

When I only updated the size, it supposed to be Mint not Khaki

**Please complete the following device information:**

Device: Windows on Chrome 
Magento 2.4.3

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [X] `venia-ui`
-   [ ] `pwa-buildpack`
-   [X] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by denyskuz** [comment]
@magento I am working on this

**Comment by denyskuz** [comment]
@magento add to contributors team

**Comment by denyskuz** [comment]
@magento I am working on this

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by denyskuz** [comment]
Someone solve this issue on the developer branch.
