### ISSUE TITLE
[bug]: 404 pages don't return 404 status code

### ISSUE THREAD

**Issue by NathaliePHPro** [magento/pwa-studio#3810]
**Describe the bug**

If the visitor enters a non existing URL, the network requests returns a 200 StatusCode while showing the Magento no route page. However it should return a 404 StatusCode

**To reproduce**

1. Go to venia.magento.com/venia-bottoms/venia-pants.html?page=1
2. Open your Inspect tool
3. Go to the network tab
4. Change the URL to https://venia.magento.com/venia-bottoms/venia-pantsblabkla
5. venia-pantsblabkla returns statusCode 200

**Expected behavior**

venia-pantsblabkla should return a statuscode 404, which would be consistent with thee 404 page shown by Magento

**Screenshots**

https://snipboard.io/iowkIO.jpg

**Please complete the following device information:**

Issue happens on all devices and all Magento PWA Studio versions

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [x] `upward-js`
-   [x] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
@NathaliePHPro Thanks for the feedback. This is expected given the current `upward.yml` in venia-ui. That initial request is for the appShell, which is successfully returned with a 200, and much later there is a `ResolveURL` request which then informs us that URL isn’t valid.

For additional support, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us).

**Comment by alecarg** [comment]
+1

**Comment by navabrind** [comment]
Is there any solution for this issue?  Still we are getting status code 200 instead of 404

**Comment by navabrind** [comment]
Thank you very much.. Exploring it
