### ISSUE TITLE
[bug]: Mega menu collapses when trying to select sub-category on 12.4

### ISSUE THREAD

**Issue by JustinConabreeAbsolunet** [magento/pwa-studio#3812]
**Describe the bug**

When trying to click on a sub category (ex Bottoms > Pants & Shorts) the menu collapses. This is due to the PageLoadingIndicator positioning of `relative` taking precedent over the positioning {{{}absolute{}}}.

**To reproduce**

1. Hover over first level category. Menu will open
1. Try to select second level category

**Expected behavior**

(/) Menu stays open when selecting sub category

**Actual  behavior**

(x) Menu does not stay open when selecting sub category

**Screenshots**

<https://user-images.githubusercontent.com/68294336/165993443-60a2eb88-130b-4345-a39a-599471fe6675.mp4>

**Possible solutions**

Change pageLoadingIndicator.module.css
``{{css
.root

{ composes: bg-gray-100 from global; composes: h-<2px> from global; /** Remove relative position for root_absolute that composes root **/ composes: overflow-hidden from global; composes: w-full from global; }

/** Add root_relative with relative positioning **/
.root_relative

{ composes: root; composes: relative from global; }

.root_absolute

{ composes: root; composes: absolute from global; composes: bottom-0 from global; composes: left-0 from global; }

}}``

Change pageLoadingIndicator.js to use root_relative instead of root
``{{jsx
return (
<div className=

{absolute ? classes.root*absolute : classes.root*relative}

>
<div className={classes[}}indicator_${loadingState}{{>} /]
</div>
);
}}``

**Please complete the following device information:**
 - Device <e.g. iPhone6, PC, Mac, Pixel3>: PC
 - Browser <e.g. Chrome, Safari>: Chrome
 - Browser Version <e.g. 22>: 100.0.4896.127
 - Magento Version <e.g Adobe Commerce 2.4>: 2.4.4

<![](-- Complete the following sections to help us apply appropriate labels) -->

**Please let us know what packages this bug is in regards to:**
 - < > `venia-concept`
 - <x> `venia-ui`
 - < > `pwa-buildpack`
 - < > `peregrine`
 - < > `pwa-devdocs`
 - < > `upward-js`
 - < > `upward-spec`
 - < > `create-pwa`

**Test Plan**
* Verify sub menu stays open and is easily accessible on desktop & mobile
* Verify an automated test is added to catch this time-sensitive issue

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by michaelyu0123** [comment]
The resolution will be made in https://github.com/magento/pwa-studio/pull/3850
