### ISSUE TITLE
[bug]: Warning message using components exported from @magento/venia-drivers 

### ISSUE THREAD

**Issue by fabiomangano** [magento/pwa-studio#3846]
**Describe the bug**
Hi, I'm following this tutorial to learn the basic of Pwa Studio: 
https://www.simicart.com/blog/magento-pwa-studio-tutorial-the-basics/?simipwa=1

Importing Link component from @magento/venia-drivers gives this error:

WARNING in ./src/drivers.js
export 'Link' was not found in '@magento/venia-ui/lib/drivers

**To reproduce**
Import the Link component.

``` 
import React from 'react';
import Icon from '@magento/venia-ui/lib/components/Icon';
import { Tag as TagIcon } from 'react-feather';
import {  Link } from '@magento/venia-drivers';
import classes from './brandicon.css';
import { FormattedMessage, useIntl } from 'react-intl';
 
const BrandIcon = () => {
   const history = useHistory();
   const { formatMessage } = useIntl();
 
   return (
       <button
           aria-label={formatMessage({
               id: 'brand.brandLabel',
               defaultMessage: 'Brands'
           })}
           className={classes.root}
           onClick={() => history.push('/brand.html'}
       >
           <Icon src={TagIcon} />
           <span className={classes.label}>
               <FormattedMessage id={'Brands'} />
           </span>
       </button>
   )
}
export default BrandIcon

```
**Expected behavior**
no error message

**Please complete the following device information:**

-   Device [MacBook Pro 13]:
-   Browser [Chrome]:
-   Magento Version [Adobe Commerce 2.3.3]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by huykon** [comment]
@fabiomangano we should import **Link** from `react-router-dom` like [this](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Footer/footer.js#L4)

**Comment by anthoula** [comment]
@fabiomangano `venia-drivers` has been deprecated for quite some time, and will be fully removing it soon. Consider importing from `react-router-dom` instead
