### ISSUE TITLE
[bug]: pathname.match is not a function

### ISSUE THREAD

**Issue by ankitseepossible** [magento/pwa-studio#3853]
**Describe the bug**

I yesterday download latest PWA studio version (12.4.0) and also set Magento back end url in .env file project running successfully but when I try to browse any category from menu then It throws an error **"pathname.match is not a function"**.

**To reproduce**

1. yarn watch
2. open app in browser
3. Click on any menu / sub item

**Screenshots**

<img width="1596" alt="Screenshot 2022-05-12 at 4 31 24 PM" src="https://user-images.githubusercontent.com/98216090/168056274-88cb3ca7-3731-4eec-bbd3-ed87043b8e30.png">

**Debug Report**

ℹ  Inspecting Dependencies
    Found 9 @magento dependencies in yarn.lock
    @magento/pwa-buildpack @ 11.3.0
    @adobe/apollo-link-mutation-queue @ 1.0.2
    @magento/babel-preset-peregrine @ 1.2.1
    @magento/eslint-config @ 1.5.3
    @magento/pagebuilder @ 7.3.0
    @magento/peregrine @ 12.4.0
    @magento/pwa-theme-venia @ 1.3.0
    @magento/upward-security-headers @ 1.0.8
    @magento/venia-ui @ 9.4.0

  ℹ  Inspecting Magento Backend
    Not using sample backend.
    Backend is UP!

  ℹ  Inspecting System
    OS: Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
    Node Version: v16.14.2
    NPM Version: 8.5.0

-   Device [PC, Mac]:
-   Browser [Chrome ]:
-   Browser Version [101]:
-   Magento Version [Adobe Commerce 2.4]:

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
Thanks for your feedback. We were not able to reproduce. If this issue is still actual, and for additional support on your question, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us).
