### ISSUE TITLE
[bug]: Gallery item Add To Cart configurable product redirect URL doesn't match tile URL

### ISSUE THREAD

**Issue by justinconabree** [magento/pwa-studio#3854]
**Describe the bug**

When clicking the add to cart button on a configurable product gallery item (the PLP for instance) the URL you're redirected to doesn't match the URL used on the product tile. 

**To reproduce**

1. Go to https://venia.magento.com/venia-bottoms/venia-pants.html?page=1
2. Click on the Add To Cart button for Gloria Palazzo Pants
3. Will be redirected to https://venia.magento.com/venia-bottoms/gloria-palazzo-pants.html

**Expected behavior**

Should be redirected to https://venia.magento.com/gloria-palazzo-pants.html, like click the image would do

**Possible solutions**
- Support product options in listings

OR
- Render a Redirect component instead of using `history.push` and prefix URL with a `/` so it uses the base URL instead of being relative

OR
- Use a Link for the button when it's a configurable product

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thanks @JustinConabreeAbsolunet ! We'll add this to some upcoming work 👍

**Comment by chris-brabender** [comment]
@anthoula - is there any update on this issue?

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
> @anthoula - is there any update on this issue?

@chris-brabender This has been reprioritized and is in our backlog
