### ISSUE TITLE
[feature]: PWA Studio / Venia Support for Login As Customer Magento Commerce feature

### ISSUE THREAD

**Issue by jurvi** [magento/pwa-studio#3862]
**Is your feature request related to a problem? Please describe.**
I have a customer that needs to use Login as Customer feature in Magento Commerce, but it seems like PWA Studio doesn't support it.

**Describe the solution you'd like**
Support the Login as Customer feature. Correctly handle the "/loginascustomer/login/index/?secret=..." route, log the admin user in as the chosen customer, and show some kind of pop up on screen reminding that the application is used as another user.

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by fooman** [comment]
Log in as customer is also available in Magento Open Source.

**Comment by glo42707** [comment]
We have triaged the ticket and sent for PO confirmation if we can take it up.

**Comment by tkacheva** [comment]
No plans to implement this feature by the product engineering. Open a PR if you are willing to contribute.
