### ISSUE TITLE
 errorPolicy in graphQL query

### ISSUE THREAD

**Issue by rashzero** [magento/pwa-studio#3872]
hello, I would like to ask how you can specify the errorPolicy in the graphQL request inside the upward.yml file, when either data or an error comes in the response, then there are no problems, but I have a request in which both data and errors come in and immediately fall into an error , although I want to ignore it and display the partial data that came

**Comment by anthoula** [comment]
Thanks for your feedback! For additional support on your question, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us).
