### ISSUE TITLE
[bug]: root:local-intercept.js need targets

### ISSUE THREAD

**Issue by theiconnz** [magento/pwa-studio#3877]
**Describe the bug**

I know this may not be a bug of PWA Studio but if someone interested or have encounter the issue I'll submit here

After installing successfully, I had to add public directory instead venia-ui so I've add following to localIntercept() function

    targets.of('@magento/pwa-buildpack').transformUpward.tap(def => {
        def.staticFromRoot.inline.body.file.template.inline =
            './public/{{ filename }}';
    });

**To reproduce**

Steps to reproduce the behaviour:

1. Go to local-intercept.js
2. add above code to localIntercept() function
3. Run yarn build

ReferenceError: targets is not defined

**Expected behavior**

It should not generate that error

**Possible solutions**

Modify local-intercept.js 

    function localIntercept(targets) {}
    module.exports = (targets) = localIntercept;

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
Hey @theiconnz , thanks for the write-up!
