### ISSUE TITLE
[bug]: Check/Money Order Payment doesn't work for Specific Countries.

### ISSUE THREAD

**Issue by aivankov-cloud** [magento/pwa-studio#3884]
**Describe the bug**
PWA checkout doesn't have revalidation for payment methods after change county in billing address.
As per attached screenshot  query should return value for **available*payment*methods** should be "Check / Money order". but returning empty array when followed below steps

**To reproduce**

1. Choose `United States`  for the General > Country Options > Default Country configuration in admin
1. Choose `Specific Countries` for the Sales > Payment methods > Check/Money Order > Payment from Applicable Countries configuration
1. Choose `United Kingdom` for the Sales > Payment methods > Check/Money Order > Payment from Specific Countries configuration
1. Go to checkout and choose `United Kingdom` in billing address

**Expected behavior**

Expected Result: Payment Methods Check/Money Order are available
Actual Result: Payment Methods Check/Money Order are NOT available

**Possible solutions**

Need to revalidate available payment methods.

**Debug Report**

**Please complete the following device information:**

-   Device <e.g. iPhone6, PC, Mac, Pixel3]: PC
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: 101.0.4951.64
-   Magento Version [e.g Adobe Commerce 2.4]: 2.4.3p1

[!-- Complete the following sections to help us apply appropriate labels! --]

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [+] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ > `create-pwa`

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
Issue is reproducible, hence confirming the issue.
