### ISSUE TITLE
Link to pwastudio.io not working

### ISSUE THREAD

**Issue by Zwernemann** [magento/pwa-studio#3900]
**Describe the request**
Documentation of PWA Studio package should be located at https://pwastudio.io
This link is not working.

**Possible solutions**
Enable the link to pwastudio.io

**Please let us know whether this is a new topic or a topic change request:**
 - [x ] New Topic Request (ie. missing entire topic/section)
 - [ ] Topic Change Request (ie. spelling, organization)

**Comment by anthoula** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
That URL is a redirect to https://developer.adobe.com/commerce/pwa-studio/

**Comment by Zwernemann** [comment]
@anthoula The link is still not working. 
![image](https://user-images.githubusercontent.com/52236002/178927719-be3f84b2-a2dd-4249-a208-9a086cdf20a8.png)

**Comment by Zwernemann** [comment]
@anthoula You closed this task, but the link is still not working.

**Comment by anthoula** [comment]
Thanks @Zwernemann - the new link is https://developer.adobe.com/commerce/pwa-studio/ and we've updated some instances in documentation where the old vanity url remained.
