### ISSUE TITLE
[bug]: peregrine useGiftOptions has a dependency to venia-ui

### ISSUE THREAD

**Issue by Buuhuu** [magento/pwa-studio#3901]
**Describe the bug**

Iiuc peregrine should not have any dependencies to venia-ui. With https://github.com/magento/pwa-studio/pull/3540/files#diff-cc37332b8508bbba81a4a3c25ab8261cb592076309b4c9faf4b331a53930c24d however a dependency was added from `useGiftOptions.js` to `@magento/venia-ui/lib/util/formValidators`. 

**Expected behavior**

No dependencies from peregrine to venia-ui.

**Possible solutions**

Move the formValidators to peregrine instead.

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by RaghavendraTirumalasetti** [comment]
Hey @Buuhuu,
Could you pls let us know more information on this ticket as actual result and the impact of actual result due to which the ticket has been raised to make the changes or please suggest if we are missing anything in order to understand expectation of the ticket.

Thanks

**Comment by glo82145** [comment]
We waited for more than 2 weeks for the update. As we have not got any update, hence closing this issue.
Please Feel free to reopen it if it is still required.

Thanks
