### ISSUE TITLE
[feature]: Adding tax information to order confirmation gql

### ISSUE THREAD

**Issue by justinconabree** [magento/pwa-studio#3904]
**Is your feature request related to a problem? Please describe.**
Analytics eventing for order confirmation will frequently require tax information. Also enables easier customisation of order confirmation page to show order totals including tax breakdown.

**Describe the solution you'd like**
Fetch tax data in the order confirmation gql

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by glo42707** [comment]
We have triaged the ticket and sent for PO confirmation if we can take it up.

**Comment by tkacheva** [comment]
@justinconabree currently we support only order number in the response. however there is an event registered on order confirmation for the Analytics to subscribe that includes the following:
```
payload: {
          order_number: placeOrderData.placeOrder.order.order_number,
          amount: orderDetailsData.cart.prices,
          shipping: shipping,
          payment: orderDetailsData.cart.selected_payment_method,
          products: orderDetailsData.cart.items
          }

```
These events can be extended with custom ones collecting the data you need
https://developer.adobe.com/commerce/pwa-studio/api/events/#order_confirmation_page_view
