### ISSUE TITLE
[bug]: Link component failing with 12.5 when no prefetch

### ISSUE THREAD

**Issue by justinconabree** [magento/pwa-studio#3906]
**Describe the bug**

The Link component can prefetch the link's page information. When this prefetch flag is false, it unsets the query that's used. This is failing as of 12.5 (which included an Apollo update).

**To reproduce**

Link component isn't implemented anywhere in base venia. Would need to use the component and not pass in `shouldPrefetch`

**Expected behavior**
Link component works seemlessly when prefetch flag is false

**Possible solutions**

There's already checks to not run query when `shouldPrefetch` is false. Just need to pass in a valid query to `useLazyQuery` even when the flag is false

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by glo82145** [comment]
Hello,
As I can see this issue got fixed in the scope of the internal Jira ticket [PWA-2967](https://jira.corp.adobe.com/browse/PWA-2967) by merging PR. Hence we are closing this.

**Comment by glo80771** [comment]
Hello,
As I can see this issue got fixed in the scope of the internal Jira ticket PWA-2967 by merging community PR https://github.com/magento/pwa-studio/pull/3907

Hence I am closing this issue.

Thanks
