### ISSUE TITLE
overlapped all the images but still not refreshing while add to home 

### ISSUE THREAD

**Issue by Dencer** [magento/pwa-studio#3914]
<img width="446" alt="Screenshot 2022-07-26 at 10 22 45 AM" src="https://user-images.githubusercontent.com/6223586/180926225-b6d586b4-7987-43ea-8527-f615d09a0a84.png">

**Comment by anthoula** [comment]
@Dencer Thank you for the feedback. Please provide additional details for your issue: Steps to reproduce, expected results, actual results.

**Comment by Dencer** [comment]
Actually for mobile its working fine , but for desktop icon is not coming.

**Comment by anthoula** [comment]
Thank you @Dencer . Can you provide steps to reproduce, and versions where this is occurring?

**Comment by anthoula** [comment]
For additional support on your issue, please see our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us)

**Comment by Dencer** [comment]
> Thank you @Dencer . Can you provide steps to reproduce, and versions where this is occurring?

Actually in Chrome browser I am getting it my app image is not updated, but its working while installing in mobile .
