### ISSUE TITLE
[bug] Item being removed from cart after editing to the same configurable option.

### ISSUE THREAD

**Issue by nonni96** [magento/pwa-studio#3915]
**Describe The Bug**

Item is being removed from the cart when editing to the same configurable option as before and pressing 'update'.

**To reproduce**

1. Go to https://venia.magento.com/thick-leather-braided-belt.html
2. Choose any size of the belt
3. Add to your cart
4. Go to 'Edit Shopping Bag'
5. Click on the 'edit item' button of the item you added to the cart
6. Click the same size you had configured in your cart
7. Click 'update'
8. See the item is now removed from the cart

**Expected behavior**

Expected to do nothing to the item, just close the popup window.

**Possible solutions**

Have a check in the peregrine talons to know if the item has not been changed, even though some options have been pressed.

**Device information**

- Chrome Browser
- Browser Version [103.0.5060.53]

**Bug regards to**

- venia-ui
- peregrine

**Comment by anthoula** [comment]
@adobe export issue to Jira project PWA as Bug

**Comment by Masumisigma** [comment]
Hi @nonni96 , Is the issue resolved? As we can see, the issue is still reproducible on https://venia.magento.com/
