### ISSUE TITLE
[Docs]: How to implement Push notification in PWA Studio

### ISSUE THREAD

**Issue by Dencer** [magento/pwa-studio#3919]
It will be great if you provide us some steps in Frontend and backend .

**Comment by anthoula** [comment]
@adobe export issue to Jira project PWA

**Comment by anthoula** [comment]
Hi @Dencer - We are tracking this internally, and planning to work on a guide on how this may be done. In the meantime, please reach out to our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us) for additional support.

**Comment by Tarun50745** [comment]
I have gone through with multiple approaches / library to implement "push notification" in our pwa-app.

Best suitable library those I found are - Firebase library and WebPush Library.

Steps to be followed with Firebase library’s implementation -

1. Install Firebase.
2. Make firebase file.
3. Setup account with Firebase.
4. register firebase with service worker.

Steps to be followed to implement withPush library -
1. write code to check for subscription.
2. write code to Subscribe to ( browser's ) PUSH SERVICE.
3. write code to send notifications from node.js server ( using Google's webPush Library ).

**Comment by glo82145** [comment]
As above information is provided, hence closing the ticket.

Please feel free to reopen it in case of any update.
