### ISSUE TITLE
[bug]: NoProductsFound component not work properly

### ISSUE THREAD

**Issue by SergioDonati** [magento/pwa-studio#3924]
**Describe the bug**

Component NoProductsFound still use category id instead of uid.

**To reproduce**

1. Go to in category page
2. Click on filter without products
3. NoProductsFound will render with warnings

**Expected behavior**

No show warnings and validation errors

**Possible solutions**

NoProductsFound and useNoProductsFound should use uid and expect a string instead of number.

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug
