### ISSUE TITLE
PWA Cart page graph-ql error

### ISSUE THREAD

**Issue by imvinayak11** [magento/pwa-studio#3945]
I am using magento 2.4.3-p2. 

I have installed PWA studio with venia concept theme. I have followed adobe docs to install PWA studio on my local system.

I am facing an issue with the cart page. basically, I have added some products to the cart, the products are visible in the mini cart but when I click on "Edit Shopping Bag"  the /cart page is showing "There are no items in your cart. ".  

I have checked the dev tools -> console, i am getting "[GraphQL error]: Message: Cannot query field "errors" on type "CartItemInterface"., Location: [object Object], Path: undefined".

API : https://testpwa.magento.com:8530/graphql?query=query+GetCartDetails%28%24cartId

dev-tools-> network- > Fetch/xhr -> preview "errors: [{message: "Cannot query field "errors" on type "CartItemInterface".",…}]"

dev-tools-> network- > Fetch/xhr -> response  "{"errors":[{"message":"Cannot query field \"errors\" on type \"CartItemInterface\".","extensions":{"category":"graphql"},"locations".

![Screenshot from 2022-08-26 15-42-37](https://user-images.githubusercontent.com/86782069/186883483-cbe6b504-8752-481e-92b1-99627cb48220.png)

**Comment by imvinayak11** [comment]
@magento I am working on this

**Comment by imvinayak11** [comment]
@magento add to contributors team

**Comment by anthoula** [comment]
Hi @imvinayak11 Thank you for the feedback! Please check the PWA version you are using is compatible with the Magento version: https://developer.adobe.com/commerce/pwa-studio/integrations/adobe-commerce/version-compatibility/
