### ISSUE TITLE
[bug]: Incorrect prop-type for tabindex in CategoryTree components

### ISSUE THREAD

**Issue by JustinConabreeAbsolunet** [magento/pwa-studio#3948]
**Describe the bug**

Developer console shows errors due to incorrect prop type declaration for `tabindex` (or `tabIndex`) in `Tree` and `Branch` and `Leaf` components under `CategoryTree`. It's defined as function but Navigation is declaring `const tabindex = isOpen ? '0' : '-1';`

Also incorrectly passing the attribute to the `button` in `categoryBranch`. Should be `tabIndex`

Loading homepage produces follow errors in console when running project in watch

```
Warning: Failed prop type: Invalid prop `tabindex` of type `string` supplied to `Tree`, expected `function`.

Warning: Failed prop type: Invalid prop `tabindex` of type `string` supplied to `Branch`, expected `function`.

Warning: Failed prop type: Invalid prop `tabindex` of type `string` supplied to `Leaf`, expected `function`.

Warning: Invalid DOM property `tabindex`. Did you mean `tabIndex`?
```

**To reproduce**

1. Run project in watch mode (or build in developer)
2. Go to homepage
3. Open developer tools
5. See errors

**Expected behavior**

No errors in console

**Possible solutions**

Change proptype to string and pass to button as tabIndex

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by JustinConabreeAbsolunet** [comment]
Hi @anthoula 

I see that 12.7 was supposed to address this issue but it's still present. The error is now just `tabIndex` instead of `tabindex` from [this PR](https://github.com/magento/pwa-studio/pull/3942/files). What needs to change is the prop type. It's being passed a string, not a function

**Comment by anthoula** [comment]
Hey @JustinConabreeAbsolunet ! Yes we've noticed that has not been resolved and we are tracking it as a separate lower priority backlog issue

**Comment by schizek** [comment]
@anthoula, are you able to provide a link so we can follow the status of the remaining issue?
