### ISSUE TITLE
[bug]: Page Builder column-line content type is not supported, this content will not be rendered.

### ISSUE THREAD

**Issue by gijsvds** [magento/pwa-studio#3949]
**Describe the bug**

Ever since we upgraded to Magento 2.4.5 our Pagebuilder content that uses a column has stopped working. We tested this on a clean Pwa Studio install with a Magento 2.4.5 backend attached to it.

**To reproduce**

1. install a fresh pwa studio environment
2. attach it to a magento 2.4.5 backend
3. use a column in pagebuilder on your homepage (or any other page)

**Expected behavior**

I expect to see the columns and their content I added using pagebuilder in the frontend application.

**Screenshots**

Landing page backend used for my current homepage:
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/94620325/187884891-b51a7597-de58-4b51-ac6f-0c1aaa0c1eca.png">

Landing page frontend used for my current homepage:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/94620325/187885223-976775da-e033-43b3-8b47-bad5e802bcc9.png">

error in console:
<img width="1909" alt="image" src="https://user-images.githubusercontent.com/94620325/187885320-f344f125-362e-4ad2-964c-3aa212f6e65e.png">

**Possible solutions**

Extend the @magento/pagebuilder/lib/ContentTypes with the new column-line type.

**Debug Report**

**_yarn build:report output :_**
yarn run v1.22.17
$ buildpack generate-build-report
  ℹ  Generating build report for pwa-test@0.0.1. This may take a moment.

  ℹ  Inspecting Dependencies
    Found 9 @magento dependencies in yarn.lock
    @magento/pwa-buildpack @ 11.4.0
    @adobe/apollo-link-mutation-queue @ 1.0.2
    @magento/babel-preset-peregrine @ 1.2.1
    @magento/eslint-config @ 1.5.3
    @magento/pagebuilder @ 7.4.1
    @magento/peregrine @ 12.5.1
    @magento/pwa-theme-venia @ 1.3.0
    @magento/upward-security-headers @ 1.0.10
    @magento/venia-ui @ 9.6.0

  ℹ  Inspecting Magento Backend
    Not using sample backend.
    Backend is UP!

  ℹ  Inspecting System
    OS: Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64
    Node Version: v16.15.0
    NPM Version: 8.5.5

✨  Done in 4.25s.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: Mac
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: Version 104.0.5112.101 (Official Build) (x86_64)
-   Magento Version [e.g Adobe Commerce 2.4]: Magento ver. 2.4.5

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [x] `pagebuilder`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@gijsvds - Thanks for the input. Is `column-line` and extension by chance? This is not part of the base supported content types.

**Comment by gijsvds** [comment]
@anthoula - Thank you for responding. No, it shouldn't be an extension. It may have something to do with this new feature in 2.4.5:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/94620325/188885205-50565c1c-d332-4445-96ab-b442849630dd.png">

maybe the name of the column-type was changed there? I'm not sure but I do know the issue started since we upgraded to magento 2.4.5

**Comment by yaroslav-qlicks** [comment]
Have same issue, when possible fix will be released?

**Comment by oleksiyzestlogic** [comment]
> Have same issue, when possible fix will be released?

I added a quick fix on my project (I know, it's a dirty fix, but it allowed us continue work on the project with minimal time spent):

1. Override config 
```
module.exports = componentOverride = {
...
    ['@magento/pagebuilder/lib/config.js']: 'src/components/Pagebuilder/config.js'
...
};
```

2. Added "column-line" and used ColumnGroup for this component 
```
...
    'column-group': {
        configAggregator: columnGroupConfigAggregator,
        component: ColumnGroup
    },
+    'column-line': {
+        configAggregator: columnGroupConfigAggregator,
+        component: ColumnGroup
+    },
    image: {
        configAggregator: imageConfigAggregator,
...
```

**Comment by gijsvds** [comment]
@oleksiyzestlogic Thank you for providing this temporary solution. We may use this in our project aswel until a fix is provided in pwa-studio.

**Comment by sanganinamrata** [comment]
@oleksiyzestlogic Thank you for this temporary solution. It helped resolve my issue temporary. But waiting from @pwa-studio-bot to release its fixes on repo only.

**Comment by apomili** [comment]
> > Have same issue, when possible fix will be released?
> 
> I added a quick fix on my project (I know, it's a dirty fix, but it allowed us continue work on the project with minimal time spent):
> 
> 1. Override config
> 
> ```
> module.exports = componentOverride = {
> ...
>     ['@magento/pagebuilder/lib/config.js']: 'src/components/Pagebuilder/config.js'
> ...
> };
> ```


Can you please specify in witch file we can add this override?
