### ISSUE TITLE
[bug]: Payment method always reverts to “Check / Money order” when there is an error with the transaction

### ISSUE THREAD

**Issue by fdussaultAbsolunet** [magento/pwa-studio#3950]
**Describe the bug**

The payment method always reverts to “_Check / Money order_” when there is an error with the transaction in PWA Studio, even if _Credit Card_ mode was previously selected.

**To reproduce**

1. Activate multiple payment methods, like check money order and braintree
2. Get a product in your cart and proceed to checkout
3. Fill the Shipping Information and Shipping Method forms
4. Select "_Credit Card_"
5. Manually refresh the browser page (as a failing payment would do)

**Expected behavior**

When there is a transaction failure, the page is refreshing but the selected payment method should remain to Credit Card rather than selecting back the first available method in the list (since credit is also available).

**Screenshots**

![image](https://user-images.githubusercontent.com/112636245/187937114-7dbd48fb-4be7-4fca-abdd-b3482147f8a7.png)

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug
