### ISSUE TITLE
Magento Docs has a Slack Channel Link, but on openning the link it says "doesn’t have an account on this workspace."

### ISSUE THREAD

**Issue by Gameboy98** [magento/pwa-studio#3956]
Magento Docs has a Slack Channel Link, but on openning the link it says "doesn’t have an account on this workspace."

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
@Gameboy98 - The site is currently working. Please try creating an account to see if that enables access.
