### ISSUE TITLE
[bug]: BrowserPersistence#getItem throws for undefined value

### ISSUE THREAD

**Issue by Buuhuu** [magento/pwa-studio#3965]
**Describe the bug**

It is possible to add an item to an instance of `BrowserPersistence` with an `undefined` value.

```
const storage = new BrowserPersistence();
storage.setItem('foobar', undefined);
```

Retrieving the same value causes an error because `getItem()` tries to parse the undefined value

```
storage.getItem('foobar'); 
// Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
//    at JSON.parse (<anonymous>)
//    at i.getItem
```

**To reproduce**

**Expected behavior**

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Adobe Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Thanks @Buuhuu . Would you share more details, and the use-case you are solving for?
