### ISSUE TITLE
[bug]: Do not clear cart id after Sign out

### ISSUE THREAD

**Issue by denyskuz** [magento/pwa-studio#3970]
**Describe the bug**

When the customer login and adds a product to the cart, her cart id doesn't clear after signing out.

**To reproduce**

1. Go to Sign In modal
2. Enter your credentials
3. Click on sign in button
4. Go to the product page
5. Add product to the cart
6. Check cart id in local storage
7. Go to the account menu
8. Click on the Sign Out link
9. Check cart id in local storage (it does not change) and product count will be the same 

**Screenshots**
Video: 
https://youtu.be/QeIS3A7w5N4

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
To disable session cookies: try the following: https://devdocs.magento.com/guides/v2.4/graphql/authorization-tokens.html#session-cookies
