### ISSUE TITLE
[bug]: Add uid instead of id in noProductsFound.js

### ISSUE THREAD

**Issue by dupadhyay3** [magento/pwa-studio#3981]
**Describe the bug**

We have already deprecated id field and we will replace it with uid changes but there is still missing one place in category page if there is no products for category then below component is called that used category.id instead of category.uid. due to id is not there in object that gives console warning for key.

![](https://user-images.githubusercontent.com/32363872/196211922-6b829476-4522-4d83-818e-5474b52e9625.png)

**@magento/venia-ui/lib/RootComponents/Category/NoProductsFound/noProductsFound.js
https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/RootComponents/Category/NoProductsFound/noProductsFound.js#L31

Only changes of UID will automatically gets the latest changes as per unique identifier.

**To reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device <e.g. iPhone6, PC, Mac, Pixel3>:
-   Browser <e.g. Chrome, Safari>:
-   Browser Version <e.g. 22>:
-   Magento Version <e.g Adobe Commerce 2.4>:

<![](-- Complete the following sections to help us apply appropriate labels) -->

**Please let us know what packages this bug is in regards to:**

-   < > `venia-concept`
-   <x> `venia-ui`
-   < > `pwa-buildpack`
-   < > `peregrine`
-   < > `pwa-devdocs`
-   < > `upward-js`
-   < > `upward-spec`
-   < > `create-pwa`

### Test Plan 
- Verify Category page loads with. products
- Create an empty category and navigate to it and verify UID is present instead of ID.
- On category apply filters and verify UID is present when filter results in products and also when filters results in no products.
- Verify same on Search pages for category filter with and without filters
- Verify existing cypress test CI job passes.
NOTE - No browser or device testing needed for this pr given no UI changes

**Comment by dupadhyay3** [comment]
@magento I am working on this

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug
