### ISSUE TITLE
[bug]: Clicking the Filters text label doesn't actually select the filter

### ISSUE THREAD

**Issue by fdussaultAbsolunet** [magento/pwa-studio#3994]
**Describe the bug**
On a mobile device or desktop, when clicking on the text of a specific filter, it doesn't select the filter. For it to work properly, you have to specifically press on the **checkbox**.

**To reproduce**

1. Go to http://develop.pwa-venia.com/default/venia-tops.html?page=1
2. Expand any filter group
3. Click on the **text label** (not the checkbox itself) to apply a filter
5. Witness the problem: the filter doesn't get selected (it used to)

**Expected behavior**

When pressing or clicking on the text label beside the filter checkbox, the filter should be applied exactly as if I have explicitly clicked on the filter checkbox. The full line should be responsive to the selection (not only the checkbox part)

**Screenshots**

<img width="359" alt="Screen Shot 2022-10-28 at 12 40 41 PM" src="https://user-images.githubusercontent.com/112636245/198689953-88595251-3220-4ef5-9a91-d9c24a1096e4.png">

**Please complete the following device information:**

-   Device: Mac M1 and iPhone11 Pro
-   Browser: Chrome (desktop), Safari (mobile)
-   Browser Version: Chrome desktop 106.0.5249.119 (Official Build) (arm64) / Safari mobile iOS 16.0.2

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by tsuda-satoshi** [comment]
I think https://github.com/magento/pwa-studio/commit/22e192ba77bf9effea8159401404b1a07d4e3640 make this bug, by changing events for checkbox from `onClick` to `onMouseDown`.
It seems that `onClick` event is fired when either click checkbox  or click label, but `onMousedDown` event is fired only when mouse is pressed over checkbox.

**Comment by Sahilsks** [comment]
Please assign it to me  @magento I am working on this

**Comment by Sahilsks** [comment]
@magento add to contributors team

**Comment by Sahilsks** [comment]
Please assign it to me https://github.com/magento I am working on this

**Comment by Sahilsks** [comment]
@magento I am working on this

**Comment by glo82145** [comment]
This issue is fixed with https://jira.corp.adobe.com/browse/PWA-3025
