### ISSUE TITLE
[bug]: Selecting payment method causing graphql error

### ISSUE THREAD

**Issue by justinconabree** [magento/pwa-studio#4003]
**Describe the bug**

In 12.7 [a fix was made](https://github.com/magento/pwa-studio/issues/3950) to visually select the method of payment that is saved as selected on the quote. However it also added an onChange function that executes a mutation to save the payment method.

https://github.com/magento/pwa-studio/pull/3969/files#diff-b3bc0e73e1c57b4b69ad1d1cc59b3d3e60021bd9ec46a399b73305079e2ebb11R54

This causes a graphql error for custom payment methods that require additional information. This can be seen by the need to pass in braintree data, which wouldn't be needed for non-braintree payment methods. Other payment methods require their own "braintree equivalent" data in order to be set

Example for our custom payment method for Moneris (code: mht), we now get an error when selecting the payment method radio button:
`message: "Required parameter \"mht\" for \"payment_method\" is missing."`

Data sent to graphql endpoint:
```
variables: {
    cartId: "ZSNL4bWFnEaYmrtCcinryj76gCvoDcho"
    paymentMethod: {
        code: "mht", 
        braintree :  {
            is_active_payment_token_enabler: false
            payment_method_nonce: "mht"
        }
    }
}
```

**Expected behavior**

No graphql error when changing radios for payment method

**Possible solutions**

Don't call setPaymentMethodOnCart at a higher level than the payment method. Leave saving the payment method to the payment method (usually when going to review step, not when selecting the radio)

**Please complete the following device information:**

-   Magento Version: Adobe Commerce 2.4.5-p1
-   PWA Studio Version: 12.7.0

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket PWA-3029 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fpwa-studio+PWA-3029&type=commits


Thanks

**Comment by justinconabree** [comment]
@glo82145 the fix is incorrect. It will break with custom payment methods that require more data than just the code (which is all except money order)
