### ISSUE TITLE
unable to start the project

### ISSUE THREAD

**Issue by satyam224152** [magento/pwa-studio#4005]
i have install fresh venia project but package json file not created 
![Screenshot from 2022-11-15 19-44-24](https://user-images.githubusercontent.com/76769857/201941397-15f241e8-3f01-4979-8245-097da6251746.png)
this is my project structure and  in src folder i had install magento project , and i had install venia 
![Screenshot from 2022-11-15 19-43-58](https://user-images.githubusercontent.com/76769857/201941562-ca17ce31-d651-4c7c-9a9c-cf06c2c6e931.png)
and this issue genrated

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Hi @satyam224152 - Would you provide more details, including steps to reproduce?
