### ISSUE TITLE
[bug]: Visual bug when cancelling changing an edit shipping method.

### ISSUE THREAD

**Issue by mattiomls** [magento/pwa-studio#4007]
**Describe the bug**

This is a visual bug when in the checkout and you have changed a shipping method (used edit shipping method) then open the edit shipping method dialog box again and press cancel/close it, you will see for a split second while it is closing the form choose the old shipping method.
If using the Dialog box with input fields this visual bug is more apparent.

As a side note it would be nice to have the carrier title displayed also in shipping method as the shipping methods on the gif are separate shipping methods with different carrier titles but can't be told apart.

**To reproduce**

1. Go to checkout with some product/s.
2. Set shipping information.
3. Set the shipping method.
4. Change the shipping method.
5. Go to edit the shipping method but don't change it and press cancel.
6. In a split second you will see the option go to the shipping method set initially in step 3.

**Expected behavior**

When the shipping method has been edited and then it is edited again it should reset after the Dialog window has been closed using the informed library.

**Screenshots**

![msedge_6OvE9JtLyD](https://user-images.githubusercontent.com/118520744/202676653-20f054ff-db80-42dc-b723-6a7d263996fa.gif)

**Possible solutions**

It seems to have to do with the buttons in the Dialog box component using the type="reset" as it seems that doing that does not do a proper reset for the states in the informed form library that is being used.

A possible solution would be to change the buttons in the Dialog box component to type="button" then using the informed library to reset the state, either when the dialog is detected as closed or creating a function that calls onClose and reset for the form in the informed library and then pass that function to the onClick on the buttons.

**Please complete the following device information:**

- Windows computer using edge browser.
- Was tested on PWA studio 12.5, Dialog box in 12.7 is also using type="reset" so should persist there.

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by anthoula** [comment]
Issue does not have a persisting affect on the state of the shipping method in checkout, so issue is minor & closing.
