### ISSUE TITLE
[bug]: PWA Scaffolding Tool uses old version

### ISSUE THREAD

**Issue by schizek** [magento/pwa-studio#4010]
**Describe the bug**

Using the create PWA scaffolding tool appears to use an old version. This appears it is related to issue #4009 that was closed without resolution.

**To reproduce**

1. Run the `yarn create @magento/pwa` or `npx @magento/create-pwa` command
2. Note that during the questionnaire portion the prompt only includes mention of Magento `2.3.3` and `2.4-develop`
    > ? Magento instance to use as a backend (will be added to .env file) (Use arrow keys)
    > ❯ Magento 2.3.3 with Venia sample data installed
    > Magento 2.4-develop with Venia sample data installed
    > Other (I will provide my own backing Magento instance)
3. Regardless of which option you select the generated `.env` file includes the following (note the mention of "Magento 2.3"...
    ```
    #### Connecting to a Magento store #############################################
    #
    #   Connect to an instance of Magento 2.3 by specifying its public domain name.
    MAGENTO_BACKEND_URL=https://venia-develop-ccewfjy-mfwmkrjfqvbjk.us-4.magentosite.cloud/
    #
    ################################################################################
    ```
    Additionally, if selecting `2.4-develop` the generated cloud instance url does not work after running `yarn watch` (as mentioned in #4009)

**Expected behavior**

I would expect to not see a reference to `2.4-develop` in the questionnaire, `2.3` in the `.env` file, and the generated 2.4 `MAGENTO_BACKEND_URL` should work.

**Debug Report**

```
❯ yarn build:report
yarn run v1.22.19
$ buildpack generate-build-report
  ℹ  Generating build report for testing2@0.0.1. This may take a moment.

  ℹ  Inspecting Dependencies
    Found 9 @magento dependencies in package-lock.json
    @magento/pwa-buildpack @ 11.4.1
    @adobe/apollo-link-mutation-queue @ 1.0.2
    @magento/babel-preset-peregrine @ 1.2.2
    @magento/eslint-config @ 1.5.3
    @magento/pagebuilder @ 7.4.2
    @magento/peregrine @ 12.6.0
    @magento/pwa-theme-venia @ 1.4.0
    @magento/upward-security-headers @ 1.0.11
    @magento/venia-ui @ 9.7.0

  ℹ  Inspecting Magento Backend
    Not using sample backend.
    Backend is UP!

  ℹ  Inspecting System
    OS: Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
    Node Version: v16.18.1
    NPM Version: 8.19.2


✨  Done in 4.38s.
```

**Please complete the following device information:**

-   Device: Mac
-   Browser: N/A - Terminal
-   Browser Version: N/A
-   Magento Version: Adobe Commerce 2.4

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [x] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket PWA-3047 by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fpwa-studio+PWA-3047++&type=commits

Thanks
