### ISSUE TITLE
PWA 

### ISSUE THREAD

**Issue by narayansinghjai** [magento/pwa-studio#4012]
i'm facing this issues when i run this cmd **yarn run watch:venia** in windows

i ｢wdm｣: wait until bundle finished: 
i ｢wds｣: Project is running at http://0.0.0.0:10000/
i ｢wds｣: webpack output is served from /
17% [0] building 60/65 modules 5 active C:\Users\jai.narayan\eclipse-workspace\PWA\pwa\pwa-studio\node_modules\html-entities\lib\index.js        
warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
× ｢wdm｣: Child client-config:
       2116 modules

    ERROR in ../pwa-buildpack/node_modules/webpack-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-2
    Module not found: Error: Can't resolve 'C:Usersjai.narayaneclipse-workspacePWApwapwa-studiopackages♂enia-concepten_US.json' in 'C:\Users\jai.narayan\eclipse-workspace\PWA\pwa\pwa-studio\packages\venia-concept'
i ｢wdm｣: Failed to compile.

**Comment by narayansinghjai** [comment]
Hi @m2-assistan

node version: v14.15.3

I have  cloned the pwa-studio respository
and performed the below commands in windows os
1. yarn install
2 .when i run the  **yarn run watch:venia**  command  im facing the below issue

Emitting no ServiceWorker in development mode.
i ｢wdm｣: wait until bundle finished: 
i ｢wds｣: Project is running at http://0.0.0.0:10001/
i ｢wds｣: webpack output is served from /
17% [0] building 61/65 modules 4 active C:\Users\jai.narayan\eclipse-workspace\PWA\pwa-studio\node_modules\html-entities\lib\index.jsBrowserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
× ｢wdm｣: Child client-config:
       2112 modules

    ERROR in (webpack)-inject-plugin/dist/webpack-inject-plugin.loader.js?id=webpack-inject-module-2
    Module not found: Error: Can't resolve 'C:Usersjai.narayaneclipse-workspacePWApwa-studiopackages♂enia-concepten_US.json' in 'C:\Users\jai.narayan\eclipse-workspace\PWA\pwa-studio\packages\venia-concept'
i ｢wdm｣: Failed to compile.

**Comment by huykon** [comment]
@narayansinghjai this was reported on https://github.com/magento/pwa-studio/issues/2810

**Comment by narayansinghjai** [comment]
@huykon could please provide any update on this

**Comment by huykon** [comment]
@narayansinghjai they haven't update this yet. You should use ubuntu or macOs for develop. Feel free to follow issue above

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug
