### ISSUE TITLE
[bug]: Sevice worker fetch static file, images error

### ISSUE THREAD

**Issue by huykon** [magento/pwa-studio#4016]
**Describe the bug**

In my progress development pwa studio, I see this issue on some Chrome browsers, not at all. I guess it causes by service worker workbox. Please help to resolve this.
![image](https://user-images.githubusercontent.com/9253798/207253697-c6d66650-1b4a-4b73-922a-a00f6841d3d3.png)

**To reproduce**

1. Go to ['home page'](https://develop.pwa-venia.com/)
2. Open inspect mode of Chrome browser (Ctrl + Shift + I)
3. Nagive to console tab

**Expected behavior**

All static files (large or small files) should be cached by workbox without error

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: Linux, Mac
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: 107.0.5304.110 
-   Magento Version [e.g Adobe Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [x] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo80771** [comment]
As this ticket is retested, the issue is not reproducible and hence the ticket remains in review and acceptance status.

**Comment by Tarun50745** [comment]
Hi @huykon ,
 
As per the defined Github guidelines, we didn’t receive any updates on my last query, hence closing this issue.
Please feel free to reopen the ticket in case reproducible in future.
