### ISSUE TITLE
[feature]: Server Side Rendering 

### ISSUE THREAD

**Issue by papiliond** [magento/pwa-studio#4021]
**Description**
I believe that PWA Studio is missing a very important feature which is mandatory for great SEO and acceptable load time performance both on desktop and mobile devices. Server Side Rendering and Static Site Generation are supported by the most popular web frontend frameworks in 2022 (e.g. Next, Nuxt, Gatsby, etc.) and it is a great way to build top-notch frontends. 

**Solution**
Rebuilding PWA Studio to a Next.js app would be such a big bite, so I don't intend to do that. I believe that we should implement Server Side Rendering support without major architecture changes and just use the [ReactDOMServer API ](https://reactjs.org/docs/react-dom-server.html) to render inside Nodejs environment. Generating the pages on the server side can take few seconds depending on the graphql queries, therefore some sort of cache is also recommended.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [x] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by papiliond** [comment]
@magento I am working on this

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Hi @papiliond , Thanks for your feedback. This feature is not currently prioritized. In the meantime, please reach out to our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us) for additional support.

**Comment by huykon** [comment]
any news for this one?
