### ISSUE TITLE
[feature]: Swatches on product at product listing page.

### ISSUE THREAD

**Issue by sanganinamrata** [magento/pwa-studio#4023]
**Is your feature request related to a problem? Please describe.**
This feature was already on the PWA studio team's Roadmap at https://github.com/magento/pwa-studio/wiki/Roadmap But it's updated now for Planning (1H 2023), May I know if this feature implemented? If yes, Then I can not see it on https://venia.magento.com/ 

**Describe the solution you'd like**
SWatches selection on product listing like category & search result page.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [x] `pwa-buildpack`
- [x] `peregrine`
- [x] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Hi @sanganinamrata , Thanks for your feedback. This feature is not currently prioritized. In the meantime, please reach out to our [PWA community Slack channel](https://github.com/magento/pwa-studio/wiki#contact-us) for additional support.
