### ISSUE TITLE
Need to add item in wishlist for guest user

### ISSUE THREAD

**Issue by arvind-netzwelt** [magento/pwa-studio#4026]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by arvind-netzwelt** [comment]
How to add wishlist item for guest users and after log-in it automatically moves to login user wishlist

**Comment by kimdontdoit** [comment]
> How to add wishlist item for guest users and after log-in it automatically moves to login user wishlist

I presume it might require storing the wish list items locally, and once a user is created (login? sign up?) will require mutation towards a default wishlist

**Comment by arvind-netzwelt** [comment]
I have already tried this but have not been able to fix the issue. Could you please provide the exact code for this?

**Comment by arvind-netzwelt** [comment]
any update on this issue

**Comment by Raymontadal** [comment]
Il me faut mon ốc pour vider

**Comment by arvind-netzwelt** [comment]
I have fixed this
