### ISSUE TITLE
[feature]: Move Out of Stock Products at Last on Category page

### ISSUE THREAD

**Issue by faisal-project** [magento/pwa-studio#4029]
**Is your feature request related to a problem? Please describe.**
No, It's new one.

**Additional context**
I want to move all out of stock product at last on category page.

Thanks

**Comment by anthoula** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by anthoula** [comment]
Hi @faisal-project - Thanks for your feedback. There are admin settings to turn On or Off the display of out of stock products, but sorting to place them at the end is not supported.
