### ISSUE TITLE
[bug]: When you click on Thumbnail, Add to cart works

### ISSUE THREAD

**Issue by Anstiuk2412** [magento/pwa-studio#4036]
'**Describe the bug**

After selecting the product configuration and clicking on Thumbnails, the product is unexpectedly added to the cart

**To reproduce**

1. Go to Product page
2. Click on Swatches
3. Click on Thumbnail

**Expected behavior**

After selecting the product configuration and clicking on Thumbnails, only the image should change

**Possible solutions**

We need add type="button" to thumbnail

**Please complete the following device information:**

-   Device All:
-   Browser ALL:
-   Browser Version ANY:
-   Magento Version [e.g Adobe Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [+] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by Anstiuk2412** [comment]
@magento I am working on this

**Comment by Anstiuk2412** [comment]
@magento add to contributors team

**Comment by Anstiuk2412** [comment]
+

**Comment by Anstiuk2412** [comment]
+

**Comment by Anstiuk2412** [comment]
I am join

**Comment by Anstiuk2412** [comment]
https://github.com/magento add to contributors team

**Comment by Anstiuk2412** [comment]
@magento I am working on this

**Comment by daniel-pettersson-ecomero** [comment]
Va fa dun f¨rn icgsfd

**Comment by glo82145** [comment]
Hello,

As I can see this issue got fixed in the scope of the internal Jira ticket [PWA-3080](https://jira.corp.adobe.com/browse/PWA-3080) by the internal team
Related commits:https://github.com/search?q=repo%3Amagento%2Fpwa-studio+PWA-3080&type=commits


Thanks
