### ISSUE TITLE
How to add Bundle product in cart

### ISSUE THREAD

**Issue by arvind-netzwelt** [magento/pwa-studio#4046]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by engcom-Alfa** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by glo24157** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by engcom-Hotel** [comment]
@adobe export issue to JIRA project PWA as Story

**Comment by arvind-netzwelt** [comment]
I Have changed the code for Bundle product but now simple product not added
Here is the code:
import { useCallback, useState } from 'react';
import { useMutation } from '@apollo/client';
import { useHistory } from 'react-router-dom';

import { useCartContext } from '@magento/peregrine/lib/context/cart';
import { useEventingContext } from '@magento/peregrine/lib/context/eventing';
import operations from './addToCart.gql';

/**
 * @param {String} props.item.uid - uid of item
 * @param {String} props.item.name - name of item
 * @param {String} props.item.stock_status - stock status of item
 * @param {String} props.item.__typename - product type
 * @param {String} props.item.url_key - item url key
 * @param {String} props.item.sku - item sku
 *
 * @returns {
 *      handleAddToCart: Function,
 *      isDisabled: Boolean,
 *      isInStock: Boolean
 * }
 *
 */
const UNSUPPORTED_PRODUCT_TYPES = [
    'VirtualProduct',
    'BundleProduct',
    'GroupedProduct',
    'DownloadableProduct'
];

export const useAddToCartButton = props => {
    const { item, urlSuffix } = props;
    const [, { dispatch }] = useEventingContext();

    const [isLoading, setIsLoading] = useState(false);

    const isInStock = Array.isArray(item) ? item[0].stock_status : item.stock_status === 'IN_STOCK';

    const productType = Array.isArray(item) ? item[0].__typename : item.__typename;
    
    const isUnsupportedProductType = UNSUPPORTED_PRODUCT_TYPES.includes(
        productType
    );
    const isDisabled = isLoading || !isInStock || isUnsupportedProductType;

    const history = useHistory();

    const [{ cartId }] = useCartContext();

    const [addToCart] = useMutation(operations.ADD_ITEM);

    const allowed = Array.isArray(item) && item.map(obj=> obj.__typename).filter(ite => ite !== "SimpleProduct").length === 0

    const handleAddToCart = useCallback(async () => {
        try {
            if (productType === 'SimpleProduct'|| allowed) {
                setIsLoading(true);

                const quantity = 1;
                const cartItem = Array.isArray(item) ? item.map(obj => ({
                    
                        quantity,
                        entered_options: [
                            {
                                uid: obj.uid,
                                value: obj.name
                            }
                        ],
                        sku: obj.sku
                    
                })): item;
                await addToCart({
                    variables: {
                        cartId,
                        cartItem,
                    }
                });

                dispatch({
                    type: 'CART_ADD_ITEM',
                    payload: {
                        cartId,
                        sku: item.sku,
                        name: item.name,
                        priceTotal:
                            item.price_range.maximum_price.final_price.value,
                        currencyCode:
                            item.price_range.maximum_price.final_price.currency,
                        discountAmount:
                            item.price_range.maximum_price.discount.amount_off,
                        selectedOptions: null,
                        quantity
                    }
                });

                setIsLoading(false);
            } else if (productType === 'ConfigurableProduct') {
                history.push(`${item.url_key}${urlSuffix || ''}`);
            } else {
                console.warn('Unsupported product type unable to handle.');
            }
        } catch (error) {
            console.error(error);
        }
    }, [productType, addToCart, cartId, item, dispatch, history, urlSuffix]);

    return {
        handleAddToCart,
        isDisabled,
        isInStock
    };
};

**Comment by glo42707** [comment]
We have triaged the ticket and sent for PO confirmation if we can take it up.

**Comment by tkacheva** [comment]
@arvind-netzwelt Bundle products are not supported OOB in PWA Studio. If you are willing to contribute the support of the bundle products from displaying in catalog to checking out cart with the bundle product in it, we will process the PR.

**Comment by glo42707** [comment]
HEY @arvind-netzwelt 
as per current scope of PWA studio, it only support simple, configurable and gift types of product for checkout.
as we can find on https://developer.adobe.com/commerce/pwa-studio/integrations/adobe-commerce/features/

however we welcome the contribution from community so if you are ready to contribute PR, accordingly we can process the PR after testing.

with this closing the ticket, please feel free to reopen the ticket if anything to be discussed.
