### ISSUE TITLE
When will stripe payment be supported?

### ISSUE THREAD

**Issue by zxiaoh** [magento/pwa-studio#4048]
![6bddaab4-308d-4739-9286-bcef05d54c78](https://user-images.githubusercontent.com/31463778/221811914-86f61e00-4972-46af-8cf2-1e375efb67f1.jpeg)

Adding multiple payment methods has reached a point where it is very important!

**Comment by OneCricketeer** [comment]
Duplicates #3258

**Comment by zxiaoh** [comment]
> Duplicates #3258

Can you be more detailed? #3258 didn't solve my problem.

**Comment by OneCricketeer** [comment]
I don't have an official answer... That issues says that there appears to be a Magneto core extension in the Marketplace for enabling Stripe payments on the backend.

Beyond that, you will need to [bring-your-own frontend Stripe components](https://stripe.com/payments/elements) into PWA Studio.

**Comment by glo82145** [comment]
Thanks @OneCricketeer for addressing the query.

As this query is addressed, hence we are closing this issue.
Please feel free to reopen if you are still have anymore query on the same.
