### ISSUE TITLE
Components for Adyen Payment method

### ISSUE THREAD

**Issue by nonni96** [magento/pwa-studio#4071]
Hi,
Are there any components available in PWA-Studio that allow support for the Adyen payment method?

Thanks

**Comment by OneCricketeer** [comment]
Not currently. It seems [Adyen has React samples](https://github.com/adyen-examples/adyen-react-online-payments) themselves, which you may be able to style. 

[Here is a sample](https://github.com/magento/pwa-studio/tree/develop/packages/extensions/venia-sample-payments-checkmo) of using doing the same for custom Check/Money Order component

**Comment by glo82145** [comment]
Thanks @OneCricketeer for commenting. 

@nonni96 As your question has been  answered with above comment, we are closing this issue. 
Please feel free to reopen this issue in case of any query.
