### ISSUE TITLE
[bug]: Users data not cleans after sign out

### ISSUE THREAD

**Issue by sm1thana** [magento/pwa-studio#4073]
**Describe the bug**
Customer's cart and payment and shipping methods are not deleting after sign out.

**To reproduce**
1. Go to venia.magento.com and sign in. 
2. See merged cart with items or add something.
3. Sign out and got reloaded.
3. You are a guest now but cart is not empty and if you will go to checkout, you will see your customer's payment and shipping methods.

**Expected behavior**
Cart, payment and shipping methods should be empty. And they were in previous versions.

**Screenshots**

![image](https://user-images.githubusercontent.com/29203592/228496116-7c4ee9c4-95d0-429d-8802-dccfa9c643e4.png)

**Please complete the following device information:**
-   Device PC:
-   Browser Chrome, Firefox:
-   Browser Version latest:

**Comment by sm1thana** [comment]
@magento I am working on this

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by RaghavendraTirumalasetti** [comment]
@magento i am working on this issue

**Comment by glo82145** [comment]
Hi @sm1thana - This is a known issue in PWA, Please go through Known issues section in [PWA ChangeLog](https://github.com/magento/pwa-studio/releases/tag/v13.2.0). 

When a user logs out, that user's local storage session persists. As a result, the cart ID from the logged out user is retrieved and given to the guest user on the computer. This causes the following error when the guest user tries to check out: An error has occurred. Please check the input and try again. To resolve this issue, try disabling graphql session sharing as described in the GraphQL documentation on session cookies here: https://devdocs.magento.com/guides/v2.4/graphql/authorization-tokens.html#session-cookies.

There is a config setting at magento backend Stores > Configuration > Services > Magento Web API > Graphql Settings. 
We can disable session from there and On logout user will have empty cart, payment and shipping methods.

**Comment by glo82145** [comment]
As Above comment provided a possible solution for your issue, we are closing this ticket. 
Please feel free to reopen this issue if you have any update or query on the same.
