### ISSUE TITLE
Adobe Sensei product recommendations not showing in PWA homepage (Localhost)

### ISSUE THREAD

**Issue by themagedigest** [magento/pwa-studio#4076]
Adobe Sensei product recommendations not showing in the PWA homepage. But the same is showing in localhost Magento homepage.

**Comment by glo82145** [comment]
Hi @themagedigest,

For using Adobe sensei product recommendations in PWA, we have to add the venia product recommendation module in Venia frontend using following command **yarn add @magento/venia-product-recommendations**

Also, please refer the following document **https://developer.adobe.com/commerce/pwa-studio/integrations/product-recommendations/** for more information.

**Comment by glo82145** [comment]
As required documentation is provided hence we are closing this issue.
Please feel free to reopen if you are still have any query on the same.
