### ISSUE TITLE
[feature]: Tailwind v3 support

### ISSUE THREAD

**Issue by justinconabree** [magento/pwa-studio#4081]
**Is your feature request related to a problem? Please describe.**
Not a problem necessarily. Tailwind v3 comes with some additional utilities which are helpful for development.

**Describe the solution you'd like**
Update to Tailwind v3. At the same time it would be good to address some of the issues with the current tailwind implementation in venia components (direct css use, priority issues, `@TODO` tailwind comments, hardcoded values in tokens.module.css/index.module.css files)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`
- [x] `pwa-theme-venia`

**Comment by justinconabree** [comment]
@magento I am working on this

**Comment by justinconabree** [comment]
Hi @glo42707 ,

Just jumped back onto this. Just working on changing media queries over to tailwind and then will pass over the site for QA/lint fixes/cypress screenshot updates. I'll try to have it finished by end of week and then the PR to non-draft when it's ready.

Also just a note that it won't impact the pagebuilder extension as none of that code is converted to Tailwind at the moment so it's a bigger job.

I'll tag you in the PR when it's changed from draft status

Thanks!

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug
