### ISSUE TITLE
Need Support for PayPal Express Checkout Integration

### ISSUE THREAD

**Issue by amadheswaran** [magento/pwa-studio#4126]
How to add the PayPal Express Checkout to the PWA studio theme? Need support for the code customization.

**Comment by glo42707** [comment]
hey @amadheswaran 

we have raised query internally for same but as far as we know pwa does not support paypal.
but we will get back on same soon.

**Comment by glo42707** [comment]
hey @amadheswaran 

as per discussion with management, we dont have any support for paypal currently but we welcome if community is ready to contirbute.
with this discussion I am closing this ticket feel free to reopen if any query or discussion needed.
