### ISSUE TITLE
[feature]: Checkout of Virtual Product

### ISSUE THREAD

**Issue by raghvendra-1112** [magento/pwa-studio#4130]
I am not able to check-out the virtual product.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-ui`
- [ ] `peregrine`

**Comment by raghvendra-1112** [comment]
@magento I am working on this

**Comment by fooman** [comment]
@raghvendra-1112 There is this https://github.com/magento/pwa-studio/issues/3615 which is the bigger picture discussion around checkout. Hasn't seen much movement unfortunately. The current implementation is very hardcoded against physical products and adding virtual products is a big undertaking so it probably pays to check with the PWA-Studio team on the implementation design before putting in much work.

**Comment by glo42707** [comment]
HEY @raghvendra-1112 
as per current scope of PWA studio, it does not support virtual product checkout.
as can find on https://developer.adobe.com/commerce/pwa-studio/integrations/adobe-commerce/features/

however we welcome the contribution from community if ready, so accordingly we can process the PR as per testing.
