### ISSUE TITLE
[PageBuilder]: PageBuilder shows plain Html code on browser when using CMS page content

### ISSUE THREAD

**Issue by aakankshagrover0206** [magento/pwa-studio#4139]

**Comment by aakankshagrover0206** [comment]
![image](https://github.com/magento/pwa-studio/assets/137872512/8a9feaa3-9507-420d-9363-22f8d924c042)

**Comment by glo80771** [comment]
Hi @aakankshagrover0206 ,
Can you please provide the HTML code which you provided on the cms page which will be useful for us to reproduce the issue?

**Comment by aakankshagrover0206** [comment]
This is the code stored in the homepage in magento admin panel. I am trying to display this widget code accessing from magento backend and displaying it on studio storefront. 
This section is under: Content > Pages > HomePage
<p>CMS homepage content goes here123.</p>
{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" title="test" show_pager="1" products_per_page="5" products_count="10" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^]^]" page_var_name="peylvx"}}

**Comment by glo80771** [comment]
Hi @aakankshagrover0206 , 
Can you please give the expected behavior of this code which has to be displayed in the studio storefront?

**Comment by aakankshagrover0206** [comment]
Hi @glo80771 
The expected code should be like this:
![image](https://github.com/magento/pwa-studio/assets/137872512/f0117ed2-34d0-4c1d-856e-c4c107debc48)

**Comment by glo80771** [comment]
Able to reproduce and hence confirming this issue.

**Comment by glo80771** [comment]
> Hi @glo80771 The expected code should be like this: ![image](https://user-images.githubusercontent.com/137872512/250858016-f0117ed2-34d0-4c1d-856e-c4c107debc48.png)

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
https://github.com/adobe export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by Tarun50745** [comment]
@aakankshagrover0206 , I am able to see widget ( as expected ) on storefront, 
Please let us know if we missed something .

Followed below steps -
1. Created a new row ( in Home page / new page ) and a column inside row.
2. Added **Text element** and **HTML code element** respectively inside the columns .
3. Pasted below code ( shared in earlier comment ) inside both the Text and HTML code elements.

CMS homepage content goes here123.
{{widget type="Magento\CatalogWidget\Block\Product\ProductsList" title="test" show_pager="1" products_per_page="5" products_count="10" template="Magento_CatalogWidget::product/widget/content/grid.phtml" conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^]^]" page_var_name="peylvx"}}

**Result**: On the storefront 
Code pasted inside **Text element** ( left column in screenshot ) ** is displaying widget ( as expected ).
Code that pasted inside **HTML code element** ( left column in screenshot ) is displaying plain code .

Below is the screenshot, 
<img width="1436" alt="Screenshot 2023-07-18 at 4 31 47 PM" src="https://github.com/magento/pwa-studio/assets/127731581/8f41ff15-2f66-4eb6-8d36-784e73e1c877">
