### ISSUE TITLE
"This Product is currently out of stock. Please try again later."

### ISSUE THREAD

**Issue by JeremyKomarov** [magento/pwa-studio#4147]
Hello,
I got a question,
Right now when ever an product is out of stock i am getting an empty response and "This Product is currently out of stock. Please try again later.",

i want to change to still getting the product even the stock item is 0

**Comment by glo42707** [comment]
Hey @JeremyKomarov 

Thanks for writing to us.

if you want product still in enable state then for that you can either disable manage stock Globally which will create impact for overall catalog or you can Disable same Manage Stock on Product specific so it will only impact to perticular product.

Here is the link for detailed info https://experienceleague.adobe.com/docs/commerce-admin/inventory/configuration/configuration.html?lang=en


please feel to reach out or Reopen ticket in case any furthure query.
