### ISSUE TITLE
How to use TypeScript with PWA Studio?

### ISSUE THREAD

**Issue by kieryk123** [magento/pwa-studio#4148]
Hi, I recently started working with PWA Studio and Magento 2. I would like to use TypeScript in my project. In the codebase, there are many venia-ui components overrides. Do you know if there is any possibility to use TypeScript and benefit from type suggestions and auto-imports in VSC?

I will appreciate any help, I'm new at PWA Studio as well as Magento.

**Comment by glo42707** [comment]
hi @kieryk123 

as per discussion as if now there is no support of Type Script on PWA-Studio, we apprtiate if community contribute for same in future.
as per answering above closing ticket. please feel free to reopen if still not clear with reply.
