### ISSUE TITLE
[bug]: Customer signin_token purged on refresh

### ISSUE THREAD

**Issue by qburst-arjunsreedhar** [magento/pwa-studio#4152]
**Describe the bug**

**To reproduce**

1. Login as a customer in PWA store
2. Set the token in storage using the BrowserPersistence util with key 'signin_token'.
3. Refresh the page

**Expected behavior**

The token should be retained in the localStorage but it is purged.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: All devices
-   Browser [e.g. Chrome, Safari]: All Browsers
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Adobe Commerce 2.4]:  Magento ver. 2.4.6

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [x] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by RaghavendraTirumalasetti** [comment]
Hi @qburst-arjunsreedhar,
As per testing, we are not able to reproduce the issue with the latest pwa local instance and also https://venia.magento.com/.

PFA for the screenshot:
<img width="1489" alt="Screenshot 2023-08-28 at 7 47 19 PM" src="https://github.com/magento/pwa-studio/assets/104980124/446ced2b-721f-4c48-b128-2e221956d07a">

**Comment by qburst-arjunsreedhar** [comment]
Hey @RaghavendraTirumalasetti, 

I was able to fix this issue by calling the handleSubmit function returned by the `useSignIn` talon but if I do not use this method and directly insert the token to localStorage this issue occurs.

**Comment by glo82145** [comment]
@adobe export issue to Jira project PWA

**Comment by glo85315** [comment]
Hi @qburst-arjunsreedhar,

Following our recent testing, we were unable to reproduce the issue using both the latest PWA local instance and the live site at https://venia.magento.com/.


https://github.com/user-attachments/assets/df3e6584-6686-4d31-86c4-a596aa8a597f

**Comment by glo42707** [comment]
clsoing this issue since it is not reproducible at pwa end and reporter was able to fix it in his end as per above comment https://github.com/magento/pwa-studio/issues/4152#issuecomment-1700706070

cc [~glo82145]
