### ISSUE TITLE
[feature]: Get Minimum Password Length from configuration

### ISSUE THREAD

**Issue by joylee306** [magento/pwa-studio#4153]
Get Minimum Password Length from configuration

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by glo11372** [comment]
we will take this enhancement

**Comment by glo82145** [comment]
@adobe export issue to Jira project PWA
