### ISSUE TITLE
[bug]: Order history is crashing with typeError

### ISSUE THREAD

**Issue by prajeswari** [magento/pwa-studio#4160]
**Describe the bug**

order history page is crashing with below typeError
Sorry! An unexpected error occurred. Debug: TypeError25X at /26.77e1e17956b0c1e98f46.js:7:4670

**To reproduce**

1.Login with user details
2. Place some orders
3. Go to Order history page

**Expected behavior**
Order history page should open without any issues.
**Screenshots**
![image](https://github.com/magento/pwa-studio/assets/78781200/ed868aa1-21a5-4cae-aea5-cad6a4ec96d8)
Magento version
-  Magento 2.4.6 P1 EE

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by Tarun50745** [comment]
Analysed issue description and followed steps as mentioned in ticket ( steps to reproduce ).

**Result**
Order history page opens without any issues along with relevant items ( and their details ).

**Screenshot :**

<img width="1440" alt="Screenshot 2023-09-08 at 8 05 26 AM" src="https://github.com/magento/pwa-studio/assets/127731581/44d9d505-28e8-4aa2-b9d1-9529cc7ca460">

**Screen recording :**
https://github.com/magento/pwa-studio/assets/127731581/62b70d10-dce9-4e17-98ad-62a860255b35

**Comment by prajeswari** [comment]
Hi @Tarun50745 ,

This issue not occurring continuously. It appears some times.

**Comment by glo82145** [comment]
We have waited for more than 14 days and didnot get any update. Hence we are closing this issue.

Please feel free to reopen in case of update.
