### ISSUE TITLE
[bug]: Deleting the cart quote_mask_id causes an add to cart error 

### ISSUE THREAD

**Issue by simonmarcoux-valtech** [magento/pwa-studio#4177]
**Describe the bug**

When deleting a user's quote_mask_id entry from the database, this user can't add to cart because of an error showing "Could not add item to cart. Please check required options and try again.". However, in the network, this error shows Could not find a cart with ID "XXX". This means that the error was not catched by the cart AsyncActions isInvalidCart method, but it instead reached the unknown error flow in ProductFullDetail. 

Alternatively, this error also happens when we manually change the is_active value of the quote entry in the quote table. We get the network error "The cart isn't active" and the user can't add to cart anymore.

A browser refresh does reset the cart properly, but we were expecting the add to cart action to also reset cart when the cart ID is invalid.

**To reproduce**

1. Go to a product page
2. Add the product to your cart.
3. Delete the user's quote_id_mask entry in the quote_id_mask db table
4. Add the same product to your cart.
5. Notice the error on the add to cart action.

**Expected behavior**
The add to cart action resets the cart Id if it is invalid and the user can proceed with adding to cart.

**Screenshots**

![cart_id_issue](https://github.com/magento/pwa-studio/assets/131485901/8f4de259-f927-4371-88f4-f62c87c089ed)
![image (80)](https://github.com/magento/pwa-studio/assets/131485901/484da9c4-0f43-448f-8a70-eb1bac330875)

**Please complete the following device information:**

-   Device [PC]:
-   Browser [Chrome]:
-   Browser Version [117]:
-   Magento Version [Adobe Commerce 2.4.6-p3]:

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [X] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by RaghavendraTirumalasetti** [comment]
We are able to reproduce this issue. Hence issue is confirmed

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
We have explored this issue and analysed in respect of PWA. We have explored the possibility of fixing it from PWA side but unfortunately it cannot be fixed from Pwa side and its not a valid scenario in magento also. Hence we are closing this ticket . 

Please feel free if you have any more update on the same.

**Comment by fooman** [comment]
@glo82145 I not sure that I fully agree with the assessment:

> ts not a valid scenario in magento also. 

Step 3
Delete the user's quote_id_mask entry in the quote_id_mask db table

is just a shortcut for accelerating what happens for the setting quote lifetime

![image](https://github.com/magento/pwa-studio/assets/455508/6325dea4-70af-4191-8c0c-29a09352db78)

(instead of the manual deletion you could wait 30 days + ensure you have a running Magento cronjob)
