### ISSUE TITLE
[bug]: yarn install broken after #4191

### ISSUE THREAD

**Issue by fooman** [magento/pwa-studio#4203]
**Describe the bug**

yarn install v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.

**To reproduce**

1. run yarn install

**Expected behavior**

no error

**Possible solutions**

remove package-lock.json introduced with https://github.com/magento/pwa-studio/commit/5c9f8b4ac2945e57b13f9522c8376a0ac039a980

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Adobe Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo80771** [comment]
The issue is reproducible and hence confirming the issue.
