### ISSUE TITLE
[Bug] Handle title and meta tags for navigation on client side

### ISSUE THREAD

**Issue by Starotitorov** [magento/pwa-studio#422]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[x] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | 2.3  |
| Operating System + version  | Ubuntu 18.04  |
| node.js version (`node -v`) | 8.12.0  |
| npm version (`npm -v`)      | 6.4.1  |

## Description

For example, open any product page _/augusta-earrings.html_ in the application and go to home page using logo link. You can see that title of the page is still _Augusta Earrings -_ and HTML head tag still contains following:

```
<html>
  <head>
    ...
    <title>Augusta Earrings - </title>
    <meta name="title" content="Augusta Earrings">
    <meta name="keywords" content="">
    <meta name="description" content="<p>Silver &amp;amp; aqua chandelier earrings.</p><ul><li>2.5&quot; length</li><li>Sterling silver</li><li>Fish hook style</li></ul>">
    ...
  </head>
  <body>
  </body>
</html>
```

This issue is not related only to this pages, it is a general issue of the application.

@ericerway, @zetlen, please, verify this.

## Expected result:

Title of the home page should be _Venia_. In html head tag we expect to have just:

```
<html>
  <head>
    ...
    <title>Venia</title>
    ...
  </head>
  <body>
  </body>
</html>
```

## Possible solutions:

Right now we do not update page title and meta tags inside head tags when we handle navigation on client side using react-router. We can use react-helmet to manage title and meta tags to the document head. https://github.com/nfl/react-helmet#readme

**Comment by zetlen** [comment]
Thanks, @Starotitorov! We de-prioritized this because the title and metadata are most important on initial load, for SEO and SMO, but it's still confusing when the user sees the browser title. Definitely worth looking at.

**Comment by vasilii-b** [comment]
Hi! I'd like to have a look on the issue. Can someone assign it to me, please? Thank you!

**Comment by awilcoxa** [comment]
Moving ticket forward as the issues is still relevant. The previously proposed solution (below) was closed, but the team will re-investigate additional solutions. 

~~Possible solutions:
Right now we do not update page title and meta tags inside head tags when we handle navigation on client side using react-router. We can use react-helmet to manage title and meta tags to the document head. https://github.com/nfl/react-helmet#readme~~
