### ISSUE TITLE
[bug]: Search products by category from searchBar doesn't work

### ISSUE THREAD

**Issue by joseamietta** [magento/pwa-studio#4223]
**Describe the bug**

Search products by category from searchBar doesn't work
https://venia.magento.com/search.html?query=shirt&category_id%5Bfilter%5D=Tops%2CMTg%3D&page=1

The attribute category_id is deprecated, should replace by category_uid

**To reproduce**

1. Open top SearchBar
2. Type 'shirt'
3. Click on 'shirt on Top'
4. The search.html page show No results found!
5. if replace category_id with category_uid from URL, It's works and sidebar category filter was actived

**Expected behavior**

Able to search products by category from searchBar

**Screenshots**

![image](https://github.com/magento/pwa-studio/assets/16170859/af5b7245-f175-4570-aa8a-48cf28cc8f5d)
![Screenshot from 2023-12-22 11-47-34](https://github.com/magento/pwa-studio/assets/16170859/34968702-5d3c-46ef-89fe-2da8bf939974)
![Screenshot from 2023-12-22 11-48-00](https://github.com/magento/pwa-studio/assets/16170859/eff7a41c-c69d-4479-af91-f1d1602296c3)

**Possible solutions**

in file node_modules/@magento/peregrine/lib/talons/SearchBar/useSuggestedCategory.js, line 12 replace category_id[filter] by category_uid[filter]

**Please complete the following device information:**

-   Device [e.g. Lenovo Thinkpad, Notebook, Ubuntu 22.04]:
-   Browser [e.g. Chrome]:
-   Browser Version [e.g. 120.0.6099.109]:
-   Magento Version [e.g Adobe Commerce 2.4.6-p3]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by joseamietta** [comment]
@magento I am working on this

**Comment by joseamietta** [comment]
@magento add to contributors team

**Comment by joseamietta** [comment]
@magento I am working on this

**Comment by RaghavendraTirumalasetti** [comment]
@magento I am working on this

**Comment by RaghavendraTirumalasetti** [comment]
Issue is reproducible with the steps Mentioned. Hence Conforming the issue.

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug
