### ISSUE TITLE
[feature]: Change user time to logout

### ISSUE THREAD

**Issue by sm1thana** [magento/pwa-studio#4230]
**Is your feature request related to a problem? Please describe.**
The user becomes unauthorized after 1 hour. I'd like to change this time.

**Describe the solution you'd like**
@magento/peregrine/lib/store/actions/user/asyncActions.js has a setToken function that sets ttl time to 3600.

```
export const setToken = token =>
    async function thunk(...args) {
        const [dispatch] = args;

        // Store token in local storage.
        // TODO: Get correct token expire time from API
        storage.setItem('signin_token', token, 3600);

        // Persist in store
        dispatch(actions.setToken(token));
    };
```

I'd like to change this time, but I can't extend this file or function.
I read this manual, but didn't find any helpful information
https://developer.adobe.com/commerce/pwa-studio/guides/general-concepts/extensibility/

I thought I could extend this file like a talon:
```
const peregrineTargets = targets.of('@magento/peregrine');
const talonsTarget = peregrineTargets.talons;
```
and get a store param from peregrineTargets, but it has only talons and hooks fields.

So, could you be so kind to help me, to change this param?

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by glo11372** [comment]
Hi @sm1thana 
Can you please elaborate this issue little bit more like in which file you are trying to extend.Please give us the detailed information.
You can also refresh token without knowing user about it and keep signed in.

**Comment by glo42707** [comment]
@adobe export jira

**Comment by glo11372** [comment]
@adobe export issue to Jira project PWA

**Comment by glo82145** [comment]
@adobe export issue to Jira project PWA

**Comment by glo11372** [comment]
@adobe export issue to Jira project PWA

**Comment by glo11372** [comment]
@adobe export issue to Jira project PWA
