### ISSUE TITLE
[bug]: cart breaking for more than 24 products

### ISSUE THREAD

**Issue by kirlkiran** [magento/pwa-studio#4242]
there is request to order more than 30 products in cart

1) cart is breaking for more than 24 products

2) checked the document Shopper-Products return data of only 24 products

Actual: only 24 products are showing proper data

Expected: unlimited no of products to show data

**Comment by glo82145** [comment]
@adobe export issue to Jira project PWA

**Comment by glo82145** [comment]
As we have waited for more than 14 days for any update on this ticket hence we are closing this issue.

Please feel free to reopen it in case of any update.
