### ISSUE TITLE
[bug]: Props error on Checkout page

### ISSUE THREAD

**Issue by ihorvyshniakov** [magento/pwa-studio#4252]
Hi, it's about `venia-ui`

**Describe the bug**

1. add product to cart
2. go to Checkout page
3. open browser console
4. watch an error with wrong prop(I think it's typo)

![Checkout props error](https://github.com/magento/pwa-studio/assets/45529959/3e0485ae-f153-49ca-82ff-64b88852412e)

**Possible solution**
Just delete [this prop](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Password/password.js#L51) from component, it's useless.
![iScreen Shoter - 20240421062157560](https://github.com/magento/pwa-studio/assets/45529959/71d0cc40-9c18-4b8b-9b05-e686ba454cf7)

> [!NOTE] 
> I really want to make this PR to your repository to get extra badge t omy github account.
> If it's possible, please help me to do this, because for now I just dont have an access for pushing to your repo.

**Comment by glo82145** [comment]
@adobe export issue to Jira project PWA
