### ISSUE TITLE
[bug]: Login issue with PWA 14.0

### ISSUE THREAD

**Issue by fmaniconereply** [magento/pwa-studio#4258]
In the new PWA 14.0.0 and Adobe Commerce 2.4.6, we are experiencing an issue with user login. The session token from the graph is returned, but the user is not logged in.

**Comment by fmaniconereply** [comment]
the problem is here
https://github.com/magento/pwa-studio/blob/release/14.0/packages/peregrine/lib/Apollo/links/index.js

**Comment by coresh** [comment]
### PWA 14.0.0 and Adobe Commerce 2.4.7: also the issue with user login

**Reproducing:

1. Path of the Magento PWA:
```
https://www.example.com/checkout
```

2. Clicking to "SIGN IN" button ->"SIGN IN"-button status bind to "disabled"
JS error output:

![Screenshot-20240505184536-783x837](https://github.com/magento/pwa-studio/assets/9606476/4eb90207-8834-4c00-bcaa-f48376d787c8)

Thank you

**Comment by Cyber-Root0** [comment]
@fmaniconereply 
Greetings,
Were you able to solve the problem manually?

**Comment by glo82145** [comment]
@adobe export issue to Jira project PWA

**Comment by huykon** [comment]
I'm facing with this issue 
![image](https://github.com/magento/pwa-studio/assets/9253798/7ced37db-6da5-4a16-b239-c1b984323992)
