### ISSUE TITLE
[bug]: PDP breadcrumbs only show one level of product category

### ISSUE THREAD

**Issue by joseamietta** [magento/pwa-studio#4261]
**Describe the bug**

The PDP breadcrumbs only show one level of product category

**To reproduce**

1. Go to https://venia.magento.com/penelope-peasant-blouse.html
2. The product is asigned to Tops > Blouses & Shirts but the breadcrumbs only show Tops

**Expected behavior**

Breadcrumbs show all levels of asigned product categories

**Screenshots**

![image](https://github.com/magento/pwa-studio/assets/16170859/7bc33f63-52e7-455d-9524-b683a0f53bac)
![image](https://github.com/magento/pwa-studio/assets/16170859/245f9d22-e740-41de-ab5e-310c6b721be7)

**Possible solutions**

The problem is in the function getBreadcrumbCategoryId on useProductFullDetail talon.
Try to get category_id intance of category_uid, while graphQl only return category_uid

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [Lenovo]:
-   Browser [Chrome]:
-   Browser Version [124.0.6367.91]:
-   Magento Version [e.g Adobe Commerce 2.4.6]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by joseamietta** [comment]
@magento I am working on this

**Comment by glo82145** [comment]
@adobe export issue to Jira project PWA
