### ISSUE TITLE
[doc]: Unable to join Slack channel - Possible broken link, or incorrect permissions

### ISSUE THREAD

**Issue by itnavigate** [magento/pwa-studio#4284]
**Describe the request**
I'd like to join  the Slack channel, but the documentation appears top be outdated.
https://github.com/magento/pwa-studio?tab=readme-ov-file#join-the-conversation

When I go to https://magentocommeng.slack.com/messages/C71HNKYS2 as per the documentation, I get a sign-in only page, with no option to sign up.
The contact us link at the bottom of the page is of no use, as it requires you to have an account already.

If I manually navigate to https://magentocommeng.slack.com/signup I get a page advising:

> This team's administrator has not enabled email signups.
> 
> Sign up for magentocommeng.slack.com
> Ask your administrator to send you an invitation.

**Possible solutions**
I am not truly sure if this is a documentation change, or a bug report.

If it is a documentation change, then I would change the link to be the correct page that permits account creation.
If the Slack channel has been disbanded, then this section needs to be removed.

However, it may be a configuration issue in the Slack setup, in which case this would need to be a bug report.

**Screenshots**
This is the page I get when following the link provided in the documentation
![image](https://github.com/magento/pwa-studio/assets/1689824/eb3fba0c-2ccf-4356-aa43-cc21cc51d81a)
As you can see, there is no sign-up option.

This is the page I get from "guessing" the signup link:
![image](https://github.com/magento/pwa-studio/assets/1689824/ba26fea8-1ebe-4f82-bc2b-3cd8b15d5d3e)

**Please let us know whether this is a new topic or a topic change request:**
 - [ ] New Topic Request (ie. missing entire topic/section)
 - [X] Topic Change Request (ie. spelling, organization)

**Comment by itnavigate** [comment]
When I click on the link in the auto comment from m2-assistant to Join the Slack, I get this page:
![image](https://github.com/magento/pwa-studio/assets/1689824/544f8c3e-2b73-4386-8c2a-e1cc081b968d)
When I follow the "Self Signup Link" I get this page:
![image](https://github.com/magento/pwa-studio/assets/1689824/a037b9b0-04ee-44e4-84d6-93c88407f156)
As you can see, the Contact Us still links to a page that requires me to be logged in.

**Comment by itnavigate** [comment]
This all stems from the fact that I want to learn Magento 2 (Currently I have an instance of 2.4.7 running) and pwa-studio, and I don't think that raising an issue is the correct place to ask my questions.

**Comment by jemoon** [comment]
@itnavigate please try with https://join.slack.com/t/magentocommeng/shared_invite/zt-2lcx0wg06-VdzoZvw0C_eI9CBGo8M3pw - I had the same issue but was given this link which is supposed to be expired within next 23 days.

**Comment by itnavigate** [comment]
Thanks @jemoon. That worked.
Are you able to leave a comment as to how you got that link so others who try can get it re-activated once it expires?

**Comment by glo42707** [comment]
closing this tikcet since worked as per last comment by @itnavigate
