### ISSUE TITLE
Cannot filter on options with a ","

### ISSUE THREAD

**Issue by vacla** [magento/pwa-studio#4304]
**Describe the bug**

After selecting a category with a "," on the category page, no results are found or wrong results shown.
This is very likey due to the delimiter being a "," here: https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/FilterModal/helpers.js#L1

**To reproduce**

1. Go to category page
2. Click on filter with a ","
3. No results found or not showing correct results

**Expected behavior**

Show results of that category

**Debug Report**

`
  ℹ  Inspecting Dependencies
    Found 9 @magento dependencies in yarn.lock
    @magento/pwa-buildpack @ 11.4.3
    @adobe/apollo-link-mutation-queue @ 1.0.2
    @magento/babel-preset-peregrine @ 1.2.3
    @magento/eslint-config @ 1.5.3
    @magento/pagebuilder @ 8.2.1
    @magento/peregrine @ 13.2.1
    @magento/pwa-theme-venia @ 1.4.0
    @magento/venia-adobe-data-layer @ 1.0.0
    @magento/venia-ui @ 10.3.0

  ℹ  Inspecting Magento Backend
    Not using sample backend.
    Backend is UP!

  ℹ  Inspecting System
    OS: #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024
    Node Version: v16.20.2
    NPM Version: 8.19.4

`

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: PC 
-   Browser [e.g. Chrome, Safari]: Chrome
-   Browser Version [e.g. 22]: 127.0.6533.72
-   Magento Version [e.g Adobe Commerce 2.4]: commerce 2.4.5-p8

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [x] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by del22123** [comment]
@vacla 
We tried reproducing this issue with the given steps, but we are unable to do so.
Can you please provide detailed steps along with filter values for us to proceed further?
Any screenshot or screen video would be highly helpful as well.

**Comment by del22123** [comment]
@vacla 
Attaching a screen video
https://github.com/user-attachments/assets/4e43948f-fec5-4168-aa70-6bcd7eadf6d8

Filter options tested in the screen video:
"Above Knee," (4 products) and "Ankle Length" (1 product)

Both single filter option as well as combination too works.

**Comment by del22123** [comment]
We didn't get any updates from the reported for more than 3 weeks and so we are closing this ticket as per the process.
Feel free to re-open this issue if incase it reoccurs.
