### ISSUE TITLE
Add to Home Screen prompt not coming on mobile

### ISSUE THREAD

**Issue by arvind-netzwelt** [magento/pwa-studio#4312]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Adobe Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by arvind-netzwelt** [comment]
I am using latest version on venia and magento2

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo85315** [comment]
Hi @arvind-netzwelt

https://github.com/user-attachments/assets/982c9a15-3736-4403-b06e-0ebc67e2f9df

,

I hope this message finds you well. I wanted to let you know that I am unable to reproduce the issue on my end. Could you please provide a video clip demonstrating the problem? This would greatly assist us in identifying and resolving the issue more effectively.

Thank you for your cooperation!

**Comment by huykon** [comment]
@glo85315 do you know PWA's Add to home screen feature ?
![image](https://github.com/user-attachments/assets/96da9b28-7c0c-44fa-89b8-bda805392948)

**Comment by arvind-netzwelt** [comment]
Already i have fixed this issue
Thanks
