### ISSUE TITLE
Venia Store URLs 301 redirect problem of trailing "/" and uppercase letters

### ISSUE THREAD

**Issue by secaliskan** [magento/pwa-studio#4347]
**Describe the bug**

Normally Magento2 with Luma; at backend manage the redirects of certain SEO needs, for example:

- At Luma any URL trailing with "/" automatically redirects to original URL w/o "/"
- At Luma if you change any letter at URL with the UPPERCASE one again Luma redirects automatically to lowercase original store URL (category, product or CMS pages)
- At Luma also www and non www redirects are working w/o problem, for example if your Base_url is https://www.domain com and you write https://domain.com at browser; Magento URL resolver redirects the URL automatically to https://www.domain.com

Those above 3 default Magento behaviour is not working on Venia storefront; https://venia.magento.com
 

**To reproduce**

1. Go to https://venia.magento.com/venia-bottoms.html?page=1
2. at Browser **manually change the URL** https://venia.magento.com/venia-bottoms.html/?page=1 (added "/" end of url)
3. Or at Browser **manually change the URL** https://venia.magento.com/venia-**BO**ttoms.html?page=1 (added "/" end of url)

**Expected behavior**

Expected behaviour Venia should replace the url with original URL like this:
https://venia.magento.com/venia-bottoms.html?page=1

**Also at console we need to see 301 redirect at headers.**

or **show 404 page** since there is no such URL storefront PAGE

Above are the expected behavior for Google to understand our storefront Page structure and URLs

But Venia is neither making 301 redirect and show the page URL like we have changed nor show the 404 page and lauch the UNCORRECT URLs like below and show the CORRECT page content...

https://venia.magento.com/venia-bottoms.html**/**?page=1 OR
https://venia.magento.com/venia-**BO**ttoms.html?page=1 

<img width="958" alt="image" src="https://github.com/user-attachments/assets/317468cf-8f87-41d7-9d55-42a123779a46">

<img width="958" alt="image" src="https://github.com/user-attachments/assets/8682847c-bd41-4268-bae0-c5a9ac6bfe81">

So, Google indexes two or more pages for each store page; what is not correct. It is a big fault for SEO...

Venia is not using backend URL resolvers OK. 
BUT also **does not have built in functionality for 301 redirections.**

Same case Admin/Marketing/URL Rewrites.
**Now at Venia Storefront 301 URL redirects working but showing 200 at headers but needs to show 301 at headers**

I didn't find any solution for those 301 redirect cases for Venia...

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]: Any device
-   Browser [e.g. Chrome, Safari]: Any browser
-   Browser Version [e.g. 22]: Any Version
-   Magento Version [e.g Adobe Commerce 2.4]: 2.4

**Please let us know what packages this bug is in regards to:**

-   [X] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [X] `upward-js`
-   [X] `upward-spec`
-   [ ] `create-pwa`

**Comment by glo82145** [comment]
https://github.com/adobe export issue to JIRA project PWA as Bug

**Comment by glo82145** [comment]
@adobe export issue to JIRA project PWA as Bug
