### ISSUE TITLE
[feature]: Ratings in Venia 

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#476]
## This issue is for the following packages:

<X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

!https://user-images.githubusercontent.com/2686596/48221152-e1d00880-e356-11e8-94a8-e080b49a0fbe.png!

As a shopper I want to view product ratings for Venia from category, product and others so that I can make an informed purchase.

- Reinstate Ratings to Category page from Venia prototype

#### Assumptions
- Ratings coverage in GraphQL/REST API
- Detailed view of Ratings and writing experience handled separately (future)
- Ratings GraphQL coverage introduced with CommEng post 2.3.0+
- GraphQL stitching out of scope; config of UPWARD to directly interact with API from the reviews provider and reuse Magento data (future)

## Tasks
[ ] Discovery for GraphQL/REST API coverage around ratings and reviews
[ ] Identify needs in GraphQL; submit issues/PR as appropriate
[ ] Implement basic functionality on Category page (read only)
[ > Testing and documentation (https://github.com/magento-research/pwa-studio/wiki/Documentation-Guidelines)

### Test Plan
- h4. Execute
1. Verify Summary rating on category listing for configurable and simple products.
1. Verify Search Product listing and PDP does not have the changes.
1. Run lighthouse on category page
1. Run cypress

- h4. Test Coverage
1. Add cypress integration test

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/477)

**Comment by pcvonz** [comment]
Hey @ericerway I can look into this.

**Comment by pcvonz** [comment]
[Docker image of the product ratings branch](https://hub.docker.com/r/vonzimp/magento_pwa/)

#### Setting up ratings with current Venia sample data

:rotating_light:  **Note:** This will probably be unnecessary in the future. 

Before adding a product review via graphql follow these steps:

1. In the admin panel select `STORES` > `Rating`
2. For each item in the table (e.g. Price, Quality, etc) set the `Default Store View` to `default`.

**Comment by ericerway** [comment]
Marking on hold until graphql-ce/pull/227 is updated and merged.

**Comment by supernova-at** [comment]
Un-assigning @pcvonz as it has been ~9 months and the blocking ticket (https://github.com/magento/graphql-ce/pull/227) is still open.

We can re-assign when this issue is no longer blocked.

**Comment by awilcoxa** [comment]
removed hold label, GraphQL dependency is merged. We'll revisit prioritization of rating/reviews feature.
