### ISSUE TITLE
[UPWARD] Discussion: reducing boilerplate for inline resolver

### ISSUE THREAD

**Issue by Vinai** [magento/pwa-studio#497]
As a developer writing UPWARD configuration, it would be nice to be able to specify string values in UPWARD yaml with less boilerplate.

## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[x ] `upward-spec`

## This issue is a:

[ ] Bug
[x ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

## Description

Implementations should treat values with a special prefix character, for example a single backtick  `` ` ``,  as an inline resolver value, instead of a context property.

For example:

```
body: `'Hello World!'
```

should be identical to

```
body:
  resolver: inline
  inline: 'Hello world!'
```

Something like a reader- or macro-preprocessor feature. Any value with that prefix character is taken as a literal by the parser.

This would be simple to implement in a parser and would make the whole thing less verbose.
Probably something like this already has been discussed internally, but I wasn't able to find any reference why it might have been rejected.

**Comment by zetlen** [comment]
Hey @Vinai . Thanks for your infinite patience on this. (I imagine you checked this issue faithfully every day for months.)

I like the purpose of the backtick, but I think it might be better to do a major version of UPWARD which uses a variable prefix (like `@` or `$`) for _context_ lookups. Then, we no longer have to worry about disambiguation, so you could start saying stuff like

```yml
helloWorld: 'Hello world!'
body: @helloWorld
```

How's that feel?

**Comment by Vinai** [comment]
Finally, an answer, I've almost given up after 9 months :)

I like the disambiguation, but for the purpose of specifying a one time string it would still require two records instead of one. So it's better because it's more readable but it's not as convenient as I would like it to be.

**Comment by zetlen** [comment]
Closing in favor of upcoming improvements to UPWARD v3.
