### ISSUE TITLE
Add initial user's details fetching

### ISSUE THREAD

**Issue by AlexeyKaryka** [magento/pwa-studio#549]
## This issue is for the following packages:

[ X ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ X ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

User's details isn't fetched after page reload
![image](https://user-images.githubusercontent.com/25349273/49081775-e3576700-f258-11e8-82e5-1766f4e154b7.png)

## Expected result:

If user sign in his details should be fetched when page will be reloaded, so in the navigation drawer user's first name and second name should be rendered properly.
![image](https://user-images.githubusercontent.com/25349273/49081745-cae74c80-f258-11e8-8a3e-b3dba43d798e.png)

## Possible solutions:

Add initial dispatches of users details to redux

**Comment by codeAdrian** [comment]
Hello, PR has been created to fix this issue: https://github.com/magento-research/pwa-studio/pull/599
