### ISSUE TITLE
Direct URL refactor for account login and SEO

### ISSUE THREAD

**Issue by Starotitorov** [magento/pwa-studio#564]
## This issue is for the following packages:

[x] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[ ] Feature suggestion
[ ] Documentation issue
[x] Tech Debt

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

Right now we put sign in and sign up forms inside navigation drawer, we do not have direct urls to open this forms. It is not good from SEO perspective. For example, right now the user needs to click three buttons to open sign up form and create an account.

## Expected result:

User should be able to open sign in and sign up forms using direct urls.

## Possible solutions:

One of the simplest solutions is to provide a separate pages for sign in and sign up forms.

**Comment by ericerway** [comment]
Updated with more descriptive title for issue. Thanks!

**Comment by awilcoxa** [comment]
De-prioritizing as use case does not seem to valid for now. closing ticket.
