### ISSUE TITLE
[Documentation]: Writing new components with PWA Studio (Venia+Peregrine)

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#619]
## This issue is for the following packages:

- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer I want to create a styled component based on the current Venia and peregrine examples in PWA Studio so that I can begin development on a new PWA.

/cc shakyshane

- [ ] Research with early adopters on styling/usage of components
- [ ] Review and validate documentation for new guidelines
- [ ] Additional sories as needed

**Comment by awilcoxa** [comment]
Deferred for now until additional delivery against Peregrine epic

**Comment by brendanfalkowski** [comment]
I'm ramping up more on the React side now, and thinking out loud with a couple questions. If the docs addressed this I think it would help people understand how Peregrine/Venia can scaffold customizations.

1. Can I use a Peregrine/Venia component's JS + tests, but provide my own CSS without having to maintain the full component in my /src? Can you extend a component but just override one import it defined (i.e the CSS)?

1. If I make a custom component `Button` how do I tell other components from Peregrine/Venia to use my `Button` in place of P/V's `Button`? Do you have to modify every component that uses P/V `Button` to use custom `Button`?

**Comment by awilcoxa** [comment]
closing as we're addressing with new docs topics that have been previously delivered as well as new tutorials.
