### ISSUE TITLE
EPIC: Accessibility for PWA *WIP*

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#623]
## This issue is for the following packages:

- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

**Comment by sirugh** [comment]
Closing this as stale.

@awilcoxa can we make sure that these needs are captured in an a11y epic internally? Then we can export issues to github as necessary.
