### ISSUE TITLE
[Optimization]: Rendering product detail page

### ISSUE THREAD

**Issue by vitalics** [magento/pwa-studio#641]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [X] Feature suggestion
- [X] Optimization
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
Each time, when the user chooses smth. for product detail page, React rerender all form(blue lines - rerenders component gives from `react dev tool`)
![image](https://user-images.githubusercontent.com/8816260/49799272-98a81580-fd55-11e8-84d2-3d7136c71c9f.png)

## Expected result:
render only interactive element(e.g. user choose color - rerender color only)

## Possible solutions:
Connect interactive elements with store separately it will be rerendered only themselves (not full form).

**Comment by DmitryShmaliuk** [comment]
Please, assigne me.

**Comment by awilcoxa** [comment]
Needs new investigation and discovery to determine extent of current issue.
