### ISSUE TITLE
[Optimization]: Rendering header when route was change

### ISSUE THREAD

**Issue by vitalics** [magento/pwa-studio#642]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [X] Feature suggestion
- [X] Optimization
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
When routing is changed, the header is rerender `burger menu`, `cart`, `search` and logo  
![image](https://user-images.githubusercontent.com/8816260/49799798-e2ddc680-fd56-11e8-9603-b2fa09333bd6.png)

## Expected result:
When route was change, not render header, it takes a user time. As a result increase speed and user accessability 

## Possible solutions:
render `header` component outside `<Route>` component

**Comment by DmitryShmaliuk** [comment]
Please, assigne me.

**Comment by awilcoxa** [comment]
Needs new investigation/discovery to determine extent of current issue.
