### ISSUE TITLE
[Optimization]: Reduce request timing

### ISSUE THREAD

**Issue by vitalics** [magento/pwa-studio#643]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [X] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [X] Feature suggestion
- [X] Optimization
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description
When User tries to add the item to `cart`, request executes about 3 seconds and make 2 requests:
- `guest-carts/UUID/items` - `POST` (~1.5 second): 
![image](https://user-images.githubusercontent.com/8816260/49800409-7794f400-fd58-11e8-92b6-3ddf8898c952.png)

- `guest-carts/UUID/totals` - `GET` (~2 seconds):
![image](https://user-images.githubusercontent.com/8816260/49800323-44eafb80-fd58-11e8-8d70-3ad05977f1d3.png)

## Expected result:
- Reduce request time on the backend side

**Comment by awilcoxa** [comment]
Optimization to REST API is currently not a priority, we will instead resolve through use of GQL. Closing issue for now.
