### ISSUE TITLE
Refactor UPWARD for better errors and stack traces

### ISSUE THREAD

**Issue by zetlen** [magento/pwa-studio#645]
## This issue is for the following packages:

- [ ] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [x] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [x] Feature suggestion
- [x] Documentation issue
- [x] Other (Please Specify) **Refactor**

## Description

_As a PWA Studio developer, I want server-side errors in UPWARD to display clear message and stack trace information, so that I can debug and correct UPWARD configuration._

Errors and stack traces in `upward-js` are unhelpful and don't correspond to the logical concepts in UPWARD. UPWARD is a virtual decision tree, and responses are results of a walk from the root of that tree. The best way to represent that virtual stack is with a concrete syntax tree which correlates decision tree nodes with positions in source code.

This issue is a placeholder for refactoring UPWARD to create that concrete syntax tree, which will not only help with debugging, but:

- Create a medium of exchange and optimization for UPWARD config
- Allow more granular extension and modification of UPWARD
- Enable better production performance via static analysis and caching of invariants

**Comment by awilcoxa** [comment]
Closing for now, will revisit given future need.
