### ISSUE TITLE
Request to own the Shop the Look category page for the Venia Storefront

### ISSUE THREAD

**Issue by ntoombs19** [magento/pwa-studio#648]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [x] Other (Please Specify) - Building out the "Shop the Look" category page in the Venia storefront

## Description

I am interested in building the Shop the Look category within the PWA Venia Storefront. The category currently displays as just a normal category with child products but it is supposed to display a carousel of "looks" to show off some of the customizability of Magento. I built the original Magento 2 Venia theme for the Marketing Department under Michele Miller so I am familiar with the requirements for the Shop the Look page. I am going to be building this page on my own anyway but I would prefer if it could be contributed to the project.

**Comment by ntoombs19** [comment]
- How will the product/category/attribute data be added and by whom?
- Assuming each "look" is a category, how should each category be displayed individually?
- The main images for each look are quite large. With load speed being an important consideration for PWA, how large (size and quality) should the images be and should the images be lazy loaded?
- I think this page would be a good candidate for animations such as parallax, fade-in content, etc...
- Should STL exist as a single component? If not, what other components should be created to enable STL functionality?
- Dependencies
	- Carousel
	- Modal
	- Pricing
	- PDP
	- Cart
	- Add to cart
- UX
	- The product images are currently not visible above the fold which is generally bad UI.
	- One of the things I noticed about the previous implementation was that it wasn't immediately apparent that the page was just one big carousel. The slide buttons weren't obvious and there were no dots or indicators for how many slides there were or where you were in the carousel.
- Attributes to be utilized to display the data for each category and product
	- Category Name
	- Category Description
	- Category Image
	- 3 Child Products
		- Name
		- Description
		- Image (main)
		- Price
		- Description Extra
		- Short Description
- Categories/Products
	- Timeless Sophistication
		- Felixia Maxi Dress
		- Stretch Belt with Leather Clasp
		- Carmina Errigs
	- Retire your LBD
		- Flora Tank Dress
		- Augusta Earrings
		- Silver Amor Bangle Set
	- Carefree Days
		- Tatiana Skirt
		- Helena Cardigan
		- Carmina Necklace
	- Perfectly Beachy
		- Hannah Sweater
		- Clara Wide Pants
		- Gold Omni Bangle Set
	- Minimalist Sensibility
		- Valeria Two-Layer Tank
		- Honora Wide Leg Pants
		- Silver Sol Earrings

**Comment by ericerway** [comment]
Thanks for the feedback @ntoombs19 -- will definitely want to get @soumya-ashok involved as we get started but hopeful we can look at discovery work in advance. Thanks again.

**Comment by soumya-ashok** [comment]
@ntoombs19 - Sorry for the extremely delayed response on this issue. Is this something you are still interested in doing?

**Comment by ntoombs19** [comment]
@soumya-ashok - No worries. Yes, I am still interested.

**Comment by soumya-ashok** [comment]
Awesome @ntoombs19 - There have been a lot of changes since you first opened this issue, and the "Shop the Look" page is not something we've fully thought through internally, so it would be good to collaborate if that's okay with you?

Let me get things together on my end, and maybe we can get on a quick call to discuss?

**Comment by sirugh** [comment]
Unfortunately Soumya is no longer with the company and this seems to have fallen through the cracks. As this issue is almost 2 years old I am going to close it for now, but if we are able to allocate resources to providing mocks/design guidance then we can re-open this.
