### ISSUE TITLE
Images should be lazy-loaded and responsive

### ISSUE THREAD

**Issue by rowan-m** [magento/pwa-studio#668]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [x] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

## Description

Images are currently loaded via an `<img>` tag. On simpler, lighter pages where the majority of the content is within the first viewport, this is fine. However on heavier, longer pages such as a category listing this has a significant performance impact.

## Expected result:

Images should be loaded on demand and at an appropriate size for the viewer.

## Possible solutions:

#398 addresses serving the appropriate format, but the front-end still needs to take advantage of that. This should be achieved via the `<picture>` element to specify multiple `<source>` options for both optimal image formats and sizes.
See https://developers.google.com/web/fundamentals/design-and-ux/responsive/images for more detail.

Lazy loading images should make use of `IntersectionObserver` to check for proximity of elements to the viewport and dynamically setting the `src` and `srcset` dynamically to trigger loading. Images should have at the least as static fallback / loading image but generating low fidelity previews may also be possible.
See https://developers.google.com/web/fundamentals/performance/lazy-loading-guidance/images-and-video/ for more detail.

Lazy loading probably wants to be quite conservative as product images are key to the experience, so don't wait until the element is in view to load but trigger it when they are close the viewport.

There's a fair amount of behaviour here that needs to encapsulated, so it feels like this deserves its own component. There may also be existing React components here that would be appropriate to bring in.

**Comment by vitalics** [comment]
@rowan-m for react we're used redux and trunk for asynchronous interaction. In this case I presume  we should get an image from store after triggering action(e.g. `getImagesFromBackend()`) and before getting an answer from store, use variable `isLoading` and `isLoaded` which declared on store.

**Comment by real34** [comment]
Gatsby image is one interesting component implementing this: https://www.gatsbyjs.org/packages/gatsby-image/

There are rooms for improvement though, but it would be a good idea to see what could be shared between both implementations.

**Comment by awilcoxa** [comment]
related to: https://github.com/magento/pwa-studio/issues/1958

**Comment by tjwiebell** [comment]
Venia core seems to be making good use of srcsets now, in addition to `loading=lazy` props that are pretty widely supported now; so this scope should be narrowed to the addition of art direction `<picture>` elements into the core Image component.

**Comment by awilcoxa** [comment]
closing as the majority of effort has been addressed in previous PR.
