### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by gil--** [magento/pwa-studio#675]
## This issue is for the following packages:

- [X] `venia-concept`
- [ ] `pwa-buildpack`
- [X] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [X] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  | windows 10 IE11 |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a merchant, I expect my site to work in all modern browsers + IE11 -- especially US based merchants.

I understand that "technically" IE11 falls outside of the list of supported browsers according to https://github.com/magento-research/pwa-studio/wiki/Definition-Of-Quality#browser-support but that's based on global usage which heavily skews mobile and B2C. Inside the US, IE11 is still >5% http://gs.statcounter.com/browser-market-share/all/united-states-of-america

Additionally, many B2B customers/merchants unfortunately deal with a significant user base still on IE11 (we have a client >15% IE11). Even in 2019, lack of IE11 is a complete turnoff for many merchants. Is there at least some basic level of support we can add so that it's not just a blank screen... I feel like the current state of Venia in IE11 is not ideal since it just shows a blank screen?

## Expected result:

PWA does not even load in IE11:

![screen shot 2018-12-17 at 6 06 55 pm](https://user-images.githubusercontent.com/3484527/50121675-7fa4d600-0227-11e9-804e-3dc733113d4d.png)

## Possible solutions:

We might need to add a missing polyfill perhaps?  Or changing babel browsers to include >5% + IE11

**Comment by ericerway** [comment]
Thanks @gil-- fully agree I'm hoping to address with graceful degradation when we fully address accessibility beyond Lighthouse requirements. That said given the limitations of IE11 the experience will not be optimal. /cc @awilcoxa to consider for the roadmap/backlog.

**Comment by gil--** [comment]
@ericerway Sounds good! Even just adding a message saying "Please use a supported browser to continue on this site"... etc. for unsupported browsers

**Comment by vitalics** [comment]
@gil-- @ericerway @awilcoxa  we does not support IE11. It describes on [definition of quality](https://github.com/magento-research/pwa-studio/wiki/Definition-Of-Quality#browser-support)  document. We support browsers more than 5%(>5%). See [browserlist ](https://browserl.ist/?q=%3E5%25) for more

**Comment by awilcoxa** [comment]
As @gil-- points out, while IE11 falls outside of the technical definition of supported browsers we should at least evaluate and scope LOE to ensure basic level of functionality. Keeping this ticket open for future grooming/discovery.

**Comment by awilcoxa** [comment]
Should investigate implementing a simple version of venia that can be rendered in IE11 or outdated browsers. 

As a part of addressing this issue, we should evaluate simply implementing messaging that informs the user that their browser is outdated and requires an update.

**Comment by brendanfalkowski** [comment]
IE11 support is very important for some B2B businesses. For one of my clients, that 14.5% share contributes $100M+ in revenue per year.

To me this is not a Venia problem, but a buildpack problem (aside from custom properties in Venia CSS).

PWA buildpack needs to transpile and polyfill the ES6 code being written so IE can understand it, and the application can't rely on service worker features to function. If PWA-features are treated as enhancement then IE11 users should have a comparable experience to other sites in IE11.

I attended a talk on differential serving earlier this year, and would love to see Magento implement something like this in buildpack: https://vimeo.com/331573291

**Comment by mRicooo** [comment]
Hi,

Can we have an update for IE11 support ?

Right now, we can't use pwa-studio for some of our clients. 
They can't accepted that 5% or 10% of their customers will be able to purcharse.

**Comment by alteyss** [comment]
> Hi,
> 
> Can we have an update for IE11 support ?
> 
> Right now, we can't use pwa-studio for some of our clients. They can't accepted that 5% or 10% of their customers will not be able to purcharse.

Hello,

Can we have an update on IE11 support? 

Looks like even the demo storefront is not working with IE11 : [demo](https://venia.magento.com/default/)

Thank you for your help.

**Comment by ericerway** [comment]
IE11 is no longer supported for Magento 2 including the Venia storefront with Magento 2.4+ in mid-2020. At that time, M2 admin (~0.5%) and worldwide usage (~1.5%) for IE11 is extremely low. Other major platforms have already dropped IE11 including Microsoft for their own products. Here are the latest requirements: https://devdocs.magento.com/guides/v2.4/install-gde/system-requirements.html 

That said, the is can be customized/extended using polyfills if needed but will not be supported by default. Thanks!
