### ISSUE TITLE
Multi-Shipment Options

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#730]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [x] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

When enabling additional shipment options in the M2 backend, the checkout flow in Venia shows them as options but they are unable to actually be selected / saved.

## Expected result:

It is expected that users should be able to select / save these alternate shipping methods during checkout.

**Comment by awilcoxa** [comment]
Addressing as a part of upcoming chart/checkout workflows. closing this issue for now and will open a new issue/PR for that effort.
