### ISSUE TITLE
Switch from feather icons to a material icon.

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#739]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [x] Feature/Update
- [ ] Documentation issue
- [ ] Other (Please Specify)

## Description

After discussion with UX, Venia Concept should use material design icons instead of feather-icons.

See #733, #376.

## Expected result:

Instead of feather icons we want to use a more flexible icon library that provides [material icons](https://github.com/google/material-design-icons).

## Possible solutions:

Removal of `react-feather` from repo.
Addition of some form of material icons ([react-icons](https://github.com/react-icons/react-icons)?).
Update of imports to use new library.

**Comment by awilcoxa** [comment]
Deferred for now but will revisit with Venia redesign/enhancements.
