### ISSUE TITLE
Braintree: Add PayPal to Payment Options

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#747]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [x] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

The only payment option available in Venia currently is Credit Card.

## Expected result:

It is desired that PayPal be added so that users can pay via PayPal as well.

## Possible solutions:

The [Braintree Web Drop In](https://github.com/braintree/braintree-web-drop-in) can be configured to allow users to select Credit Card or PayPal before entering details.

[See the Demo here](https://braintree.github.io/braintree-web-drop-in/).

We'll need to create a [PayPal Sandbox account](https://developer.paypal.com/docs/classic/lifecycle/sb_create-accounts/#) to link to, and we should probably move the current Braintree Sandbox account out of Andy's personal email.

**Comment by shuafried** [comment]
When is this planned to release?

**Comment by awilcoxa** [comment]
Needs additional core team research prior to defining implementation details.  

Better approach may be to determine payment integrations as an extension rather than preferring Braintree implementation. 

Moving back to core backlog for further definition.

**Comment by supernova-at** [comment]
Internal epic PWA-1240 will tackle this.

**Comment by gabriel3iri** [comment]
was this feature added after all? or will it be?
