### ISSUE TITLE
EPIC: Implement Magento 2 admin support for PWA Studio

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#77]
## This issue is for the following packages:

[ ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[X] `pwa-module`
[X] `pwa-devdocs`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a developer, I want to enable PWA Studio for my Magento 2 store so that I can begin development and launch a successful Progressive Web App storefront with all testing considerations.

Integration with Magento 2 (core)
Required module for Magento 2 support (including overrides)
Safety switch in Magento 2 for service workers (safe caching)
Multiple store support (for testing)

## Expected result:

Updated module for Magento 2 to support override, safety needs and partial rollout (testing) where needed in a production and development environment.
Testing and documentation as appropriate

**Comment by awilcoxa** [comment]
closing legacy epic for now, we have newer stories that represent current thinking on magento admin integration and we'll pick up the conversation there: #2120
