### ISSUE TITLE
Navigation panel accrues significant delay over time

### ISSUE THREAD

**Issue by JStein92** [magento/pwa-studio#771]
![peek 2019-01-22 07-37](https://user-images.githubusercontent.com/27716099/51546861-ed8d8000-1e19-11e9-9500-8b286638c86a.gif)

The left navigation panel accrues a click handler delay over time - the more you navigate it, the worse it gets.

Reproduce by clearing application cache, then simply opening and closing the side nav over and over.

## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [x] Bug
- [ ] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  | Kubuntu - Chrome/Firefox|
| node.js version (`node -v`) | 10.8.0 |
| npm version (`npm -v`)      | 6.2.0|

## Description

Delay on all left panel nav actions appears after repeated use.

## Expected result:

This should be a near instant, smooth experience.

**Comment by supernova-at** [comment]
@jimbo any chance this is fixed in #1552 ?
