### ISSUE TITLE
[BUG] Unit tests from an IDE not being ran

### ISSUE THREAD

**Issue by VitaliyBoyko** [magento/pwa-studio#791]
**Describe the bug**
Since the last update (changing package manager from NPM to Yarn), I’ve got an error running unit tests form the PhpStorm.
``` Test suite failed to run

    /Applications/MAMP/htdocs/pwa/scripts/jest-enzyme-setup.js:5
    import Enzyme from 'enzyme';
           ^^^^^^

    SyntaxError: Unexpected identifier

      86 |   const setupTestFrameworkScriptFile = jestIntellijUtil.getOriginalSetupTestFrameworkScriptFile();
      87 |   if (setupTestFrameworkScriptFile) {
    > 88 |     require(setupTestFrameworkScriptFile);
         |     ^
      89 |   }
      90 | 
      91 |   const testFilePath = getTestFilePath();
```

**To Reproduce**
1. Pull the latest `develop` branch and configure the Yarn workspace
2. Add new Jest runner with the Default Configuration file project_root/jest.config.js
3. Try to run some tests

**Expected behavior**
Test being launched.

**Screenshots**
![image](https://user-images.githubusercontent.com/20116393/51960944-b9424100-2463-11e9-94c5-a8820096ce26.png)

**Please complete the following device information:**
1. Mac OS Mojave
2. Node v11.8.0
3. Yarn 1.13.0
4. PhpStorm 2018.3.3

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `pwa-buildpack`
- [x] `peregrine`
- [x] `pwa-devdocs`
- [x] `upward-js`
- [x] `upward-spec`

**Comment by awilcoxa** [comment]
Can you try this on Node 10, if this still causes problems please verify that there are no existing bugs with jest integration and php storm. Also, can you try yarn clean all and yarn build all before running tests?

**Comment by VitaliyBoyko** [comment]
HI @awilcoxa 
On Node v10.16.0 the issue remains the same. Cleaning yarn build did not help either. Thanks!

**Comment by VitaliyBoyko** [comment]
I've found a similar bug here https://stackoverflow.com/questions/50766289/configuring-jest-enzyme-to-run-tests-in-phpstorm. But with no solution there.

**Comment by zetlen** [comment]
@VitaliyBoyko Hey, is this still happening to you? It looks a lot like `babel-jest` isn't running, which might be the fault of the test runner. Can you please post a step-by-step repro so we can create this issue in our own copies of PhpStorm?

**Comment by awilcoxa** [comment]
@VitaliyBoyko I'm closing this ticket for now given stale state. If you're still experiencing this please let us know by re-opening the ticket or reaching out via the community slack channel.
