### ISSUE TITLE
Unwanted page skeleton with page navigator displayed when user clicks on category which doesnt contain any products.

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#823]
Description:
Unwanted page skeleton with page navigator displayed (PFA screen) when user clicks on category which doesn't have any products.

1. Create a new category on Admin UI and don't assign any products to it.
2. Navigate to Venia storefront (clear browser cache if venia storefront is already accessed on the browser ).
3. Click on newly created category.

Expected behavior:
User should be shown with informative message about products not available in this category (Please check with Business on exact message content)

Actual :
Blank page skeleton is displayed with page navigation icons.

Screen:
![image.png](https://images.zenhubusercontent.com/5c585c5aecb0076f3e898431/89efd7bc-12d7-4d37-abe7-2b3764c2f955) 

Screen:

**Comment by Jordaneisenburger** [comment]
I'd like to take ownership of this issue

**Comment by Jordaneisenburger** [comment]
I'd like to take ownership of this issue
