### ISSUE TITLE
Http Headers for File/Directory Resolvers

### ISSUE THREAD

**Issue by bbatsche** [magento/pwa-studio#889]
There is no way to inject headers into a response from File or Directory Resolver. This would be especially valuable for adding `Cache-Control` headers or similar to these resolvers, so that intermediate caches may store those assets and push some of the load off of the Upward server.

**Comment by zetlen** [comment]
This is a very good point. However, we're closing this because #1529 will probably deprecate live DirectoryResolver resolution anyway, in favor of compile-time configuration that gets exported to nginx or Apache or Fastly, you name it. I bet you'd be happier with this anyway, @bbatsche .
