### ISSUE TITLE
[bug]: Windows contributor workflow is broken

### ISSUE THREAD

**Issue by sirugh** [magento/pwa-studio#898]
**Describe the bug**
There are several issues when trying to get the app to run locally or install. The installation bit should be handled with #864 but trying to develop locally is a headache.

**To Reproduce**
On a Windows 10 machine, checkout the app and run `yarn install`. Then try to run any of the normal script commands like `yarn run lint` or `yarn run watch:venia` or `yarn run build`.

**Expected behavior**
All root package scripts work including `lint`, `test`, `build`, `watch:venia`, `watch:all`, etc.

**Please complete the following device information:**
 - Device: PC
 - OS: Windows 10
 - NPM version6.4.1
 - Node Version 10.15.1
 - Yarn Version 1.13.0

**Additional context**
This should address the workflow for contributors of _this_ repo. Developers should still be able to add pwa-studio packages like `venia-concept` or `peregrine` and utilize them within their own workflows.

**Problems and Possible solutions**

| Problem | Output | Fix |
| ----------- | ----------- |---|
| Use of env vars breaks commands, ie. `BABEL_ENV`. | |Use [cross-env](https://github.com/kentcdodds/cross-env) for commands that use env variables. |
|`yarn build`| Assuming fix using cross-env, still has issues: [![Image from Gyazo](https://i.gyazo.com/41c57e80c79f1a9d340ae745699aec49.png)](https://gyazo.com/41c57e80c79f1a9d340ae745699aec49) |RootComponent path resolution. |
| `yarn run prettier:validate` |[![Image from Gyazo](https://i.gyazo.com/ffbc9202c6e76bd0674eb553a1948e4f.png)](https://gyazo.com/ffbc9202c6e76bd0674eb553a1948e4f)|Replace `'` with `"`|
| `yarn run watch:venia`| [![Image from Gyazo](https://i.gyazo.com/35fef052c87c162cd0fbfc8c5bfe7a46.png)](https://gyazo.com/35fef052c87c162cd0fbfc8c5bfe7a46)|RootComponent path resolution.|
| `yarn test` | This actually runs the tests but there are issues with path resolution/matching ||

**Comment by awilcoxa** [comment]
Moved to for grooming as this needs review and planning from devops for PR #899

**Comment by awilcoxa** [comment]
Not a high priority at this time, moving the issue to backlog and @sirugh will close the PR and the team will come back to this at a later time/date.

**Comment by sirugh** [comment]
PR: https://github.com/magento-research/pwa-studio/pull/899

**Comment by awilcoxa** [comment]
closed for inactivity

**Comment by koushikch7** [comment]
I am Facing the same issue in my windows environment.
