### ISSUE TITLE
EPIC: PWA Extensibility and Marketplace

### ISSUE THREAD

**Issue by awilcoxa** [magento/pwa-studio#947]
Goal: Magento PWA studio must support the ecosystem of partner and community developers who want to create extensions within our framework, this should also support a process for making said extensions available on the Magento marketplace. 

Epic should contain issues for: 

### Discovery

1. Decide which use cases the PWA should support. Do we support installation of extension with no developer intervention for the SMB?
2. Decide where the source of truth is for list of installed extensions
3. Decide how NPM packages should be distributed
4. Create API for an extension to modify PWA code at buildtime.
  - Should it be a decorator/interceptor which could make an arbitrary change? Stability vs versatility
  - Should it be driven by GraphQL types, like di.xml binds concrete overrides to common interfaces?

### Marketplace Dependency Definition

1. Make EQP process including testing and validation
2. Create UX wireframes for Marketplace installation workflow

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-24

**Comment by cherdman** [comment]
Reopening for visibility and will close once we publish our plans for extensibility and Marketplace integration.
