### ISSUE TITLE
Peregrine: Homepage Component

### ISSUE THREAD

**Issue by awilcoxa** [magento/pwa-studio#973]
Represents effort to refactor the existing Venia homepage (landing page) component to the Peregrine Hooks library. Includes effort required to refactor existing component, create any needed enhancement to Peregrine hooks, and ensure GQL consumption where possible. 

Currently, Venia Implementation for home page contains only the title and the category widget. We do not pull in CMS content from the Magento backend.

**Comment by awilcoxa** [comment]
Based on grooming, converting current implementation of homepage adds no value (only contains a category widget). 

We'll defer and this ticket and move back to backlog until venia homepage adds more value.

**Comment by soumya-ashok** [comment]
@awilcoxa 
1. Is the home page only going to be enabled by Pagebuilder content?
2. There are a lot of moving parts on the full design of the home page including featured products, carousels, shop the look etc. that haven't been implemented. Do we need to open separate stories for all of those, or maybe link already created issues to this one?

**Comment by awilcoxa** [comment]
@soumya-ashok 
1. No, this ticket was only meant to represent refactor of the existing home/landing page (which is essentially just a category view) 
2. This ticket does not represent any new functionality. New features will have epics/issues created as needed in future (or that already exist in the backlog).

**Comment by awilcoxa** [comment]
Moved to modular component library milestone for @jimbo and @sirugh review. If this is already accounted for in existing work then we can close this ticket.

**Comment by awilcoxa** [comment]
Closing since the work is contained in #1604
